### PR TITLE
Give Amy Chen access to pushing to cluster-api staging registry

### PR DESCRIPTION
**Pull request by amy**
Reference Issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/795
Summary: I would like to smooth out the release process for cluster-api and need access to pushing images to the staging registry.

### CODE REVIEW

**Comment by amy** [comment]
cc/ @dims @chuckha

**Comment by dims** [comment]
@amy can you please get a +1/lgtm from one of the leads?

**Comment by chuckha** [comment]
@timothysc or @justinsb, can you give a +1 here? This work will allow more than just you to push new release container images for cluster-api :D

**Comment by dims** [comment]
@chuckha your +1 is good enough since you are already in the group.

/lgtm

**Comment by cblecker** [comment]
Ran the update for this.

**Comment by thockin** [comment]
Are these staging repos now actively being used?  That would be good to
know so they don't get nuked as we iterate on setup...

**Pull request merged**
