### PR TITLE
Image promotion for cluster-api-azure v1.16.0

### PR DESCRIPTION
**Pull request by mboersma**
Image promotion for cluster-api-azure v1.16.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork mboersma --project cluster-api-azure --reviewers "@jackfrancis @mboersma @nojnhuh @Jont828 @willie-yao" --tag v1.16.0
```

/hold
cc: @jackfrancis @mboersma @nojnhuh @Jont828 @willie-yao

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by mboersma** [comment]
/hold cancel

SHA `d63c198` matches that for v1.16.0 in the [staging repository](https://console.cloud.google.com/gcr/images/k8s-staging-cluster-api-azure/global/cluster-api-azure-controller@sha256:d63c19885fc56cca30a7c139b11232240b9dab451eb0fc29f69491411e35d2dd/details).

**Review by nojnhuh — APPROVED** [review]
/lgtm

**Pull request merged**
