### PR TITLE
add listx to test-infra-oncall and k8s-infra-prow-oncall

### PR DESCRIPTION
**Pull request by listx**

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

@spiffxp @BenTheElder Is this intended? Not seeing @listx in this list: https://github.com/kubernetes/test-infra/blob/master/OWNERS_ALIASES#L3

**Comment by listx** [comment]
> /hold
> 
> @spiffxp @BenTheElder Is this intended? Not seeing @listx in this list: https://github.com/kubernetes/test-infra/blob/master/OWNERS_ALIASES#L3

There's a PR pending for that here https://github.com/kubernetes/test-infra/pull/23338

**Comment by cblecker** [comment]
@listx Awesome! Once that one is merged, no problem approving this :)

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold cancel

**Pull request merged**
