### PR TITLE
Update Google groups for 1.32 release docs shadows

### PR DESCRIPTION
**Pull request by chanieljdan**
Update Google groups for 1.32 release docs shadows

### CODE REVIEW

**Comment by chanieljdan** [comment]
Fixed trailing spaces

/retest

**Comment by chanieljdan** [comment]
/assign @cpanato 

Hi @cpanato! Could I get your approval on this PR?

**Comment by ameukam** [comment]
cc @kubernetes/sig-release-leads

**Review by cpanato — APPROVED** [review]

**Pull request merged**
