### PR TITLE
Image promotion for cluster-api-helm v0.1.1-alpha.1

### PR DESCRIPTION
**Pull request by Jont828**
Image promotion for cluster-api-helm v0.1.1-alpha.1
This is an automated PR generated from `kpromo`
```
kpromo pr --fork Jont828 --project cluster-api-helm --reviewers "@Jont828 @jackfrancis" --tag v0.1.1-alpha.1 --image cluster-api-helm-controller
```

/hold
cc: @Jont828 @jackfrancis

### CODE REVIEW

**Comment by Jont828** [comment]
@mboersma

**Comment by dtzar** [comment]
You're introducing new features, so wouldn't you want to do v0.1.2-alpha.0 or v0.2.1-alpha.0 ?

**Review by mboersma — APPROVED** [review]
/lgtm

Remove the hold when you're ready. 🎉

**Pull request merged**
