### PR TITLE
Add CAPI operator staging group

### PR DESCRIPTION
**Pull request by alexander-demicev**
Add CAPI operator staging group

### CODE REVIEW

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@alexander-demicev see https://github.com/kubernetes/k8s.io/pull/2640/files, what you have currently just adds a mailing list for ACL.

**Comment by alexander-demicev** [comment]
@dims I included a new commit with what is left to do

**Comment by dims** [comment]
ugh 

```
time="17:15:02.908" level=fatal msg="run `cip run`: promote images: filtering edges: filtering promotion edges: reading registries: getting tag list: GET https://us-east1-docker.pkg.dev/v2/token?scope=repository%3Ak8s-artifacts-prod%2Fimages%2Fe2e-test-images%2Fagnhost%3Apull&service=: TOOMANYREQUESTS: Quota exceeded for quota metric 'Requests per project per region' and limit 'Requests per project per region per minute per region' of service 'artifactregistry.googleapis.com' for consumer 'project_number:388270116193'." diff=102ms
```

**Comment by dims** [comment]
/assign @ameukam 

Arnaud, please see the failure in the cip presubmit test. Looks like we need to bump limits

**Comment by ameukam** [comment]
> /assign @ameukam
> 
> Arnaud, please see the failure in the cip presubmit test. Looks like we need to bump limits

It's mostly a bug with the Artifact Registry API. we face this sometimes during the patch releases. I'll suggest to give a day before to a retry.

**Pull request merged**
