### PR TITLE
experimental: canary promotion of conformance-amd64

### PR DESCRIPTION
**Pull request by ameukam**
Canary promotion using geranos

### CODE REVIEW

**Comment by ameukam** [comment]
cc @BenTheElder

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Review by puerco — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
still waiting for post-k8sio-image-promo, when the image is live I'll trigger an immediate fresh run of geranos and check the logs, the GCS-to-S3 appears to be paused as planned.

xref: https://github.com/kubernetes/test-infra/pull/28922

**Comment by BenTheElder** [comment]
it's working now 🎉

**Pull request merged**
