### PR TITLE
Fix group name for II coop.

### PR DESCRIPTION
**Pull request by ameukam**
Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
Tried to applied the binding for this group but got : 
```
Error: Request "Create IAM Members roles/owner group:k8s-infra-ii-coop@kubernetes.io for \"project \\\"projects/k8s-infra-ii-sandbox\\\"\"" returned error: Error applying IAM policy for project "projects/k8s-infra-ii-sandbox": Error setting IAM policy for project "projects/k8s-infra-ii-sandbox": googleapi: Error 400: Request contains an invalid argument., badRequest
```

**Comment by ameukam** [comment]
This issue was the non-existence of `k8s-infra-ii-coop@kubernetes.io`. @spiffxp made a manual reconciliation. 

```shell
./terraform apply -auto-approve
data.google_organization.org: Refreshing state... [id=organizations/758905017065]
data.google_billing_account.account: Refreshing state... [id=018801-93540E-22A20E]
google_project.project: Refreshing state... [id=projects/k8s-infra-ii-sandbox]
google_project_service.project["cloudbuild.googleapis.com"]: Refreshing state... [id=k8s-infra-ii-sandbox/cloudbuild.googleapis.com]
google_project_service.project["storage-component.googleapis.com"]: Refreshing state... [id=k8s-infra-ii-sandbox/storage-component.googleapis.com]
google_project_service.project["containerregistry.googleapis.com"]: Refreshing state... [id=k8s-infra-ii-sandbox/containerregistry.googleapis.com]
google_project_service.project["containeranalysis.googleapis.com"]: Refreshing state... [id=k8s-infra-ii-sandbox/containeranalysis.googleapis.com]
google_project_service.project["container.googleapis.com"]: Refreshing state... [id=k8s-infra-ii-sandbox/container.googleapis.com]
google_project_iam_member.k8s_infra_ii_coop: Creating...
google_project_iam_member.k8s_infra_ii_coop: Still creating... [10s elapsed]
google_project_iam_member.k8s_infra_ii_coop: Creation complete after 11s [id=projects/k8s-infra-ii-sandbox/roles/owner/group:k8s-infra-ii-coop@kubernetes.io]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Followup to https://github.com/kubernetes/k8s.io/pull/1967
ref: https://github.com/kubernetes/k8s.io/issues/1758

**Pull request merged**
