### PR TITLE
Promote NPD image v0.8.17

### PR DESCRIPTION
**Pull request by wangzhen127**
https://pantheon.corp.google.com/gcr/images/k8s-staging-npd/global/node-problem-detector@sha256:a510d7d95d071fa901bf71b10e6c7df3e8361c8383b5cf792e97a3e36dee80b8/details

/assign @Random-Liu 
/cc @vteratipally @hakman

### CODE REVIEW

**Comment by wangzhen127** [comment]
/hold

@Random-Liu Can you help review? I will manually unhold after you verify and update the v0.8.17 release note with uploaded tar files. Thanks!

**Comment by hakman** [comment]
@wangzhen127 Could we promote this in advance?

**Comment by wangzhen127** [comment]
/unhold

NPD tar files have been uploaded to release notes. Promoting container image now.

**Pull request merged**
