### PR TITLE
releng: Image promotion for kubernetes v1.24.3-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for kubernetes v1.24.3-rc.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork cpanato --tag v1.24.3-rc.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by cpanato** [comment]
/assign @saschagrunert @puerco @ameukam 
cc @kubernetes/release-managers

**Comment by ameukam** [comment]
Let's wait https://github.com/kubernetes/k8s.io/pull/3855 to get merged before we merge it.

**Review by saschagrunert — APPROVED** [review]

**Comment by palnabarun** [comment]
@ameukam -- this would need a rebase.

**Pull request closed without merging**
