### PR TITLE
releng: Image promotion for v1.22.0-beta.0

### PR DESCRIPTION
**Pull request by onlydole**
Image promotion for Kubernetes v1.22.0-beta.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by puerco** [comment]
Thank you Taylor!!
/lgtm

**Review by justaugustus — APPROVED** [review]
:shipit: 
Stage for digest xref: https://console.cloud.google.com/cloud-build/builds;region=global/53c33ec5-e44e-48d0-b8d4-1d4ee825da6b?project=kubernetes-release-test

/hold cancel

**Pull request merged**
