### PR TITLE
releng: Image promotion for v1.18.17 / v1.18.18-rc.0 / v1.19.9 / v1.19.10-rc.0 / v1.20.5 / v1.20.6-rc.0

### PR DESCRIPTION
**Pull request by puerco**
Image promotion for Kubernetes v1.18.17 / v1.18.18-rc.0 / v1.19.9 / v1.19.10-rc.0 / v1.20.5 / v1.20.6-rc.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
