### PR TITLE
GCP: Add more AR regions

### PR DESCRIPTION
**Pull request by ameukam**
Part of:
  - https://github.com/kubernetes/registry.k8s.io/issues/172

Add newly open regions for image promotion in order to serve image layers on those regions.

### CODE REVIEW

**Comment by ameukam** [comment]
/hold

Cc @dims 
cc @kubernetes/release-engineering

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
