### PR TITLE
Image promotion for cluster-api v1.3.0-beta.1

### PR DESCRIPTION
**Pull request by ykakarap**
Image promotion for cluster-api v1.3.0-beta.1
This is an automated PR generated from `kpromo`
```
kpromo pr --fork ykakarap --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @sbueringer @vincepri" --tag v1.3.0-beta.1 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @CecileRobertMichon @enxebre @fabriziopandini @sbueringer @vincepri

### CODE REVIEW

**Comment by ykakarap** [comment]
cc @dntosas @cpanato @hackeramitkumar
@oscr @sayantani11 @VibhorChinda
@furkatgofurov7 @nawazkh @aniruddha2000 @alexander-demicev

**Comment by oscr** [comment]
Great!

/lgtm

**Comment by nawazkh** [comment]
Thanks! looks good to me

**Review by alexander-demicev — APPROVED** [review]
🎉
/lgtm

**Pull request merged**
