### PR TITLE
staging scheduler simulator image

### PR DESCRIPTION
**Pull request by sanposhiho**
Hello team.

This PR creates a staging repo for the scheduler simulator.
I followed the documentation below to make the changes, but please let me know if there is anything I missed.
https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#staging-repos

The project name is sched_simulator because the name can have a maximum of 18 characters.

part of https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/19

@adtac @Huang-Wei @alculquicondor Please check that your e-mail address is correct. 🙇

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Running into issues with `./ensure-staging-storage.sh sched-simulator`

```
Ensuring staging GCR repo: gcr.io/k8s-staging-sched-simulator
    Ensuring a GCR repo exists for project: k8s-staging-sched-simulator
    Using default tag: latest
    latest: Pulling from pause
    Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
    Status: Image is up to date for k8s.gcr.io/pause:latest
    k8s.gcr.io/pause:latest
    Using default tag: latest
    The push refers to repository [gcr.io/k8s-staging-sched-simulator/ceci-nest-pas-une-image]
    5f70bf18a086: Preparing
    e16a89738269: Preparing
    5f70bf18a086: Preparing
    unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by spiffxp** [comment]
I had reset docker to factory defaults, needed to `gcloud auth configure-docker`.  Did that and re-ran.  Should be good to go!

**Comment by sanposhiho** [comment]
Thanks @spiffxp!!

**Pull request merged**
