### PR TITLE
promote image for e2e test issue-74893

### PR DESCRIPTION
**Pull request by aojea**
The new image supports:
- multiple architectures  https://github.com/kubernetes/kubernetes/pull/96792
- IPv6 https://github.com/kubernetes/kubernetes/pull/95328

I´ve followed the instructions in https://github.com/kubernetes/kubernetes/blob/master/test/images/README.md#making-changes-to-images

### CODE REVIEW

**Comment by aojea** [comment]
hmm 

> E0111 10:51:33.197115      12 inventory.go:508] edge {{gcr.io/k8s-staging-provider-aws   true} {aws-ebs-csi-driver latest} sha256:3801d90c7cfb438b308166681c59aa6576d1e614223e1d17eee9997287bac17e {asia.gcr.io/k8s-artifacts-prod/provider-aws k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com  false} {aws-ebs-csi-driver latest}}: tag latest: ERROR: tag move detected from sha256:3801d90c7cfb438b308166681c59aa6576d1e614223e1d17eee9997287bac17e to sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f

what does it mean?

**Comment by aojea** [comment]
@wongma7 it seems that this image sha that shows up in the err https://github.com/kubernetes/k8s.io/pull/1515#issuecomment-757882682 was changed by you recently in https://github.com/kubernetes/k8s.io/commit/94e17d6a707b46904a663d43637a59a57af643bd

can you please take a look or just point me on how to solve it?

**Comment by aojea** [comment]
ping @justaugustus for guidance 
https://github.com/kubernetes/k8s.io/pull/1515#issuecomment-757882682

**Comment by claudiubelu** [comment]
I don't think we're at fault here, the job fails on another image, more specifically, the ``aws-ebs-csi-driver`` image, which should be addressed. This PR should be fine, the sha is also good.

**Comment by wongma7** [comment]
Fixing on my side

**Comment by spiffxp** [comment]
Keeping an eye on the results of https://github.com/kubernetes/k8s.io/pull/1519 merging

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
