### PR TITLE
Remove 'contributor' DNS record

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by thockin** [comment]
Jorge (I think) asked to recall teh domain because it wasn't ready yet.

**Comment by ixdy** [comment]
cc @castrojo 
/lgtm
/hold

**Comment by ixdy** [comment]
/approve

I guess we don't have self-approvals enabled on this repo?

**Comment by thockin** [comment]
From email:

```
From: Jorge Castro <jorge@heptio.com>
Date: Fri, 9 Nov 2018 16:47:34 -0500
Subject: Re: CNAME for contributor.k8s.io
To: Tim Hockin <thockin@google.com>
Content-Type: multipart/alternative; boundary="000000000000b86292057a424e30"

--000000000000b86292057a424e30
Content-Type: text/plain; charset="UTF-8"

Heya Tim, looks like we're taking the site back to the drawing board, can
you remove these cnames?

contributor.kubernetes.io and contributor.k8s.io, we're going to just use
the netlify URL for a while.
```

**Comment by thockin** [comment]
Also, it has been removed from serving for a month :)  This repo config is
not live yet

**Pull request merged**
