### PR TITLE
Add kwok dns name

### LINKED ISSUE #4581: DNS REQUEST: kwok.sigs.k8s.io
### Type of DNS update:
one of: Create, Delete, Update

### Domain being modified:
`kwok.sigs.k8s.io`

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/kwok docs (@wzshiming, @yibozhuang, @Huang-Wei)
kwok.sigs:
  type: CNAME
  value: k8s-kwok.netlify.app.
```

### PR DESCRIPTION
**Pull request by wzshiming**
Fixes kubernetes-sigs/kwok#125
Fixes kubernetes/org#3911
Fixes #4581

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/approve
/lgtm

Could you remove WIP from the PR title?

**Comment by munnerz** [comment]
Approving on behalf of DNS owners - holding in case any more amendments need making :)

/approve
/hold

**Comment by wzshiming** [comment]
/unhold

Site is now live on https://k8s-kwok.netlify.app

**Pull request merged**
