### PR TITLE
Promote cluster-proportional-autoscaler 1.8.2 images

### PR DESCRIPTION
**Pull request by MrHohn**
We are cutting a new release for cluster-proportional-autoscaler and need to release these images.
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler@sha256:762ef69b7093a8c4c83472aabdf79f4c5eb6743b122b2c06ca740f44cb00ca9d/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-amd64@sha256:e310b7e60ed5dabcf9945fb86ee049bafde69b01ac0b9eb647c2b96c273e18d8/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-arm@sha256:ba9d51870f9a718f91fb2a0df6366da36b2e5484a3331049b226310b5d59993d/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-arm64@sha256:549b40bf6c29920f0f023fd97a6a9197f785f15799523c3486456a1bd24c840f/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-ppc64le@sha256:a9ba5e939a4f8f0ded4a6b222d01b6922fce231f7977098112d51e409fce81f0/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065

Ref https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/89.

### CODE REVIEW

**Comment by MrHohn** [comment]
cc @rifelpet @johngmyers

**Comment by listx** [comment]
It also appears that there is not yet a manifest file that uses gcr.io/k8s-image-staging (the repo you actually pushed the images to). The patch in this PR is for images that promote from gcr.io/k8s-staging-cpa.

**Comment by MrHohn** [comment]
> It also appears that there is not yet a manifest file that uses gcr.io/k8s-image-staging (the repo you actually pushed the images to). The patch in this PR is for images that promote from gcr.io/k8s-staging-cpa.

Oops, thanks for catching it! Turned out I forgot to update the staging repo when pushing. Will fix that.

**Comment by MrHohn** [comment]
> Oops, thanks for catching it! Turned out I forgot to update the staging repo when pushing. Will fix that.

Okay, I have pushed the images to the new staging repo: gcr.io/k8s-staging-cpa, PTAL, thanks!

**Pull request merged**
