### PR TITLE
releng: Promote kube-cross:v1.15.8-1

### PR DESCRIPTION
**Pull request by cpanato**
- `kube-cross:v1.15.8-1`: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-release-push-image-kube-cross/1357628759531851776

Required for go1.15.8 updates: https://github.com/kubernetes/release/issues/1895

/assign @hasheddan @saschagrunert @xmudrii @puerco @ameukam 

cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
