### PR TITLE
Setup image release for leaderworkerset

### PR DESCRIPTION
**Pull request by liurupeng**
This is repo for the image release: https://github.com/kubernetes-sigs/lws

### CODE REVIEW

**Comment by liurupeng** [comment]
@ahg-g could you help check? thanks!

**Comment by ahg-g** [comment]
@MadhavJivrajani can you please take a look, it is ready now

**Comment by liurupeng** [comment]
@kow3ns could you help check this cl? it has been blocked for more than a week? thanks!

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by ameukam** [comment]
This is actuated.

<details>
<summary>Details</summary>

$./ensure-staging-storage.sh k8s-staging-lws
Ensuring staging projects... 
Configuring staging project: k8s-staging-lws 
  Ensuring project exists: k8s-staging-lws 
  Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-staging-lws].
  Waiting for [operations/cp.6332055347394227971] to finish...
  ..done.
  billingAccountName: billingAccounts/018801-93540E-22A20E
  billingEnabled: true
  name: projects/k8s-staging-lws/billingInfo
  projectId: k8s-staging-lws
  Updated IAM policy for project [k8s-staging-lws].
  @@ -1,2 +1 @@
  -- member: user:ameukam@gmail.com
  -  role: roles/owner
  +[]
  Ensuring k8s-infra-staging-lws@kubernetes.io are project viewers 
  Updated IAM policy for project [k8s-staging-lws].
  @@ -1 +1,2 @@
  -[]
  +- member: group:k8s-infra-staging-lws@kubernetes.io
  +  role: roles/viewer
  Ensuring necessary enabled services staging project: k8s-staging-lws 
  plan to enable/disable the following services
  to_enable:
    - artifactregistry.googleapis.com
    - cloudasset.googleapis.com
    - cloudbuild.googleapis.com
    - cloudkms.googleapis.com
    - containerregistry.googleapis.com
    - iam.googleapis.com
    - iamcredentials.googleapis.com
    - logging.googleapis.com
    - policytroubleshooter.googleapis.com
    - pubsub.googleapis.com
    - secretmanager.googleapis.com
    - storage-api.googleapis.com
    - storage-component.googleapis.com
  to_disable: []
  Operation "operations/acat.p2-772186053622-dad4706c-0be3-46fa-b8cf-4e7fa18a3f32" finished successfully.
  Operation "operations/acat.p2-772186053622-49b589e4-b919-47e0-8712-b7e084c36d58" finished successfully.
  Operation "operations/acf.p2-772186053622-8dcc88b4-5427-4b6a-8103-1e14f691689e" finished successfully.
  Operation "operations/acat.p2-772186053622-1bf10478-eacf-4ead-8fc7-2c4e5114fd78" finished successfully.
  Operation "operations/acat.p2-772186053622-3564deb9-282c-4889-adbc-b106eea289c2" finished successfully.
  Operation "operations/acat.p2-772186053622-30ea7741-29d4-4f65-af29-9010f890f620" finished successfully.
  Operation "operations/acat.p2-772186053622-fe1a65af-8508-4ec9-969c-94af73e483f5" finished successfully.
  Operation "operations/acat.p2-772186053622-798e9c7c-0560-49e0-bb8d-bfa595180bdb" finished successfully.
  @@ -12,8 +12,7 @@ intent:
     - secretmanager.googleapis.com
     - storage-api.googleapis.com
     - storage-component.googleapis.com
  -enabled: []
  -expected:
  +enabled:
     - artifactregistry.googleapis.com
     - cloudasset.googleapis.com
     - cloudbuild.googleapis.com
  @@ -27,7 +26,7 @@ expected:
     - secretmanager.googleapis.com
     - storage-api.googleapis.com
     - storage-component.googleapis.com
  -to_enable:
  +expected:
     - artifactregistry.googleapis.com
     - cloudasset.googleapis.com
     - cloudbuild.googleapis.com
  @@ -41,4 +40,5 @@ to_enable:
     - secretmanager.googleapis.com
     - storage-api.googleapis.com
     - storage-component.googleapis.com
  +to_enable: []
   to_disable: []
  Ensuring disabled services for staging project: k8s-staging-lws 
  Operation "operations/acat.p17-772186053622-ce6902ed-69e7-40de-87d9-0420bc0d5f73" finished successfully.
  Operation "operations/acat.p17-772186053622-6116805e-462e-43bf-baaf-33e84059f9b4" finished successfully.
  Ensuring containeranalysis service agent binding removed for staging project: k8s-staging-lws 
  Ensuring serviceAccount:k8s-infra-gcr-vuln-scanning@k8s-artifacts-prod.iam.gserviceaccount.com can view vulnernability scanning results for project: k8s-staging-lws 
  Updated IAM policy for project [k8s-staging-lws].
  @@ -2,6 +2,8 @@
     role: roles/viewer
   - member: serviceAccount:772186053622@cloudbuild.gserviceaccount.com
     role: roles/cloudbuild.builds.builder
  +- member: serviceAccount:k8s-infra-gcr-vuln-scanning@k8s-artifacts-prod.iam.gserviceaccount.com
  +  role: roles/containeranalysis.occurrences.viewer
   - member: serviceAccount:service-772186053622@containerregistry.iam.gserviceaccount.com
     role: roles/containerregistry.ServiceAgent
   - member: serviceAccount:service-772186053622@gcp-sa-cloudbuild.iam.gserviceaccount.com
  Ensuring staging AR repo: us-central1-docker.pkg.dev/k8s-staging-lws/images 
    Create request issued for: [images]
    Waiting for operation [projects/k8s-staging-lws/locations/us-central1/operations/b550f71f-ca53-4843-82cd-525866fc6419] to complete...
    ...............................................done.
    Created repository [images].
    Updated IAM policy for repository [images].
    @@ -1 +1,2 @@
    -[]
    +- member: allUsers
    +  role: roles/artifactregistry.reader
  Ensuring staging GCR repo: gcr.io/k8s-staging-lws 
    Ensuring a GCR repo exists for project: k8s-staging-lws 
    Using default tag: latest
    latest: Pulling from pause
    Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
    Status: Image is up to date for k8s.gcr.io/pause:latest
    k8s.gcr.io/pause:latest
    Using default tag: latest
    The push refers to repository [gcr.io/k8s-staging-lws/ceci-nest-pas-une-image]
    5f70bf18a086: Preparing
    e16a89738269: Preparing
    5f70bf18a086: Preparing
    5f70bf18a086: Layer already exists
    e16a89738269: Layer already exists
    latest: digest: sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74 size: 938
    WARNING: Successfully resolved tag to sha256, but it is recommended to use sha256 directly.
    Digests:
    - gcr.io/k8s-staging-lws/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
      Associated tags:
     - latest
    Tags:
    - gcr.io/k8s-staging-lws/ceci-nest-pas-une-image:latest
    Deleted [gcr.io/k8s-staging-lws/ceci-nest-pas-une-image:latest].
    Deleted [gcr.io/k8s-staging-lws/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
    Enabling Bucket Policy Only for gs://artifacts.k8s-staging-lws.appspot.com...
    gs://artifacts.k8s-staging-lws.appspot.com/
    @@ -1,3 +1,5 @@
    +- member: allUsers
    +  role: roles/storage.objectViewer
     - member: projectEditor:k8s-staging-lws
       role: roles/storage.legacyBucketOwner
     - member: projectOwner:k8s-staging-lws
    Ensuring k8s-infra-staging-lws@kubernetes.io can write to GCR for project: k8s-staging-lws 
    gs://artifacts.k8s-staging-lws.appspot.com/
    @@ -1,5 +1,7 @@
     - member: allUsers
       role: roles/storage.objectViewer
    +- member: group:k8s-infra-staging-lws@kubernetes.io
    +  role: roles/storage.objectAdmin
     - member: projectEditor:k8s-staging-lws
       role: roles/storage.legacyBucketOwner
     - member: projectOwner:k8s-staging-lws
    gs://artifacts.k8s-staging-lws.appspot.com/
    @@ -1,5 +1,7 @@
     - member: allUsers
       role: roles/storage.objectViewer
    +- member: group:k8s-infra-staging-lws@kubernetes.io
    +  role: roles/storage.legacyBucketWriter
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/storage.objectAdmin
     - member: projectEditor:k8s-staging-lws
    Ensuring GCR admins can admin GCR for project: k8s-staging-lws 
    Updated IAM policy for project [k8s-staging-lws].
    @@ -1,3 +1,5 @@
    +- member: group:k8s-infra-artifact-admins@kubernetes.io
    +  role: roles/viewer
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/viewer
     - member: serviceAccount:772186053622@cloudbuild.gserviceaccount.com
    gs://artifacts.k8s-staging-lws.appspot.com/
    @@ -1,5 +1,7 @@
     - member: allUsers
       role: roles/storage.objectViewer
    +- member: group:k8s-infra-artifact-admins@kubernetes.io
    +  role: roles/storage.objectAdmin
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/storage.legacyBucketWriter
     - member: group:k8s-infra-staging-lws@kubernetes.io
    gs://artifacts.k8s-staging-lws.appspot.com/
    @@ -1,5 +1,7 @@
     - member: allUsers
       role: roles/storage.objectViewer
    +- member: group:k8s-infra-artifact-admins@kubernetes.io
    +  role: roles/storage.legacyBucketOwner
     - member: group:k8s-infra-artifact-admins@kubernetes.io
       role: roles/storage.objectAdmin
     - member: group:k8s-infra-staging-lws@kubernetes.io
    Ensuring GCS access logs enabled for GCR bucket in project: k8s-staging-lws 
    Enabling logging on gs://artifacts.k8s-staging-lws.appspot.com/...
    @@ -1 +1 @@
    -gs://artifacts.k8s-staging-lws.appspot.com/ has no logging configuration.
    +{"logBucket": "k8s-infra-artifacts-gcslogs", "logObjectPrefix": "artifacts.k8s-staging-lws.appspot.com"}
  Ensuring staging GCS bucket: gs://k8s-staging-lws 
    Ensuring gs://k8s-staging-lws exists and is world readable in project: k8s-staging-lws 
    Creating gs://k8s-staging-lws/...
    Enabling Bucket Policy Only for gs://k8s-staging-lws...
    gs://k8s-staging-lws/
    @@ -1,3 +1,5 @@
    +- member: allUsers
    +  role: roles/storage.objectViewer
     - member: projectEditor:k8s-staging-lws
       role: roles/storage.legacyBucketOwner
     - member: projectOwner:k8s-staging-lws
    Ensuring gs://k8s-staging-lws has auto-deletion of 60 days 
    Setting lifecycle configuration on gs://k8s-staging-lws/...
    @@ -1 +1 @@
    -gs://k8s-staging-lws/ has no lifecycle configuration.
    +{"rule": [{"action": {"type": "Delete"}, "condition": {"age": 60}}]}
    Ensuring GCS admins can admin gs://k8s-staging-lws in project: k8s-staging-lws 
    gs://k8s-staging-lws/
    @@ -1,5 +1,7 @@
     - member: allUsers
       role: roles/storage.objectViewer
    +- member: group:k8s-infra-artifact-admins@kubernetes.io
    +  role: roles/storage.objectAdmin
     - member: projectEditor:k8s-staging-lws
       role: roles/storage.legacyBucketOwner
     - member: projectOwner:k8s-staging-lws
    gs://k8s-staging-lws/
    @@ -1,5 +1,7 @@
     - member: allUsers
       role: roles/storage.objectViewer
    +- member: group:k8s-infra-artifact-admins@kubernetes.io
    +  role: roles/storage.legacyBucketOwner
     - member: group:k8s-infra-artifact-admins@kubernetes.io
       role: roles/storage.objectAdmin
     - member: projectEditor:k8s-staging-lws
    Ensuring k8s-infra-staging-lws@kubernetes.io can write to gs://k8s-staging-lws in project: k8s-staging-lws 
    gs://k8s-staging-lws/
    @@ -4,6 +4,8 @@
       role: roles/storage.legacyBucketOwner
     - member: group:k8s-infra-artifact-admins@kubernetes.io
       role: roles/storage.objectAdmin
    +- member: group:k8s-infra-staging-lws@kubernetes.io
    +  role: roles/storage.objectAdmin
     - member: projectEditor:k8s-staging-lws
       role: roles/storage.legacyBucketOwner
     - member: projectOwner:k8s-staging-lws
    gs://k8s-staging-lws/
    @@ -4,6 +4,8 @@
       role: roles/storage.legacyBucketOwner
     - member: group:k8s-infra-artifact-admins@kubernetes.io
       role: roles/storage.objectAdmin
    +- member: group:k8s-infra-staging-lws@kubernetes.io
    +  role: roles/storage.legacyBucketWriter
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/storage.objectAdmin
     - member: projectEditor:k8s-staging-lws
    Ensuring GCS access logs enabled for gs://k8s-staging-lws in project: k8s-staging-lws 
    Enabling logging on gs://k8s-staging-lws/...
    @@ -1 +1 @@
    -gs://k8s-staging-lws/ has no logging configuration.
    +{"logBucket": "k8s-infra-artifacts-gcslogs", "logObjectPrefix": "k8s-staging-lws"}
  Ensuring staging GCB 
    Ensuring staging bucket: gs://k8s-staging-lws-gcb 
      Ensuring gs://k8s-staging-lws-gcb exists and is world readable in project: k8s-staging-lws 
      Creating gs://k8s-staging-lws-gcb/...
      Enabling Bucket Policy Only for gs://k8s-staging-lws-gcb...
      gs://k8s-staging-lws-gcb/
      @@ -1,3 +1,5 @@
      +- member: allUsers
      +  role: roles/storage.objectViewer
       - member: projectEditor:k8s-staging-lws
         role: roles/storage.legacyBucketOwner
       - member: projectOwner:k8s-staging-lws
      Ensuring gs://k8s-staging-lws-gcb has auto-deletion of 60 days 
      Setting lifecycle configuration on gs://k8s-staging-lws-gcb/...
      @@ -1 +1 @@
      -gs://k8s-staging-lws-gcb/ has no lifecycle configuration.
      +{"rule": [{"action": {"type": "Delete"}, "condition": {"age": 60}}]}
      Ensuring GCS admins can admin gs://k8s-staging-lws-gcb in project: k8s-staging-lws 
      gs://k8s-staging-lws-gcb/
      @@ -1,5 +1,7 @@
       - member: allUsers
         role: roles/storage.objectViewer
      +- member: group:k8s-infra-artifact-admins@kubernetes.io
      +  role: roles/storage.objectAdmin
       - member: projectEditor:k8s-staging-lws
         role: roles/storage.legacyBucketOwner
       - member: projectOwner:k8s-staging-lws
      gs://k8s-staging-lws-gcb/
      @@ -1,5 +1,7 @@
       - member: allUsers
         role: roles/storage.objectViewer
      +- member: group:k8s-infra-artifact-admins@kubernetes.io
      +  role: roles/storage.legacyBucketOwner
       - member: group:k8s-infra-artifact-admins@kubernetes.io
         role: roles/storage.objectAdmin
       - member: projectEditor:k8s-staging-lws
      Ensuring k8s-infra-staging-lws@kubernetes.io can write to gs://k8s-staging-lws-gcb in project: k8s-staging-lws 
      gs://k8s-staging-lws-gcb/
      @@ -4,6 +4,8 @@
         role: roles/storage.legacyBucketOwner
       - member: group:k8s-infra-artifact-admins@kubernetes.io
         role: roles/storage.objectAdmin
      +- member: group:k8s-infra-staging-lws@kubernetes.io
      +  role: roles/storage.objectAdmin
       - member: projectEditor:k8s-staging-lws
         role: roles/storage.legacyBucketOwner
       - member: projectOwner:k8s-staging-lws
      gs://k8s-staging-lws-gcb/
      @@ -4,6 +4,8 @@
         role: roles/storage.legacyBucketOwner
       - member: group:k8s-infra-artifact-admins@kubernetes.io
         role: roles/storage.objectAdmin
      +- member: group:k8s-infra-staging-lws@kubernetes.io
      +  role: roles/storage.legacyBucketWriter
       - member: group:k8s-infra-staging-lws@kubernetes.io
         role: roles/storage.objectAdmin
       - member: projectEditor:k8s-staging-lws
    Ensuring k8s-infra-staging-lws@kubernetes.io can use GCB in project: k8s-staging-lws 
    Updated IAM policy for project [k8s-staging-lws].
    @@ -1,5 +1,7 @@
     - member: group:k8s-infra-artifact-admins@kubernetes.io
       role: roles/viewer
    +- member: group:k8s-infra-staging-lws@kubernetes.io
    +  role: roles/cloudbuild.builds.editor
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/viewer
     - member: serviceAccount:772186053622@cloudbuild.gserviceaccount.com
    Updated IAM policy for project [k8s-staging-lws].
    @@ -2,6 +2,8 @@
       role: roles/viewer
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/cloudbuild.builds.editor
    +- member: group:k8s-infra-staging-lws@kubernetes.io
    +  role: roles/serviceusage.serviceUsageConsumer
     - member: group:k8s-infra-staging-lws@kubernetes.io
       role: roles/viewer
     - member: serviceAccount:772186053622@cloudbuild.gserviceaccount.com
    Ensuring gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com can use GCB in project: k8s-staging-lws 
    Updated IAM policy for project [k8s-staging-lws].
    @@ -8,6 +8,8 @@
       role: roles/viewer
     - member: serviceAccount:772186053622@cloudbuild.gserviceaccount.com
       role: roles/cloudbuild.builds.builder
    +- member: serviceAccount:gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com
    +  role: roles/cloudbuild.builds.builder
     - member: serviceAccount:k8s-infra-gcr-vuln-scanning@k8s-artifacts-prod.iam.gserviceaccount.com
       role: roles/containeranalysis.occurrences.viewer
     - member: serviceAccount:service-772186053622@containerregistry.iam.gserviceaccount.com
    gs://k8s-staging-lws-gcb/
    @@ -14,3 +14,5 @@
       role: roles/storage.legacyBucketOwner
     - member: projectViewer:k8s-staging-lws
       role: roles/storage.legacyBucketReader
    +- member: serviceAccount:gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com
    +  role: roles/storage.objectCreator
    gs://k8s-staging-lws-gcb/
    @@ -16,3 +16,5 @@
       role: roles/storage.legacyBucketReader
     - member: serviceAccount:gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com
       role: roles/storage.objectCreator
    +- member: serviceAccount:gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com
    +  role: roles/storage.objectViewer
    Ensuring gcb-image-builder@k8s-staging-lws.iam.gserviceaccount.com exists and can sign artifacts in project: k8s-staging-lws 
    Created service account [gcb-image-builder].
    @@ -0,0 +1,7 @@
    +displayName: used by prow to build container images and sign artifacts for k8s-staging-lws
    +email: gcb-image-builder@k8s-staging-lws.iam.gserviceaccount.com
    +etag: MDEwMjE5MjA=
    +name: projects/k8s-staging-lws/serviceAccounts/gcb-image-builder@k8s-staging-lws.iam.gserviceaccount.com
    +oauth2ClientId: '103893335499797883978'
    +projectId: k8s-staging-lws
    +uniqueId: '103893335499797883978'
    Updated IAM policy for serviceAccount [gcb-image-builder@k8s-staging-lws.iam.gserviceaccount.com].
    @@ -1 +1,2 @@
    -[]
    +- member: serviceAccount:gcb-image-builder@k8s-staging-lws.iam.gserviceaccount.com
    +  role: roles/iam.serviceAccountTokenCreator
    Updated IAM policy for project [k8s-staging-lws].
    @@ -10,6 +10,8 @@
       role: roles/cloudbuild.builds.builder
     - member: serviceAccount:gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com
       role: roles/cloudbuild.builds.builder
    +- member: serviceAccount:gcb-image-builder@k8s-staging-lws.iam.gserviceaccount.com
    +  role: roles/cloudbuild.builds.editor
     - member: serviceAccount:k8s-infra-gcr-vuln-scanning@k8s-artifacts-prod.iam.gserviceaccount.com
       role: roles/containeranalysis.occurrences.viewer
     - member: serviceAccount:service-772186053622@containerregistry.iam.gserviceaccount.com
Configuring special cases for Release Managers 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-artifact-promoter 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-build-image 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-ci-images 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-cip-test 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-experimental 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-kubernetes 
  Empowering kubernetes-release-test GCB service account to admin GCR 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-releng 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-releng-test 
  Empowering k8s-infra-release-viewers@kubernetes.io as project viewers in k8s-staging-publishing-bot 
Done
</details>

**Pull request merged**
