### PR TITLE
Promote descheduler images to v0.24.0

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @ingvagabund

**Comment by damemi** [comment]
/hold
just double checking the process is set up right

**Comment by damemi** [comment]
/hold
holding again because we may want to include https://github.com/kubernetes-sigs/descheduler/pull/801 in this release

**Comment by seanmalloy** [comment]
I verified all the image SHA's are correct.

I'm my opinion it is safe to promote this image. A follow up release v0.24.1 can be done to bump to Go version 1.18.2. See below comments for reference.
* https://github.com/kubernetes-sigs/descheduler/pull/801#issuecomment-1133114099
* https://github.com/kubernetes-sigs/descheduler/pull/801#issuecomment-1133115706

/lgtm

**Comment by damemi** [comment]
/hold cancel
like @seanmalloy said, we'll go ahead with these for v0.24.0 and publish a v0.24.1 patch for go1.18.2

**Pull request merged**
