### PR TITLE
Add txtdirect staging repo

### PR DESCRIPTION
**Pull request by stp-ip**
Create staging repo to prepare redirector pulling artifact from Kubernetes controlled location (and (help with testing).

### CODE REVIEW

**Comment by cblecker** [comment]
Why do we need this?

**Comment by stp-ip** [comment]
Tim was suggesting it and it felt like a prerequisite for the redirector PR: https://github.com/kubernetes/k8s.io/pull/227#discussion_r313019427

**Comment by cblecker** [comment]
@thockin Do we need to host our own binary? Why couldn't we just use upstream's directly?

**Comment by cblecker** [comment]
@stp-ip Does txtdirect publish it's own official image somewhere? Or is it just a docker file, and up to the user to build it?

**Comment by stp-ip** [comment]
> @stp-ip Does txtdirect publish it's own official image somewhere? Or is it just a docker file, and up to the user to build it?

txtdirect builds their own images yes. 

In detail:
txtdirect provides a vanity url for containers such as `c.txtdirect.org/txtdirect:dev-9f1280f`, which currently is backed by: https://console.cloud.google.com/gcr/images/txtdirect-223710/GLOBAL/txtdirect

Build is done by GCB into GCR. Vanity url is doing redirects to the underlying store as well as redirect non container requests to the above GCR url so one can see the list just by visiting: `c.txtdirect.org/txtdirect`

**Comment by cblecker** [comment]
I'm fine then with just referencing those images, and not building our own.

@thockin Do you disagree?

**Comment by stp-ip** [comment]
Rebased

**Comment by stp-ip** [comment]
Had a brief discussion with Tim and Ben on this and a rough idea was a multi tier system:
1. Use staging repo + GCB build from the project itself <- opt-in
2. Use staging repo + GCB build from a build repo under k8s <- opt-in, but preferred for critical images such as CoreDNS
3. Use upstream images 

Risks/opportunities
1: Adds another process and does not prevent the code from disappearing
2: Most flexible and might be enough to replace 1 as well. We may bundle release code for each build within the repo or github releases.
3: Risk of loosing access to both builds, build code and code in general.

We don't have clear policies around this and I wanted to loop Tim back in to discuss your concerns.
There needs to be a conscious decision here, which I would love to write down into policy afterwards.
In my view. Let's go with 2 and keep 3 to a minimum.

**Comment by thockin** [comment]
Any reason this needs to be help any longer?

**Comment by stp-ip** [comment]
Rebase done.

**Comment by thockin** [comment]
actuated now

**Pull request merged**
