### PR TITLE
Image promotion for cluster-api v1.7.9

### PR DESCRIPTION
**Pull request by Sunnatillo**
Image promotion for cluster-api v1.7.9
This is an automated PR generated from `kpromo`
```
kpromo pr --fork Sunnatillo --project cluster-api --reviewers "@chrischdi @enxebre @fabriziopandini @sbueringer @vincepri" --tag v1.7.9 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @chrischdi @enxebre @fabriziopandini @sbueringer @vincepri

### CODE REVIEW

**Review by chandankumar4 — APPROVED** [review]
/lgtm

**Comment by Sunnatillo** [comment]
Sha's are checked

**Comment by chrischdi** [comment]
/approve

/hold

for v1.9.0 to merge first

**Pull request merged**
