### PR TITLE
releng: Add CNI maintainers and Release Managers to CNI IAM group

### PR DESCRIPTION
**Pull request by justaugustus**
- Add containernetworking/plugins maintainers to CNI IAM group
- Add Release Managers to CNI IAM group

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

ref: https://github.com/kubernetes/sig-release/issues/245, https://github.com/containernetworking/plugins/issues/446

### CODE REVIEW

**Comment by bartsmykla** [comment]
Hi @justaugustus. Unfortunately I don't know everyone yet. Would you be so kind and give me some help with pointing emails from [commit](https://github.com/kubernetes/k8s.io/pull/591/commits/f86f60452d4011e5e3c88b4df87b09df4f7c6945) to [names of release managers](https://github.com/kubernetes/sig-release/blob/master/release-managers.md)?

**Comment by justaugustus** [comment]
@bartsmykla -- I'm unsure why that question would cause this PR to be held, when that has not be a PR requirement in the past. Has the process changed? Can you explain?
/hold cancel

---

Members of the @kubernetes/release-managers and @kubernetes/sig-release-admins group:

      - caselim@gmail.com - Caleb Miles
      - ctadeu@gmail.com - Carlos Panato
      - dmaceachern@vmware.com - Doug MacEachern
      - feiskyer@gmail.com - Pengfei Ni
      - hhorl@pivotal.io - Hannes Hörl
      - idealhack@gmail.com - Yang Li
      - saschagrunert@gmail.com - Sascha Grunert
      - stephen.k8s@agst.us - Stephen Augustus
      - tpepper@gmail.com - Tim Pepper

**Comment by bartsmykla** [comment]
@justaugustus when I'm accepting or rejecting the PR, I'm signing my name it's correct. As I wrote in my comment I don't know all of the people. I trust you, but still it's much easier to find a mistake when multiple eyes are looking so there was my request for you.
Does anything changes? No.

**Comment by justaugustus** [comment]
Linking the CNI maintainers list so you know them too: https://github.com/containernetworking/plugins/blob/master/OWNERS.md

**Comment by bartsmykla** [comment]
@justaugustus found it before, so didn't ask for those, but thank you for a link

**Pull request merged**
