### PR TITLE
Promote scheduler-plugins release v0.19.8

### PR DESCRIPTION
**Pull request by seanmalloy**
This is the first release that provides a controller image in addition
to a kube-scheduler image. Also, starting with this release AMD64 and
ARM64 images are provided.

### CODE REVIEW

**Comment by seanmalloy** [comment]
My brain is tired. Need to double check that I got all the image SHA's correct.

/hold

**Comment by seanmalloy** [comment]
To the best of my ability all the SHAs line up.

The scheduler and controller images can be pulled from the staging registry using the below commands. I have not done this yet.
```
docker pull gcr.io/k8s-staging-scheduler-plugins/controller:v20210311-v0.19.8
docker pull gcr.io/k8s-staging-scheduler-plugins/kube-scheduler:v20210311-v0.19.8
```

**Comment by seanmalloy** [comment]
I confirmed the images can be pulled from the staging registry. I did not test the images. @Huang-Wei @denkensk feel free to download and test these images prior to approving the PR.

/hold cancel
/assign @Huang-Wei 
/cc @denkensk

**Comment by Huang-Wei** [comment]
Thanks @seanmalloy . Let me verify the image locally and get back to you later.

**Comment by Huang-Wei** [comment]
@seanmalloy I've verified both scheduler and controller images work properly. It's just the document needs to be updated - such as RBAC, ServiceAccount etc. Let's track those in scheduler-plugins repo.

/ok-to-test

**Pull request merged**
