### PR TITLE
Ingress NGINX: Rework images.

### PR DESCRIPTION
**Pull request by Gacko**

### CODE REVIEW

**Review by strongjz — APPROVED** [review]
/approved
/lgtm

**Comment by longwuyuan** [comment]
[The sha of the newly built cfssl image in cloudbuild seems different from the sha being promoted in this PR for the cfssl image. @Gacko hoping you can clarify if its a issue or not
```

```](https://kubernetes.slack.com/archives/C021E147ZA4/p1723623469022479)

**Comment by Gacko** [comment]
This is the commit to `main` which triggered the build: https://github.com/kubernetes/ingress-nginx/commit/b933310da5914adbf3f243b5cf902c245d5a0cef
This is the triggered job: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-ingress-nginx-cfssl/1823305527631810560
And this is the build log: https://storage.googleapis.com/kubernetes-jenkins/logs/post-ingress-nginx-cfssl/1823305527631810560/artifacts/build.log

There you can see:

```
#20 pushing manifest for gcr.io/k8s-staging-ingress-nginx/cfssl:v1.0.0@sha256:fffd36e2f1c8fd485ec6fd24c6d55f0817b54352274293d2a247b8a0d924c5b0
#20 pushing manifest for gcr.io/k8s-staging-ingress-nginx/cfssl:v1.0.0@sha256:fffd36e2f1c8fd485ec6fd24c6d55f0817b54352274293d2a247b8a0d924c5b0 8.7s done
```

So I'd expect this image to be in the staging registry. Anyway, gonna check that later.

**Comment by longwuyuan** [comment]
I was curious if the sha in this image has any relevance from the fact that this is the sha of the latest cfssl image

**Pull request merged**
