### PR TITLE
apps/perfdash: migrate ingress to v1

### PR DESCRIPTION
**Pull request by spiffxp**
Changed fields per https://kubernetes.io/docs/reference/using-api/deprecation-guide/

Part of issue https://github.com/kubernetes/k8s.io/issues/2316

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm
Thanks!

**Comment by spiffxp** [comment]
Hooray, slack notifications for app deployments work!  From https://kubernetes.slack.com/archives/CUD6HL48N/p1627428950009300
Screen Shot 2021-07-27 at 4 38 18 PM

**Comment by spiffxp** [comment]
(I was really using this to verify the results of https://github.com/kubernetes/test-infra/pull/23040 landing)

**Comment by rikatz** [comment]
Ooh this is cool!!

**Pull request merged**
