### PR TITLE
Promotes E2E images

### PR DESCRIPTION
**Pull request by claudiubelu**
Promotes E2E images which were updated in the [1] PR, which removed the Windows Server 20H2 support in the E2E images.

These hashes has been obtained by running:

```
#!/bin/bash

declare -a images=(agnhost:2.41 busybox:1.29-4 httpd:2.4.39-4 httpd:2.4.38-4 jessie-dnsutils:1.7 kitten:1.7 nautilus:1.7 nginx:1.15-4 nginx:1.14-4 nonroot:1.4 redis:5.0.5-3 resource-consumer:1.12 sample-apiserver:1.17.7)

for image in "${images[@]}"; do
  echo "Image: ${image} - $(manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/${image} | jq '.digest')"
done

```

[1] https://github.com/kubernetes/kubernetes/pull/112924

### CODE REVIEW

**Comment by marosset** [comment]
@claudiubelu - do you want to promote resource-consumer:v1.13 as part of this PR too?

If not I'll open up a follow-up PR.

**Comment by claudiubelu** [comment]
> @claudiubelu - do you want to promote resource-consumer:v1.13 as part of this PR too?
> 
> If not I'll open up a follow-up PR.

Added here.

**Comment by marosset** [comment]
/lgtm
Thanks!

**Review by mkumatag — APPROVED** [review]
/lgtm

o/p from the above script:
```shell
Image: agnhost:2.41 - "sha256:920e2d3651a4fe8f6bea4ccbcb18b94435a5500983bea089d4f13a720128341d"
Image: busybox:1.29-4 - "sha256:2e0f836850e09b8b7cc937681d6194537a09fbd5f6b9e08f4d646a85128e8937"
Image: httpd:2.4.39-4 - "sha256:3fe7acf013d1264ffded116b80a73dc129a449b0fccdb8d21af8279f2233f36e"
Image: httpd:2.4.38-4 - "sha256:148b022f5c5da426fc2f3c14b5c0867e58ef05961510c84749ac1fddcb0fef22"
Image: jessie-dnsutils:1.7 - "sha256:24aaf2626d6b27864c29de2097e8bbb840b3a414271bf7c8995e431e47d8408e"
Image: kitten:1.7 - "sha256:03446e7dc02d04378c747bc731fb44249b13bcd836c7ae83aa7690b9e6e57b29"
Image: nautilus:1.7 - "sha256:80ba6c8c44f9623f06e868a1aa66026c8ec438ad814f9ec95e9333b415fe3550"
Image: nginx:1.15-4 - "sha256:db048754ae68ae337d8fa96494c96d2a1204c3320f5dcf7e8e71085adec85da6"
Image: nginx:1.14-4 - "sha256:5c99cf6a02adda929b10321dbf4ecfa00d87be9ba4fb456006237d530ab4baa1"
Image: nonroot:1.4 - "sha256:ee9f50b3c64b174d296d91ca9f69a914ac30e59095dfb462b2b518ad28a63655"
Image: redis:5.0.5-3 - "sha256:0feb07fd50eace4b7ba1a3652fe2819c61cdcf87e39f640a8a39bd5ce3f456b0"
Image: resource-consumer:1.12 - "sha256:30d3e948997ba596f895a8786281201c9d599dc9d8017bca0cec74efbc5e0d44"
Image: resource-consumer:1.13 - "sha256:ba5e047a337e5d0709bc57df45b95b2c7f6f2794b290e4e24f7fc8980d60b25a"
Image: sample-apiserver:1.17.7 - "sha256:8d70890151aa5d096f331cb9da1b9cd5be0412b7363fe67b5c3befdcaa2a28d0"
```

**Pull request merged**
