### PR TITLE
releng: Image promotion for kubernetes v1.21.11 / v1.21.12-rc.0 / v1.22.8 / v1.22.9-rc.0

### PR DESCRIPTION
**Pull request by palnabarun**
Image promotion for kubernetes v1.21.11 / v1.21.12-rc.0 / v1.22.8 / v1.22.9-rc.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork palnabarun --tag v1.21.11 --tag v1.21.12-rc.0 --tag v1.22.8 --tag v1.22.9-rc.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by cpanato** [comment]
> Note: Got a lot of warnings like
> 
> ```
> digest sha256:56c78b65d3e7494cc8d8fe17a708a22b6e88d7003ba57ea9cca216d3f3eb10d5: unsupported MediaType application/vnd.oci.image.manifest.v1+json
> ```
> 
> I am guessing that these are related to the image signatures.
> 
> cc: @puerco @cpanato @saschagrunert

yes

**Comment by palnabarun** [comment]
/hold cancel

(the bot seems to be slow today)

**Comment by ameukam** [comment]
> /hold cancel
> 
> (the bot seems to be slow today)

Current issue with Github: https://www.githubstatus.com/incidents/fpk08rxnqjz2.

**Comment by palnabarun** [comment]
> Current issue with Github: https://www.githubstatus.com/incidents/fpk08rxnqjz2.

😢

**Pull request merged**
