### PR TITLE
Add cloud provider openstack infra

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by mdbooth** [comment]
/lgtm

Thanks, @jichenjc! I was hoping to work on this myself last week but other priorities intervened 😞 I think the next step after this is going to be a `cloudbuild.yaml`, right?

**Comment by jichenjc** [comment]
yes, I am following the guide and do this by a step by step way :)

**Comment by ameukam** [comment]
/approve
/hold

Remove the hold when ready to merge.

**Comment by mdbooth** [comment]
@jichenjc Is this good to go?

**Comment by jichenjc** [comment]
/hold cancel

didn't see above `hold` flag :) 
it's ready to go

**Pull request merged**
