### PR TITLE
Image promotion for cluster-api v1.8.0-beta.0

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Image promotion for cluster-api v1.8.0-beta.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork adilGhaffarDev --project cluster-api --reviewers "@chrischdi @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri" --tag v1.8.0-beta.0 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @chrischdi @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
LGTM

all sha`s are correct.

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
