### PR TITLE
Re-deploy k8s-infra-scalability-tests-logs to kubernetes-public

### PR DESCRIPTION
**Pull request by ameukam**
Ref: https://github.com/kubernetes/k8s.io/pull/2239#issue-672836712.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
Bucket deleted on `k8s-infra-prow-build` project and recreated in `kubernetes-public`.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
