### PR TITLE
Image promotion for capi-operator v0.2.0

### PR DESCRIPTION
**Pull request by alexander-demicev**
Image promotion for capi-operator v0.2.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork alexander-demicev --project capi-operator --tag v0.2.0 --image cluster-api-operator
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by alexander-demicev — COMMENTED** [review]
/unhold
/lgtm

**Comment by cpanato** [comment]
please update kpromo to the latest release and run the command again, that will promote to the correct directory, the `k8s.gcr.io/images` is deprecated

/hold

**Comment by cpanato** [comment]
you can close this PR as well

**Comment by alexander-demicev** [comment]
thanks a lot, didn't notice it's using a deprecated registry

**Pull request closed without merging**
