### PR TITLE
releng: Image promotion for kubernetes v1.22.17 / v1.22.18-rc.0

### PR DESCRIPTION
**Pull request by ameukam**
Image promotion for kubernetes v1.22.17 / v1.22.18-rc.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork ameukam --interactive --reviewers "" --tag v1.22.17 --tag v1.22.18-rc.0
```

/hold
cc:

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Review by puerco — APPROVED** [review]

**Comment by xmudrii** [comment]
/hold
Batch jobs are not yet supported (see https://github.com/kubernetes-sigs/promo-tools/pull/691 for more details).

**Comment by saschagrunert** [comment]
/unhold 
The other PR merged

**Pull request merged**
