### PR TITLE
Add TestGrid API to DNS

### PR DESCRIPTION
**Pull request by chases2**
Attempt at implementation of https://github.com/kubernetes/k8s.io/issues/4710

### CODE REVIEW

**Comment by dims** [comment]
@chases2 verification CI job failed, can you please peek?

**Comment by michelle192837** [comment]
Sean's out for a couple more week unfortunately, but I can try and make a PR with a fix.

**Comment by BenTheElder** [comment]
/close
https://github.com/kubernetes/k8s.io/pull/4792

**Pull request closed without merging**
