### PR TITLE
add DNS for CAPI release-1.5 release branch

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
DNS updates for Cluster API release-1.5 branch.

Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8429

### CODE REVIEW

**Comment by nawazkh** [comment]
Thanks for promptly getting this up @Prajyot-Parab ! Can we also please populate the PR description for others to get the context?

Otherwise it looks good to me!
/lgtm

**Review by nawazkh — APPROVED** [review]

**Comment by killianmuldoon** [comment]
/lgtm
@ameukam for approval


/hold 
To add some information to the PR description linking to this in the CAPI release tasks.

**Pull request merged**
