### PR TITLE
add @puerco to auditors group

### PR DESCRIPTION
**Pull request by puerco**
Hey all, I'd like to start implementing the missing bits on the audit script. I'm requesting access to the auditors group to be able to run it and start coding the missing bits.

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test
/approve

I'm good with this. @thockin @dims ?

**Comment by dims** [comment]
/lgtm

@cblecker please run the script when you get a chance

**Comment by puerco** [comment]
Thanks @cblecker @dims !

**Comment by cblecker** [comment]
Applied. You should now have access.

**Pull request merged**
