### PR TITLE
Add 1 git-crypt collaborator - @spiffxp

### PR DESCRIPTION
**Pull request by dims**
New collaborators:

	D9D2852C Aaron Crickenberger <spiffxp@gmail.com>

This will enable Aaron to run the automation needed for groups.yaml sync to google groups.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by cblecker** [comment]
oh, actually
/lgtm cancel

Can you also add him to https://github.com/kubernetes/k8s.io/blob/master/groups/OWNERS ?

**Comment by dims** [comment]
notes for next time :)

https://medium.com/@sumitkum/securing-your-secret-keys-with-git-crypt-b2fa6ffed1a6

**Pull request merged**
