### PR TITLE
registry.k8s.io: Update known GCP artifact registry prod repositories

### PR DESCRIPTION
**Pull request by ameukam**
Update Test manifest with europe-west3 and europe-west10

### CODE REVIEW

**Comment by ameukam** [comment]
cc @upodroid @dims @BenTheElder

**Comment by ameukam** [comment]
`pull-k8sio-verify` is expected to fail. Adding both regions in https://github.com/kubernetes/k8s.io/pull/6309

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by yussufsh** [comment]
Just want to report that `pull-k8sio-verify` jobs are failing because of this change in all new PRs.

Apologies if I am wrong but on debugging I found the length of registries [here](https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/manifests/k8s-staging-addon-manager/promoter-manifest.yaml) does not match total 22 production registries.

**Comment by yussufsh** [comment]
I see now the PRs to add the new registries are in the open state. I'll wait and check back.

**Pull request merged**
