### PR TITLE
Bump network proxy to 0.31.0

### PR DESCRIPTION
**Pull request by cheftako**
Images for [server](https://pantheon.corp.google.com/gcr/images/k8s-staging-kas-network-proxy/global/proxy-server@sha256:89932c0b3f4bb0d14a2faa6e832cbb665bb83d6953b83b7bf365833f4907e3a6/details), [agent](https://pantheon.corp.google.com/gcr/images/k8s-staging-kas-network-proxy/global/proxy-agent@sha256:a61124c6a86c3a2e1212858a4d82958f727e1bca4fb7e324fde2e7b16f0c6c15/details).

### CODE REVIEW

**Comment by jkh52** [comment]
I double checked the images.

/lgtm

Hold just to allow title update (should say v0.31.0, not v0.30.0)

/hold

**Comment by cheftako** [comment]
Title fixed.

**Pull request merged**
