### PR TITLE
releng: Image promotion for v1.18.16 / v1.18.17-rc.0 / v1.19.8 / v1.19.9-rc.0 / v1.20.3 / v1.20.4-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for Kubernetes v1.18.16 / v1.18.17-rc.0 / v1.19.8 / v1.19.9-rc.0 / v1.20.3 / v1.20.4-rc.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by puerco** [comment]
Thanks @cpanato !
/hold cancel

**Pull request merged**
