### PR TITLE
update owners of CAPO

### PR DESCRIPTION
**Pull request by jichenjc**

### CODE REVIEW

**Comment by jichenjc** [comment]
@mdbooth @hidekazuna @sbueringer let me know your thoughts

**Comment by mdbooth** [comment]
Is there any reason not to add all maintainers here?

**Comment by sbueringer** [comment]
> Is there any reason not to add all maintainers here?

I think it would make sense to have all maintainers in this list

**Comment by jichenjc** [comment]
@mdbooth @sbueringer updated just now

**Comment by jichenjc** [comment]
@seanschneeweiss @tobiasgiese FYI

**Review by mdbooth — APPROVED** [review]
Thanks!

/lgtm

**Pull request merged**
