### PR TITLE
Allow k8s-staging-e2e-test-images GCB to access secrets

### PR DESCRIPTION
**Pull request by spiffxp**
[This job](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-e2e-test-images.yaml) which uses [this cloudbuild.yaml](https://github.com/kubernetes/kubernetes/blob/master/test/images/cloudbuild.yaml) needs to be able to call out to a remote docker instance that can build windows images. We had originally been doing this by using kubernetes secrets, but now that the image build has been moved to GCB, we need to pass in secrets to GCB somehow.

This takes the approach of using Secret Manger, and enabling the secretAccessor role for the GCB service account as described here: https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials#store_credentials

~Note: I have only run `ensure-staging-storage.sh e2e-test-images`, and since our billing quota is maxed out, I had to comment out the `gclouc beta billing projects link` command in `lib.sh` to get it to work.~

~I'd like to hear whether folks think:~
~- we should tighten this down further and only allow secret access on a per-secret basis~
~- we should leave as-is; enable secretmanager for all projects, but special-case per-project secret access~
~- we should make this the default for all staging projects, and ensure each project's GCB can access secrets in that project~

EDIT: narrowed the use case down to https://github.com/kubernetes/k8s.io/pull/857#issuecomment-626838955

It's expected that N staging projects will need their GCB service account to access 3 secrets to talk to a remote windows docker instance.  The secrets are hosted in the k8s-infra-prow-build-trusted project, and IAM policies are added to each of those specific secrets for each of the GCB service accounts (currently N=1)

/cc @claudiubelu @dims

### CODE REVIEW

**Comment by claudiubelu** [comment]
Thanks for doing this. This looks pretty much like what we need in order to get GCB to use the sig-windows Windows build nodes for the Windows images.

However, if I'm not mistaken, this only empowers GCB to have access to the ``k8s-staging-e2e-test-images`` secrets, and the actual secret containing the Windows build nodes certificates was not created yet, right? If you need them, you can find them in prow under the name ``windows-img-promoter-cert``, or I can send them to you if needed.

> 
> I'd like to hear whether folks think:
> 
>     * we should tighten this down further and only allow secret access on a per-secret basis
> 
>     * we should leave as-is; enable secretmanager for all projects, but special-case per-project secret access
> 
>     * we should make this the default for all staging projects, and ensure each project's GCB can access secrets in that project
> 

FWIW, we are going to need to do this in multiple jobs / projects. For example, one other projects I've looked into is CSI secret store driver (https://github.com/kubernetes/test-infra/pull/17335), and other sig-windows folks are looking into other CSI drivers as well, and I'm going to have to do the same for the pause image. So, it would be helpful for multiple projects to be able to access the same secret in order to get the necessary certs.

**Comment by spiffxp** [comment]
I purposely haven't put in the secret yet until I get some consensus on the approach we'd like to take here

If the intent is to share secrets across GCB jobs, then I think I'd rather store the secret in the project hosting the prow build cluster, and special-case access from specific project GCB service account to  specific secrets, eg:

```bash
for prj in "${staging_projects_that_need_windows_secret[@]}"; do
  gcloud secrets add-iam-policy-binding \
    --project="k8s-infra-prow-builds-trusted" windows-img-promoter-cert  \
    --member="serviceAccount:$(gcb_service_account_email "${prj}")" \
    --role="roles/secretmanager.secretAccessor" 
done
```

**Comment by claudiubelu** [comment]
So, if another project will also require access to a specific secret, it will have to send a PR for it, which will have to be approved, right? Yeah, that sounds reasonable to me.

**Comment by spiffxp** [comment]
I have access to the `windows-img-promoter-cert` secret, what I'm less clear on is whether I should jam in a yaml file with base64 encoded keys, or create three secrets for each file contained within

**Comment by claudiubelu** [comment]
Hm, they were sent as files initially, so my original thought was a .tar.gz. I would say that 3 secrets would work best, it's easier to just fetch those secrets and store the contents into the necessary files.

**Comment by spiffxp** [comment]
Stored as three secrets labeled after the old secret name
```console
$ gcloud secrets list --project=k8s-infra-prow-build-trusted --filter=labels.secret-group=windows-img-promoter-cert --format="value(name)"
windows-remote-docker_ca-pem
windows-remote-docker_cert-pem
windows-remote-docker_key-pem
```

**Comment by spiffxp** [comment]
@dims and @thockin any objections to this approach? I've stored the secrets as described in the latest comments, but won't run the script in this PR until it's merged

**Comment by dims** [comment]
No objections from me. feel free to remove hold when ready.

/lgtm
/hold

**Comment by spiffxp** [comment]
Ran `terraform apply` for `infra/gcp/clusters/k8s-infra-prow-build/prow-build` (I needed to update resource definitions to prevent terraform from nuking a nodepool, opened https://github.com/kubernetes/k8s.io/pull/946)
Ran `terraform apply` for `infra/gcp/clusters/k8s-infra-prow-build-trusted/prow-build-trusted`

**Comment by spiffxp** [comment]
Running `./infra/gcp/ensure-staging-storage.sh` ...

**Comment by spiffxp** [comment]
The run bailed out here
```
Configuring staging: release-test
  Ensuring project exists: k8s-staging-release-test
  billingAccountName: billingAccounts/018801-93540E-22A20E
  billingEnabled: true
  name: projects/k8s-staging-release-test/billingInfo
  projectId: k8s-staging-release-test
  Empowering k8s-infra-staging-release-test@kubernetes.io as project viewers
  ERROR: Policy modification failed. For a binding with condition, run "gcloud alpha iam policies lint-condition" to identify issues in condition.
  ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Group k8s-infra-staging-release-test@kubernetes.io does not exist.
```

Which is true, `k8s-infra-staging-release-test@kubernetes.io` doesn't exist in groups.yaml

It looks like https://github.com/kubernetes/k8s.io/pull/742 removed it.  @justaugustus what should we be doing here? I followed a trail of links to https://github.com/kubernetes/release/issues/1161 which indicates it may be safe to delete `release-test` from the list of staging projects and delete the GCP project?

**Comment by spiffxp** [comment]
I'm commenting out mentions of `release-test` out and re-running `./infra/gcp/ensure-staging-storage.sh`

**Comment by justaugustus** [comment]
> It looks like #742 removed it. @justaugustus what should we be doing here? I followed a trail of links to [kubernetes/release#1161](https://github.com/kubernetes/release/issues/1161) which indicates it may be safe to delete `release-test` from the list of staging projects and delete the GCP project?

@spiffxp -- Yep, both `k8s-staging-release-test` and `k8s-infra-sig-release-prototype` are safe to delete.

Active releng projects are listed here: https://github.com/kubernetes/sig-release/blob/master/release-engineering/gcp.md#projects

I think at the time that we had initially raised deleting these projects, @thockin mentioned that there wasn't really a deletion flow for the scripts, so we punted and filed the issue to come back to later.

**Pull request merged**
