### PR TITLE
Add staging for cluster-api-provider-docker and add OWNERS files for cluster-api related repos

### PR DESCRIPTION
**Pull request by detiber**
- Adds a staging repo for cluster-api-provider-docker
- Adds OWNERS files for cluster-api related staging directories
  - approvers are based on the approvers for the code repos.

### CODE REVIEW

**Comment by chuckha** [comment]
/lgtm

i wonder if this will work

**Comment by dims** [comment]
2019/09/06 16:54:07  ======================= Updates =========================
2019/09/06 16:54:21 Trying to create group: k8s-infra-staging-capi-docker@kubernetes.io
2019/09/06 16:54:22 > Successfully created group k8s-infra-staging-capi-docker@kubernetes.io
2019/09/06 16:54:23 > Successfully updated group settings for k8s-infra-staging-capi-docker@kubernetes.io to allow external members and other security settings
2019/09/06 16:54:24 Added davanum@gmail.com to k8s-infra-staging-capi-docker@kubernetes.io as a MEMBER
2019/09/06 16:54:24 Added ha.chuck@gmail.com to k8s-infra-staging-capi-docker@kubernetes.io as a MEMBER
2019/09/06 16:54:25 Added detiber@gmail.com to k8s-infra-staging-capi-docker@kubernetes.io as a MEMBER
2019/09/06 16:54:26 Added hi@amycod.es to k8s-infra-staging-capi-docker@kubernetes.io as a MEMBER
2019/09/06 16:54:26 Added goldsteina@vmware.com to k8s-infra-staging-capi-docker@kubernetes.io as a MEMBER
2019/09/06 16:54:27 Added prignanov@vmware.com to k8s-infra-staging-capi-docker@kubernetes.io as a MEMBER

**Comment by dims** [comment]
```
[dims@dims-a01 16:56] ~/go/src/k8s.io/k8s.io/infra/gcp ⟩ ./ensure-staging-storage.sh capi-docker
capi-docker
Ensuring project exists: k8s-staging-capi-docker
Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-staging-capi-docker].
Waiting for [operations/cp.4675173434034346820] to finish...done.
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-capi-docker/billingInfo
projectId: k8s-staging-capi-docker
Empowering k8s-infra-staging-capi-docker@kubernetes.io as project viewers
Updated IAM policy for project [k8s-staging-capi-docker].
bindings:
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-staging-capi-docker@kubernetes.io
  role: roles/viewer
etag: BwWR6Ku8J2c=
version: 1
Enabling the container registry API
Operation "operations/acf.7d32ae45-df31-4a6e-9bd0-39962c7d3078" finished successfully.
Ensuring the registry exists and is readable
Using default tag: latest
latest: Pulling from pause
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Image is up to date for k8s.gcr.io/pause:latest
k8s.gcr.io/pause:latest
The push refers to repository [gcr.io/k8s-staging-capi-docker/ceci-nest-pas-une-image]
5f70bf18a086: Layer already exists
e16a89738269: Pushed
latest: digest: sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74 size: 938
Digests:
- gcr.io/k8s-staging-capi-docker/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- gcr.io/k8s-staging-capi-docker/ceci-nest-pas-une-image:latest
Deleted [gcr.io/k8s-staging-capi-docker/ceci-nest-pas-une-image:latest].
Deleted [gcr.io/k8s-staging-capi-docker/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-capi-docker.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-capi-docker].
bindings:
- members:
  - serviceAccount:service-44019431644@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-capi-docker@kubernetes.io
  role: roles/viewer
etag: BwWR6K54hWo=
version: 1
Empowering k8s-infra-staging-capi-docker@kubernetes.io to GCR
Enabling the GCS API
Operation "operations/acf.111a314f-a5a9-4507-adc5-bed67ec9900e" finished successfully.
Ensuring the bucket exists and is world readable
Creating gs://k8s-staging-capi-docker/...
Enabling Bucket Policy Only for gs://k8s-staging-capi-docker...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-capi-docker/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-capi-docker/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-capi-docker].
bindings:
- members:
  - serviceAccount:service-44019431644@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-capi-docker@kubernetes.io
  role: roles/viewer
etag: BwWR6LBQGJc=
version: 1
Empowering k8s-infra-staging-capi-docker@kubernetes.io to GCS
Done
```

**Comment by dims** [comment]
Love it when a plan comes together. Kudos to all of you! ❤️ 😍

**Pull request merged**
