### PR TITLE
Update org admins group

### PR DESCRIPTION
**Pull request by cblecker**
Update per https://github.com/kubernetes/k8s.io/pull/370#issuecomment-535349146

Add @dims and @spiffxp.

/assign @dims @thockin 
/approve

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by cblecker** [comment]
Ran the script. They're in the group now.

**Comment by thockin** [comment]
Uggh, we should have called this `k8s-infra-gcp-org-admins`

**Comment by cblecker** [comment]
We can change it?

**Comment by thockin** [comment]
Can you PR me a change before I go delete my own access to the org (which I was about to do :)

I can approve from mobile and you can run the sync, then I can actuate the change this afternoon (scary!)

**Comment by cblecker** [comment]
@thockin https://github.com/kubernetes/k8s.io/pull/380

**Pull request merged**
