### PR TITLE
Adding 1.22 Release Notes shadows to the Google groups

### PR DESCRIPTION
**Pull request by pmmalinov01**
Adding release notes shadow to the mailing lists

/assign @savitharaghunathan @guineveresaenger @annajung @erismaster @divya-mohan0209 @kikisdeliveryservice
/cc @cici37 @Damans227 @sladyn98 @simcard0000

/milestone v1.22

### CODE REVIEW

**Comment by divya-mohan0209** [comment]
I would suggest retaining the names of folks who are choosing to shadow under different roles this cycle & let the respective lead make changes in the comment associated with them.

**Comment by pmmalinov01** [comment]
@divya-mohan0209 Got that and addressed. I was thinking we should let the other Lead add his team as he wishes.

**Comment by pmmalinov01** [comment]
Thanks @dims, you are awesome :)

**Comment by pmmalinov01** [comment]
I did a big misclick, sorry.

**Comment by annajung** [comment]
/hold

@kubernetes/release-team-leads can we address this comment first https://github.com/kubernetes/k8s.io/pull/1978#issuecomment-828677558

**Comment by pmmalinov01** [comment]
This got resolved by [2056](https://github.com/kubernetes/k8s.io/pull/2056)
/close

**Pull request closed without merging**
