### PR TITLE
infra/gcp: mv bash scripts to a dedicated folder

### PR DESCRIPTION
**Pull request by ameukam**
Ref: #516

Move every bash script used for GCP operations to a separated folder.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
I ran 

```shell
ensure-conformance-storage.sh
ensure-releng.sh
```

to ensure nothing is broken.

**Comment by ameukam** [comment]
cc @dims @spiffxp

**Comment by spiffxp** [comment]
Hm, not sure I was quite ready to relocate all the bash to `infra/gcp/bash`... let me see what's outstanding

**Comment by spiffxp** [comment]
I don't see terraform modules relocated in this PR, I'm assuming that's coming (or I can do as followup)

**Comment by spiffxp** [comment]
Ah this had some copy-pasta from https://github.com/kubernetes/k8s.io/pull/2630, this is actually _just_ about moving the bash

**Comment by ameukam** [comment]
> I don't see terraform modules relocated in this PR, I'm assuming that's coming (or I can do as followup)

Sorry. made a mistake during a `git rebase`. 

/retitle infra/gcp: mv bash scripts to a dedicated folder

**Comment by spiffxp** [comment]
I don't see anything major pending

I had a README I was working on for this dir, I'll adjust accordingly and open today/tomorrow

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
