### PR TITLE
Promote agnhost 2.32

### PR DESCRIPTION
**Pull request by mtaufen**
This promotes the version of agnhost with the conformance test fix from
https://github.com/kubernetes/kubernetes/pull/101589

/assign @liggitt 

/sig auth

### CODE REVIEW

**Comment by liggitt** [comment]
not sure how to verify the sha, but I agree with the title of the PR

**Comment by mtaufen** [comment]
`docker pull gcr.io/k8s-staging-e2e-test-images/agnhost:2.32` is how I got it.

**Pull request merged**
