### PR TITLE
Add dns records for the contributor site

### PR DESCRIPTION
**Pull request by mrbobbytables**
I believe these are setup correctly.
Netlify will handle the redirect of k8s.dev to kubernetes.dev.

/cc @cblecker

### CODE REVIEW

**Comment by cblecker** [comment]
Are we ready to go live with the site?

**Comment by mrbobbytables** [comment]
Just about, there is 1 PR open in k/community and the blog post that needs to be merged - but I'd like to get this going so I can make sure all the netlify configs are set / redirects configured on that side.

Think a quiet launch and then when those other 2 items are sorted out we then announce / socialize it.

**Comment by mrbobbytables** [comment]
To follow-up - here is the soft launch plan:
- DNS records are updated, the links are sent to the ContribEx ML for verification / vetting and **not** broadcast widely
- If after 1 week everything appears fine, any small issues resolved we move to launch with a coordinated effort with the marketing team.

**Pull request merged**
