### PR TITLE
triage-party: add sig-release repo and update sig-release-team filters

### PR DESCRIPTION
**Pull request by cpanato**
- add sig-release github repo
- update filters for the sig release tab

Also update the deployment to remove the gh proxy, we are not using that right now

/assign @ameukam

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold

Thank you so much for doing this. Remove hold when ready to deploy.

**Comment by cpanato** [comment]
deploying...

**Comment by cpanato** [comment]
done. watching to see if makes any difference

**Pull request merged**
