### PR TITLE
Add 1.22 CI Signal shadows to email groups

### PR DESCRIPTION
**Pull request by mkorbi**
Adds 1.22 CI Signal shadows to:
-  release-team@
-  release-team-shadows@
-  k8s-infra-prow-viewers@

Removes 1.21 CI Signal shadows from:
-  release-team@
-  release-team-shadows@
-  k8s-infra-prow-viewers@

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]

**Comment by saschagrunert** [comment]
/hold

Do we wanna combine those changes in one single PR, @kubernetes/release-team-leads ?

cc @kubernetes/sig-release-leads

**Comment by divya-mohan0209** [comment]
I would second your suggestion, @saschagrunert . However, there would need to be a single action owner in that case making all of those changes OR all the role leads being given access to a forked branch for pushing their respective changes.

**Comment by justaugustus** [comment]
Let's make this a single action and have one of the RT Lead, RT Lead shadows, or EA take care of it (as they should have access to contact info for the entire 1.22 team).

**Comment by savitharaghunathan** [comment]
> Let's make this a single action and have one of the RT Lead, RT Lead shadows, or EA take care of it (as they should have access to contact info for the entire 1.22 team).

I will create a PR to prune the list. Thanks 😊

**Comment by pmmalinov01** [comment]
@savitharaghunathan thanks for it.

**Comment by spiffxp** [comment]
/close
I'm closing this since `rg 1.21 groups/sig-release/` shows no more 1.21 entries remain.  I think https://github.com/kubernetes/k8s.io/pull/2056 took care of this

**Pull request closed without merging**
