### PR TITLE
Migrate external IP addresses configuration to Terraform

### PR DESCRIPTION
**Pull request by ameukam**
Switch to Terraform for management of external IP addresses except
prow-k8s-io-ingress-staging given it needs to be renamed.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Review by spiffxp — CHANGES_REQUESTED** [review]
/hold
I think this is the right time to try using `for_each` instead of copy pasting resources. This is why I ended up waving off earlier. If I have time to push up my WIP I will. The trick was going to be migrating

**Comment by ameukam** [comment]
> /hold
> I think this is the right time to try using `for_each` instead of copy pasting resources. This is why I ended up waving off earlier. If I have time to push up my WIP I will. The trick was going to be migrating

I didn't want to use the `for_each` because we manage 2 IP versions. I didn't want to introduce more complexity for those resources.

**Review by spiffxp — APPROVED** [review]
/hold cancel
/lgtm
I opened https://github.com/kubernetes/k8s.io/issues/2275 to cover redoing this as `for_each`.  I think it'd be possible to have one set for IPv6 and one for IPv4, or a struct that defaults to ipv4

This is going to get undone by https://github.com/kubernetes/k8s.io/pull/2252 though so I'll merge this and deploy

**Comment by spiffxp** [comment]
I ran into some copy paste errors, opened https://github.com/kubernetes/k8s.io/pull/2276 with what I ultimately deployed

**Comment by spiffxp** [comment]
This is being deployed via https://github.com/kubernetes/k8s.io/pull/2252#issuecomment-870920388

**Comment by spiffxp** [comment]
Got lots of errors like this:
```
Error: Error creating GlobalAddress: googleapi: Error 409: The resource 'projects/kubernetes-public/global/addresses/gcsweb-k8s-io' already exists, alreadyExists
│
│   with google_compute_global_address.gcsweb_k8s_io,
│   on external-ips.tf line 6, in resource "google_compute_global_address" "gcsweb_k8s_io":
│    6: resource "google_compute_global_address" "gcsweb_k8s_io" {
```

I think I'll need to do some import / state mangling

**Comment by spiffxp** [comment]
```
terraform import google_compute_global_address.gcsweb_k8s_io projects/kubernetes-public/global/addresses/gcsweb-k8s-io
terraform import google_compute_global_address.k8s_io_ingress_canary projects/kubernetes-public/global/addresses/k8s-io-ingress-canary
terraform import google_compute_global_address.k8s_io_ingress_canary_v6 projects/kubernetes-public/global/addresses/k8s-io-ingress-canary-v6
terraform import google_compute_global_address.k8s_io_ingress_prod projects/kubernetes-public/global/addresses/k8s-io-ingress-prod
terraform import google_compute_global_address.k8s_io_ingress_prod_v6 projects/kubernetes-public/global/addresses/k8s-io-ingress-prod-v6
terraform import google_compute_global_address.node_perf_dash projects/kubernetes-public/global/addresses/node-perf-dash-k8s-io-ingress-prod
terraform import google_compute_global_address.perf_dash projects/kubernetes-public/global/addresses/perf-dash-k8s-io-ingress-prod
terraform import google_compute_global_address.sippy projects/kubernetes-public/global/addresses/sippy-ingress-prod
terraform import google_compute_global_address.slack projects/kubernetes-public/global/addresses/slack-infra-ingress-prod
terraform import google_compute_global_address.release_triage projects/kubernetes-public/global/addresses/triage-party-release-ingress-prod
```

**Pull request merged**
