### PR TITLE
[cip]Add cluster-api-controller image for image promotion

### LINKED ISSUE #300: Pilot container-image-promoter promotion process with cluster-api
/assign @detiber 
/cc @dims @listx @amy 

refs:
- https://kubernetes.slack.com/archives/CCK68P2Q2/p1562778773325500?thread_ts=1562776843.324300&cid=CCK68P2Q2
- https://github.com/kubernetes/k8s.io/issues/157#issuecomment-510131578

/area artifacts

### PR DESCRIPTION
**Pull request by detiber**
- Adds the cluster-api-controller image for image promotion

Resolves #300 

/assign @dims 
/cc @listx @amy @spiffxp

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
I'll leave /lgtm to others

**Comment by detiber** [comment]
/hold
This is likely blocked on https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/71

**Comment by listx** [comment]
@detiber After adding a line for renaming the image, you will see the dry run in the `pull-k8sio-cip` job with the renamed endpoint.

**Pull request merged**
