### PR TITLE
Add stp-ip to CoreDNS staging group

### PR DESCRIPTION
**Pull request by stp-ip**
Thought it might be helpful for testing or pushing critical CoreDNS patch releases to add myself due to the intersection of CoreDNS maintainer and helping with the infra wg.

Happy for this to be closed without merge, if this doesn't make sense.

### CODE REVIEW

**Comment by cblecker** [comment]
@dims Who’s responsible for this image? sig-network? sig-node?

Ultimately, being involved with the wg doesn’t make a difference, it’s up to the responsible sig to decide who and how their image gets published.

**Comment by dims** [comment]
i'd say sig-release ... WDYT @justaugustus ?

**Comment by cblecker** [comment]
Q: Do we actually rebuild the coredns image? Or do we just pull down the image, and push it up to our repo?

If it's the former, we should put it in GCB because it's a "core" image, and reduce humans to 0.
If it's the latter, could we not use the promoter?

Either way, for core images like this, I think the goal is to get humans out of the loop (ref #367)

**Comment by dims** [comment]
@stp-ip wanna rebase this please?

**Pull request merged**
