### PR TITLE
Reduce the noise on verify fixing yamlint

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Comment by ameukam** [comment]
@kubernetes/release-engineering PTAL.

/hold
I'll advise we wait for the patch releases to get out before we merge this.

**Review by saschagrunert — APPROVED** [review]
Changes LGTM, but let's wait as @ameukam said.

**Review by xmudrii — APPROVED** [review]

**Comment by BenTheElder** [comment]
Hey, you'll have to move this to registry.k8s.io/, sorry we're working on https://github.com/kubernetes/enhancements/issues/3720 ref https://github.com/kubernetes/k8s.io/pull/4934 https://github.com/kubernetes/test-infra/pull/29069 

[forcing bot to process this, will reopen immediately]
/close

**Comment by TerryHowe** [comment]
> The linter is still complaining about the yaml warnings on both set of folders now :( . Error messages are twice as long

Yeh, registry.k8s.io files were not covered in this change. I'll need to rebase and fix them.

/hold

**Comment by TerryHowe** [comment]
/unhold
```
Verifying verify-yamllint.sh
[0;32mSUCCESS[0m  verify-yamllint.sh	34s
```

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by ameukam** [comment]
@TerryHowe we can ignore the `k8s.gcr.io` path since PRs for this path are blocked.

**Pull request merged**
