### PR TITLE
Image promotion for cluster-api-helm v0.1.0-alpha.10

### PR DESCRIPTION
**Pull request by Jont828**
Image promotion for cluster-api-helm v0.1.0-alpha.10
This is an automated PR generated from `kpromo`
```
kpromo pr --fork Jont828 --project cluster-api-helm --reviewers "@Jont828 @CecileRobertMichon @jackfrancis" --tag v0.1.0-alpha.10 --image cluster-api-helm-controller
```

/hold
cc: @Jont828 @CecileRobertMichon @jackfrancis

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by Jont828** [comment]
@CecileRobertMichon Can we approve this?

**Comment by CecileRobertMichon** [comment]
@Jont828 the PR is already approved but it has a hold label

It's up to you to remove the hold when ready to merge

**Pull request merged**
