### PR TITLE
Move ASNs infos to a dedicated place.

### PR DESCRIPTION
**Pull request by ameukam**
Move those files to a dedicated place for better ownership.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
closes: https://github.com/kubernetes/k8s.io/issues/1914

**Review by hh — APPROVED** [review]
/approve
/lgtm

**Comment by BobyMCbobs** [comment]
This is fine. Thank you @ameukam

**Comment by ameukam** [comment]
@BobyMCbobs Can you please add as a followup, a README describing what you plan do to with those informations or what's the intent of `registry.k8s.io ? Could be interesting for anyone looking at this folder. Thank you. :-)

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs Can you please add as a followup, a README describing what you plan do to with those informations or what's the intent of `registry.k8s.io ? Could be interesting for anyone looking at this folder. Thank you. :-)

Made a PR https://github.com/kubernetes/k8s.io/pull/1976

**Pull request merged**
