### PR TITLE
Add bentheelder as cluster admin

### PR DESCRIPTION
**Pull request by ameukam**
As suggested by @thockin: https://github.com/kubernetes/k8s.io/issues/504#issuecomment-582514361. 

cc @BenTheElder @cblecker @bartsmykla 

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/approve
/hold

I'm good with this.

**Comment by BenTheElder** [comment]
I solemnly swear to not break the cluster :+)
https://github.com/kubernetes/kubernetes/pull/79947#issuecomment-510204989

**Comment by dims** [comment]
w00t!

**Comment by dims** [comment]
/approve
/lgtm

@cblecker please release hold when you run the script. thanks!

**Comment by cblecker** [comment]
You're an admin now @BenTheElder . Don't break it :)

**Pull request merged**
