### PR TITLE
Remove 1.20 shadows and add 1.21 Enhancement shadows 

### PR DESCRIPTION
**Pull request by annajung**
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>

- ~Remove all 1.20 SIG release shadows from `release-team-shadows` and `release-team`~
- ~Add all 1.21 Leads to `release-team`~
- Add 1.21 Enhancement shadows to `release-team-shadows` and `release-team`

/assign @palnabarun @onlydole @kikisdeliveryservice @savitharaghunathan @bai

### CODE REVIEW

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Review by onlydole — APPROVED** [review]
This looks good to me! Thank you, @annajung! 

/hold for others to review

**Review by palnabarun — CHANGES_REQUESTED** [review]
@annajung -- as a general note, can we hold off on removing people from the lists?

The reason being some people are returning back to the team. We can prune the list after all the shadows have been finalized and onboarded to the release team.

**Comment by annajung** [comment]
@palnabarun Sure/ So, I shouldn't remove 1.20 Enhancement shadows and leave that for someone else to clean up? Or only clean up Enhancements?

**Comment by palnabarun** [comment]
@annajung -- yup! 👍🏽

**Comment by palnabarun** [comment]
We will clean up the list of any person still annotated with 1.20 after all role leads update the list.

**Comment by annajung** [comment]
PTAL. Edited to include only adding 1.21 Enhancement shadows to the `release-team` and `release-team-shadows`

**Review by palnabarun — APPROVED** [review]
@annajung -- Thank you so much! 👍🏽 

/lgtm
/hold cancel

**Comment by palnabarun** [comment]
/retitle Add 1.21 Enhancement Shadows to release-team@ and release-team-shadows@

**Pull request merged**
