### PR TITLE
artifacts.k8s.io: add managed certificates

### PR DESCRIPTION
**Pull request by justinsb**
The module doesn't seem to be ready for managed certificates yet, but
it seems much clearer when it is explicitly inlined anyway.

### CODE REVIEW

**Comment by justinsb** [comment]
This escalated quickly!  Using the DNS challenge with managed certificates (so I can't see the key) requires me to use the new google_certificate_manager_certificate, but that doesn't work well with our serverless_negs module (it complains that we specify both ssl_certificates and certificate_map on google_compute_target_https_proxy).  Also trying to use the version of the module that supports managed certificates kicks off an upgrade storm which I think we don't want right now.

I figure the raw objects are actually more easy to understand than the module, albeit slightly more tedious.  But the line count is not ridiculous - 90 lines instead of 50 lines - to me that 's worth it.

**Comment by justinsb** [comment]
And we can now do things like:

```
curl -L -v --resolve artifacts.k8s.io:443:34.110.216.12 https://artifacts.k8s.io/binaries/kops/1.26.0-beta.2/darwin/amd64/kops.sha256
```

and

```
curl -L -v --resolve artifacts.k8s.io:80:34.110.216.12 http://artifacts.k8s.io/binaries/kops/1.26.0-beta.2/darwin/amd64/kops.sha256
```

The IPv6 address is `2600:1901:0:a641::` if anyone is feeling fancy.

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by ameukam** [comment]
I think we can merge this.
/approve

**Pull request merged**
