### PR TITLE
chore: add lfx mentee to capg group

### PR DESCRIPTION
**Pull request by richardcase**
Add Phong to the CAPG account so that he can use GCP for the duration of the mentorship.

/cc @cpanato @meobilivang

### CODE REVIEW

**Comment by meobilivang** [comment]
Howdy👋 I'm Phong - just got accepted for [LFX Mentorship Spring '23](https://mentorship.lfx.linuxfoundation.org/project/55469b74-0c98-44f1-b8e1-4244a736bf82) to work on CAPG.

Appreciate for setting this up for me 🙇

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
