### PR TITLE
apps: move prow

### PR DESCRIPTION
**Pull request by ameukam**
Part of https://github.com/kubernetes/k8s.io/issues/2150

move prow(ghproxy) to apps
Ensure script `deploy.sh` is present
Ensure OWNERS is present.
Update k8s.io/README.md to refect changes

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/assign @spiffxp
cc @jimdaga

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
Remove when ready to deploy

**Comment by spiffxp** [comment]
/hold cancel
I'll deploy

**Comment by spiffxp** [comment]
Fixup PR incoming
```
$ ./deploy.sh
persistentvolumeclaim/ghproxy configured
service/ghproxy configured
serviceaccount/ghproxy configured
externalsecret.kubernetes-client.io/k8s-infra-ci-robot-github-token configured
The Deployment "ghproxy" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"component":"ghproxy"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Comment by spiffxp** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates - right, updating a deployment's label selector isn't allowed in v1

since I couldn't tell that anything was using ghproxy in aaa, I deleted/recreated the deployment
```
spiffxp@cloudshell:~/k8s.io/apps/prow (spiffxp-gke-dev)$ k delete -f ghproxy_deployment.yaml
persistentvolumeclaim "ghproxy" deleted
deployment.apps "ghproxy" deleted
service "ghproxy" deleted
spiffxp@cloudshell:~/k8s.io/apps/prow (spiffxp-gke-dev)$ k create -f ghproxy_deployment.yaml
persistentvolumeclaim/ghproxy created
deployment.apps/ghproxy created
service/ghproxy created
spiffxp@cloudshell:~/k8s.io/apps/prow (spiffxp-gke-dev)$ ./deploy.sh
Warning: resource persistentvolumeclaims/ghproxy is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
persistentvolumeclaim/ghproxy configured
Warning: resource deployments/ghproxy is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
deployment.apps/ghproxy configured
Warning: resource services/ghproxy is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
service/ghproxy configured
serviceaccount/ghproxy unchanged
externalsecret.kubernetes-client.io/k8s-infra-ci-robot-github-token unchanged
```

**Pull request merged**
