### PR TITLE
publish scheduler-plugins v0.29.7

### PR DESCRIPTION
**Pull request by Huang-Wei**
Starting from this release, scheduler-plugins adopts distroless image buildkit to generate all-in-one image. So we're not adding images for specific platforms.

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/hold

The images have some issues.

**Comment by Huang-Wei** [comment]
/unhold

Image issues have been fixed.

**Comment by Huang-Wei** [comment]
cc @denkensk could you help /lgtm?

**Review by tenzen-y — COMMENTED** [review]
Feel free to merge this PR.
/lgtm

**Pull request merged**
