### PR TITLE
Image promotion for releng 1.21.2-bullseye-0 / 1.19.7-bullseye-0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for releng 1.21.2-bullseye-0 / 1.19.7-bullseye-0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork cpanato --interactive --project releng --tag 1.21.2-bullseye-0 --tag 1.19.7-bullseye-0
```

related to https://github.com/kubernetes/release/issues/2948

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
