### PR TITLE
Add capi kubeadm repository

### PR DESCRIPTION
**Pull request by liztio**

### CODE REVIEW

**Comment by dims** [comment]
working on this now

**Comment by dims** [comment]
Google groups created - DONE
```
2019/07/18 17:31:29 Trying to create group: k8s-infra-staging-cluster-api-kubeadm@kubernetes.io
2019/07/18 17:31:30 > Successfully created group k8s-infra-staging-cluster-api-kubeadm@kubernetes.io
2019/07/18 17:31:31 > Successfully updated group settings for k8s-infra-staging-cluster-api-kubeadm@kubernetes.io to allow external members and other security settings
2019/07/18 17:31:32 Added davanum@gmail.com to k8s-infra-staging-cluster-api-kubeadm@kubernetes.io as a MEMBER
2019/07/18 17:31:33 Added ha.chuck@gmail.com to k8s-infra-staging-cluster-api-kubeadm@kubernetes.io as a MEMBER
2019/07/18 17:31:34 Added detiber@gmail.com to k8s-infra-staging-cluster-api-kubeadm@kubernetes.io as a MEMBER
2019/07/18 17:31:34 Added vince@vincepri.com to k8s-infra-staging-cluster-api-kubeadm@kubernetes.io as a MEMBER
2019/07/18 17:31:35 Added hi@amycod.es to k8s-infra-staging-cluster-api-kubeadm@kubernetes.io as a MEMBER
2019/07/18 17:31:36 Added frostl@vmware.com to k8s-infra-staging-cluster-api-kubeadm@kubernetes.io as a MEMBER
```

**Comment by dims** [comment]
@liztio we need a shorter id. Also please update the google group name as well in addition to shortening the id in ensure-staging-storage.sh

```
[dims@dims-vmware-laptop 17:32] ~/go/src/k8s.io/k8s.io ⟩ infra/gcp/ensure-staging-storage.sh cluster-api-kubeadm
cluster-api-kubeadm
Ensuring project exists: k8s-staging-cluster-api-kubeadm
ERROR: (gcloud.projects.create) argument PROJECT_ID: Bad value [k8s-staging-cluster-api-kubeadm]: Project IDs must start with a lowercase letter and can have lowercase ASCII letters, digits or hyphens. Project IDs must be between 6 and 30 characters.
Usage: gcloud projects create [PROJECT_ID] [optional flags]
  optional flags may be  --enable-cloud-apis | --folder | --help | --labels |
                         --name | --organization | --set-as-default

For detailed information on this command and its flags, run:
  gcloud projects create --help
```

**Comment by liztio** [comment]
@dims updated, lmk if you want it squashed

**Comment by dims** [comment]
```
2019/07/19 10:20:02  ======================= Updates =========================
2019/07/19 10:20:14 Trying to create group: k8s-infra-staging-capi-kubeadm@kubernetes.io
2019/07/19 10:20:15 > Successfully created group k8s-infra-staging-capi-kubeadm@kubernetes.io
2019/07/19 10:20:16 > Successfully updated group settings for k8s-infra-staging-capi-kubeadm@kubernetes.io to allow external members and other security settings
2019/07/19 10:20:17 Added davanum@gmail.com to k8s-infra-staging-capi-kubeadm@kubernetes.io as a MEMBER
2019/07/19 10:20:17 Added ha.chuck@gmail.com to k8s-infra-staging-capi-kubeadm@kubernetes.io as a MEMBER
2019/07/19 10:20:18 Added detiber@gmail.com to k8s-infra-staging-capi-kubeadm@kubernetes.io as a MEMBER
2019/07/19 10:20:19 Added vince@vincepri.com to k8s-infra-staging-capi-kubeadm@kubernetes.io as a MEMBER
2019/07/19 10:20:20 Added hi@amycod.es to k8s-infra-staging-capi-kubeadm@kubernetes.io as a MEMBER
2019/07/19 10:20:21 Added frostl@vmware.com to k8s-infra-staging-capi-kubeadm@kubernetes.io as a MEMBER
```

**Comment by dims** [comment]
```
[dims@dims-vmware-laptop 10:21] ~/go/src/k8s.io/k8s.io ⟩ infra/gcp/ensure-staging-storage.sh capi-kubeadm
capi-kubeadm
Ensuring project exists: k8s-staging-capi-kubeadm
Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-staging-capi-kubeadm].
Waiting for [operations/cp.6114739646491025278] to finish...done.


Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update

billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-capi-kubeadm/billingInfo
projectId: k8s-staging-capi-kubeadm
Empowering k8s-infra-staging-capi-kubeadm@kubernetes.io as project viewers
Updated IAM policy for project [k8s-staging-capi-kubeadm].
bindings:
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-staging-capi-kubeadm@kubernetes.io
  role: roles/viewer
etag: BwWOCXNZc2E=
version: 1
Enabling the container registry API
Operation "operations/acf.60bf8023-ce7e-486d-9ddc-7ace8657bfed" finished successfully.
Ensuring the registry exists and is readable
Using default tag: latest
latest: Pulling from pause
a3ed95caeb02: Pull complete
4964c72cd024: Pull complete
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Downloaded newer image for k8s.gcr.io/pause:latest
The push refers to repository [gcr.io/k8s-staging-capi-kubeadm/ceci-nest-pas-une-image]
5f70bf18a086: Layer already exists
e16a89738269: Pushed
latest: digest: sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74 size: 938
Digests:
- gcr.io/k8s-staging-capi-kubeadm/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- gcr.io/k8s-staging-capi-kubeadm/ceci-nest-pas-une-image:latest
Deleted [gcr.io/k8s-staging-capi-kubeadm/ceci-nest-pas-une-image:latest].
Deleted [gcr.io/k8s-staging-capi-kubeadm/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-capi-kubeadm.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-capi-kubeadm].
bindings:
- members:
  - serviceAccount:service-778608689920@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-capi-kubeadm@kubernetes.io
  role: roles/viewer
etag: BwWOCXXwIZI=
version: 1
Empowering k8s-infra-staging-capi-kubeadm@kubernetes.io to GCR
Enabling the GCS API
Operation "operations/acf.2c0c2a13-6cef-4c65-b2ed-f159e32d2686" finished successfully.
Ensuring the bucket exists and is world readable
Creating gs://k8s-staging-capi-kubeadm/...
Enabling Bucket Policy Only for gs://k8s-staging-capi-kubeadm...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-capi-kubeadm/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-capi-kubeadm/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-capi-kubeadm].
bindings:
- members:
  - serviceAccount:service-778608689920@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-capi-kubeadm@kubernetes.io
  role: roles/viewer
etag: BwWOCXdvHpQ=
version: 1
Empowering k8s-infra-staging-capi-kubeadm@kubernetes.io to GCS
Done
```

**Pull request merged**
