### PR TITLE
Switch to ManagedCertificate for Triage-Party.

### PR DESCRIPTION
**Pull request by ameukam**
Use a Google-managed SSL certificate through `ManagedCertificate`
for Triage-Party.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
GKE cluster `aaa` is now `1.17.17`:

```
gcloud container clusters describe aaa --format='value(currentMasterVersion)' --region=us-central1
1.17.17-gke.2800
``` 

and meet the requirement to use the GA version of `ManagedCertificate`.

/hold

**Review by cpanato — COMMENTED** [review]
/lgmt

/hold to wait when @ameukam is ready to deploy

**Comment by ameukam** [comment]
Ingress is configured with a new TLS certificate provided by Google : 

```shell
openssl s_client -showcerts -connect release.triage.k8s.io:443
CONNECTED(00000003)
depth=2 C = US, O = Google Trust Services LLC, CN = GTS Root R1
verify return:1
depth=1 C = US, O = Google Trust Services LLC, CN = GTS CA 1D4
verify return:1
depth=0 CN = release.triage.k8s.io
verify return:1
```

https://www.ssllabs.com/ssltest/analyze.html?d=release.triage.k8s.io

**Comment by ameukam** [comment]
The old certificate is removed : 

```shell
kubectl delete certificate release-triage-k8s-io -n triageparty-release
certificate.cert-manager.io "release-triage-k8s-io" deleted
```

**Pull request merged**
