### PR TITLE
AWS: Add a replication role for registry.k8s.io

### PR DESCRIPTION
**Pull request by ameukam**
Related to:
 - https://github.com/kubernetes/registry.k8s.io/issues/172

Define permissions needed to use S3 replication in the same account.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @bryantbiggs

**Review by bryantbiggs — APPROVED** [review]
/lgtm based off https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/examples/s3-replication/iam.tf

**Comment by ameukam** [comment]
cc @dims

**Pull request merged**
