### PR TITLE
GCP: Enable Artifact Registry for the Boskos projects

### PR DESCRIPTION
**Pull request by ameukam**
Ensure the service is enabled for all the Boskos projects.
It's currently not consistent across the entire list.

Also auto-linting of the bash script.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/hold

cc @kubernetes/sig-k8s-infra-leads

**Comment by BenTheElder** [comment]
uhhhh maybe we shouldn't do that?

**Comment by BenTheElder** [comment]
Do we have retention policies for these? What are we pushing to boskos projects? Which users are doing this?

I could've sworn we only used GCS tarballs for kube-up and kops?

**Comment by ameukam** [comment]
> Do we have retention policies for these?

We probably want to set this on AR repos if e2e tests continue to produce those images.

**Comment by ameukam** [comment]
I think we at least need a container registry for `cloud-controller-manager`. No exactly sure which tests need this

**Comment by ameukam** [comment]
@BenTheElder Friendly ping. :)

**Comment by BenTheElder** [comment]
OK, so we'll need to patch the tests to push to AR instead of GCR next, and then we need to see if we can make boskos clean these or otherwise enable a retention policy in every project.

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
