### PR TITLE
Update DNS admins

### PR DESCRIPTION
**Pull request by cblecker**
- Remove @brendandburns, @ixdy, @idvoretskyi, and @hh who are inactive in this area
- Add @bartsmykla and @munnerz (and add @spiffxp to OWNERS)

### CODE REVIEW

**Comment by cblecker** [comment]
/hold
for acks

/assign @bartsmykla @munnerz @spiffxp

**Comment by idvoretskyi** [comment]
No objections :)

**Comment by BenTheElder** [comment]
ACK

**Comment by dims** [comment]
/approve
/lgtm

@cblecker please remove hold when you are ready to merge this

**Comment by cblecker** [comment]
I'm going to leave it to @munnerz to remove the hold when he confirms he's good with more power (and responsibility), as everyone else has already checked in. :)

**Comment by munnerz** [comment]
Ack - yes, thanks!

/unhold

**Comment by cblecker** [comment]
I ran the script!

**Pull request merged**
