### PR TITLE
Add Eric Smalling as member

### PR DESCRIPTION
**Pull request by ericsmalling**
Per conversation with @PushkarJ , please add me as a member of the group.

### CODE REVIEW

**Comment by PushkarJ** [comment]
@ericsmalling has volunteered to shadow me on triaging k/k vulnerability scans, so adding his email address to this list will allow him to get alerted when the next scan fails

/lgtm

**Comment by ericsmalling** [comment]
@tabbysable @IanColdwater - I believe this is waiting on approval from one of you.

**Pull request merged**
