### PR TITLE
apps/prow: Fix URL for jobs results

### PR DESCRIPTION
**Pull request by ameukam**
- Fix URL for job results
- Switch to GKE Workload Identity for the prow-controller-manager

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @spiffxp @dims

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by ameukam** [comment]
Successful job pushed results : 
https://gcsweb.k8s.io/gcs/k8s-infra-prow-results/logs/k8s-infra-prow-heartbeat/1441452546488012800/.

**Comment by ameukam** [comment]
Ref : https://github.com/kubernetes/k8s.io/issues/1394
Umbrella: issue : https://github.com/kubernetes/k8s.io/issues/752

**Pull request merged**
