### PR TITLE
k8s.gcr.io: Remove Artifact registry repositories

### PR DESCRIPTION
**Pull request by ameukam**
Follow-up of:
  - https://github.com/kubernetes/k8s.io/pull/4065

Remove Artifact Registry repositories as destination registries for the
image promoter. An issue with AR IAM block the image promotion
process.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @puerco

**Comment by ameukam** [comment]
We should look at a different approach about to test AR promotion process.

**Comment by puerco** [comment]
Should we te also remove the images from the manifest? If we run it l like this they are going to be promoted to GCR and not AR:
https://github.com/kubernetes/k8s.io/blob/6ca9ca57841206b3b7df976c84356e3d62e8b74f/k8s.gcr.io/images/k8s-staging-experimental/images.yaml#L1-L56

**Comment by ameukam** [comment]
> Should we te also remove the images from the manifest? If we run it l like this they are going to be promoted to GCR and not AR:
> 
> https://github.com/kubernetes/k8s.io/blob/6ca9ca57841206b3b7df976c84356e3d62e8b74f/k8s.gcr.io/images/k8s-staging-experimental/images.yaml#L1-L56

@puerco Done.

**Comment by puerco** [comment]
Awesome, let's kick it :rocket: 
/lgtm

**Pull request merged**
