### PR TITLE
Point node-perf-dash to the new endpoint and remove the staging record.

### PR DESCRIPTION
**Pull request by lorqor**

### CODE REVIEW

**Comment by bartsmykla** [comment]
We also need to change the certificate.yaml file 
/hold

**Comment by lorqor** [comment]
Thanks. Done.

**Comment by bartsmykla** [comment]
DNSes updated:

```shell
✗ dns(dns-push-refactoring#3603bfe) ❀ make push-local
/Users/afrael/Projects/github.com/kubernetes/k8s.io/dns/push.sh \
                --check-zone-script ./octodns-docker/check-zone.py \
                --octodns-config ./octodns-config.yaml \
                --zone-configs zone-configs \
                --confirm
Using /tmp/octodns.rrX7Ru/zones for cooked config files
Dry-run to zones: canary.k8s.io. canary.kubernetes.io. canary.x-k8s.io. canary.k8s-e2e.com.
Push to zones: canary.k8s.io. canary.kubernetes.io. canary.x-k8s.io. canary.k8s-e2e.com.
Testing zone: canary.k8s.io.
  test failed, might be propagation delay, will retry... (1/12)
  test failed, might be propagation delay, will retry... (2/12)
  test failed, might be propagation delay, will retry... (3/12)
  test failed, might be propagation delay, will retry... (4/12)
  test failed, might be propagation delay, will retry... (5/12)
Zone: canary.k8s.io. SUCCEEDED
Testing zone: canary.kubernetes.io.
Zone: canary.kubernetes.io. SUCCEEDED
Testing zone: canary.x-k8s.io.
Zone: canary.x-k8s.io. SUCCEEDED
Testing zone: canary.k8s-e2e.com.
Zone: canary.k8s-e2e.com. SUCCEEDED
Dry-run to zones: k8s.io. kubernetes.io. x-k8s.io. k8s-e2e.com.
Push to zones: k8s.io. kubernetes.io. x-k8s.io. k8s-e2e.com.
Testing zone: k8s.io.
  test failed, might be propagation delay, will retry... (1/12)
  test failed, might be propagation delay, will retry... (2/12)
  test failed, might be propagation delay, will retry... (3/12)
  test failed, might be propagation delay, will retry... (4/12)
Zone: k8s.io. SUCCEEDED
Testing zone: kubernetes.io.
Zone: kubernetes.io. SUCCEEDED
Testing zone: x-k8s.io.
Zone: x-k8s.io. SUCCEEDED
Testing zone: k8s-e2e.com.
Zone: k8s-e2e.com. SUCCEEDED
```

**Pull request merged**
