### PR TITLE
Promote pdcsi v1.8.12 and v1.7.14 to k8s-prod

### PR DESCRIPTION
**Pull request by tyuchn**
[v1.8.12](https://pantheon.corp.google.com/gcr/images/k8s-staging-cloud-provider-gcp/global/gcp-compute-persistent-disk-csi-driver@sha256:f742b86b7501abb632392305a233c7540db4ca97ed66273369cee07ecb1614b5/details?e=-13802955&mods=logs_tg_prod) [v1.7.14](https://pantheon.corp.google.com/gcr/images/k8s-staging-cloud-provider-gcp/global/gcp-compute-persistent-disk-csi-driver@sha256:a89d2a61e9659521d2c99b9b84b48585b2bc063afd15316b78788bae15068b67/details?e=-13802955&mods=logs_tg_prod)

### CODE REVIEW

**Comment by msau42** [comment]
/ok-to-test

I don't see them in head: https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-cloud-provider-gcp/images.yaml

**Comment by mattcary** [comment]
> /ok-to-test
> 
> I don't see them in head: https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-cloud-provider-gcp/images.yaml

thx, I'll push them out

**Pull request merged**
