### PR TITLE
releng: Promote go-runner:v2.3.1-go1.15.9-buster.0

### PR DESCRIPTION
**Pull request by cpanato**
related workstream: https://github.com/kubernetes/release/issues/1940

Prowjob: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-go-runner/1369922648464691200

/assign @justaugustus @hasheddan @saschagrunert @ameukam @xmudrii @puerco 
cc @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
