### PR TITLE
Add go.k8s.io/owners redirect

### PR DESCRIPTION
**Pull request by spiffxp**
So I can answer "what's OWNERS?" with a shorter uri instead
of having to scrounge for a deep link all the time.

### CODE REVIEW

**Comment by spiffxp** [comment]
/close
I'm closing this under the auspices that under the effort to improve coverage of tests for conformance, we shouldn't be writing or promoting tests for beta features (PodDisruptionBudget doesn't appear to be going stable anytime soon, ref: https://github.com/kubernetes/features/issues/85)

**Comment by spiffxp** [comment]
/reopen
errant comment, too many tabs, nevermind

**Comment by ixdy** [comment]
deployed.

**Pull request merged**
