### PR TITLE
Rename seccomp-operator to security-profiles-operator

### PR DESCRIPTION
**Pull request by saschagrunert**
Renaming the operator to it's new proposed name.

Refers to https://github.com/kubernetes/org/issues/2177

### CODE REVIEW

**Comment by saschagrunert** [comment]
Okay, this can be an issue: 
```
groups_test.go:113: Number of characters in project name "security-profiles-operator" should not exceed 18; is: 26
```

**Comment by saschagrunert** [comment]
Can we increase the number of chars for a project name? Otherwise I will think about an abbreviation, like `sp-operator`… 🙂

**Comment by nikhita** [comment]
> Can we increase the number of chars for a project name?

IIRC that restriction comes from Google's side :upside_down_face:

**Comment by nikhita** [comment]
@saschagrunert context here - https://github.com/kubernetes/k8s.io/pull/399

**Comment by saschagrunert** [comment]
Renamed the group name to `sp-operator`

**Comment by saschagrunert** [comment]
@dims can this be merged with the abbreviated group names?

**Comment by spiffxp** [comment]
FYI @dims we should have manually deleted the old renamed project whenever this was actuated.  We don't have anything setup to auto-delete stuff that is "orphaned" from these scripts

**Comment by spiffxp** [comment]
Noticed in https://github.com/kubernetes/k8s.io/pull/1395

**Comment by spiffxp** [comment]
```
$ gcloud projects delete k8s-staging-seccomp-operator
Deleted [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-staging-seccomp-operator].

You can undo this operation for a limited period by running the command below.
    $ gcloud projects undelete k8s-staging-seccomp-operator

See https://cloud.google.com/resource-manager/docs/creating-managing-projects for information on shutting down projects.
```

**Comment by dims** [comment]
@spiffxp good point!

**Pull request merged**
