### PR TITLE
apps: Upgrade redirect to the latest stable version

### PR DESCRIPTION
**Pull request by ameukam**
Related:
  - https://github.com/kubernetes/k8s.io/issues/3131

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
Currently deployed in the canary namespace.

**Comment by ameukam** [comment]
Deployed in the canary namespace:

```bash
$ kubectl get pods -n k8s-io-canary -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}'
W0810 16:09:40.174337    3416 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

k8s-io-67d559c69c-2hjr2:	nginx:1.22-alpine, 
k8s-io-67d559c69c-7hmm8:	nginx:1.22-alpine,
```

**Comment by ameukam** [comment]
Running a few commands to test the new version:

```bash
curl --header  "Host: git.k8s.io" -I http://34.102.239.89/release
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 10 Aug 2022 16:38:09 GMT
Content-Type: text/html
Content-Length: 138
Location: https://github.com/kubernetes/release/
Via: 1.1 google
```
```bash
curl --header  "Host: apt.k8s.io" -I http://34.102.239.89/
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 10 Aug 2022 16:39:12 GMT
Content-Type: text/html
Content-Length: 138
Location: https://packages.cloud.google.com/apt/
Via: 1.1 google
```

```bash
 curl --header  "Host: dl.k8s.io" -I http://34.102.239.89/release/latest.txt
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 10 Aug 2022 16:42:59 GMT
Content-Type: text/html
Content-Length: 138
Location: https://storage.googleapis.com/kubernetes-release/release/latest.txt
Via: 1.1 google
```

```bash
curl --header  "Host: go.k8s.io" -I http://34.102.239.89/oncall
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 10 Aug 2022 16:45:22 GMT
Content-Type: text/html
Content-Length: 138
Location: https://storage.googleapis.com/test-infra-oncall/oncall.html
Via: 1.1 google
```

**Comment by dims** [comment]
/approve
/lgtm
/hold

(please remove hold when ready)

**Pull request merged**
