### PR TITLE
Create gcr.io/k8s-staging-build-image

### PR DESCRIPTION
**Pull request by javier-b-perez**
Create an staging repository where to host the build image kube-cross.
This is part of #158

/assign @dims @justinsb @thockin

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm 
/hold

i'll run the script to create the google group and whoever can create the gcs bucket, please remove the hold and then run the script for creating the bucket.

**Comment by dims** [comment]
DONE!

```
2019/07/03 20:35:29 Trying to create group: k8s-infra-staging-build-image@kubernetes.io
2019/07/03 20:35:30 > Successfully created group k8s-infra-staging-build-image@kubernetes.io
2019/07/03 20:35:31 > Successfully updated group settings for k8s-infra-staging-build-image@kubernetes.io to allow external members and other security settings
2019/07/03 20:35:32 Added davanum@gmail.com to k8s-infra-staging-build-image@kubernetes.io as a MEMBER
2019/07/03 20:35:33 Added jbperez@google.com to k8s-infra-staging-build-image@kubernetes.io as a MEMBER
2019/07/03 20:35:34 Added linusa@google.com to k8s-infra-staging-build-image@kubernetes.io as a MEMBER
```

**Comment by thockin** [comment]
Is this the right scope?  Are there going to be other artifacts that this same group of people will need to administer?

**Comment by javier-b-perez** [comment]
> Is this the right scope? Are there going to be other artifacts that this same group of people will need to administer?

the first item in mind is kube-cross, probably other images required to build, maybe even debian base images.
There might be others from the community as well that are interested in owning kube-cross.

**Comment by thockin** [comment]
Exactly what I was thinking.  And you're happy with "build-image" as the umbrella repo for all these?

**Comment by listx** [comment]
Here are some alternate names for consideration:

"k8s-staging-prelude"
"k8s-staging-build-infra"

But I don't have strong opinions in this area because dims already created the resources and also I don't think we have an official policy on naming conventions anyway.

/lgtm

**Comment by thockin** [comment]
We don't have a convention here, and I don't think we need one.  Just
think forward to the things that will be in here.  Will "build-image"
be sufficiently descriptive that people won't be confused about its
purpose?

Maybe we should add a README in each dir explaining what the point of
that repository is?

**Comment by dims** [comment]
@listx let's do this ...
+1 to add a `k8s.gcr.io/k8s-staging-build-image/README.md` with some details.

**Comment by javier-b-perez** [comment]
Added README.md

**Comment by dims** [comment]
@listx can you please remove hold and run the script to create the new bucket?

**Comment by javier-b-perez** [comment]
@thockin can you please create the bucket/project?

**Comment by dims** [comment]
i'll take care of this @javier-b-perez

**Comment by dims** [comment]
Created the ML

```
2019/07/09 06:37:00 > Successfully created group k8s-infra-staging-build-image@kubernetes.io
2019/07/09 06:37:01 > Successfully updated group settings for k8s-infra-staging-build-image@kubernetes.io to allow external members and other security settings
2019/07/09 06:37:02 Added davanum@gmail.com to k8s-infra-staging-build-image@kubernetes.io as a MEMBER
2019/07/09 06:37:03 Added jbperez@google.com to k8s-infra-staging-build-image@kubernetes.io as a MEMBER
2019/07/09 06:37:04 Added linusa@google.com to k8s-infra-staging-build-image@kubernetes.io as a MEMBER
```

**Comment by dims** [comment]
created the GCS bucket

```
[dims@dims-laptop 06:37] ~/go/src/k8s.io/k8s.io ⟩ ./infra/gcp/ensure-staging-storage.sh build-image
build-image
Ensuring project exists: k8s-staging-build-image
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-build-image/billingInfo
projectId: k8s-staging-build-image
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-build-image.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-build-image].
bindings:
- members:
  - serviceAccount:service-960211007710@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNPSchTgg=
version: 1
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
Empowering k8s-infra-staging-build-image@kubernetes.io to GCR
Enabling the GCS API
Operation "operations/acf.f5ff894a-543a-4e52-9bdb-3abe4c84160e" finished successfully.
Ensuring the bucket exists and is world readable
Creating gs://k8s-staging-build-image/...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-build-image/...
Ensuring the bucket has auto-deletion of 30 days
Setting lifecycle configuration on gs://k8s-staging-build-image/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-build-image].
bindings:
- members:
  - serviceAccount:service-960211007710@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNPShvEwA=
version: 1
Empowering k8s-infra-staging-build-image@kubernetes.io to GCS
Done

```

**Pull request merged**
