### PR TITLE
releng: Add Marky to Release Manager Associates

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
See https://kubernetes.slack.com/archives/C2C40FMNF/p1600794158073200

cc @saschagrunert 

Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
Please update the commit message and PR title to describe what's happening here.
`releng: Add Marky to Release Manager Associates`

The PR title and commit message should be able to stand on their own, without needing context from Slack.
ref: https://github.com/kubernetes/sig-release/issues/1256

**Review by justaugustus — CHANGES_REQUESTED** [review]
@markyjackson-taulia -- A few things:

- My previous comment --> https://github.com/kubernetes/k8s.io/pull/1271#issuecomment-696902572
- Remove yourself from `k8s-infra-prow-viewers@kubernetes.io` (this access is covered by the releng-viewers group)
- Add yourself to the following groups (which are in the `sig-release` subdir):
  - k8s-infra-release-viewers@
  - release-managers@

**Comment by saschagrunert** [comment]
@markyjackson-taulia this commit does not contain any code changes, do you still work on it?

**Comment by dims** [comment]
/hold

nothing to process here as @saschagrunert mentioned

**Comment by markyjackson-taulia** [comment]
@saschagrunert for review

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve
Thanks for the fix!

**Comment by saschagrunert** [comment]
/assign @dims 

For approval.

**Pull request merged**
