### PR TITLE
releng: Image promotion for v1.17.15 / v1.17.16-rc.0 / v1.18.13 / v1.18.14-rc.0 / v1.19.5 / v1.19.6-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for Kubernetes v1.17.15 / v1.17.16-rc.0 / v1.18.13 / v1.18.14-rc.0 / v1.19.5 / v1.19.6-rc.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
