### PR TITLE
Update DNS for development branch for the cluster-api documentation

### PR DESCRIPTION
**Pull request by detiber**
I had previously forgotten that the subdomain used needs to be the same as the branch prefix for the Netlify URL, updated the DNS records accordingly.

/assign @ncdc @cblecker @dims

### CODE REVIEW

**Comment by haosdent** [comment]
lgtm

**Comment by detiber** [comment]
Manual action is still required on this as the DNS update isn't automated on postsubmit (yet).

**Comment by detiber** [comment]
This has been completed now.

**Pull request merged**
