### PR TITLE
Added go.k8s.io/test-health redirect

### PR DESCRIPTION
**Pull request by cjwagner**
Makes https://go.k8s.io/test-health redirect to velodrome Bigquery metrics dashboard at http://velodrome.k8s.io/dashboard/db/bigquery-metrics
/cc @fejta @ixdy

### CODE REVIEW

**Comment by fejta** [comment]
Thanks! I would like Jeff to review this
/unassign

**Comment by ixdy** [comment]
/lgtm
canary cluster passes tests. thanks!

**Comment by ixdy** [comment]
deployed to prod namespace.

**Pull request merged**
