### PR TITLE
Update OWNERS files

### PR DESCRIPTION
**Pull request by ameukam**
Update OWNERS to use aliases and drop fellow contributors.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims

**Comment by dims** [comment]
/approve
/lgtm

/hold

(please remove hold when ready!)

**Comment by ameukam** [comment]
FYI @BenTheElder @upodroid

**Comment by BenTheElder** [comment]
I will again note that the problem with this is it loses the history of which packages you actually reviewed and approved, makes emeritus impossible, and for a repo like this you'd just add the leads to the root owners anyhow

**Comment by BenTheElder** [comment]
(But maybe also explicitly list some or all of them in the subdirs they're actively reviewing with root owners as a fallback, we want to assign leaf reviewers / approvers)

**Pull request merged**
