### PR TITLE
releng: Image promotion for kubernetes v1.23.0-rc.0 / v1.24.0-alpha.0

### PR DESCRIPTION
**Pull request by Verolop**
Image promotion for kubernetes v1.23.0-rc.0 / v1.24.0-alpha.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork verolop --interactive --tag v1.23.0-rc.0 --tag v1.24.0-alpha.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]

**Comment by puerco** [comment]
/approve 
Here we goo

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
