### PR TITLE
Bump network proxy to v0.0.6

### PR DESCRIPTION
**Pull request by Jefftree**
/cc @caesarxuchao 
/assign @cheftako

### CODE REVIEW

**Comment by Jefftree** [comment]
/hold
There seems to be something off with the docker build script after the client/proxy module split.

**Comment by Sh4d1** [comment]
So the push images fails is due to https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/72

**Comment by Jefftree** [comment]
@cheftako We fixed the image push pipeline and I changed this PR to bump to v0.0.6. PTAL

/unhold

**Pull request merged**
