### PR TITLE
k8s-infra-prow-build: Install kubecost

### PR DESCRIPTION
**Pull request by koksay**
Create `kubecost` namespsace and install Kubecost with manifests generated via `helm template`

### CODE REVIEW

**Comment by koksay** [comment]
/hold
it seems that #6468 will be reverted; there is no point in deploying Kubecost w/o that one.

**Comment by koksay** [comment]
/hold
postpone this after kubecon and k8s 1.30 release

**Comment by xmudrii** [comment]
We're yet to consider how we are going to proceed with this one
/lifecycle frozen

**Pull request closed without merging**
