### PR TITLE
AWS: Add account for infrastructure services.

### PR DESCRIPTION
**Pull request by ameukam**
Add an account to support services and resources that can be used across different accounts.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @sftim

**Review by sftim — COMMENTED** [review]
Thanks

/lgtm

/hold
@ameukam feel free to unhold when you want to deploy this

**Comment by ameukam** [comment]
Account and OU created:

```bash
Plan: 2 to add, 0 to change, 0 to destroy.
aws_organizations_organizational_unit.infrastructure: Creating...
aws_organizations_organizational_unit.infrastructure: Creation complete after 2s [id=ou-unv1-pvh1fjp7]
module.infra_shared_services.aws_organizations_account.this: Creating...
module.infra_shared_services.aws_organizations_account.this: Still creating... [10s elapsed]
module.infra_shared_services.aws_organizations_account.this: Creation complete after 13s [id=678544613731]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

**Comment by ameukam** [comment]
Part of:
- https://github.com/kubernetes/k8s.io/issues/4685

**Pull request merged**
