### PR TITLE
Refactor infra/gcp libs

### PR DESCRIPTION
**Pull request by thockin**
lib.sh is getting hard to read or change.  Some simple refactoring will help keep it straight while we do a bigger change to TF (probably).

This is almost entirely moving code around.  I did it in a few commits for easiest review.  If this is better to other eyes than mine, more to follow.

@justaugustus - for #641, you can use `empower_svcacct_to_write_gcs_bucket`

### CODE REVIEW

**Comment by justaugustus** [comment]
LGTM, but I'll leave it to @dims or @cblecker to put their seal on it.

**Comment by thockin** [comment]
adding more reviewers to try to unblock @justaugustus

**Comment by dims** [comment]
Sorry reviewing now @thockin

**Comment by dims** [comment]
/lgtm

sorry for the delay!

**Pull request merged**
