### PR TITLE
Add 1.20 Comms Shadows to release-team and release-team-shadows

### PR DESCRIPTION
**Pull request by jrsapi**
**What this PR does / why we need it:**

This adds all 4 Comms shadows to the 1.20 Kubernetes release
team mailing list and the release team shadows mailing list.

/assign @jeremyrickard @savitharaghunathan @hasheddan @palnabarun @lachie83

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Review by palnabarun — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
/hold
/approve cancel

Your rebase is now also promoting something

**Comment by jrsapi** [comment]
Closing and will resubmit a PR to add Comms shadows emails.

**Pull request closed without merging**
