### PR TITLE
Rename project cpva to cpa

### PR DESCRIPTION
**Pull request by MrHohn**
...and put promoter-manifest.yaml to the correct location.

This is a follow up of https://github.com/kubernetes/k8s.io/pull/725
/assign @listx

### CODE REVIEW

**Comment by MrHohn** [comment]
Re https://github.com/kubernetes/k8s.io/pull/725#issuecomment-610650037, @spiffxp I guess it may be too late now to rename the group? If so I can revert this PR to only fix the promoter-manifest.yaml path.

**Comment by spiffxp** [comment]
I think a rename of the group will work, but I'm less clear whether all of the other staging resources will be auto-deleted, let me take a look

**Comment by listx** [comment]
Belated /lgtm from me

**Comment by spiffxp** [comment]
groups reconciled, now to reconcile the other gcp resources

**Comment by spiffxp** [comment]
Finished run of `./infra/gcp/ensure-staging-storage.sh cpa`

**Comment by MrHohn** [comment]
Thank you @spiffxp!

**Comment by spiffxp** [comment]
I guess the resources didn't get created under the old name, since I was unable to delete what the old project would have been named
```$ gcloud projects delete k8s-staging-cpva
ERROR: (gcloud.projects.delete) User [spiffxp@google.com] does not have permission to access project [k8s-staging-cpva] (or it may not exist): The caller does not have permission```

**Pull request merged**
