### PR TITLE
cluster-api: adjust DNS to new book versioning scheme

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

Implements part of https://github.com/kubernetes-sigs/cluster-api/issues/6017

### CODE REVIEW

**Comment by sbueringer** [comment]
/cc @CecileRobertMichon @fabriziopandini @vincepri 

/hold
Waiting until the certificate has been updated (https://github.com/kubernetes-sigs/cluster-api/issues/6017#issuecomment-1040895843)

**Comment by fabriziopandini** [comment]
/lgtm
thanks for taking care of this!

**Comment by sbueringer** [comment]
/hold cancel
https://github.com/kubernetes-sigs/cluster-api/issues/6017#issuecomment-1041875755


/assign @dims
for approval

**Comment by dims** [comment]
/approve
/lgtm

please watch the jobs here: https://github.com/kubernetes/k8s.io/tree/main/dns#applying-the-update

**Comment by sbueringer** [comment]
Thx for the hint. Job is green. Now checking if our book is still available.. :)

**Pull request merged**
