### PR TITLE
Add staging gcr bucket for cluster-api-aws

### PR DESCRIPTION
**Pull request by detiber**
Adds configuration to enable a staging gcr repo for cluster-api-provider-aws

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

/hold

(hold for anyone who can run the infra/gcp/ensure-staging-storage.sh script.)

**Comment by dims** [comment]
google group has been created

```
2019/07/05 12:05:35 Trying to create group: k8s-infra-staging-cluster-api-provider-aws@kubernetes.io
2019/07/05 12:05:36 > Successfully created group k8s-infra-staging-cluster-api-provider-aws@kubernetes.io
2019/07/05 12:05:36 > Successfully updated group settings for k8s-infra-staging-cluster-api-provider-aws@kubernetes.io to allow external members and other security settings
2019/07/05 12:05:37 Added davanum@gmail.com to k8s-infra-staging-cluster-api-provider-aws@kubernetes.io as a MEMBER
2019/07/05 12:05:38 Added ha.chuck@gmail.com to k8s-infra-staging-cluster-api-provider-aws@kubernetes.io as a MEMBER
2019/07/05 12:05:39 Added detiber@gmail.com to k8s-infra-staging-cluster-api-provider-aws@kubernetes.io as a MEMBER
2019/07/05 12:05:40 Added vince@vincepri.com to k8s-infra-staging-cluster-api-provider-aws@kubernetes.io as a MEMBER
2019/07/05 12:05:40 Added hi@amycod.es to k8s-infra-staging-cluster-api-provider-aws@kubernetes.io as a MEMBER
```

**Comment by dims** [comment]
@detiber hmm, looks like we may have to shorten the length 

```
cluster-api-provider-aws
Ensuring project exists: k8s-staging-cluster-api-provider-aws
ERROR: (gcloud.projects.create) argument PROJECT_ID: Bad value [k8s-staging-cluster-api-provider-aws]: Project IDs must start with a lowercase letter and can have lowercase ASCII letters, digits or hyphens. Project IDs must be between 6 and 30 characters.
```

Can you please use smaller suffix? i.e, shorten `cluster-api-provider-aws` such that even after adding a `k8s-staging-` prefix we are within 30 chars? (we will have to add this validation somewhere!)

**Comment by detiber** [comment]
@dims I updated all references of `cluster-api-provider-aws` to `cluster-api-aws`

**Comment by dims** [comment]
Thanks! new group created old group deleted.

```
2019/07/05 13:14:21 Trying to create group: k8s-infra-staging-cluster-api-aws@kubernetes.io
2019/07/05 13:14:22 > Successfully created group k8s-infra-staging-cluster-api-aws@kubernetes.io
2019/07/05 13:14:23 > Successfully updated group settings for k8s-infra-staging-cluster-api-aws@kubernetes.io to allow external members and other security settings
2019/07/05 13:14:23 Added davanum@gmail.com to k8s-infra-staging-cluster-api-aws@kubernetes.io as a MEMBER
2019/07/05 13:14:24 Added ha.chuck@gmail.com to k8s-infra-staging-cluster-api-aws@kubernetes.io as a MEMBER
2019/07/05 13:14:25 Added detiber@gmail.com to k8s-infra-staging-cluster-api-aws@kubernetes.io as a MEMBER
2019/07/05 13:14:25 Added vince@vincepri.com to k8s-infra-staging-cluster-api-aws@kubernetes.io as a MEMBER
2019/07/05 13:14:26 Added hi@amycod.es to k8s-infra-staging-cluster-api-aws@kubernetes.io as a MEMBER
2019/07/05 13:14:27 > Successfully updated group settings for k8s-infra-staging-kops@kubernetes.io to allow external members and other security settings
2019/07/05 13:14:28 > Successfully updated group settings for k8s-infra-staging-publishing-bot@kubernetes.io to allow external members and other security settings
2019/07/05 13:14:29 > Successfully updated group settings for k8s-infra-team-private@kubernetes.io to allow external members and other security settings
2019/07/05 13:14:31 Removing group k8s-infra-staging-cluster-api-provider-aws@kubernetes.io
```

/approve
/lgtm

/hold

(hold for anyone who can run the infra/gcp/ensure-staging-storage.sh script.)

**Comment by dims** [comment]
@thockin it's a bit better now with the additional powers, but still run into this issue.

```
[dims@dims-a01 12:40] ~/go/src/k8s.io/k8s.io ⟩ ./infra/gcp/ensure-staging-storage.sh cluster-api-aws
cluster-api-aws
Ensuring project exists: k8s-staging-cluster-api-aws
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-cluster-api-aws/billingInfo
projectId: k8s-staging-cluster-api-aws
Enabling the container registry API
Ensuring the registry exists and is readable
Using default tag: latest
latest: Pulling from pause
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Image is up to date for k8s.gcr.io/pause:latest
The push refers to repository [gcr.io/k8s-staging-cluster-api-aws/ceci-nest-pas-une-image]
5f70bf18a086: Preparing
e16a89738269: Preparing
unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

**Comment by dims** [comment]
`Done` :)

```
[dims@dims-a01 12:50] ~/go/src/k8s.io/k8s.io ⟩ ./infra/gcp/ensure-staging-storage.sh cluster-api-aws
cluster-api-aws
Ensuring project exists: k8s-staging-cluster-api-aws
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-cluster-api-aws/billingInfo
projectId: k8s-staging-cluster-api-aws
Enabling the container registry API
Ensuring the registry exists and is readable
Using default tag: latest
latest: Pulling from pause
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Image is up to date for k8s.gcr.io/pause:latest
The push refers to repository [gcr.io/k8s-staging-cluster-api-aws/ceci-nest-pas-une-image]
5f70bf18a086: Layer already exists
e16a89738269: Pushed
latest: digest: sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74 size: 938
Digests:
- gcr.io/k8s-staging-cluster-api-aws/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- gcr.io/k8s-staging-cluster-api-aws/ceci-nest-pas-une-image:latest
Deleted [gcr.io/k8s-staging-cluster-api-aws/ceci-nest-pas-une-image:latest].
Deleted [gcr.io/k8s-staging-cluster-api-aws/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-cluster-api-aws.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-cluster-api-aws].
bindings:
- members:
  - serviceAccount:service-433651898792@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNLkENtJ4=
version: 1
Empowering k8s-infra-staging-cluster-api-aws@kubernetes.io to GCR
Enabling the GCS API
Operation "operations/acf.2f381631-de1f-4abd-b211-92c5c97f4128" finished successfully.
Ensuring the bucket exists and is world readable
Creating gs://k8s-staging-cluster-api-aws/...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-cluster-api-aws/...
Ensuring the bucket has auto-deletion of 30 days
Setting lifecycle configuration on gs://k8s-staging-cluster-api-aws/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-cluster-api-aws].
bindings:
- members:
  - serviceAccount:service-433651898792@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNLkJbr4g=
version: 1
Empowering k8s-infra-staging-cluster-api-aws@kubernetes.io to GCS
Done
```

**Comment by detiber** [comment]
Just verified and this is working as expected, thanks everyone!

**Pull request merged**
