### PR TITLE
Migrate ingress for slack-infra

### PR DESCRIPTION
**Pull request by ameukam**
Switch the API version of the ingress for slack-infra.
Ref: https://github.com/kubernetes/k8s.io/issues/1031

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
Remove when ready to deploy

**Comment by ameukam** [comment]
Ingress applied : 
```console
kubectl apply -n slack-infra -Rf resources/
certificate.cert-manager.io/slack-infra unchanged
ingress.networking.k8s.io/slack-infra configured
...

kubectl get ingress.networking.k8s.io -n slack-infra
NAME          HOSTS   ADDRESS         PORTS     AGE
slack-infra   *       34.107.195.71   80, 443   305d
```

**Pull request merged**
