### PR TITLE
Migrate to broadcom mail address

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

While I'm figuring out if others want to migrate as well

**Comment by sbueringer** [comment]
@vincepri @ncdc Just fyi. Your VMware mail addresses also still show up in this file. Just in case you want to migrate :)

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Comment by neolit123** [comment]
/hold
in case more changes are needed.

**Comment by neolit123** [comment]
> @vincepri @ncdc Just fyi. Your VMware mail addresses also still show up in this file. Just in case you want to migrate :)

generally, using a private email for everything is better in the external space if the employer allows it.

**Comment by sbueringer** [comment]
> > @vincepri @ncdc Just fyi. Your VMware mail addresses also still show up in this file. Just in case you want to migrate :)
> 
> generally, using a private email for everything is better in the external space if the employer allows it.

I'm personally using my private mail for all permissions and my work mail only for the alerts. Because I don't want them in my private mail box :)

**Comment by sbueringer** [comment]
/hold cancel

We're good. For other folks. Please open separate PRs

**Pull request merged**
