### PR TITLE
Promote git-sync v3.3.3

### PR DESCRIPTION
**Pull request by thockin**
cc @nan-yu @janetkuo

### CODE REVIEW

**Comment by stp-ip** [comment]
The v3.3.3 release is missing from the git-sync repo. Happy for this to get merge anyway, but wanted to flag this.

**Comment by thockin** [comment]
I was holding the release announcement until this went in. :)

**Comment by thockin** [comment]
OK, I published the release in github

**Comment by thockin** [comment]
@janetkuo @nan-yu Since you are allowed to approve this now, does one of you care to give an LGTM ?

**Pull request merged**
