### PR TITLE
Enroll prow build clusters to a GKE release channel.

### PR DESCRIPTION
**Pull request by ameukam**
Enrolling prow build clusters to the GKE release channel `STABLE`:
https://cloud.google.com/kubernetes-engine/docs/release-notes-stable.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
This is should validate we can enroll GKE clusters to a release with Terraform. Next step will be to enroll to the rapid channel.

/hold
/assign @spiffxp @thockin

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
Would like to wait for a quiet period to roll this out

**Comment by spiffxp** [comment]
I've run `terraform apply` for both clusters

**Pull request merged**
