### PR TITLE
Setup image release for etcd-manager

### PR DESCRIPTION
**Pull request by hakman**

### CODE REVIEW

**Comment by hakman** [comment]
@dims @ameukam It seems that a script needs to be run to get gs://k8s-staging-etcd-manager-gcb created.
Could you help with that?
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/etcd-manager-postsubmit-push-to-staging/1802725141285703680
```
Running...
$ARTIFACTS is set, sending logs to /logs/artifacts
2024/06/17 15:29:10 Build directory: .
2024/06/17 15:29:10 Config directory: /home/prow/go/src/github.com/kubernetes-sigs/etcd-manager
2024/06/17 15:29:10 cd-ing to build directory: .
2024/06/17 15:29:10 Creating source tarball at /tmp/2658760862...
2024/06/17 15:29:13 Uploading /tmp/2658760862 to gs://k8s-staging-etcd-manager-gcb/source/a2a8b42d-d6fb-4478-86f0-93870465a377.tgz...
BucketNotFoundException: 404 gs://k8s-staging-etcd-manager-gcb bucket does not exist.
2024/06/17 15:29:16 Failed to run some build jobs: [failed to upload source: failed to upload files: exit status 1]
```

**Comment by dims** [comment]
@hakman sorry i meant to do that and forgot.

**Comment by dims** [comment]
Apologies again, looks like we need another piece of the puzzle before we can get this working :( so please watch that one

https://github.com/kubernetes/k8s.io/issues/3961

**Comment by hakman** [comment]
No worries, thanks again @dims!

**Pull request merged**
