### PR TITLE
Add 1.21 Docs Shadows to release-team and release-team-shadows in sig-release groups.yaml

### PR DESCRIPTION
**Pull request by reylejano**
- Add 1.21 Docs shadows to `release-team` and `release-team-shadows` in groups.yaml

/assign @palnabarun @onlydole @kikisdeliveryservice @savitharaghunathan @bai

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by palnabarun — CHANGES_REQUESTED** [review]
@reylejano -- Can we please keep the changeset to only additions for now?

The reason we don't want to remove folks is that some folks are returning to the team. We will prune the list of inactive once all the shadows are onboarded. :)

**Comment by reylejano** [comment]
@palnabarun I made the changes to only additions

**Comment by palnabarun** [comment]
@reylejano -- Thank you :)

/lgtm

**Pull request merged**
