### PR TITLE
Image promotion for cluster-api v1.5.3

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Image promotion for cluster-api v1.5.3
This is an automated PR generated from `kpromo`
```
kpromo pr --fork furkatgofurov7 --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri" --tag v1.5.3 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Seems to be an issue here - we should have 4 images to be promoted.

**Comment by furkatgofurov7** [comment]
@killianmuldoon we have run everything in order, images are in staging repo and post push images job finished [fine](https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api&job=post-cluster-api-push-image), however make promote-images did update only one image 🤔

**Comment by killianmuldoon** [comment]
Can you try runng kpromo again? You'll have to close this PR

**Comment by furkatgofurov7** [comment]
> Can you try runng kpromo again? You'll have to close this PR

Thanks, let me try re-running it. 

/close

**Pull request closed without merging**
