### PR TITLE
Add k8s.dev and kubernetes.dev DNS zones

### PR DESCRIPTION
**Pull request by cblecker**
Add k8s.dev and kubernetes.dev DNS zones to our DNS management. I've already created the zones, this just hooks up the push config.

### CODE REVIEW

**Comment by cblecker** [comment]
cc @mrbobbytables @caniszczyk

**Comment by thockin** [comment]
Mechanically this seems fine - what are we doing with that domain?  Who is running it, paying for it, etc?

**Comment by mrbobbytables** [comment]
@thockin It's for the contributor site. The LF owns the domain 👍 
Here is the current WIP - https://kubernetes-contributor.netlify.app/

You'll be able to goto kubernetes.dev/guide (or k8s.dev/guide) for the contributor guide as well as some of the other resources. Right now the content is pretty lean, but we'll be surfacing more in the future, developer guide, some of our docs on things like mailinglists/zoom/slack etc.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
