### PR TITLE
groups: shard some more group definitions to subdirectories

### PR DESCRIPTION
**Pull request by spiffxp**
Related: 
- Part of: https://github.com/kubernetes/k8s.io/issues/460
- Followup to: https://github.com/kubernetes/k8s.io/pull/2675

The actual group moves are broken down mostly one-group-per-commit with the exception of `k8s-infra-concorm-*`, `k8s-infra-staging-cluster-api-*` and `k8s-infra-staging-capi-*`.  I'll edit the description to summarize.

This is being done to prepare for delegation of group approval authority. Something living in root groups.yaml should be a very rare exception, and root group approvers should only really get notified of group additions or removals, to make sure the name is in line with policy.

This is part 2 of N, I'm trying to avoid a difficult-to-rebase PR hanging out while people add more groups or change memberships.

```
$ git log --pretty=oneline main..HEAD | grep "groups: mv" | awk '{print "- `" $6 "/groups.yaml` now contains: `" $4 "`"}' | sort
```
- `sig-api-machinery/groups.yaml` now contains: `k8s-infra-staging-storage-migrator`
- `sig-apps/groups.yaml` now contains: `k8s-infra-staging-examples`
- `sig-auth/groups.yaml` now contains: `k8s-infra-staging-csi-secrets-store`
- `sig-cli/groups.yaml` now contains: `k8s-infra-staging-kustomize`
- `sig-cloud-provider/groups.yaml` now contains: `k8s-infra-staging-cloud-provider-*`
- `sig-cloud-provider/groups.yaml` now contains: `k8s-infra-staging-kas-network-proxy`
- `sig-cloud-provider/groups.yaml` now contains: `k8s-infra-staging-provider-*`
- `sig-cluster-lifecycle/groups.yaml` now contains: `k8s-infra-staging-etcdadm`
- `sig-cluster-lifecycle/groups.yaml` now contains: `k8s-infra-staging-kops`
- `sig-cluster-lifecycle/groups.yaml` now contains: `k8s-infra-staging-kubeadm`
- `sig-cluster-lifecycle/groups.yaml` now contains: `k8s-infra-staging-scl-image-builder`
- `sig-contributor-experience/groups.yaml` now contains: `k8s-infra-staging-slack-infra`
- `sig-instrumentation/groups.yaml` now contains: `k8s-infra-staging-kube-state-metrics`
- `sig-instrumentation/groups.yaml` now contains: `k8s-infra-staging-metrics-server`
- `sig-instrumentation/groups.yaml` now contains: `k8s-infra-staging-prometheus-adapter`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-cpa`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-dns`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-external-dns`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-gatway-api`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-ingress-nginx`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-ingressconformance`
- `sig-network/groups.yaml` now contains: `k8s-infra-staging-networking`
- `sig-node/groups.yaml` now contains: `k8s-infra-staging-cri-tools`
- `sig-node/groups.yaml` now contains: `k8s-infra-staging-nfd`
- `sig-node/groups.yaml` now contains: `k8s-infra-staging-npd`
- `sig-node/groups.yaml` now contains: `k8s-infra-staging-sp-operator`
- `sig-release/groups.yaml` now contains: `k8s-infra-staging-publishing-bot`
- `sig-scheduling/groups.yaml` now contains: `k8s-infra-staging-descheduler`
- `sig-scheduling/groups.yaml` now contains: `k8s-infra-staging-sched-simulator`
- `sig-scheduling/groups.yaml` now contains: `k8s-infra-staging-scheduler-plugins`
- `sig-storage/groups.yaml` now contains: `k8s-infra-staging-csi`
- `sig-storage/groups.yaml` now contains: `k8s-infra-staging-git-sync`
- `wg-k8s-infra/groups.yaml` now contains: `k8s-infra-staging-infra-tools`

### CODE REVIEW

**Comment by spiffxp** [comment]
Confirmation that there are no membership changes as a result of this:
```
$ go run reconcile.go
2021/09/09 08:57:28 confirm: false -- dry-run mode, changes will not be pushed
2021/09/09 08:57:28 reading config file: config.yaml
2021/09/09 08:57:28 config: BotID:            wg-k8s-infra-api@kubernetes.io
2021/09/09 08:57:28 config: SecretVersion:    projects/k8s-gsuite/secrets/gsuite-groups-manager_key/versions/latest
2021/09/09 08:57:28 config: GroupsPath:       /Users/spiffxp/w/kubernetes/k8s.io/groups
2021/09/09 08:57:28 config: RestrictionsPath: /Users/spiffxp/w/kubernetes/k8s.io/groups/restrictions.yaml
2021/09/09 08:57:28 config: ConfirmChanges:   false
2021/09/09 08:57:28 reading restrictions config file: /Users/spiffxp/w/kubernetes/k8s.io/groups/restrictions.yaml
2021/09/09 08:57:28 reading groups.yaml files recursively at /Users/spiffxp/w/kubernetes/k8s.io/groups
2021/09/09 08:57:28 groups: committee-code-of-conduct/groups.yaml
2021/09/09 08:57:28 groups: committee-product-security/groups.yaml
2021/09/09 08:57:28 groups: committee-steering/groups.yaml
2021/09/09 08:57:28 groups: groups.yaml
2021/09/09 08:57:28 groups: sig-api-machinery/groups.yaml
2021/09/09 08:57:28 groups: sig-apps/groups.yaml
2021/09/09 08:57:28 groups: sig-architecture/groups.yaml
2021/09/09 08:57:28 groups: sig-auth/groups.yaml
2021/09/09 08:57:28 groups: sig-autoscaling/groups.yaml
2021/09/09 08:57:28 groups: sig-cli/groups.yaml
2021/09/09 08:57:28 groups: sig-cloud-provider/groups.yaml
2021/09/09 08:57:28 groups: sig-cluster-lifecycle/groups.yaml
2021/09/09 08:57:28 groups: sig-contributor-experience/groups.yaml
2021/09/09 08:57:28 groups: sig-docs/groups.yaml
2021/09/09 08:57:28 groups: sig-instrumentation/groups.yaml
2021/09/09 08:57:28 groups: sig-network/groups.yaml
2021/09/09 08:57:28 groups: sig-node/groups.yaml
2021/09/09 08:57:28 groups: sig-release/groups.yaml
2021/09/09 08:57:28 groups: sig-scalability/groups.yaml
2021/09/09 08:57:28 groups: sig-scheduling/groups.yaml
2021/09/09 08:57:28 groups: sig-security/groups.yaml
2021/09/09 08:57:28 groups: sig-storage/groups.yaml
2021/09/09 08:57:28 groups: sig-testing/groups.yaml
2021/09/09 08:57:28 groups: wg-k8s-infra/groups.yaml
2021/09/09 08:57:28  ======================= Updates =========================
$
```

**Comment by ameukam** [comment]
/lgtm
/hold
If others want to comment

**Pull request merged**
