### PR TITLE
registry.k8s.io: Add europe-west3 and europe-west10 - Part 1

### PR DESCRIPTION
**Pull request by ameukam**
Add regions europe-west3 and europe-west10 to the promotion process.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering 
cc @upodroid @dims @BenTheElder

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
