### PR TITLE
[WIP] (test): attempt to move existing tag to a different image

### PR DESCRIPTION
**Pull request by listx**
/hold

### CODE REVIEW

**Comment by listx** [comment]
This PR tests that a PR trying to move an existing production tag to a new image should *fail* (presubmit should fail).

**Comment by listx** [comment]
OK looks like the presubmit failed with the wrong error. Fixing that up here: https://github.com/kubernetes/test-infra/pull/23151

**Comment by spiffxp** [comment]
Is this still needed or can we close this now?

**Comment by listx** [comment]
> Is this still needed or can we close this now?

Based on https://github.com/kubernetes/k8s.io/issues/1520#issuecomment-920473393 we can close this.

/close

**Pull request closed without merging**
