### PR TITLE
Added new members to community group

### PR DESCRIPTION
**Pull request by rajula96reddy**
Added new members as discussed in the contrib-ex marketing call

cc: @parispittman

### CODE REVIEW

**Comment by spiffxp** [comment]
/ok-to-test
/approve
/cc @parispittman 
can you confirm with an /lgtm

**Comment by spiffxp** [comment]
@justaugustus Yeah I hear you, we've cut out github team managers to stop manual changes, and we already have ownerless/managerless groups for k8s-infra staging, why not do the same here.  

That said, it's not clear to me at this time whether owners or managers are needed, I could see the need if certain permissions that this tool doesn't reconcile are locked to those roles. I think some outreach is needed before throwing the hammer down.

If you want to give it a go with release-managers I'm in favor of it.

**Comment by justaugustus** [comment]
@spiffxp -- Hmmmm, the first thing that comes to mind as they're mail-enabled groups is moderation.
Should all members be able to moderate messages? 

Anywho, I don't want to distract from this PR. Will open an issue about this.

**Comment by parispittman** [comment]
@spiffxp @justaugustus - all of our managers should be able to moderate messages while the members should only view. it's not public email as individual matters, but not coc, are discussed here. will the new set up mean that everyone listed can view only and/or moderate all the things no matter what?

**Comment by spiffxp** [comment]
@parispittman I think this isn't the place to try and figure out a new owners/manager/members policy, if these changes look good as-is /lgtm and /hold cancel

**Comment by parispittman** [comment]
sure just to keep this going and if there is an issue we will PR in a change. if the folks listed read this, test it; i'll reach out individually. 

/lgtm

**Comment by spiffxp** [comment]
ran `make run -- --confirm` in `/groups`

**Pull request merged**
