### PR TITLE
Image promotion for scl-image-builder v0.1.31

### PR DESCRIPTION
**Pull request by mboersma**
Image promotion for scl-image-builder v0.1.31
This is an automated PR generated from `kpromo`
```
kpromo pr --fork mboersma --project scl-image-builder --reviewers "@AverageMarcus @jsturtevant @kkeshavamurthy @mboersma @drew-viles" --tag v0.1.31
```

/hold
cc: @AverageMarcus @jsturtevant @kkeshavamurthy @mboersma @drew-viles

### CODE REVIEW

**Comment by mboersma** [comment]
SHA `641225c0` matches that at the [staging repository](https://console.cloud.google.com/gcr/images/k8s-staging-scl-image-builder/global/cluster-node-image-builder-amd64@sha256:641225c0172e0ff116f13e494ec85ce859d6f56e058306054c41d1e7dc1502bf/details). 👍🏻

**Review by drew-viles — APPROVED** [review]

**Pull request merged**
