### PR TITLE
move registry-sandbox.k8s.io to the new loadbalancer

### PR DESCRIPTION
**Pull request by BenTheElder**
New GCLB is from https://github.com/kubernetes/k8s.io/pull/5249

The old LB still exists, but the new one should be ready to go already.

We're *only* doing this on the staging deployment, will circle back and do production later after confirming staging is working fine.

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/hold

( please remove hold when ready @BenTheElder )

**Comment by BenTheElder** [comment]
/hold cancel
Here we go!

I've locally overridden resolution in curl and things look good (#5249)

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-dns/1656090157624856576 🟢 

now we keep an eye on https://testgrid.k8s.io/sig-k8s-infra-registry ignoring the pull-* jobs (maybe should make another dashboard without those ...)

**Comment by BenTheElder** [comment]
Note the 107.178.255.82 IP used:

```
$ curl --verbose https://registry-sandbox.k8s.io/v2/pause/manifest/3.1
*   Trying 107.178.255.82:443...
* Connected to registry-sandbox.k8s.io (107.178.255.82) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=registry-sandbox.k8s.io
*  start date: May  9 02:40:52 2023 GMT
*  expire date: Aug  7 03:36:47 2023 GMT
*  subjectAltName: host "registry-sandbox.k8s.io" matched cert's "registry-sandbox.k8s.io"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /v2/pause/manifest/3.1]
* h2h3 [:scheme: https]
* h2h3 [:authority: registry-sandbox.k8s.io]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7fcfd8811400)
> GET /v2/pause/manifest/3.1 HTTP/2
> Host: registry-sandbox.k8s.io
> user-agent: curl/7.87.0
> accept: */*
> 
< HTTP/2 307 
< content-type: text/html; charset=utf-8
< location: https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifest/3.1
< x-cloud-trace-context: 842d86cb81cc1c0daa642050b5dcad7b;o=1
< date: Wed, 10 May 2023 00:15:26 GMT
< server: Google Frontend
< content-length: 115
< via: 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< 
<a href="https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifest/3.1">Temporary Redirect</a>.

* Connection #0 to host registry-sandbox.k8s.io left intact

```

Looks good.

**Pull request merged**
