### PR TITLE
Change alpine registry to avoid docker.io rate limiting 

### PR DESCRIPTION
**Pull request by pkprzekwas**
/assign @ameukam @dims

### CODE REVIEW

**Comment by aojea** [comment]
@pkprzekwas @ameukam @dims 

I see two possible problems with this image, correct me if I'm wrong:
1. depends on `gcr.io`
2. uses `latest` tag

can we use `registry.k8s.io/alpine-with-bash:1.0`instead, or anything from the public registry and with a tag that is not `latest`? I just pick that from https://oci.dag.dev/?repo=registry.k8s.io, but I do not have clear where it is coming from,  we have several images on the public repo that can work for this, `agnhost` per example

**Comment by ameukam** [comment]
@aojea Dockerfile for this image: https://github.com/kubernetes/test-infra/blob/master/images/alpine/Dockerfile

**Comment by aojea** [comment]
yeah, you clarified on the other comment, I think that my suggestion is to pin it

**Pull request merged**
