### PR TITLE
Remove perf-dash-canary.k8s.io subdomain

### PR DESCRIPTION
**Pull request by bartsmykla**
Waiting for confirmation from @mm4tt or @wojtek-t everything works and we can remove perf-dash-canary.k8s.io

/hold
/cc @mm4tt @wojtek-t 

ref. #549, #776 

+ removed subdomain from perf-dash certificate manifest

Signed-off-by: Bart Smykla <bsmykla@vmware.com>

### CODE REVIEW

**Comment by mm4tt** [comment]
Everything works, feel free to proceed.

Thanks!

**Comment by bartsmykla** [comment]
DNS were reconcilled and new `certificate.yaml` applied to the cluster

**Pull request merged**
