### PR TITLE
update root owners with current TLs

### PR DESCRIPTION
**Pull request by BenTheElder**
/cc @ameukam @dims 
FYI @upodroid

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/approve

_With great power, come great responsibilities..._

cc @thockin

**Comment by upodroid** [comment]
Can you apply this patch as well please? couple of `no_parent_owners` without the main alias

```
 mahamed  MAHAALI-M-2PY9  ~  Desktop  Git  k8s.io   main  4✎  $  git diff main
diff --git a/OWNERS b/OWNERS
index 39ed6d701..64683eb60 100644
--- a/OWNERS
+++ b/OWNERS
@@ -5,12 +5,14 @@ approvers:
 - cblecker # sig-contribex tl
 - dims # sig-k8s-infra chair
 - nikhita # sig-contribex tl
-- spiffxp # sig-k8s-infra chair
+- upodroid # sig-k8s-infra tl
+- bentheelder # sig-k8s-infra tl
 - thockin
 
 emeritus_approvers:
 - mikedanese
 - bartsmykla
+- spiffxp
 
 labels:
 - sig/k8s-infra
diff --git a/artifacts/OWNERS b/artifacts/OWNERS
index 41bfafc93..0339a2476 100644
--- a/artifacts/OWNERS
+++ b/artifacts/OWNERS
@@ -3,7 +3,7 @@
 options:
   # Root approvers for this repo include contributors who are not involved
   # in artifact promotion. We're blocking root approvals here to ensure
-  # manifests are reviewed by Release Engineering and/or WG K8s Infra
+  # manifests are reviewed by Release Engineering and/or SIG K8s Infra
   # approvers.
   #
   # Long-term, a separate repo has been proposed for these artifact promotion
diff --git a/dns/OWNERS b/dns/OWNERS
index 100c195ff..b402530c9 100644
--- a/dns/OWNERS
+++ b/dns/OWNERS
@@ -3,15 +3,13 @@
 options:
   no_parent_owners: true
 approvers:
-  - ameukam
-  - bentheelder
-  - cblecker
-  - dims
-  - munnerz
-  - spiffxp
+  - sig-k8s-infra-leads
   - thockin
 emeritus_approvers:
   - bartsmykla
+  - spiffxp
+  - cblecker
+  - munnerz
 
 labels:
   - area/dns
diff --git a/groups/OWNERS b/groups/OWNERS
index d7d65ee11..eb4f911f7 100644
--- a/groups/OWNERS
+++ b/groups/OWNERS
@@ -8,11 +8,9 @@ options:
   no_parent_owners: true
 
 approvers:
-- ameukam
 - cblecker
-- dims
 - thockin
-- spiffxp
+- sig-k8s-infra-leads
 - nikhita
 
 reviewers:
```

**Comment by BenTheElder** [comment]
done

**Pull request merged**
