### PR TITLE
WIP: Tool to create LoadBalancer in front of GCS backend

### PR DESCRIPTION
**Pull request by justinsb**
All hard-coded currently, but working towards declarative management.

### CODE REVIEW

**Comment by justinsb** [comment]
/assign thockin

WIP, but this is IMO an easier way to manage than bash.  This could be because I don't have a good bash hammer though.

**Comment by thockin** [comment]
Who write this in Go rather than shell+gcloud?

**Comment by justinsb** [comment]
So I'm hoping we can:

* Have richer reconciliation than we can realistically/reliably implement in bash (we're not there yet in the go code, to be fair)
* Use this same code/mechanism for auditing (hence the separate Find function)
* Use this same code/mechanism for dry-run (again, the Find vs Reconcile split)
* Reuse and share this code in other places in k8s where we configure infrastructure
* Work towards a maintainable code base that allows other developers to contribute - bash is not great for collaboration, and our bash code doesn't have a great track record

**Comment by justinsb** [comment]
We chose to do this in bash instead

/close

**Pull request closed without merging**
