### PR TITLE
Rename seccomp-operator images and manifests to security-profiles-operator

### PR DESCRIPTION
**Pull request by saschagrunert**
The directories still had the old seccomp-operator name, which is now fixed.

cc @hasheddan @pjbgf

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
approve in principle, but would like to confirm the old named infra doesn't exit before removing hold

**Comment by spiffxp** [comment]
Yes, the old project does exist
```
$ gcloud projects describe k8s-staging-seccomp-operator
createTime: '2020-07-20T10:36:19.356Z'
lifecycleState: ACTIVE
name: k8s-staging-seccomp-operator
parent:
  id: '758905017065'
  type: organization
projectId: k8s-staging-seccomp-operator
projectNumber: '494128219691'
```

I'm going to delete once I find whatever PR/issue renamed it

**Comment by spiffxp** [comment]
Looks like we failed to delete the old project during the rename https://github.com/kubernetes/k8s.io/pull/1313

**Comment by spiffxp** [comment]
/hold cancel
old project has been deleted

**Comment by saschagrunert** [comment]
Thank you @spiffxp :pray: !

**Pull request merged**
