### PR TITLE
Move cert-manager to apps

### PR DESCRIPTION
**Pull request by jimdaga**
## Resolves:
* https://github.com/kubernetes/k8s.io/issues/2150 (Part of umbrella issue)

## Notes:
- It's my understanding that cert-manager may be sunset soon, so keeping the changes limited in this PR.

## Changes:
* Move `cert-manager` directory under the `apps/cert-manager` path.
* Add  default `deploy.sh` script.
* Update various README notes:
  - Link to the current version of docs for the running version of cert-manager (v0.13)
  - Add note about having to setup `clusterrolebinding` 
  - Update with the `deploy.sh` info

## Question 
- [ ] Are we OK with leaving the `clusterrolebinding` step outside of `deploy.sh`?

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/approve
/hold

Leave the `/hold cancel` to @spiffxp. :-)

**Comment by spiffxp** [comment]
Hm
```
$ ./deploy.sh
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io configured
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io configured
namespace/cert-manager unchanged
serviceaccount/cert-manager-cainjector unchanged
serviceaccount/cert-manager unchanged
serviceaccount/cert-manager-webhook unchanged
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector unchanged
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:auth-delegator configured
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:webhook-requester unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges unchanged
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-view unchanged
clusterrole.rbac.authorization.k8s.io/cert-manager-edit unchanged
service/cert-manager unchanged
service/cert-manager-webhook unchanged
deployment.apps/cert-manager-cainjector configured
deployment.apps/cert-manager unchanged
deployment.apps/cert-manager-webhook configured
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook configured
clusterissuer.cert-manager.io/letsencrypt-prod configured
clusterissuer.cert-manager.io/letsencrypt-staging configured
clusterissuer.cert-manager.io/selfsigning-issuer unchanged
the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "cert-manager". You must pass '--namespace=kube-system' to perform this operation.
```

Diffing output of `kubectl get clusterissuer -A` from before and after
```
10c10
<     generation: 2
---
>     generation: 3
12c12
<     resourceVersion: "254365400"
---
>     resourceVersion: "436255683"
31c31
<             name: k8s-io-v6
---
>             name: k8s-io
53c53
<     generation: 2
---
>     generation: 3
55c55
<     resourceVersion: "114571644"
---
>     resourceVersion: "436255688"
79d78
<           - smyk.la
```

**Comment by spiffxp** [comment]
Two things:
1. cert-manager.yaml has resources specified in multiple namespaces 
  - I don't want to munge cert-manager.yaml too much or try to figure out if it can be redone to not use kube-system
  - We could make deploy.sh not use a namespace flag here and just trust the resources to do the right thing
  - We could split the file into cluster-scoped and namespace-scoped (similar to what I've done for a non-/apps thing in https://github.com/kubernetes/k8s.io/pull/2371)
2. the change k8s-io-v6 to k8s-io   
  - I'm trying to track down what this is or was about, will edit with more info

**Comment by ameukam** [comment]
@spiffxp the certificate remaining managed by cert-manager is `k8s-io-canary`. It's a self-signed certificate. Plan is to replace it with 10-year certificate manually created : https://github.com/kubernetes/k8s.io/issues/2173

**Comment by jimdaga** [comment]
@spiffxp It looks like `cert-manager.yaml` is just a clone of https://github.com/jetstack/cert-manager/releases/download/v0.13.1/cert-manager.yaml with one change. 

```
diff ~/Downloads/cert-manager.yaml ~/git/k8s.io/cert-manager/cert-manager.yaml
6277c6277
<
---
>
6324a6325
>           - --max-concurrent-challenges=20
6337c6338
<
---
>
6397c6398
<
---
>
6468c6469
<
---
>
```

Per their docs, we don't need namespace:
```
$ kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.13.1/cert-manager.yaml
```
So I think removing the namespace logic from `deploy.sh` will be fine.

**Comment by jimdaga** [comment]
PR with that change if you agree with removing namespace: https://github.com/kubernetes/k8s.io/pull/2379

**Comment by spiffxp** [comment]
You beat me to the deploy.sh change, I'll rebase https://github.com/kubernetes/k8s.io/pull/2380 on top of that

**Comment by spiffxp** [comment]
>Are we OK with leaving the clusterrolebinding step outside of deploy.sh?
I will look at this next, but am not sure how deeply it's worth answering this if we're going to get rid of it.

**Pull request merged**
