### PR TITLE
some fixes to cip-auditor/deploy.sh

### PR DESCRIPTION
**Pull request by listx**
I encountered these while trying to run it as

```
$ ./deploy.sh k8s-artifacts-prod 5c9a73a90fdfd08adaf3d53ae863144922958911952dfa67cbf9a0d33dedde63
```

(The digest is from the auditor image that was just promoted moments ago in https://github.com/kubernetes/k8s.io/pull/595).

FWIW, the deployment did *not* succeed because the Cloud Run API has not yet been enabled for the k8s-artifacts-prod project. Below is the full log:

```
 $ ./deploy.sh k8s-artifacts-prod 5c9a73a90fdfd08adaf3d53ae863144922958911952dfa67cbf9a0d33dedde63
API [run.googleapis.com] not enabled on project [388270116193]. Would 
you like to enable and retry (this will take a few minutes)? (y/N)?  y

Enabling service [run.googleapis.com] on project [388270116193]...
ERROR: (gcloud.run.deploy) PERMISSION_DENIED: The caller does not have permission
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: |-
    [ORIGINAL ERROR] generic::permission_denied: Permission denied to enable service [run.googleapis.com]
     Details: [{
    	[Failure: Permission denied to enable service [run.googleapis.com]
     Checks:
    AND-ServiceAccessAndenableCheck
    {
    	IAM{policy: 'serviceusage_services-/resourcemanager_projectnumbers/\/0000005a66b3cd61/services/run.googleapis.com' resource: 'projectnumbers/388270116193/services/run.googleapis.com' 	permission: 'serviceusage.services.enable'}
    	allowed: false auditlog: true cloudaudit: false
    }
    {
    	IAM{policy: 'servicemanagement_services-/000000a878b0410c/run.googleapis.com' resource: 'services/run.googleapis.com' 	permission: 'servicemanagement.services.bind'}
    	allowed: true auditlog: false cloudaudit: false
    }/AND-ServiceAccessAndenableCheck]
    	allowed: false auditlog: true cloudaudit: false
    }]

     (Neither system permission tenantmanagement.write granted nor fine-grained check com.google.api.tenant.auth.PublicAnnotations$DefaultTenantManagerAuthChecker passed): securityContext=RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithObligations{delegate=ValidatedSecurityContextWithPeer{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0x1a468bb4a7, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=jdog26.prod.google.com;is_authenticated_host=false;role=one-platform-tenant-manager;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=loggable_peer { username: "one-platform-tenant-manager" primary_role: "one-platform-tenant-manager" unauthenticated_host: "jdog26.prod.google.com" jobname_chosen_by_user: "prod.tenant-manager-server" unauthenticated_borg_cell: "jd" }}}}}}}}
    com.google.apps.framework.auth.IamPermissionDeniedException: Permission denied to enable service [run.googleapis.com]
     Details: [{
    	[Failure: Permission denied to enable service [run.googleapis.com]
     Checks:
    AND-ServiceAccessAndenableCheck
    {
    	IAM{policy: 'serviceusage_services-/resourcemanager_projectnumbers/\/0000005a66b3cd61/services/run.googleapis.com' resource: 'projectnumbers/388270116193/services/run.googleapis.com' 	permission: 'serviceusage.services.enable'}
    	allowed: false auditlog: true cloudaudit: false
    }
    {
    	IAM{policy: 'servicemanagement_services-/000000a878b0410c/run.googleapis.com' resource: 'services/run.googleapis.com' 	permission: 'servicemanagement.services.bind'}
    	allowed: true auditlog: false cloudaudit: false
    }/AND-ServiceAccessAndenableCheck]
    	allowed: false auditlog: true cloudaudit: false
    }]

     (Neither system permission tenantmanagement.write granted nor fine-grained check com.google.api.tenant.auth.PublicAnnotations$DefaultTenantManagerAuthChecker passed): securityContext=RecordingSecurityContext{delegate=ValidatedSecurityContextWithSystemAuthorizationPolicy{delegate=ValidatedSecurityContextWithObligations{delegate=ValidatedSecurityContextWithPeer{delegate=ContextWithGaiaMintToken{delegate=ValidatedIamSecurityContext{user=gaiauser/0x1a468bb4a7, creds=EndUserCreds{loggable_credential { type: GAIA_MINT loggable_gaia_mint { } } loggable_credential { type: SERVICE_CONTROL_TOKEN }}, peer=protocol=loas;psp_version=0;level=strong_privacy_and_integrity;host=jdog26.prod.google.com;is_authenticated_host=false;role=one-platform-tenant-manager;security_realm=campus-sln;is_delegated=false;user_type=MDB_USER_NON_PERSON, InternalIAMIdentity{log=loggable_peer { username: "one-platform-tenant-manager" primary_role: "one-platform-tenant-manager" unauthenticated_host: "jdog26.prod.google.com" jobname_chosen_by_user: "prod.tenant-manager-server" unauthenticated_borg_cell: "jd" }}}}}}}}
```

/cc @dims can you enable Cloud Run api for `k8s-artifacts-prod`?

### CODE REVIEW

**Comment by listx** [comment]
@dims There's a chance we might have to jump over a couple more hoops because some other APIs necessary for the auditor might not have been enabled yet.

/cc @thockin

**Comment by dims** [comment]
seems to be already enabled @listx 

```
dims@dims-a01:~$ gcloud --project=k8s-artifacts-prod services list
NAME                                 TITLE
bigquery.googleapis.com              BigQuery API
bigquery.googleapis.com              BigQuery API
bigquerystorage.googleapis.com       BigQuery Storage API
cloudapis.googleapis.com             Google Cloud APIs
clouddebugger.googleapis.com         Stackdriver Debugger API
clouderrorreporting.googleapis.com   Stackdriver Error Reporting API
cloudresourcemanager.googleapis.com  Cloud Resource Manager API
cloudtrace.googleapis.com            Stackdriver Trace API
compute.googleapis.com               Compute Engine API
containeranalysis.googleapis.com     Container Analysis API
containerregistry.googleapis.com     Container Registry API
containerscanning.googleapis.com     Container Scanning API
datastore.googleapis.com             Cloud Datastore API
logging.googleapis.com               Stackdriver Logging API
monitoring.googleapis.com            Stackdriver Monitoring API
oslogin.googleapis.com               Cloud OS Login API
pubsub.googleapis.com                Cloud Pub/Sub API
run.googleapis.com                   Cloud Run API
servicemanagement.googleapis.com     Service Management API
serviceusage.googleapis.com          Service Usage API
sql-component.googleapis.com         Cloud SQL
stackdriver.googleapis.com           Stackdriver API
storage-api.googleapis.com           Google Cloud Storage JSON API
storage-component.googleapis.com     Cloud Storage
```

**Comment by dims** [comment]
/approve
/lgtm
/hold

please remove hold if you want to merge, +1 to iterate to get this working. just ping me with fresh PRs

**Comment by listx** [comment]
@dims I am coordinating with thockin on this right now which is why you see the updated Cloud Run api being enabled (Tim did that just now). Still, the changes in this PR fix the deploy script's unbound variables so they should still be merged.

**Comment by dims** [comment]
/hold cancel

Ack thanks @listx @thockin

**Pull request merged**
