### PR TITLE
groups.yaml: add 1.20 Enhancements Shadows

### PR DESCRIPTION
**Pull request by kikisdeliveryservice**
add shadows to release-team and release-team-shadows

### CODE REVIEW

**Comment by kikisdeliveryservice** [comment]
cc: @lachie83

**Comment by dims** [comment]
needs rebase @kikisdeliveryservice

**Comment by kikisdeliveryservice** [comment]
@dims thanks fixed!

**Comment by dims** [comment]
/approve

please ask one of the leads to `/lgtm` @kikisdeliveryservice

**Pull request merged**
