### PR TITLE
Add xmudrii as K8s Infra Tech Lead

### PR DESCRIPTION
**Pull request by xmudrii**
Add myself (@xmudrii) as a SIG K8s Infra Tech Lead.

**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/community/issues/8204

/assign @BenTheElder @dims @ameukam @upodroid

### CODE REVIEW

**Comment by dims** [comment]
Need to update test case as well :) 

/approve

**Comment by xmudrii** [comment]
@dims Fixed, PTAL :)

**Pull request merged**
