### PR TITLE
remove notice that the promoter is WIP

### PR DESCRIPTION
**Pull request by listx**
/cc @dims @bskiba

### CODE REVIEW

**Comment by bskiba** [comment]
There is a second mention of it [closer to the top of the page](https://github.com/kubernetes/k8s.io/blob/c84b048020a4642c63d56b9bd082166684f4ac89/k8s.gcr.io/README.md#staging-repos)

**Comment by listx** [comment]
> There is a second mention of it [closer to the top of the page](https://github.com/kubernetes/k8s.io/blob/c84b048020a4642c63d56b9bd082166684f4ac89/k8s.gcr.io/README.md#staging-repos)

ACK, changed.

**Pull request merged**
