### PR TITLE
fix some permission errors around the cip-auditor deployment script

### PR DESCRIPTION
**Pull request by listx**
These errors were encountered today while trying to run the deployment script (`infra/gcp/cip-auditor/deploy.sh`).

/cc @thockin @dims
/hold

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by listx** [comment]
> This Looks OK. Have you actually run it?

No, because I don't have access to edit things inside k8s-artifacts-prod.

**Comment by thockin** [comment]
OK.  I ran it and it completed successfully

**Comment by listx** [comment]
> > This Looks OK. Have you actually run it?
> 
> No, because I don't have access to edit things inside k8s-artifacts-prod.

For the record, just want to clarify that I am in the `k8s-infra-artifact-admins@kubernetes.io` group so I do have `Cloud Run Admin` and `Viewer` roles. However the ensure script requires enabling APIs and whatnot, which are things not covered by the aforementioned roles.

**Pull request merged**
