### PR TITLE
Update DNS for redirector to point to Ingress IP

### PR DESCRIPTION
**Pull request by ixdy**
This is the next part of https://github.com/kubernetes/k8s.io/issues/215 (item 3).

The `Ingress` has been set up, and tests consistently pass when targeted against it.

/assign @thockin

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/hold

please remove hold when you wish @ixdy

**Comment by ixdy** [comment]
This is good to go, though I'll need someone to push DNS (@thockin or @BenTheElder?) 

/hold cancel

**Comment by BenTheElder** [comment]
@ixdy taking a look

**Comment by BenTheElder** [comment]
```console
[bentheelder@bentheelder:~/go/src/k8s.io/k8s.io/dns·2019-04-04T11:09:07-0700·master@0a09aa7]
$ ./push.sh
Dry-run to canary zones
Pushing to canary zones
Canary push SUCCEEDED
Testing canary zone: canary.k8s.io.
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
Canary canary.k8s.io. SUCCEEDED
Testing canary zone: canary.kubernetes.io.
Canary canary.kubernetes.io. SUCCEEDED
Dry-run to prod zones
Pushing to prod zones
Prod push SUCCEEDED
Testing prod zone: k8s.io.
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
  test failed, might be propagation delay, will retry...
Prod k8s.io. SUCCEEDED
Testing prod zone: kubernetes.io.
Prod kubernetes.io. SUCCEEDED
```

**Comment by BenTheElder** [comment]
the above is actually the result of:
- `gcloud auth application-default login`
- `cd dns`
- `docker build -t ${USER}/octodns ./octodns-docker`
- `./push.sh`

should be pushed now.

**Pull request merged**
