### PR TITLE
Image promotion for capi-operator v0.10.0

### PR DESCRIPTION
**Pull request by alexander-demicev**
Image promotion for capi-operator v0.10.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork alexander-demicev --project capi-operator --reviewers "@Danil-Grigorev @Fedosin @alexander-demicev @damdo @furkatgofurov7" --tag v0.10.0 --image cluster-api-operator
```

/hold
cc: @Danil-Grigorev @Fedosin @alexander-demicev @damdo @furkatgofurov7

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
Thanks folks!
/lgtm

**Comment by furkatgofurov7** [comment]
Let's not forget to create new jobs for the release branch in test-infra repo

**Pull request merged**
