### PR TITLE
Add BigDarkClown@ to sig-autoscaling, remove inactive members.

### PR DESCRIPTION
**Pull request by BigDarkClown**

### CODE REVIEW

**Comment by gjtempleton** [comment]
Since I haven't been able to move https://github.com/kubernetes/k8s.io/pull/4925 forward as hoped, worth doing cleanup of non-active members as [discussed here](https://github.com/kubernetes/k8s.io/pull/4925#discussion_r1133302860) whilst we're touching this.

**Comment by BigDarkClown** [comment]
^ Sounds reasonable, I'll update this PR to also remove the non-active members.

**Comment by BigDarkClown** [comment]
Done.

**Comment by gjtempleton** [comment]
Thanks.
/lgtm
/approve

**Pull request merged**
