### PR TITLE
releng: Image promotion for kubernetes v1.21.14

### PR DESCRIPTION
**Pull request by ameukam**
Image promotion for kubernetes v1.21.14
This is an automated PR generated from `kpromo`
```
kpromo pr --fork ameukam --interactive --reviewers "" --tag v1.21.14
```

/hold
cc:

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Comment by puerco** [comment]
@ameukam are you sending the rc in another PR?

**Pull request merged**
