### PR TITLE
Add comment for k8s-infra-prow tide labels

### PR DESCRIPTION
**Pull request by eddiezane**
This PR is to ensure that #2795 does not happen.

/assign @ameukam

### CODE REVIEW

**Comment by ameukam** [comment]
/hold
k8s-infra-ci-robot took over again.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
Sorry we didn't have something like this here in the first place. Good catch

**Comment by spiffxp** [comment]
>k8s-infra-ci-robot took over again.

So the way to get its tide to stop trying to look at this repo is to remove the tide query entirely.  The current status is that both tides report to the same context, so last one to update wins.  It's not very friendly to new contributors to this repo.  It does let us know that k8s-infra's tide is running and doing stuff though.  So I could go either way.

**Comment by spiffxp** [comment]
/close
I'm going to close this given #2803 merged

**Pull request closed without merging**
