### PR TITLE
GCP: Bump terraform provider for kubernetes-public

### PR DESCRIPTION
**Pull request by ameukam**
Bump the terraform provider and at the same time fix a bug affecting a pubsub topic.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/sig-k8s-infra-leads

**Review by upodroid — APPROVED** [review]
/hold cancel when ready

**Comment by ameukam** [comment]
@michelle192837 FYI:

```bash
google_pubsub_subscription.kettle_ci_logs_subscription: Creation complete after 7s [id=projects/kubernetes-public/subscriptions/k8s-infra-kettle]
google_pubsub_subscription_iam_binding.ci_logs_subscription_binding: Creating...
google_pubsub_subscription_iam_binding.ci_logs_subscription_binding: Creation complete after 8s [id=projects/kubernetes-public/subscriptions/k8s-infra-kettle/roles/pubsub.editor]
```

**Comment by michelle192837** [comment]
Thanks!

**Pull request merged**
