### PR TITLE
Remove the legacy AWS owned test account 607362164682

### PR DESCRIPTION
**Pull request by dims**
related to https://github.com/kubernetes/k8s.io/issues/5194

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

**Review by upodroid — APPROVED** [review]
LGTM

**Comment by dims** [comment]
```
davanum@cloudshell:~ (kubernetes-public)$ kubectl delete secret -n test-pods aws-credentials-607362164682
secret "aws-credentials-607362164682" deleted
```

**Pull request merged**
