### PR TITLE
Machine readable domain inventory

### PR DESCRIPTION
**Pull request by techtonik**
to maintain a list of all domains programmatically

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/k8s.io/30)

### CODE REVIEW

**Comment by ixdy** [comment]
how was this list compiled? "programmatically" implies a script, which I don't see here.

**Comment by techtonik** [comment]
I compiled it manually and got stuck to create a link checking and reporting script. I thought I could reuse link checking code from Sphinx, but got carried away with refactoring, which now seems pointless. I'll try to commit something in the next couple of days.

**Comment by ixdy** [comment]
OK. I just worry that having a list separate from the configmaps isn't very helpful, since it'll almost certainly get out of sync.

**Comment by techtonik** [comment]
I've not yet learned about http://kubernetes.io/docs/user-guide/configmap/ so I started with an oldschool way.

**Comment by thockin** [comment]
What's the objective?

**Comment by techtonik** [comment]
@thockin automate maintenance of domains. Right now implement a human readable status check for config, like in #18 to catch things like expired domain names or missing entries (through DNS API).

**Comment by techtonik** [comment]
Ready for review.
```
k8s.io               302   Redirect
changelog.k8s.io     302   Redirect
code.k8s.io          302   Redirect
docs.k8s.io          302   Redirect
examples.k8s.io      302   Redirect
get.k8s.io           200   OK
issue.k8s.io         302   Redirect
issues.k8s.io        302   Redirect
jenkins.k8s.io       None  DNSLookupError
pr.k8s.io            302   Redirect
prs.k8s.io           302   Redirect
rel.k8s.io           302   Redirect
releases.k8s.io      302   Redirect
slack.k8s.io         200   OK
submit-queue.k8s.io  200   OK
www.k8s.io           302   Redirect
yum.k8s.io           302   Redirect
apt.k8s.io           302   Redirect
dl.k8s.io            302   Redirect
features.k8s.io      302   Redirect
feature.k8s.io       302   Redirect
reviewable.k8s.io    302   Redirect
testgrid.k8s.io      302   Redirect
ci-test.k8s.io       302   Redirect
gcsweb.k8s.io        404   Not Found
go.k8s.io            404   Not Found
pr-test.k8s.io       302   Redirect

27 domains, 3 errors
```

**Comment by thockin** [comment]
I'm afraid I still don't understand - we already have a test that tests these more completely and correctly.  2 of your 3 errors (404) are not errors, just that the / URL doesn't have meaning.  The third appears to be a domain we don't actually use.

Other than being yet another place to update when adding a domain - what value does this have?

**Comment by techtonik** [comment]
@thockin can you point me to that test? I'd like to see where it gets its list of domains. If I knew it exists, I would spend my free time on writing domain management config instead.

The point is to have a human-friendly, but also machine readable format for various services that project maintains. For the newcomers like myself it is very hard to understand what is available - where is bugtracker, binaries, and interesting dashboard etc. All these services are probably documented somewhere, but most interesting ones for development are usually known only to existing developers (like `gcsweb` with convenient `kubectl` downloads for Windows).

"domain" for the web is the same as "entrypoint" for binary executable on operating system. It is where the process starts. Or maybe domain is the executable of the web. So being able to "dir" the new project is an awesome feature as for me. =)

**Comment by techtonik** [comment]
It will help me to redirect my efforts into something usable for the project if you could explain how the current domain configuration is managed. Do you manually setup 302 redirects and add new third level domains? If so which interface is used?

**Comment by thockin** [comment]
https://github.com/kubernetes/k8s.io/blob/master/k8s.io/test.py

**Comment by thockin** [comment]
Is this still something you're thinking about?  I'm not sure what the goal is..

**Comment by techtonik** [comment]
@thockin yes, but 1. more generic declarative format for the start, 2. available for 3rd party developers to implement, 3. less verbose license terms

**Pull request closed without merging**
