### PR TITLE
Added bartsmykla to k8s-infra-team-private group

### PR DESCRIPTION
**Pull request by bartsmykla**
Signed-off-by: Bart Smykla <bartek@smykla.com>

### CODE REVIEW

**Comment by cblecker** [comment]
Do we use the @kuebrnetes.io list here for anything, as opposed to https://groups.google.com/forum/#!forum/k8s-infra-team-private ?

**Comment by dims** [comment]
@cblecker zoom account i think

**Comment by cblecker** [comment]
Zoom is k8s-infra-team-private@googlegroups.com not @kubernetes.io.

**Comment by bartsmykla** [comment]
Hmm, I don't see any other `k8s-infra-team-private` in `groups.yaml` file :-(

**Pull request merged**
