### PR TITLE
terraform: Prepare upgrade terraform to 4.0.0

### PR DESCRIPTION
**Pull request by ameukam**
Prepare the upgrade to 4.0.0 for the GCP terraform providers:

- bump the provider to 3.90.1
- remove fields unsupport in 4.0.0. The fieds unsupported in 4.0.0 can
  be found here: https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/guides/version_4_upgrade#resource-google_container_cluster
- ensure Shielded Nodes feature is disabled. See: https://github.com/hashicorp/terraform-provider-google/pull/10403

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/hold
cc @spiffxp @endocrimes

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Review by endocrimes — APPROVED** [review]
yay for shielding 🎉

**Review by cpanato — COMMENTED** [review]
/lgtm

**Comment by ameukam** [comment]
Ran `terraform plan` for `k8s-infra-prow-build-trusted`: 

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.prow_build_cluster.google_container_cluster.prod_cluster[0] will be updated in-place
  ~ resource "google_container_cluster" "prod_cluster" {
        id                          = "projects/k8s-infra-prow-build-trusted/locations/us-central1/clusters/prow-build-trusted"
        name                        = "prow-build-trusted"
        # (27 unchanged attributes hidden)

      ~ workload_identity_config {
          - identity_namespace = "k8s-infra-prow-build-trusted.svc.id.goog" -> null
          + workload_pool      = "k8s-infra-prow-build-trusted.svc.id.goog"
        }
        # (17 unchanged blocks hidden)
    }
```

Ran `terraform apply`:

```shell
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Modifying... [id=projects/k8s-infra-prow-build-trusted/locations/us-central1/clusters/prow-build-trusted]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Still modifying... [id=projects/k8s-infra-prow-build-trusted/l...s-central1/clusters/prow-build-trusted, 10s elapsed]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Still modifying... [id=projects/k8s-infra-prow-build-trusted/l...s-central1/clusters/prow-build-trusted, 20s elapsed]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Modifications complete after 27s [id=projects/k8s-infra-prow-build-trusted/locations/us-central1/clusters/prow-build-trusted]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
````

**Comment by ameukam** [comment]
I had to update the billing budgets in `k8s-infra-kubernetes-io`. Somehow I got duplicate for notification channels : 

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_billing_budget.capg_budget will be updated in-place
  ~ resource "google_billing_budget" "capg_budget" {
        id              = "billingAccounts/018801-93540E-22A20E/budgets/48207778-f6ad-44c1-9bd1-1b88e3006c81"
        name            = "48207778-f6ad-44c1-9bd1-1b88e3006c81"
        # (2 unchanged attributes hidden)

      ~ all_updates_rule {
          ~ monitoring_notification_channels = [
              - "projects/kubernetes-public/notificationChannels/5718453951835890521",
              + "projects/kubernetes-public/notificationChannels/13343268313622391552",
            ]
            # (2 unchanged attributes hidden)
        }




        # (7 unchanged blocks hidden)
    }

  # google_billing_budget.k8s_infra will be updated in-place
  ~ resource "google_billing_budget" "k8s_infra" {
        id              = "billingAccounts/018801-93540E-22A20E/budgets/c29e1d1a-8040-4e9e-a0b8-8743e5364d73"
        name            = "c29e1d1a-8040-4e9e-a0b8-8743e5364d73"
        # (2 unchanged attributes hidden)

      ~ all_updates_rule {
          ~ monitoring_notification_channels = [
              - "projects/kubernetes-public/notificationChannels/5718453951835890521",
              + "projects/kubernetes-public/notificationChannels/13343268313622391552",
            ]
            # (2 unchanged attributes hidden)
        }




        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
google_billing_budget.k8s_infra: Modifying... [id=billingAccounts/018801-93540E-22A20E/budgets/c29e1d1a-8040-4e9e-a0b8-8743e5364d73]
google_billing_budget.capg_budget: Modifying... [id=billingAccounts/018801-93540E-22A20E/budgets/48207778-f6ad-44c1-9bd1-1b88e3006c81]
google_billing_budget.k8s_infra: Modifications complete after 3s [id=billingAccounts/018801-93540E-22A20E/budgets/c29e1d1a-8040-4e9e-a0b8-8743e5364d73]
google_billing_budget.capg_budget: Modifications complete after 3s [id=billingAccounts/018801-93540E-22A20E/budgets/48207778-f6ad-44c1-9bd1-1b88e3006c81]

Apply complete! Resources: 0 added, 2 changed, 0 destroyed.
```

**Comment by ameukam** [comment]
Ran `terraform apply` for `k8s-infra-prow-build`: 

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.prow_build_cluster.google_container_cluster.prod_cluster[0] will be updated in-place
  ~ resource "google_container_cluster" "prod_cluster" {
        id                          = "projects/k8s-infra-prow-build/locations/us-central1/clusters/prow-build"
        name                        = "prow-build"
        # (27 unchanged attributes hidden)

      ~ workload_identity_config {
          - identity_namespace = "k8s-infra-prow-build.svc.id.goog" -> null
          + workload_pool      = "k8s-infra-prow-build.svc.id.goog"
        }
        # (18 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Modifying... [id=projects/k8s-infra-prow-build/locations/us-central1/clusters/prow-build]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Still modifying... [id=projects/k8s-infra-prow-build/locations/us-central1/clusters/prow-build, 10s elapsed]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Still modifying... [id=projects/k8s-infra-prow-build/locations/us-central1/clusters/prow-build, 20s elapsed]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Still modifying... [id=projects/k8s-infra-prow-build/locations/us-central1/clusters/prow-build, 30s elapsed]
module.prow_build_cluster.google_container_cluster.prod_cluster[0]: Modifications complete after 34s [id=projects/k8s-infra-prow-build/locations/us-central1/clusters/prow-build]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by ameukam** [comment]
I skipped `kubernetes-public`. @spiffxp is making changes on the terraform state for this project in https://github.com/kubernetes/k8s.io/pull/3028. 

/hold cancel

**Comment by spiffxp** [comment]
Done with kubernetes-public
```
terraform init -upgrade
terraform apply
```
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # google_container_cluster.cluster will be updated in-place
  ~ resource "google_container_cluster" "cluster" {
        id                          = "aaa"
        name                        = "aaa"
        # (27 unchanged attributes hidden)

      ~ workload_identity_config {
          - identity_namespace = "kubernetes-public.svc.id.goog" -> null
          + workload_pool      = "kubernetes-public.svc.id.goog"
        }
        # (20 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

google_container_cluster.cluster: Modifying... [id=aaa]
google_container_cluster.cluster: Still modifying... [id=aaa, 10s elapsed]
google_container_cluster.cluster: Still modifying... [id=aaa, 20s elapsed]
google_container_cluster.cluster: Still modifying... [id=aaa, 30s elapsed]
google_container_cluster.cluster: Modifications complete after 35s [id=aaa]
```

**Pull request merged**
