### PR TITLE
Image promotion for build-image v0.5.8 / v0.6.3

### PR DESCRIPTION
**Pull request by haitch**
Image promotion for build-image v0.5.8 / v0.6.3
This is an automated PR generated from `kpromo`
```
kpromo pr --fork haitch --interactive --project build-image --tag v0.5.8 --tag v0.6.3
```

/xref: https://github.com/kubernetes/release/issues/3738 

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by cpanato — CHANGES_REQUESTED** [review]
it is missing the other archs like `distroless-iptables-ppc64le` / `distroless-iptables-s390x`

**Comment by haitch** [comment]
ah, I don't see how to configure kpromo to do that, do I have to manually update those?

**Comment by haitch** [comment]
@cpanato have to do a manual edit, extract image hash from https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-distroless-iptables/1838117605244669952

**Comment by haitch** [comment]
have to manually cross-check with following docker pull command, either I am not using kpromo tool correctly, or the tool need some update.

- docker manifest inspect -v gcr.io/k8s-staging-build-image/distroless-iptables@sha256:7c961ad4732bddd1c8b7ede12027fbf9a7b2f3d750921faf6d7a74c894d81f7b 

- docker manifest inspect -v gcr.io/k8s-staging-build-image/distroless-iptables@sha256:f7d49886640191408cddc8aac6056c8a7957ba74eab88e95f1a69e207b3c3ef2

**Comment by jeremyrickard** [comment]
> ah, I don't see how to configure kpromo to do that, do I have to manually update those?

I don't believe that we need to specify anything for this.  Can you share the kpromo version info?

Manually editing the manifests isn't something I think we want to do.

**Comment by haitch** [comment]
GitVersion:    v4.0.5
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
GoVersion:     go1.21.3
Compiler:      gc
Platform:      linux/amd64

**Comment by haitch** [comment]
install from main, and retrying, closing this PR

**Comment by haitch** [comment]
ah, I think I know the reason, I ran this kpromo tool too soon before the container image fully available from gcr.

**Pull request closed without merging**
