### PR TITLE
Add Giant Swarm to distributors list

### PR DESCRIPTION
**Pull request by stone-z**
Fixes https://github.com/kubernetes/security/issues/118

### CODE REVIEW

**Comment by stone-z** [comment]
CLA has been signed

**Comment by spiffxp** [comment]
/hold
FYI @kubernetes/product-security-committee I would like someone from your group (or from the list) to /lgtm this before we /approve

How would you recommend updating the instructions at https://github.com/kubernetes/security/blob/master/private-distributors-list.md to make folks aware that we're looking for sponsorship here?  One thought I had was to suggest moving this list into its own folder with its own OWNERS file with a suggested list of reviewers (approval still needs to come from /groups root for now)

**Comment by spiffxp** [comment]
>One thought I had was to suggest moving this list into its own folder with its own OWNERS file with a suggested list of reviewers (approval still needs to come from /groups root for now)

I'm going to go ahead and do this for now

**Comment by spiffxp** [comment]
opened https://github.com/kubernetes/k8s.io/pull/1822, we could either opt to hold that until this merged, or ask this be rebased once that merges

**Comment by stone-z** [comment]
> One thought I had was to suggest moving this list into its own folder with its own OWNERS file with a suggested list of reviewers (approval still needs to come from /groups root for now)

That would make sense to me. From the outside I wasn't sure who best to ping, so automating it might help others in the future.

Thanks for getting us sorted out :pray:

**Review by spiffxp — APPROVED** [review]
/approve
/hold cancel

**Pull request merged**
