### PR TITLE
Add sig-scalability members to k8s-infra-prow-viewers@kubernetes.io

### PR DESCRIPTION
**Pull request by jkaniuk**
Add sig-scalability members to k8s-infra-prow-viewers@kubernetes.io

/cc @spiffxp
/cc @dims

### CODE REVIEW

**Comment by dims** [comment]
welcome aboard! :)

/approve
/lgtm

**Comment by jkaniuk** [comment]
Thanks, it works :)

**Comment by jkaniuk** [comment]
@dims - how could I see metrics for default and scalability clusters?
some of scalability jobs are run on those

**Comment by dims** [comment]
@jkaniuk we'll have to ask @BenTheElder / @spiffxp as i don't know the answer

**Comment by BenTheElder** [comment]
If you mean the default cluster in prow.k8s.io, it's not public (not a wg-k8s-infra project, it's an old google.com project), replied to your internal thread regarding that. Not sure on "scalability", I think prow is just scheduling to that and your team owns the project ...?

**Pull request merged**
