### PR TITLE
Promote CoreDNS v1.7.1 and v1.8.0

### PR DESCRIPTION
**Pull request by stp-ip**

### CODE REVIEW

**Review by rajansandeep — APPROVED** [review]
/lgtm
thank you @stp-ip

**Comment by rajansandeep** [comment]
Is there a time frame as to when the images are promoted?
Seems like the images aren't available in k8s.gcr.io yet

**Comment by stp-ip** [comment]
Should be quite close after merge. Will check what's up.

**Comment by stp-ip** [comment]
Jobs ran without error and checked the repo as well: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/EU/coredns/coredns?gcrImageListsize=30

The last version v1.7.0 was still using the root due to it using the legacy path as well. 

Should be available under k8s.gcr.io/coredns/coredns:v1.8.0

On mobile so can't check myself.

**Comment by chrisohaver** [comment]
@stp-ip thanks!  I checked and it works.

**Pull request merged**
