### PR TITLE
Add Associate PSC members to distributors-announce list

### PR DESCRIPTION
**Pull request by joelsmith**

### CODE REVIEW

**Comment by spiffxp** [comment]
/approve
/hold
feel free to `/hold cancel` when you've gotten /lgtm from whomever you need it from

**Comment by swamymsft** [comment]
> @joelsmith: GitHub didn't allow me to request PR reviews from the following users: swamymsft.
> 
> Note that only [kubernetes members](https://github.com/orgs/kubernetes/people) and repo collaborators can review this PR, and authors cannot review their own PRs.

Anything I have to do here?

**Comment by joelsmith** [comment]
> Anything I have to do here?

@swamymsft You need to go through the process of joining the Kubernetes community as a member. See https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by spiffxp** [comment]
If you're ready for this to merge, please `/hold cancel`.  If you're waiting for more members to `/lgtm` then don't mind me, I just wasn't sure who you wanted sign off from on this.

**Pull request merged**
