### PR TITLE
Add external-dns to k8s.gcr.io

### PR DESCRIPTION
**Pull request by njuettner**

### CODE REVIEW

**Comment by njuettner** [comment]
@nikhita do the OWNERS also need to join the K8s org before we can merge this? This would mean creating an issue once more? 

/cc @Raffo @hjacobs

**Comment by nikhita** [comment]
> @nikhita do the OWNERS also need to join the K8s org before we can merge this? 

Yes, the OWNERS would need to join the org before this can be merged - since only members can lgtm and approve PRs.

> This would mean creating an issue once more?

Yes, membership to the @kubernetes GitHub org warrants a separate issue.

**Comment by njuettner** [comment]
@dims @nikhita sorry that this took a bit longer but we finally made to have at least 3 people for now who are in the K8s org. I dropped @hjacobs for now because he's on vacation and we would like to proceed with the pipeline to release a new image. 
Nevertheless I would like to add @hjacobs again after he's back from vacation and I assume this is not a problem, right?

Do you mind if you can take a look again?

Thank you!

**Comment by nikhita** [comment]
Tiny nit: can you squash the commits into a single commit? Looks good otherwise!

/assign @dims 
since dims has powers to run the script

**Comment by njuettner** [comment]
@nikhita 👍 , thanks for having a look again

**Comment by dims** [comment]
@njuettner please rebase

/hold

**Comment by dims** [comment]
@njuettner looks like a merge commit snuck in .. can you please rebase so we don't have one?

**Comment by njuettner** [comment]
@dims fixed.

**Pull request merged**
