### PR TITLE
backfill gcr.io/google-containers

### PR DESCRIPTION
**Pull request by listx**
This is the last backfill before the flip on July 13, 2020. [1] [2]

[1]: https://groups.google.com/d/msg/kubernetes-sig-release/ew-k9PEBckQ/KFgMqOO_AQAJ
[2]: https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/Vanity-Domain-Flip.md

### CODE REVIEW

**Comment by dims** [comment]
@listx feel free to remove hold when you are ready.

**Comment by listx** [comment]
Thanks!

/hold cancel

**Pull request merged**
