### PR TITLE
terraform: cleanup prow terraform

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/2220
- Followup to: https://github.com/kubernetes/k8s.io/pull/2844
- Followup to: https://github.com/kubernetes/k8s.io/pull/2847

Miscellaneous cleanup for both prow projects
- rm tf-state-mv.sh now that https://github.com/kubernetes/k8s.io/pull/2844 is deployed
- convert workload_identity_service_accounts to map for brevity
- move the prow-deployer k8s-infra-prow-build IAM binding to k8s-infra-prow-build terraform
- split up main.tf files to make it clearer which file to edit for what

The goal in splitting up is to point someone looking to add a new secret or service account to a file that looks much less scary than a single monolithic terraform file

### CODE REVIEW

**Comment by dims** [comment]
/lgtm
/hold

please remove hold when ready @spiffxp (or if you need additional eyes)

**Comment by spiffxp** [comment]
Ran `terraform apply` in `k8s-infra-prow-build-trusted` and `k8s-infra-prow-build`

**Pull request merged**
