### PR TITLE
registry-sandbox.k8s.io: add support of env vars in staging

### PR DESCRIPTION
**Pull request by ameukam**
- Ensure env variables can be add to HCL code handling the Cloud Run
services for registry-sandbox.k8s.io
- Use variables instead locals for common configuration.
- bump terraform providers

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @BenTheElder

**Comment by Riaankl** [comment]
/retitle registery.k8s.io: add support of env vars in staging
/cc @ameukam

**Comment by ameukam** [comment]
/retitle registry-sandbox.k8s.io: add support of env vars in staging

**Pull request merged**
