### PR TITLE
Release etcd 3.5.0-0 image

### PR DESCRIPTION
**Pull request by pacoxu**
Part of kubernetes/kubernetes#102294

```
[root@daocloud ~]# docker pull gcr.io/k8s-staging-etcd/etcd:3.5.0-0
3.5.0-0: Pulling from k8s-staging-etcd/etcd
5dea5ec2316d: Already exists
f19a5990e757: Pull complete
ea2d08d27074: Pull complete
677a5c6b24cf: Pull complete
12201bf2f59f: Downloading [==========================>                        ]  5.111MB/9.669MB
12201bf2f59f: Pull complete
Digest: sha256:9ce33ba33d8e738a5b85ed50b5080ac746deceed4a7496c550927a7a19ca3b6d
Status: Downloaded newer image for gcr.io/k8s-staging-etcd/etcd:3.5.0-0
gcr.io/k8s-staging-etcd/etcd:3.5.0-0
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/hold
for https://github.com/kubernetes/release/pull/2123
does this image build with the new kube-cross image? I need check

**Comment by serathius** [comment]
/milestone v1.22
ping @justaugustus

**Comment by justaugustus** [comment]
> /hold
> for [kubernetes/release#2123](https://github.com/kubernetes/release/pull/2123)
> does this image build with the new kube-cross image? I need check

I'll be doing some verification on whether that is actually required (https://github.com/kubernetes/release/pull/2124, https://github.com/kubernetes/k8s.io/pull/2248), but it doesn't need to block this PR.

/hold cancel
/lgtm
/approve

**Comment by serathius** [comment]
This was incorrect sha to be promoted. It promoted `sha256:9ce33ba33d8e738a5b85ed50b5080ac746deceed4a7496c550927a7a19ca3b6d` that was result of `docker pull`
image

Instead of `sha256:9aeb407e6e534cdc82317a6f435b34e64d9c2bb60af945fae4f4204e47c4e6c8` that was under tag 
image

Using docker pull is not correct way to get image hashes as docker will pull the image for local machine and not the multi arch manifest.

**Pull request merged**
