### PR TITLE
remove images that we dont promote

### PR DESCRIPTION
**Pull request by cpanato**
some images that we usually don't promote were added to this PR https://github.com/kubernetes/k8s.io/pull/3268
Removing those, however not 100% sure if that is ok.

/kind cleanup

/assign @justaugustus @saschagrunert @palnabarun @puerco 
cc @kubernetes/release-managers

### CODE REVIEW

**Comment by saschagrunert** [comment]
Is the tool capable of removing already promoted images?

**Comment by cpanato** [comment]
> Is the tool capable of removing already promoted images?

i think if that is promoted it will not remove it

**Comment by saschagrunert** [comment]
> > Is the tool capable of removing already promoted images?
> 
> i think if that is promoted it will not remove it

Then we probably should keep it for integrity reasons.

**Comment by cpanato** [comment]
@saschagrunert thanks, makes sense

/close

**Pull request closed without merging**
