### PR TITLE
prow: update kubernetes-external-secrets to v8.1.2

### PR DESCRIPTION
**Pull request by spiffxp**
Trialing on prow before aaa to verify it comes up OK, and that prow is capable of auto-deploying this

Also using this as an opportunity to exercise the changes in https://github.com/kubernetes/test-infra/pull/22525 and https://github.com/kubernetes/k8s.io/pull/2190

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc @ameukam 
ref: https://github.com/kubernetes/k8s.io/pull/2148#issuecomment-856519985

**Comment by ameukam** [comment]
/lgtm
/hold
Remove hold when ready to deploy.

**Comment by spiffxp** [comment]
So this failed to deploy automatically, specifically in trying to revoke some existing RBAC permissions:
```
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"rbac.authorization.k8s.io/v1\",\"kind\":\"ClusterRole\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"kubernetes-external-secrets\"},\"name\":\"kubernetes-external-secrets\"},\"rules\":[{\"apiGroups\":[\"\"],\"resources\":[\"secrets\"],\"verbs\":[\"create\",\"update\"]},{\"apiGroups\":[\"\"],\"resources\":[\"namespaces\"],\"verbs\":[\"get\",\"watch\",\"list\"]},{\"apiGroups\":[\"apiextensions.k8s.io\"],\"resourceNames\":[\"externalsecrets.kubernetes-client.io\"],\"resources\":[\"customresourcedefinitions\"],\"verbs\":[\"get\",\"update\"]},{\"apiGroups\":[\"kubernetes-client.io\"],\"resources\":[\"externalsecrets\"],\"verbs\":[\"get\",\"watch\",\"list\"]},{\"apiGroups\":[\"kubernetes-client.io\"],\"resources\":[\"externalsecrets/status\"],\"verbs\":[\"get\",\"update\"]}]}\n"}},"rules":[{"apiGroups":[""],"resources":["secrets"],"verbs":["create","update"]},{"apiGroups":[""],"resources":["namespaces"],"verbs":["get","watch","list"]},{"apiGroups":["apiextensions.k8s.io"],"resourceNames":["externalsecrets.kubernetes-client.io"],"resources":["customresourcedefinitions"],"verbs":["get","update"]},{"apiGroups":["kubernetes-client.io"],"resources":["externalsecrets"],"verbs":["get","watch","list"]},{"apiGroups":["kubernetes-client.io"],"resources":["externalsecrets/status"],"verbs":["get","update"]}]}
to:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole"
Name: "kubernetes-external-secrets", Namespace: ""
for: "/home/prow/go/src/github.com/kubernetes/k8s.io/infra/gcp/clusters/projects/k8s-infra-prow-build-trusted/prow-build-trusted/resources/kubernetes-external-secrets_rbac.yaml": clusterroles.rbac.authorization.k8s.io "kubernetes-external-secrets" is forbidden: user "prow-deployer@k8s-infra-prow-build-trusted.iam.gserviceaccount.com" (groups=["system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:[""], Resources:["namespaces"], Verbs:["get" "watch" "list"]}
{APIGroups:[""], Resources:["secrets"], Verbs:["create" "update"]}
{APIGroups:["apiextensions.k8s.io"], Resources:["customresourcedefinitions"], ResourceNames:["externalsecrets.kubernetes-client.io"], Verbs:["get" "update"]}
{APIGroups:["kubernetes-client.io"], Resources:["externalsecrets"], Verbs:["get" "watch" "list"]}
{APIGroups:["kubernetes-client.io"], Resources:["externalsecrets/status"], Verbs:["get" "update"]}
```

Everything else updated though, so I suspect this is working anyway

**Pull request merged**
