### PR TITLE
add k8s.io/apiserver

### PR DESCRIPTION
**Pull request by deads2k**
Add entry for godeping k8s.io/apiserver.

### CODE REVIEW

**Comment by deads2k** [comment]
@lavalamp I recall needing this for godeping https://github.com/kubernetes/k8s.io/pull/41

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
I probably need to remember how to push this before it will take effect.

**Comment by deads2k** [comment]
> I probably need to remember how to push this before it will take effect.

https://github.com/kubernetes/apiserver is synced and ready when this rolls out.  Mention me when its pushed?

**Comment by thockin** [comment]
pushed - should work now

**Pull request merged**
