### PR TITLE
Add staging project for kubernetes/examples

### PR DESCRIPTION
**Pull request by justinsb**
This will allow pushing artifacts via the new process.  cf https://github.com/kubernetes/examples/pull/407#issuecomment-732332458

### CODE REVIEW

**Comment by justinsb** [comment]
/retitle [WIP] Add staging project for kubernetes/examples

TODO:

* Get email for sebgoa

cc @idvoretskyi @sebgoa  (owners of kubernetes/examples)

**Comment by justinsb** [comment]
/retitle Add staging project for kubernetes/examples

Added the email address for sebgoa@.  Also added some comments with the github username, just because otherwise I worry this will get out of hand (e.g. we already have two emails for you, @idvoretskyi)

**Comment by dims** [comment]
/approve
/lgtm

Still need to run the script! (Note to myself!)

**Comment by dims** [comment]
Done!

**Pull request merged**
