### PR TITLE
infra/gcp/prow-build: Add bucket for scalability prowjobs

### PR DESCRIPTION
**Pull request by ameukam**
Ref:
https://github.com/kubernetes/k8s.io/issues/1310#issuecomment-856692948.

Part of https://github.com/kubernetes/k8s.io/issues/1469.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
remove when ready to deploy

**Comment by spiffxp** [comment]
/hold cancel
I'll deploy post-merge

**Comment by ameukam** [comment]
Deployed successfully.

**Comment by ameukam** [comment]
Ref https://github.com/kubernetes/k8s.io/issues/2241

**Pull request merged**
