### PR TITLE
infra/gcp: fix typos in external ips

### PR DESCRIPTION
**Pull request by spiffxp**
Fixup for errors encoutnered while deploying https://github.com/kubernetes/k8s.io/pull/2242

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold
_hiding in the closet_

**Comment by spiffxp** [comment]
/hold
lol I didn't catch them in review either 😅

**Comment by spiffxp** [comment]
well, good thing I forgot to type `cancel` above, I found a few missing descriptions that were going to cause terraform to delete/recreate IP's

**Comment by spiffxp** [comment]
/hold cancel
This has already been deployed, just needs an lgtm

**Pull request merged**
