### PR TITLE
releng: Image promotion for v1.20.0-alpha.1

### PR DESCRIPTION
**Pull request by hasheddan**
Image promotion for Kubernetes v1.20.0-alpha.1
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

Logs from the cloudbuild:

- [Mock Stage](https://console.cloud.google.com/cloud-build/builds/c42b07cc-a943-40ff-9869-aa5cc1f0529f?project=kubernetes-release-test)
- [Mock Release](https://console.cloud.google.com/cloud-build/builds/89e17d72-243f-4661-8510-c0e2d94dbcf0?project=kubernetes-release-test)
- [Stage](https://console.cloud.google.com/cloud-build/builds/b61df31b-b70c-48b2-91dc-26bc8ed03d74?project=648026197307)

@kubernetes/release-engineering
/assign @justaugustus @saschagrunert

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve

/hold
If anything is blocking. If not, feel free to unhold.

**Comment by saschagrunert** [comment]
/hold cancel

We see no blockers.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
