### PR TITLE
groups: Add kubernetes.io owned google group for sig-k8s-infra

### LINKED ISSUE #3205: Migrate kubernetes-sig-k8s-infra@googlegroups.com to kubernetes.io managed google group
Part of:
 - https://github.com/kubernetes/community/issues/3541

Placeholder issue to track all of the things that need to be done to ensure the migration is successful.

- [X] Create domain-owned google group `sig-k8s-infra@kubernetes.io` : https://github.com/kubernetes/k8s.io/pull/3206
- [X] Create domain-owned Google Drive folder `sig-k8s-infra`:
    - Created on 12/16/2021 by @mrbobbytables using `contributors@`
- [x] Add/Transfer meeting notes to the new Google drive folder
- [x] Create/Update Google calendar bi-weekly meeting invite
- [ ] rename references of `kubernetes-sig-k8s-infra@googlegroups.com`: https://cs.k8s.io/?q=kubernetes-sig-k8s-infra&i=nope&files=&excludeFiles=&repos=
- [ ] Ensure docs sharing is done with the new Google group
- [x] Ensure Google Data Studio dashboards are shared with new Google group

This list is not exhaustive. I'll update it if needed

Related:
- https://github.com/kubernetes/community/issues/5877

/priority important-soon
/kind cleanup
/milestone v1.24

### PR DESCRIPTION
**Pull request by ameukam**
Part of:
  - https://github.com/kubernetes/k8s.io/issues/3205

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims @spiffxp @thockin 

/hold

**Comment by ameukam** [comment]
FYI @mrbobbytables @parispittman

**Comment by dims** [comment]
/approve
/lgtm

@ameukam please feel free to remove hold

**Pull request merged**
