### PR TITLE
Add registry.k8s.io generate audit script

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Adds a script to generate a blob list of the objects in the registry.k8s.io S3 buckets.

Later, it might be good to group it by aws/s3 when there are more providers and there is more auditing.

This will be consumed by a ProwJob.

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
Fixes https://github.com/kubernetes/k8s.io/issues/3992

**Review by asim-reza — COMMENTED** [review]
Why are the generated files so big? and why are they needed in the repo?

**Comment by dims** [comment]
@asim-reza these are "audit" which means, we track who did what and when and save it for historical record. say 6 months from now, we wanted to check on something that happened today, we will be able to pull that up. this is the way we assure the community as all actions are open for inspection. also helps us catch if anyone made a mistake.

**Review by spiffxp — CHANGES_REQUESTED** [review]
```
$ find . -type f | grep -v .git | xargs wc -l | tail -n1
  316192 total
``` 
I think I agree with @asim-reza.  A naive line count in this repo is ~300K, while this PR adds ~11M... this doesn't feel right.

With the full caveat that I have been away while most of the discussion and work on registry.k8s.io has happened, I don't understand why this approach is necessary.

Our audit scripts today do not list the contents of GCS buckets, GCR repos, or GAR repos.  I'm not exactly clear why we feel compelled to do so for S3.

**Comment by dims** [comment]
@spiffxp i am with you as well, i hadn't peeked at the files ... yep, it's too big.

**Comment by spiffxp** [comment]
/close
Will take further discussion over to https://github.com/kubernetes/k8s.io/issues/3992

**Pull request closed without merging**
