### PR TITLE
Re-add 1.20 Comms Shadows Emails to Groups

### PR DESCRIPTION
**Pull request by jrsapi**
Updated and sorted Comms shadows to the 1.20 Kubernetes release team mailing list and shadow mailing list. 
Part of shadow onboarding task. 

/assign @jeremyrickard @savitharaghunathan @hasheddan @palnabarun @lachie83

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by savitharaghunathan — COMMENTED** [review]
/lgtm

**Review by palnabarun — APPROVED** [review]
/lgtm

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
