### PR TITLE
Add voelzmo to sig-autoscaling members and staging-image owners

### PR DESCRIPTION
**Pull request by voelzmo**
Reason: to help with releases for VPA

### CODE REVIEW

**Comment by BenTheElder** [comment]
Hey, you'll have to move this to registry.k8s.io/, sorry we're working on https://github.com/kubernetes/enhancements/issues/3720 ref https://github.com/kubernetes/k8s.io/pull/4934 https://github.com/kubernetes/test-infra/pull/29069 

[forcing bot to process this, will reopen immediately]
/close

**Comment by voelzmo** [comment]
I'll close this for now after our discussions in the SIG Autoscaling meeting. The plan is to come up with a more structured path for obtaining these permissions in the autoscaler repo.

**Pull request closed without merging**
