### PR TITLE
releng: Image promotion for kubernetes v1.30.0-alpha.1

### PR DESCRIPTION
**Pull request by marosset**
Image promotion for kubernetes v1.30.0-alpha.1
This is an automated PR generated from `kpromo`
```
kpromo pr --fork marosset --tag v1.30.0-alpha.1
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
