### PR TITLE
prow: Add k8s-infra-build-clusters-kubeconfig ExternalSecret

### PR DESCRIPTION
**Pull request by ameukam**
Ref: https://github.com/kubernetes/k8s.io/issues/1475
Umbrella issue of setup of k8s-infra prow instance: https://github.com/kubernetes/k8s.io/issues/1394

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
Secret have been created in GCP Secret Manager. 
Ran : `ensure-main-project.sh`

```shell
Ensuring secrets destined for apps in 'aaa' exist in: kubernetes-public 
  Ensuring 'prow' secret 'k8s-infra-build-clusters-kubeconfig' exists in 'kubernetes-public' and is owned by 'k8s-infra-rbac-prow@kubernetes.io' 
  Updated IAM policy for secret [k8s-infra-build-clusters-kubeconfig].
  @@ -1 +1,2 @@
  -[]
  +- member: group:k8s-infra-rbac-prow@kubernetes.io
  +  role: roles/secretmanager.admin
  Updated secret [k8s-infra-build-clusters-kubeconfig].
  Ensuring 'prow' secret 'k8s-infra-ci-robot-github-token' exists in 'kubernetes-public' and is owned by 'k8s-infra-rbac-prow@kubernetes.io' 
...
```

Will deploy the ExternalSecret post-merge.

**Review by spiffxp — APPROVED** [review]
/hold
But careful here, two prow control planes point at the same build cluster makes for unexpected behavior

I don't think that's what you've done but the name implies it could happen. Put the hold on for you to remove as ack

**Comment by ameukam** [comment]
> /hold
> But careful here, two prow control planes point at the same build cluster makes for unexpected behavior
> 
> I don't think that's what you've done but the name implies it could happen. Put the hold on for you to remove as ack

The configuration for k8s-infra-prow will use a different namespace than `test-pods` : https://github.com/ameukam/k8s.io/blob/13764652b921204e9f2af529c388433ed7d3047a/k8s-infra-prow.k8s.io/config.yaml#L3. 
First phase will be to add jobs that only related to self-maintenance and auto-upgrade of k8s-infra-prow (Will update https://github.com/kubernetes/k8s.io/pull/2235 once this is merged).

**Review by cpanato — APPROVED** [review]
/lgtm

/hold for @spiffxp

**Comment by ameukam** [comment]
Deployed :

```shell
./deploy.sh 
persistentvolumeclaim/ghproxy unchanged
deployment.apps/ghproxy configured
service/ghproxy unchanged
serviceaccount/ghproxy unchanged
externalsecret.kubernetes-client.io/k8s-infra-ci-robot-github-token unchanged
externalsecret.kubernetes-client.io/k8s-infra-build-clusters-kubeconfig created
```

**Pull request merged**
