### PR TITLE
Add DNS for CAPIBM release branches

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Add DNS for CAPIBM release branches

### CODE REVIEW

**Comment by Prajyot-Parab** [comment]
@dims - how do i ensure that following domains are added to the netlify cert? Is this documented somewhere?

**Comment by Prajyot-Parab** [comment]
> @dims - how do i ensure that following domains are added to the netlify cert? Is this documented somewhere?

cc - @cblecker

**Comment by Prajyot-Parab** [comment]
ptal - @cblecker @dims

**Comment by dims** [comment]
/approve
/lgtm

if auto deploy does not work, please ping @cblecker :)

**Pull request merged**
