### PR TITLE
Revert deleted ASN data

### PR DESCRIPTION
**Pull request by BobyMCbobs**
The data here is needed for running the [public-log-asn-matcher](https://github.com/kubernetes/k8s.io/tree/main/images/public-log-asn-matcher), it was removed sometime ago and will allow it to work again.

The report generated out of the data from _public-log-asn-matcher_ was requested by @BenTheElder.

cc @Riaankl

### CODE REVIEW

**Comment by Riaankl** [comment]
/assign @BenTheElder 
We need to merge these file back in as we need them to run the data query.

**Comment by BenTheElder** [comment]
1) quibble but, this report is for k8s.gcr.io, not registry.k8s.io?
2) Where and why are we still actively processing this? Are we unable to produce a static snapshot of k8s.gcr.io and keep the stats on hand without continuing to process this? (xref #4402, we're really cost constrained right now)

**Comment by BenTheElder** [comment]
I'm actually hoping to see the historical reports, the results from k8s.gcr.io's current data hopefully become increasingly irrelevant as we get people to switch, but it's good to understand where we came from and which other providers to target for local copies.

**Comment by hh** [comment]
Agreed. We need this back to generate a static report. We will run the job manually, but it references the ASN files restored in this PR. The historical data has been purged. We gotta regenerate it to view the report again.

**Comment by ameukam** [comment]
Data query and storage should not be done on the `kubernetes.io` org for the moment.

Since `registry.k8s.io` use Artifact Registry, we lose access to the audit logs for provide relevant information. The data collected will be partial. 
I would suggest to do this on a different GCP org.

**Comment by BobyMCbobs** [comment]
> 1. quibble but, this report is for k8s.gcr.io, not registry.k8s.io?

@BenTheElder, the report uses $BUCKET_usage data from buckets found in kubernetes org projects.
If there are buckets which the usage data is being written to there, it will pull from that that.

>     2. Where and why are we still actively processing this? 

This is a manually run job. By default, it produces a BigQuery dataset in _k8s-infra-ii-sandbox_ as _etl_script_generated_set_$DATE_.

> Are we unable to produce a static snapshot of k8s.gcr.io and keep the stats on hand without continuing to process this? (xref [shut down k8s.gcr.io bigquery analysis #4402](https://github.com/kubernetes/k8s.io/issues/4402), we're really cost constrained right now)

How do you mean?
The process generates a database containing the required information for the report. It would be good to keep at least the latest around for that reason.

**Comment by hh** [comment]
> I would suggest to do this on a different GCP org.

Are you asking the CNCF provide another GCP org to process this dataset and resulting queries to avoid touching the remaining credits for this year?

I don't think generating a single data set, or the report will have a huge impact on cost.

**Comment by ameukam** [comment]
> > I would suggest to do this on a different GCP org.
> 
> Are you asking the CNCF provide another GCP org to process this dataset and resulting queries to avoid touching the remaining credits for this year?

Pause the generation of this data until we have a better control of the GCP budget is what I'm asking. We can later revisit how we optimize that BQ storage. 

> I don't think generating a single data set, or the report will have a huge impact on cost.

**Pull request closed without merging**
