### PR TITLE
prow: add k8s-triage-robot-github-token secret

### PR DESCRIPTION
**Pull request by spiffxp**
Part of https://github.com/kubernetes/test-infra/issues/12296

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold
Remove hold when ready to deploy.

**Comment by spiffxp** [comment]
Provisioned the secret already, merging this PR will deploy the `ExternalSecret` to k8s-infra-prow-build-trusted
```
$ ./ensure-e2e-projects.sh does-not-exist
Ensuring external secrets exist for use by k8s-infra-prow-build-trusted
  Ensuring secret 'k8s-triage-robot-github-token' exists in 'k8s-infra-prow-build-trusted' and is owned by 'github@kubernetes.io'
  Created secret [k8s-triage-robot-github-token].
  Updated secret [k8s-triage-robot-github-token].
  Updated IAM policy for secret [k8s-triage-robot-github-token].
  @@ -1 +1,2 @@
  -[]
  +- member: group:k8s-infra-prow-oncall@kubernetes.io
  +  role: roles/secretmanager.admin
  Updated IAM policy for secret [k8s-triage-robot-github-token].
  @@ -1,2 +1,4 @@
  +- member: group:github@kubernetes.io
  +  role: roles/secretmanager.admin
   - member: group:k8s-infra-prow-oncall@kubernetes.io
     role: roles/secretmanager.admin
  Ensuring secret 'cncf-ci-github-token' exists in 'k8s-infra-prow-build-trusted' and is owned by 'k8s-infra-ii-coop@kubernetes.io'
  Updated secret [cncf-ci-github-token].
  Ensuring secret 'snyk-token' exists in 'k8s-infra-prow-build-trusted' and is owned by 'k8s-infra-code-organization@kubernetes.io'
  Updated secret [snyk-token].
Ensuring e2e projects used by prow...
  Skipping unrecognized e2e project name: does-not-exist
Done
```

**Comment by spiffxp** [comment]
Secret has been synced
```
$ k --context=prow-build-trusted get secrets -n test-pods | grep triage
k8s-triage-robot-github-token              Opaque                                1      96s
```

**Pull request merged**
