### PR TITLE
Add release-0.3 and tip for cluster-api

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
@thockin is just merging this enough or do i still need to run some stuff by hand? (if i remember right you were making changes there, is it already done?)

/assign @thockin

**Comment by CecileRobertMichon** [comment]
ping @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
