### PR TITLE
releng: Image promotion for v1.18.12 / v1.18.13-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for Kubernetes v1.18.12 / v1.18.13-rc.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
