### PR TITLE
Promote AWS CCM v1.26.1 artifacts

### PR DESCRIPTION
**Pull request by hakman**
/cc @olemarkus @dims

### CODE REVIEW

**Comment by pacoxu** [comment]
This makes https://testgrid.k8s.io/sig-release-releng-blocking#ci-k8sio-file-promo-mirrors failed for access deny errors.

**Comment by hakman** [comment]
@pacoxu This is a general problem when promoting artifacts. See https://github.com/kubernetes/k8s.io/issues/4913.

**Comment by dims** [comment]
Looks like things are holding up!

https://artifacts.k8s.io/binaries/cloud-provider-aws/v1.27.1/linux/amd64/ecr-credential-provider-linux-amd64
https://artifacts.k8s.io/binaries/cloud-provider-aws/v1.27.1/linux/amd64/ecr-credential-provider-linux-amd64.sha256

You can browse other artifacts here:
https://console.cloud.google.com/storage/browser/k8s-artifacts-prod/binaries/cloud-provider-aws

**Pull request merged**
