### PR TITLE
Promote a selection of 1.25.2 and 1.25.3-rc.0 images to experimental repo

### PR DESCRIPTION
**Pull request by upodroid**
Promoted a selection of images from https://github.com/kubernetes/k8s.io/pull/4254 to the experimental repository.

#4277 must be merged first.

/hold

/cc @kubernetes/release-engineering @dims

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by upodroid** [comment]
/hold cancel

thanks

**Comment by upodroid** [comment]
The promotion was successful. 🎉  🎉  🎉 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-image-promo/1575442499118305280

```
 REDACTED  MCW0CDP3YY  tmp  client  latest  $  COSIGN_EXPERIMENTAL=1 cosign tree europe-west2-docker.pkg.dev/k8s-artifacts-prod/images/experimental/kube-apiserver:v1.25.3-rc.0
📦 Supply Chain Security Related artifacts for an image: europe-west2-docker.pkg.dev/k8s-artifacts-prod/images/experimental/kube-apiserver:v1.25.3-rc.0
└── 🔐 Signatures for an image tag: europe-west2-docker.pkg.dev/k8s-artifacts-prod/images/experimental/kube-apiserver:sha256-11cc44684f00310cfdab91de8d26c0340f06226c4b09fa5b75ba9444d8ed082b.sig
   ├── 🍒 sha256:060b4d402bf9f97651ed6a178477d506487f5f95970d2f89f7d171fdbe05cfe6
   └── 🍒 sha256:574c0912aa746a1aa08f6190da998127b846818760b815f8c61c2b69bd3ae44e
```

I'm going to roll out the changes to the manifests in waves and then delete the gcr-to-ar-sync prow jobs.

**Pull request merged**
