### PR TITLE
Add mrfaizal to k8s-infra-prow-viewers

### PR DESCRIPTION
**Pull request by mrfaizal**
New Googler working in the Prow space

### CODE REVIEW

**Comment by dims** [comment]
@spiffxp @zawodny @liggitt can you please guide @mrfaizal on the cla stuff on your end?

**Comment by liggitt** [comment]
> @spiffxp @Zawodny @liggitt can you please guide @mrfaizal on the cla stuff on your end?

done

**Comment by dims** [comment]
removed `@` from title

**Pull request merged**
