### PR TITLE
add livenessprobe and node-driver-registrar image into the prod image list

### PR DESCRIPTION
**Pull request by andyzhangx**
https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/global/livenessprobe@sha256:933940f13b3ea0abc62e656c1aa5c5b47c04b15d71250413a6b821bd0c58b94e/details

Image type
Docker Manifest List
Media type
application/vnd.docker.distribution.manifest.list.v2+json
Project
k8s-staging-sig-storage
Repository
livenessprobe
Digest
sha256:933940f13b3ea0abc62e656c1aa5c5b47c04b15d71250413a6b821bd0c58b94e
Virtual size
0 B
Created
Jan 1, 1970, 8:00:00 AM
Uploaded
May 13, 2022, 6:07:41 AM
Tags
v2.7.0

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
thanks a lot, I also created a release https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.5.1 for node-driver-registrar, could you please add it here too?

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
> thanks a lot, I also created a release https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.5.1 for node-driver-registrar, could you please add it here too?

done, also added registrar v2.5.1

Image type
Docker Manifest List
Media type
application/vnd.docker.distribution.manifest.list.v2+json
Project
k8s-staging-sig-storage
Repository
csi-node-driver-registrar
Digest
sha256:0103eee7c35e3e0b5cd8cdca9850dc71c793cdeb6669d8be7a89440da2d06ae4
Virtual size
0 B
Created
Jan 1, 1970, 8:00:00 AM
Uploaded
May 12, 2022, 2:37:56 AM
Tags
v2.5.1

**Comment by pohly** [comment]
/assign @msau42

For approval.

**Comment by mauriciopoppe** [comment]
@andyzhangx is there a reason why this bug was closed?

**Comment by andyzhangx** [comment]
already addressed by https://github.com/kubernetes/k8s.io/pull/3737

**Pull request closed without merging**
