### PR TITLE
Switch main site host header to real backend

### PR DESCRIPTION
**Pull request by thockin**
pushed and activated now that the switchover is done

### CODE REVIEW

**Comment by ixdy** [comment]
Not a huge deal, but it seems like some self-generated redirects now go to kubernetes.github.io - e.g. if you go to https://kubernetes.io/docs instead of https://kubernetes.io/docs/ (trailing slash).

**Comment by thockin** [comment]
crap, how do I fix that?  I could re-enable github to think it owns the
custom domain (would have to disable 'enforce ssl') and have it generate
redirects to  the custom domain.  That's probably the only solution, eh?

**Comment by thockin** [comment]
OK, I fixed it by basically rolling this back.  Good catch

**Comment by thockin** [comment]
ugh, it only does HTTP, not https.

**Comment by ixdy** [comment]
ugh, that might be worse than redirecting to kubernetes.github.io.

**Comment by thockin** [comment]
I think I fixed it.  PR coming once I fix tests.  If you are up - poke
around the site?

**Comment by ixdy** [comment]
yeah, seems to be working. sweet!

(and now I notice that blog.kubernetes.io is HTTP-only, but this time it's Blogger that doesn't support HTTPS for custom domains.)

**Pull request merged**
