### PR TITLE
Release etcd 3.5.1-0 image

### PR DESCRIPTION
**Pull request by pacoxu**
Part of kubernetes/kubernetes#105706

```
[root@pacoall ~]#  docker pull gcr.io/k8s-staging-etcd/etcd:3.5.1-0
Trying to pull repository gcr.io/k8s-staging-etcd/etcd ...
3.5.1-0: Pulling from gcr.io/k8s-staging-etcd/etcd
e8614d09b7be: Pull complete
45b6afb4a92f: Pull complete
f951ee5fe858: Pull complete
0c6b9ab3ebf9: Pull complete
7314eabc351c: Pull complete
Digest: sha256:64b9ea357325d5db9f8a723dcf503b5a449177b17ac87d69481e126bb724c263
Status: Downloaded newer image for gcr.io/k8s-staging-etcd/etcd:3.5.1-0
```

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/lgtm
Since I /approved the cluster/ changes in kubernetes/kubernetes (ref: https://github.com/kubernetes/kubernetes/pull/106065)

But I don't think I have /approve for this

**Comment by spiffxp** [comment]
It looks like the initial postsubmit for https://github.com/kubernetes/kubernetes/pull/106065 failed due to a flake: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1455716701483044864

But was retried, so this was the job that pushed the new image: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1455748964987965440

**Review by justaugustus — APPROVED** [review]

**Pull request merged**
