### PR TITLE
k8s.gcr.io/images/k8s-staging-kube-state-metrics/: Add OWNERS file

### PR DESCRIPTION
**Pull request by lilic**
We won't add a promotion image yet, only on next release.

cc @brancz @tariq1890

### CODE REVIEW

**Comment by brancz** [comment]
I assume I can't lgtm this, but let's try.

/lgtm

**Comment by brancz** [comment]
cc @spiffxp @cblecker

**Comment by lilic** [comment]
Hmm this seems strange, says good to be merged but tide says pending?

https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fk8s.io+author%3Alilic+head%3Aadd-owners

**Comment by nikhita** [comment]
LOL, tide is slow :P

**Comment by lilic** [comment]
LOL :D it heard me :D

**Pull request merged**
