### PR TITLE
tweak rate limiting following log analysis

### PR DESCRIPTION
**Pull request by BenTheElder**
1. shorten rate limit window with same approximate rate limit rounded down to the nearest integer-per-second
2. increase temp-ban duration to maximum (1h)
3. update and clarify comments

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/hold

( for additional approvals or until you are ready to land this @BenTheElder )

**Comment by BenTheElder** [comment]
/hold cancel

first we'll watch this deploy to staging, which also gives some more time for any objection raising
(also, we can roll back any production changes if there are objections later, I think this should be fine, it's a relatively small tweak)

**Comment by BenTheElder** [comment]
auto-deploy to staging: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8s-deploy-registry/1816575907268136960

**Comment by BenTheElder** [comment]
working in staging, will roll out to prod

**Comment by BenTheElder** [comment]
done

**Comment by BenTheElder** [comment]
So far we've not seen anyone hit the ban threshold (which is NOT any higher after this change) since tweaking the rate limit threshold (maybe we're getting clients to back off more now? too early to say)

We are rate limiting 8 IPs in the past hour:


| ASN | Number of IPs |
|--|--|
| AMAZON-02 | 1 |
| ENTEL CHILE S.A., CL | 1 |
| GOOGLE-CLOUD-PLATFORM | 5 |
| MICROSOFT-CORP-MSN-AS-BLOCK | 1 |

And temp-banning none since the change.

Will have to check back later, 1h is a small sample period for the registry and we previously only temp-banned a subset of clients (that's expected, the two tier limit is intended to first throttle short bursts to maintain the rate limit, and then temp ban sustained excessive usage ignoring the throttling).

**Comment by BenTheElder** [comment]
In the past 12 hours We have 16 IPs hitting the temp-ban threshold and 64 hitting the rate limit threshold.

I didn't stop to track down the ASNs but at a glance it looks similar to before.

This seems like a good result, by far the majority of clients that wind up getting rate limited only hit a temporary rate limit, and still less than 20 clients actually get temp-banned for persisting past the 30s burst limit.

**Pull request merged**
