### PR TITLE
Add irvi in leads list

### PR DESCRIPTION
**Pull request by irvifa**

### CODE REVIEW

**Comment by cblecker** [comment]
/hold

@irvifa: Sorry, which community group are you a lead of? I don't see your user in sigs.yaml

**Comment by mrbobbytables** [comment]
@cblecker https://github.com/kubernetes/community/pull/5125/files
needs-rebase atm =/

**Comment by irvifa** [comment]
@cblecker it's on the PR that have been mentioned by Bob

**Pull request merged**
