### PR TITLE
releng: promote kube-cross:v1.15.10-legacy-1 / v1.15.10-1

### PR DESCRIPTION
**Pull request by cpanato**
related workstream: https://github.com/kubernetes/release/issues/1940

Prowjob: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-release-push-image-kube-cross/1370298262535278592

/assign @justaugustus @hasheddan @saschagrunert @ameukam @xmudrii @puerco 
cc @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
