### PR TITLE
releng: Image promotion for kubernetes v1.25.0-rc.0 / v1.26.0-alpha.0

### PR DESCRIPTION
**Pull request by jeremyrickard**
Image promotion for kubernetes v1.25.0-rc.0 / v1.26.0-alpha.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork jeremyrickard --interactive --tag v1.25.0-rc.0 --tag v1.26.0-alpha.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by dims** [comment]
runtime panic in the logs!

```
goroutine 4669 [running]:
runtime.throw({0x27d1cd9?, 0x8?})
	runtime/panic.go:992 +0x71 fp=0xc00e573d30 sp=0xc00e573d00 pc=0x438671
runtime.mapaccess2_faststr(0xc00e573f10?, 0x6b69af?, {0xc000998100, 0x76})
	runtime/map_faststr.go:117 +0x3d4 fp=0xc00e573d98 sp=0xc00e573d30 pc=0x4131f4
sigs.k8s.io/promo-tools/v3/internal/promoter/image.(*DefaultPromoterImplementation).FindSingedEdges.func1({{{0xc000762280, 0x1d}, {0x0, 0x0}, {0x0, 0x0}, 0x1}, {{0xc0013cd300, 0x10}, {0xc0013cdf50, ...}}, ...})
	sigs.k8s.io/promo-tools/v3/internal/promoter/image/sign.go:74 +0xec fp=0xc00e573f10 sp=0xc00e573d98 pc=0x1e41b0c
sigs.k8s.io/promo-tools/v3/internal/promoter/image.(*DefaultPromoterImplementation).FindSingedEdges.func2()
	sigs.k8s.io/promo-tools/v3/internal/promoter/image/sign.go:99 +0x55 fp=0xc00e573fe0 sp=0xc00e573f10 pc=0x1e419d5
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc00e573fe8 sp=0xc00e573fe0 pc=0x46b981
created by sigs.k8s.io/promo-tools/v3/internal/promoter/image.(*DefaultPromoterImplementation).FindSingedEdges
	sigs.k8s.io/promo-tools/v3/internal/promoter/image/sign.go:72 +0x2e5
```

**Comment by puerco** [comment]
@dims yep I saw :( We fixed it in https://github.com/kubernetes-sigs/promo-tools/pull/594 but unfortunately, we forgot to cut a new promoter release. It is harmless but we needed to retrigger the presubmit. 

Slack ref:  https://kubernetes.slack.com/archives/CJH2GBF7Y/p1660077714102019?thread_ts=1660057694.134999&cid=CJH2GBF7Y

**Comment by puerco** [comment]
Thanks @jeremyrickard !
/lgtm

**Pull request merged**
