### PR TITLE
infra/gcp/aaa: Subscribe GKE cluster aaa to the regular channel

### PR DESCRIPTION
**Pull request by ameukam**
Subscribe to the release channel : https://cloud.google.com/kubernetes-engine/docs/release-schedule.

Use variable for `image_type`.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by ameukam** [comment]
Running : `terraform apply`.

**Comment by ameukam** [comment]
Change applied : 

```bash
gcloud container clusters describe aaa --region us-central1 --project kubernetes-public --format='value(releaseChannel)'
channel=REGULAR
```

**Comment by spiffxp** [comment]
Gah sorry, I got pulled into meetings until just now, and so I can confirm you did deploy those changes :)

**Pull request merged**
