### PR TITLE
Add EmilienM to CAPO maintainers

### PR DESCRIPTION
**Pull request by EmilienM**
This was proposed and approved here:
kubernetes-sigs/cluster-api-provider-openstack#2115

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by mdbooth** [comment]
This one requires approval from everybody! Lets try:

sig-architecture-leads: @dims 
sig-cluster-lifecycle-leads: @fabriziopandini

🙏

**Pull request merged**
