### PR TITLE
Promote capdo v0.4.1 images

### PR DESCRIPTION
**Pull request by prksu**
This PR promotes the CAPDO v0.4.1 image

/cc @cpanato @MorrisLaw

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by prksu** [comment]
the error message says about `tag latest: ERROR: tag move detected` in `aws-ebs-csi-driver`

```log
E0108 13:26:36.707674      12 inventory.go:508] edge {{gcr.io/k8s-staging-provider-aws   true} {aws-ebs-csi-driver latest} sha256:3801d90c7cfb438b308166681c59aa6576d1e614223e1d17eee9997287bac17e {eu.gcr.io/k8s-artifacts-prod/provider-aws k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com  false} {aws-ebs-csi-driver latest}}: tag latest: ERROR: tag move detected from sha256:3801d90c7cfb438b308166681c59aa6576d1e614223e1d17eee9997287bac17e to sha256:3bd9663e40ed9fc14e92199ce3405c9412d1b8e7e1222e5a8a4f2a7bc42dca91
``` 

cc @dims @spiffxp 
are you have more insight about this failure?

**Comment by dims** [comment]
/assign @listx 

Linus, failure is unrelated to the PR, can you please take a look?

**Comment by prksu** [comment]
another PR have the same issue https://github.com/kubernetes/k8s.io/pull/1515

**Comment by prksu** [comment]
the issue already fixed here https://github.com/kubernetes/k8s.io/pull/1519
/retest

**Pull request merged**
