### PR TITLE
Update audit for 2021-04-27

### PR DESCRIPTION
**Pull request by BobyMCbobs**

### CODE REVIEW

**Review by spiffxp — CHANGES_REQUESTED** [review]
Sorry, what's the purpose of this PR? I have been keeping tabs on https://github.com/kubernetes/k8s.io/pull/1903 as an audit PR with outstanding changes, I will merge that when things I commented on there have been resolved or created as followup issues

**Comment by spiffxp** [comment]
/close
Please /reopen and rebase if you think this remains relevant

**Comment by BobyMCbobs** [comment]
> Sorry, what's the purpose of this PR? I have been keeping tabs on #1903 as an audit PR with outstanding changes, I will merge that when things I commented on there have been resolved or created as followup issues

Needed some update on the observability of the k8s-infra-ii-sandbox project permissions and what was on _main_ seemed out of date. 
My PR is not needed anymore, since https://github.com/kubernetes/k8s.io/pull/2001 has merged.

Thank you!

**Pull request closed without merging**
