### PR TITLE
WG Serving mailing list

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
/sig apps

WG Serving mailing lists as per instructions.

Goes in combination with these two PRs:

- https://github.com/kubernetes/community/pull/7823
- https://github.com/kubernetes/community/pull/7830

More leads to be added after the first meeting

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@SergeyKanzhelev 

> terrytangyuan
> User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev 
> 
> > terrytangyuan
> > User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

We fixed it already. I'll need to push some empty commit to clear it up. Will do later when at the computer. Thank you!

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm

**Pull request merged**
