### PR TITLE
apps/k8s-io: fix go.k8s.io/triage test

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- part of: https://github.com/kubernetes/k8s.io/issues/1305
- followup to: https://github.com/kubernetes/k8s.io/pull/2544

Fix failed test case

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm
Thanks

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-deploy-app-k8s-io/1427287365755342848
 
```
FAIL: test_go (__main__.RedirTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 198, in test_go
    'https://storage.googleapis.com/k8s-gubernator/triage/index.html')
  File "./test.py", line 100, in assert_temp_redirect
    self.assert_multischeme_redirect(partial_url, expected_loc, 302, **kwargs)
  File "./test.py", line 97, in assert_multischeme_redirect
    scheme + '://' + partial_url, expected_loc, expected_code, **kwargs)
  File "./test.py", line 92, in assert_scheme_redirect
    % (url, expected_loc, resp.getheader('location')))
AssertionError: 'https://storage.googleapis.com/k8s-triage/index.html' != 'https://storage.googleapis.com/k8s-gubernator/triage/index.html'
- https://storage.googleapis.com/k8s-triage/index.html
+ https://storage.googleapis.com/k8s-gubernator/triage/index.html
?                                    +++++++++++
 : 
GET "http://go.kubernetes.io/triage" got an unexpected redirect location:
 want: https://storage.googleapis.com/k8s-gubernator/triage/index.html
 got:  https://storage.googleapis.com/k8s-triage/index.html
```

The  CI failed is related with this ?

**Comment by pacoxu** [comment]
According to the test failure, we need to revert this PR. 

@spiffxp

**Pull request merged**
