### PR TITLE
Update groups.yaml

### PR DESCRIPTION
**Pull request by NavedtheDev**

### CODE REVIEW

**Comment by dims** [comment]
@NavedtheDev this is the `leads@kubernetes.io` google group. Can you please indicate which SIG or WG you are the chair/lead of?

**Comment by NavedtheDev** [comment]
> @NavedtheDev this is the `leads@kubernetes.io` google group. Can you please indicate which SIG or WG you are the chair/lead of?

Sorry Sir if there is any mistake done from my side. But, I am not a chair/lead of any SIG or WG. 
I am really sorry if I have done any mistake.

**Comment by sftim** [comment]
/hold

>  I am not a chair/lead of any SIG or WG.

**Comment by ameukam** [comment]
Invalid PR.

/close

**Pull request closed without merging**
