### PR TITLE
remove non existing image hashes from staging repo

### PR DESCRIPTION
**Pull request by humblec**
The nfsplugin and smbplugin hashes looks to be unavailable in staging repo which causes the  generate script to mark for removal. These hashes would have been promoted to prod but right now missing in the staging repo. this commit mark those non existing hashes for removal to avoid disruption of capturing generate script output.

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Cc @andyzhangx @msau42 @xing-yang @pohly @jsafrane

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @xing-yang 

For approval.

**Pull request merged**
