### PR TITLE
k8s.gcr.io: Fix promoter manifest location for k8s-staging-addon-manager

### PR DESCRIPTION
**Pull request by justaugustus**
Noticed during a RelEng meeting that the promoter manifest for addon-manager is in the wrong directory.
This PR should actually trigger the addon-manager v9.1.2 images promotion from https://github.com/kubernetes/k8s.io/pull/1309.
cc: @MrHohn @spencer-p @dekkagaijin 

```console
$ skopeo inspect docker://k8s.gcr.io/addon-manager/kube-addon-manager:v9.1.2
FATA[0000] Error parsing image name "docker://k8s.gcr.io/addon-manager/kube-addon-manager:v9.1.2": Error reading manifest v9.1.2 in k8s.gcr.io/addon-manager/kube-addon-manager: manifest unknown: Failed to fetch "v9.1.2" from request "/v2/addon-manager/kube-addon-manager/manifests/v9.1.2". 
```

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @dims @spiffxp 
cc: @listx @kubernetes/release-engineering

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
From https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/k8s.io/1407/pull-k8sio-cip/1326194189301452800:

```console
I1110 16:05:33.812073      13 inventory.go:1911] ---------- BEGIN PROMOTION (DRY RUN) ----------
I1110 16:05:33.812149      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812157      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812162      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812167      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812173      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812178      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812183      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812190      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812195      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812200      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812205      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812223      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812228      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812233      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812241      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812246      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812251      13 inventory.go:1659] Request <nil>: OK
I1110 16:05:33.812256      13 inventory.go:1659] Request <nil>: OK
captured reqs summary:
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager -> asia.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager: Tag: 'v9.1.2' <ADD> sha256:a4f55e897391d6d46bee8bc2b7388c6fa146b9d956985db8ca3d72ca027c70f8
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager -> eu.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager: Tag: 'v9.1.2' <ADD> sha256:a4f55e897391d6d46bee8bc2b7388c6fa146b9d956985db8ca3d72ca027c70f8
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager -> us.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager: Tag: 'v9.1.2' <ADD> sha256:a4f55e897391d6d46bee8bc2b7388c6fa146b9d956985db8ca3d72ca027c70f8
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-amd64 -> asia.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-amd64: Tag: 'v9.1.2' <ADD> sha256:a4f55e897391d6d46bee8bc2b7388c6fa146b9d956985db8ca3d72ca027c70f8
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-amd64 -> eu.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-amd64: Tag: 'v9.1.2' <ADD> sha256:a4f55e897391d6d46bee8bc2b7388c6fa146b9d956985db8ca3d72ca027c70f8
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-amd64 -> us.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-amd64: Tag: 'v9.1.2' <ADD> sha256:a4f55e897391d6d46bee8bc2b7388c6fa146b9d956985db8ca3d72ca027c70f8
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm -> asia.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-arm: Tag: 'v9.1.2' <ADD> sha256:7a341655fe377b2b409c38b5944e27afef557d4803b7413320c7cb387df34655
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm -> eu.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-arm: Tag: 'v9.1.2' <ADD> sha256:7a341655fe377b2b409c38b5944e27afef557d4803b7413320c7cb387df34655
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm -> us.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-arm: Tag: 'v9.1.2' <ADD> sha256:7a341655fe377b2b409c38b5944e27afef557d4803b7413320c7cb387df34655
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm64 -> asia.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-arm64: Tag: 'v9.1.2' <ADD> sha256:dd17f08a81b60c8025e5e991cdd31341c7bc7b049e3fb603ed8827636aaa6dcf
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm64 -> eu.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-arm64: Tag: 'v9.1.2' <ADD> sha256:dd17f08a81b60c8025e5e991cdd31341c7bc7b049e3fb603ed8827636aaa6dcf
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-arm64 -> us.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-arm64: Tag: 'v9.1.2' <ADD> sha256:dd17f08a81b60c8025e5e991cdd31341c7bc7b049e3fb603ed8827636aaa6dcf
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-ppc64le -> asia.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-ppc64le: Tag: 'v9.1.2' <ADD> sha256:a7aba057e5b31f1709121878ce21ab33de2cd7929a417bd1efa37573a7ddd92b
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-ppc64le -> eu.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-ppc64le: Tag: 'v9.1.2' <ADD> sha256:a7aba057e5b31f1709121878ce21ab33de2cd7929a417bd1efa37573a7ddd92b
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-ppc64le -> us.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-ppc64le: Tag: 'v9.1.2' <ADD> sha256:a7aba057e5b31f1709121878ce21ab33de2cd7929a417bd1efa37573a7ddd92b
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-s390x -> asia.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-s390x: Tag: 'v9.1.2' <ADD> sha256:086f879de315fc2af950c7c916e01a7a1a573032aa34a0ec8dd1fc8a003bd468
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-s390x -> eu.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-s390x: Tag: 'v9.1.2' <ADD> sha256:086f879de315fc2af950c7c916e01a7a1a573032aa34a0ec8dd1fc8a003bd468
captured req: gcr.io/k8s-staging-addon-manager/kube-addon-manager-s390x -> us.gcr.io/k8s-artifacts-prod/addon-manager/kube-addon-manager-s390x: Tag: 'v9.1.2' <ADD> sha256:086f879de315fc2af950c7c916e01a7a1a573032aa34a0ec8dd1fc8a003bd468
I1110 16:05:33.812708      13 cip.go:418] ********** FINISHED (DRY RUN) **********
```

**Comment by MrHohn** [comment]
Sorry for the trouble and thanks for the fix!

**Pull request merged**
