### PR TITLE
test images: Promote images with Windows Server 2022 support

### PR DESCRIPTION
**Pull request by claudiubelu**
These PRs [1][2] added Windows Server 2022 support to the E2E test images.

[1] https://github.com/kubernetes/kubernetes/pull/104451
[2] https://github.com/kubernetes/kubernetes/pull/104455

Image SHAs:

```
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/agnhost:2.33 | jq '.[0].Digest'
"sha256:5b3a9f1c71c09c00649d8374224642ff7029ce91a721ec9132e6ed45fa73fd43"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/busybox:1.29-2 | jq '.[0].Digest'
"sha256:c318242786b139d18676b1c09a0ad7f15fc17f8f16a5b2e625cd0dc8c9703daf"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/echoserver:2.4 | jq '.[0].Digest'
"sha256:f245a63205ddf676928102669b6430b8d2b19ea1e89a44f0393bf27c64b19943"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/httpd:2.4.38-2 | jq '.[0].Digest'
"sha256:1b9d1b2f36cb2dbee1960e82a9344aeb11bd4c4c03abf5e1853e0559c23855e3"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/httpd:2.4.39-2 | jq '.[0].Digest'
"sha256:20f25f275d46aa728f7615a1ccc19c78b2ed89435bf943a44b339f70f45508e6"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/jessie-dnsutils:1.5 | jq '.[0].Digest'
"sha256:11e6a66017ba4e4b938c1612b7a54a3befcefd354796c04e1dba76873a13518e"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/kitten:1.5 | jq '.[0].Digest'
"sha256:96ad9ff35599fd8844b133c8e1d60910f82fddc4799b96b60dadb054f24d47f2"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/nautilus:1.5 | jq '.[0].Digest'
"sha256:99c0d6f1ad24a1aa1905d9c6534d193f268f7b23f9add2ae6bb41f31094bdd5c"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/nginx:1.14-2 | jq '.[0].Digest'
"sha256:13616070e3f29de4417eee434a8ef472221c9e51b3d037b5a6b46cef08eb7443"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/nginx:1.15-2 | jq '.[0].Digest'
"sha256:55d0552eb6538050ea7741e46b35d27eccffeeaed7010f9f2bad0a89c149bc6f"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/nonroot:1.2 | jq '.[0].Digest'
"sha256:b9e2958a3dd879e3cf11142228c6d073d0fc4ea2e857c3be6f4fb0ab5fb2c937"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/redis:5.0.5-1 | jq '.[0].Digest'
"sha256:d008cae1115464b2cb17a5655bb9ec2553c6f26c58edb0b69dc9b76fc0bcd554"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/resource-consumer:1.10 | jq '.[0].Digest'
"sha256:89f16100a57624bfa729b9e50c941b46a4fdceaa8818b96bdad6cab8ff44ca45"
ubuntu@ubuntu:~/run_e2e/k8s.io$ manifest-tool inspect --raw gcr.io/k8s-staging-e2e-test-images/sample-apiserver:1.17.5 | jq '.[0].Digest'
"sha256:f9c93b92b6ff750b41a93c4e4fe0bfe384597aeb841e2539d5444815c55b2d8f"
```

### CODE REVIEW

**Review by mkumatag — COMMENTED** [review]
/lgtm

**Comment by claudiubelu** [comment]
For some reason, the approve label didn't get added. :/

**Pull request merged**
