### PR TITLE
Promote artifacts for kops 1.17.2

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by bartsmykla** [comment]
Hi @justinsb, could you rebase the PR? :-)

**Comment by cblecker** [comment]
Is this still need @justinsb?
/lifecycle stale

**Comment by justinsb** [comment]
Sorry for delay - rebased!

We might want to rethink having all the images in one file as it causes conflicts; the proposed file manifests seem to avoid this (it supports multiple files, and the convention I'm using is one file per tag/version).

**Comment by justinsb** [comment]
Rebased to fix conflicts

**Pull request merged**
