### PR TITLE
gcp/dl: Define IAM policy for the production bucket

### PR DESCRIPTION
**Pull request by ameukam**
Define an IAM policy allowing release managers to access the production
bucket in read-only.

### CODE REVIEW

**Comment by ameukam** [comment]
cc @upodroid @BenTheElder

**Comment by ameukam** [comment]
FYI @kubernetes/release-engineering

**Review by xmudrii — APPROVED** [review]
/lgtm
/hold
for other folks to take a look

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
