### PR TITLE
DNS TTL -> 3600

### PR DESCRIPTION
**Pull request by thockin**
Other than prow, any other special cases?

### CODE REVIEW

**Comment by BenTheElder** [comment]
are we waiting for input on possible further snowflakes, or on actuation?

**Comment by stp-ip** [comment]
Fine with the change, but would love to hear the actual insight from the DNS people Tim looped in before doing preventive measures that might not address the actual problem.

**Comment by thockin** [comment]
I will actuate

**Comment by thockin** [comment]
Pushed.  I had to add `--force` in push.sh because of the number of changes, which is by intention.

**Comment by BenTheElder** [comment]
ACK

**Pull request merged**
