### PR TITLE
Image promotion for build-image v0.6.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for build-image v0.6.0
This is an automated PR generated from `kpromo`

xref: https://github.com/kubernetes/release/issues/3650

```
kpromo pr --fork cpanato --interactive --project build-image --tag v0.6.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by Verolop — COMMENTED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
