### PR TITLE
Add jackfrancis and remove shysank as CAPZ maintainers

### PR DESCRIPTION
**Pull request by mboersma**
Syncs up with https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/OWNERS_ALIASES

cc: @jackfrancis

### CODE REVIEW

**Comment by jackfrancis** [comment]
danke @mboersma

**Comment by jsturtevant** [comment]
lgtm

**Comment by mboersma** [comment]
Updated to remove @shysank from the list of active reviewers. See Kubernetes-sigs/cluster-api-provider-azure#2366.

**Comment by mboersma** [comment]
/retitle Add jackfrancis and remove shysank as CAPZ reviewers

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by mboersma** [comment]
/retitle Add jackfrancis and remove shysank as CAPZ maintainers

**Pull request merged**
