### PR TITLE
Image promotion for cluster-api v1.3.0-beta.0

### PR DESCRIPTION
**Pull request by sbueringer**
Image promotion for cluster-api v1.3.0-beta.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork sbueringer --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @sbueringer @vincepri" --tag v1.3.0-beta.0 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @CecileRobertMichon @enxebre @fabriziopandini @sbueringer @vincepri

### CODE REVIEW

**Review by ykakarap — APPROVED** [review]
/lgtm

**Comment by CecileRobertMichon** [comment]
@ykakarap @sbueringer should we change the promote-images make target in CAPI so it CCs the GitHub release team? 

/lgtm

**Comment by sbueringer** [comment]
@CecileRobertMichon  @ykakarap will do it

**Comment by ykakarap** [comment]
> @ykakarap @sbueringer should we change the promote-images make target in CAPI so it CCs the GitHub release team in the PR body?
> 
> /lgtm

Good idea. Will do.

**Comment by sbueringer** [comment]
Test: @kubernetes-sigs/cluster-api-maintainers

**Pull request merged**
