### PR TITLE
Add aws-encryption-provider staging repo

### PR DESCRIPTION
**Pull request by phuhung273**
Ref https://github.com/kubernetes-sigs/aws-encryption-provider/issues/71

### CODE REVIEW

**Comment by phuhung273** [comment]
Hi @dims @micahhausler, can you please help me with this PR. The doc state that `images.yaml` need at least 1 image. I cannot find how to publish that first image.

Checking this PR 2 weeks back #7351, look like we need a new image in gcr.io

**Comment by dims** [comment]
cc @upodroid

**Comment by upodroid** [comment]
This PR needs to be tweaked, I'll open a new one with the correct changes

**Comment by upodroid** [comment]
Please publish your images to 
`us-central1-docker.pkg.dev/k8s-staging-images/aws-encryption-provider` 

Thanks

**Pull request closed without merging**
