### PR TITLE
releng: Image promotion for v1.20.0-alpha.3

### PR DESCRIPTION
**Pull request by gianarb**
Image promotion for Kubernetes v1.20.0-alpha.3
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
