### PR TITLE
Image promotion for cluster-api v1.4.0-beta.0

### PR DESCRIPTION
**Pull request by ykakarap**
Image promotion for cluster-api v1.4.0-beta.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork ykakarap --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri" --tag v1.4.0-beta.0 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by ykakarap** [comment]
> 

Typo in `/approve` 😅

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
