### PR TITLE
promote etcd 3.4.13-4

### PR DESCRIPTION
**Pull request by pacoxu**
```
[root@pacoall ~]# docker pull  gcr.io/k8s-staging-etcd/etcd:3.4.13-4
Trying to pull repository gcr.io/k8s-staging-etcd/etcd ...
3.4.13-4: Pulling from gcr.io/k8s-staging-etcd/etcd
Digest: sha256:53e00d778301d4ce87aa369ec6ce38137a8b1fb627b00d978dd628b0687b8a7b
Status: Image is up to date for gcr.io/k8s-staging-etcd/etcd:3.4.13-4
[root@pacoall ~]#
[root@pacoall ~]# docker pull k8s.gcr.io/etcd:3.4.13-4
Trying to pull repository k8s.gcr.io/etcd ...
Pulling repository k8s.gcr.io/etcd
unauthorized: authentication required
[root@pacoall ~]# docker pull registry.k8s.io/etcd:3.4.13-4
Trying to pull repository registry.k8s.io/etcd ...
Pulling repository registry.k8s.io/etcd
Error: image etcd:3.4.13-4 not found
```
See https://github.com/kubernetes/kubernetes/pull/117921#discussion_r1233205475

### CODE REVIEW

**Review by wasup-yash — APPROVED** [review]
LGTM

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
