### PR TITLE
Update comms shadow email; Release Team 1.26

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

This PR corrects a typo in @Debanitrkl's email that came from a contact form, which has now also been corrected

/cc @Debanitrkl @palnabarun

### CODE REVIEW

**Review by Debanitrkl — APPROVED** [review]
/lgtm

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
