### PR TITLE
Update capi-openstack image hash

### PR DESCRIPTION
**Pull request by jichenjc**
kubernetes/k8s.io#1397 requested capi-openstack v0.3.2 version
but the sha is wrong per 
https://console.cloud.google.com/gcr/images/k8s-staging-capi-openstack/GLOBAL/capi-openstack-controller@sha256:cfdd7a67771e7a3fd956205c3351ad116e912b47982a95902b120bba036d7775/details?tab=info

so this PR is trying to upgrade the sha ..

### CODE REVIEW

**Comment by jichenjc** [comment]
for https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/661

**Comment by jichenjc** [comment]
@sbueringer @hidekazuna can you help to comment? Thanks

**Comment by hidekazuna** [comment]
seems fine, I do not have right to add lgtm though.

**Comment by sbueringer** [comment]
@hidekazuna Afaik you only have to join the Kubernetes org

**Comment by justaugustus** [comment]
FYI -- @listx @thockin @kubernetes/release-engineering 
This should've been a violation of the presubmit.

**Comment by thockin** [comment]
ohhhh, yes it should

**Comment by justaugustus** [comment]
> This should've been a violation of the presubmit.

Filed https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/277 for this.

**Comment by jichenjc** [comment]
sorry, not familiar with the releaes workflow, anything we need to do to revert/restore the change?

**Comment by listx** [comment]
> sorry, not familiar with the releaes workflow, anything we need to do to revert/restore the change?

Nothing needs to be reverted or changed as of this time; see my [comment](https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/277#issuecomment-726457256).

**Pull request merged**
