### PR TITLE
registry.k8s.io: decrease verbosity

### PR DESCRIPTION
**Pull request by ameukam**
reduce verbosity of archeio to minimize logging cost.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/hold
Will deploy on Monday/Tuesday.
cc @dims @BenTheElder

**Comment by dims** [comment]
/lgtm

early next week sounds good @ameukam

**Comment by BenTheElder** [comment]
ACK
How much is this costing currently?

**Comment by ameukam** [comment]
> ACK How much is this costing currently?

Currently ~975 $ but it's a growing cost.

**Comment by ameukam** [comment]
Deployed:

```bash
...
Apply complete! Resources: 0 added, 20 changed, 0 destroyed.
```

**Pull request merged**
