### PR TITLE
releng: temporary release manager access for salaxander

### PR DESCRIPTION
**Pull request by salaxander**
Requesting elevation of privileges to cut alpha release scheduled for November 01 2022.

cc: @jeremyrickard @cici37 @puerco

### CODE REVIEW

**Comment by jeremyrickard** [comment]
Can you open a tracking issue in https://github.com/kubernetes/sig-release/issues so we can remember to clean this. up after?

**Comment by jeremyrickard** [comment]
example: https://github.com/kubernetes/sig-release/issues/2024

**Comment by salaxander** [comment]
> kubernetes/sig-release#2024

Looks like we've already got this one -> https://github.com/kubernetes/sig-release/issues/2034

**Comment by jeremyrickard** [comment]
That is your longer lived RMA access (and should be closed now). We need one to explicitly track the elevated permissions

**Comment by puerco** [comment]
Ready @salaxander, lift the hold whenever you want to make it effective.

/approve
/hold

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
