### PR TITLE
Added RT lead shadows to k8s-infra-release-viewers and release-managers

### PR DESCRIPTION
**Pull request by alejandrox1**
xref: https://github.com/kubernetes/sig-release/issues/933

Signed-off-by: alejandrox1 <alarcj137@gmail.com>

### CODE REVIEW

**Comment by cblecker** [comment]
@alejandrox1 @justaugustus Should folks be cycled out of this list too?

**Comment by justaugustus** [comment]
@cblecker -- I'm planning to do pruning in a future PR, but I'll need to look over the lists, and I don't want to hold this one up since the 1.18 cycle starts on Monday.

**Pull request merged**
