### PR TITLE
test images: Promotes httpd and nginx images

### PR DESCRIPTION
**Pull request by claudiubelu**
A few fixes were merged for Windows images.

### CODE REVIEW

**Comment by claudiubelu** [comment]
Oh wow @dims , that was extremely fast. :)) I didn't even get to post a few extra details about the images. :))

I was going to mention that we've had a ``pull-kubernetes-e2e-aks-engine-azure-windows`` run on https://github.com/kubernetes/kubernetes/pull/87607 using the staging images and the tests using the httpd and nginx images passed.

**Comment by dims** [comment]
thanks for the info @claudiubelu  :)

**Comment by pacoxu** [comment]
link https://github.com/kubernetes/kubernetes/pull/99631 for the new httpd image label.

**Pull request merged**
