### PR TITLE
Add CoreDNS maintainers to the CoreDNS group and image staging

### PR DESCRIPTION
**Pull request by rajansandeep**
Adding myself and CoreDNS maintainers to help in pushing CoreDNS release to promoter.
I'm a CoreDNS maintainer and also involved in upgrading the CoreDNS version in upstream k8s every release.

### CODE REVIEW

**Comment by stp-ip** [comment]
/hold /approve

Approval on my side until we have GCB automate that would make direct uploads mostly unnecessary and only keep the OWNERS file around.

**Comment by bartsmykla** [comment]
Hi @stp-ip why /hold? Is it mistake?

**Comment by stp-ip** [comment]
Just wanted to get another review in before I decide this on my own :)

**Comment by thockin** [comment]
Are there other CoreDNS maintainers who need this access?

**Comment by stp-ip** [comment]
@johnbelamaric, @chrisohaver and @yongtang come to mind here as they are both interacting with both Kubernetes and are maintainers in CoreDNS.

The general plan is still automation, which minimizes the long term need. So with Dims, Sandeep and me we should have a good ability to promote for now, but happy to add some of the others as well on their request.

**Comment by yongtang** [comment]
@rajansandeep @stp-ip I am glad to help for contributing to CoreDNS release to k8s . You can add my name.

**Comment by johnbelamaric** [comment]
Sure, you can add mine as well.

**Comment by rajansandeep** [comment]
I updated the PR to include all
PTAL to see if the info is correct

**Comment by rajansandeep** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the kubernetes org.
> 
> Once all users have been added as [members](https://git.k8s.io/community/community-membership.md#member) of the org, you can trigger verification by writing `/verify-owners` in a comment.
> 
> * yongtang
>   
>   * k8s.gcr.io/images/k8s-staging-coredns/OWNERS

Looks like I can't include @yongtang

**Comment by yongtang** [comment]
Is it possible to add me as an org member?

**Comment by chrisohaver** [comment]
> Is it possible to add me as an org member?

https://github.com/kubernetes/community/blob/master/community-membership.md

**Comment by yongtang** [comment]
> https://github.com/kubernetes/community/blob/master/community-membership.md

OK I will keep an eye on pushing coredns to k8s, and contribute as needed. Will submit a member request after some time. Please keep me in the loop for coredns related k8s updates.

**Comment by spiffxp** [comment]
Changes are live

**Comment by stp-ip** [comment]
thx

**Pull request merged**
