### PR TITLE
Revert group name to staging-cip-test

### PR DESCRIPTION
**Pull request by thockin**
The name has to match the project

### CODE REVIEW

**Comment by thockin** [comment]
and I need you to activate this and remove the wrong named group :)

**Comment by thockin** [comment]
This needs to be deployed :)


*From: *Kubernetes Prow Robot <notifications@github.com>
*Date: *Thu, May 9, 2019 at 10:02 PM
*To: *kubernetes/k8s.io
*Cc: *Tim Hockin, Author

Merged #259 <https://github.com/kubernetes/k8s.io/pull/259> into master.

**Comment by cblecker** [comment]
Just deployed it :)

**Comment by cblecker** [comment]
```
2019/05/09 22:08:31  ======================= Updates =========================
2019/05/09 22:08:40 Trying to create group: k8s-infra-staging-cip-test@kubernetes.io
2019/05/09 22:08:40 > Successfully created group k8s-infra-staging-cip-test@kubernetes.io
2019/05/09 22:08:41 > Successfully updated group settings for k8s-infra-staging-cip-test@kubernetes.io to allow external members and other security settings
2019/05/09 22:08:43 Added davanum@gmail.com to k8s-infra-staging-cip-test@kubernetes.io as a MEMBER
2019/05/09 22:08:44 Added ihor@cncf.io to k8s-infra-staging-cip-test@kubernetes.io as a MEMBER
2019/05/09 22:08:45 Added linusa@google.com to k8s-infra-staging-cip-test@kubernetes.io as a MEMBER
2019/05/09 22:08:46 Added spiffxp@google.com to k8s-infra-staging-cip-test@kubernetes.io as a MEMBER
2019/05/09 22:08:46 Added thockin@google.com to k8s-infra-staging-cip-test@kubernetes.io as a MEMBER
2019/05/09 22:08:52 Removing group k8s-infra-artifact-promoter-test@kubernetes.io
```

**Comment by thockin** [comment]
You can also remove the old group that I errantly asked for the rename to :)

*From: *Christoph Blecker <notifications@github.com>
*Date: *Thu, May 9, 2019 at 10:09 PM
*To: *kubernetes/k8s.io
*Cc: *Tim Hockin, Author

2019/05/09 22:08:31  ======================= Updates =========================

**Comment by thockin** [comment]
And pushed to cip-test

*From: *Tim Hockin <notifications@github.com>
*Date: *Thu, May 9, 2019 at 10:14 PM
*To: *kubernetes/k8s.io
*Cc: *Tim Hockin, Your activity

You can also remove the old group that I errantly asked for the rename to :)

**Pull request merged**
