### PR TITLE
Add a nodepool with bigger nodes

### PR DESCRIPTION
**Pull request by thockin**
Perf-dash needs more memory than existing nodes could offer.

### CODE REVIEW

**Comment by thockin** [comment]
xref #549

**Comment by bartsmykla** [comment]
Hi @dims @thockin 

Can you run the terraform to provision this new pool?

**Comment by dims** [comment]
@bartsmykla i believe @cblecker is the one with terraform knowledge, hopefully we can add a README or something that can guide me to do this next time Christoph (if there's one already please let me know)

**Comment by bartsmykla** [comment]
@dims I'm working on it exactly right now :-D

**Comment by thockin** [comment]
I can apply this now

**Comment by thockin** [comment]
Done

**Comment by bartsmykla** [comment]
Thank you @thockin! :-)

**Pull request merged**
