### PR TITLE
Request static address for prow staging

### PR DESCRIPTION
**Pull request by ameukam**
Request a public static ip address for prow staging instance.
Ref: https://github.com/kubernetes/k8s.io/issues/1394

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by thockin** [comment]
For use by a Service LB or by an Ingress?

Can you suggest a name (and add it to infra/gcp/ensure-static-ips.sh) ?

**Comment by thockin** [comment]
I am dumb and thought this was an issue.  I will create your IP :)

**Comment by thockin** [comment]
Created

/lgtm
/approve

**Comment by ameukam** [comment]
@thockin can you please paste the IP address created ? I don't have access to the _External IP Addresses_.

**Comment by bartsmykla** [comment]
@ameukam
```
prow-k8s-io-ingress-staging | 35.190.121.209
```

**Pull request merged**
