### PR TITLE
configure kueue to promote from AR instead of GCR

### PR DESCRIPTION
**Pull request by upodroid**
ref:
- https://github.com/kubernetes-sigs/kueue/pull/2476

@alculquicondor

### CODE REVIEW

**Comment by alculquicondor** [comment]
/hold
I suppose we need to start publishing images here first https://github.com/kubernetes-sigs/kueue/pull/2476

However, I'm going on vacation today. I don't feel like changing this right now, as sometimes our customers depend on quick bugfixes from the staging.

**Comment by alculquicondor** [comment]
FYI @mimowo @gabesaba @tenzen-y, in case you feel comfortable  proceeding with this.

**Comment by upodroid** [comment]
We merge this PR after the other 2 merged.

**Comment by tenzen-y** [comment]
> FYI @mimowo @gabesaba @tenzen-y, in case you feel comfortable proceeding with this.

LGTM

**Review by tenzen-y — COMMENTED** [review]
Thanks!
/lgtm
/approve

/hold cancel

**Pull request merged**
