### PR TITLE
releng: Image promotion for kubernetes v1.24.0-rc.1

### PR DESCRIPTION
**Pull request by jimangel**
Image promotion for kubernetes v1.24.0-rc.1
This is an automated PR generated from `kpromo`
```
kpromo pr --fork jimangel --reviewers "" --tag v1.24.0-rc.1
```

/hold
cc:

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
