### PR TITLE
Fix promotion of ecr-credential-provider images

### PR DESCRIPTION
**Pull request by ialidzhikov**
See https://github.com/kubernetes/k8s.io/pull/7283#issuecomment-2345364246

I computed manually the sha256s from https://console.cloud.google.com/storage/browser/k8s-staging-provider-aws.

prod-artifacts: https://console.cloud.google.com/storage/browser/k8s-artifacts-prod/binaries/cloud-provider-aws

### CODE REVIEW

**Comment by cartermckinnon** [comment]
That did it: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-file-promo/1834165363848253440

thanks @ialidzhikov

**Comment by ialidzhikov** [comment]
Thank you, @cartermckinnon ! 🚀

**Pull request merged**
