### PR TITLE
Fastly: use a private bucket as origin for dl.k8s.io

### PR DESCRIPTION
**Pull request by ameukam**
- Ensure the VCL service can use a GCS private bucket as origin using AWS
  auth headers. GCS API is S3-compatible. We apply the snippet from https://quic.fastly.com/documentation/solutions/examples/google-cloud-storage-origin-private/
  - Enable Shielding for the service. More informations on https://www.fastly.com/documentation/guides/concepts/shielding/
  - Disable the healthcheck for the service. This is not required since we
    have Origin Inspector activated and is currently not working with the
    private bucket.
- Only enable custom headers for debugging

### CODE REVIEW

**Comment by ameukam** [comment]
/hold

I will deploy this next Monday.

cc @dims @BenTheElder

**Review by BenTheElder — COMMENTED** [review]
This vaguely looks right? and I trust you. But I'm also no expert here.
/lgtm
/approve
/hold

@bentheelder reviewing VCL:

**Comment by BenTheElder** [comment]
I think we may need to revert. Seeing failures downloading `https://dl.k8s.io/easy-rsa/easy-rsa.tar.gz` in Kubernetes PR blocking jobs.

**Comment by BenTheElder** [comment]
https://kubernetes.slack.com/archives/CCK68P2Q2/p1724109194402359?thread_ts=1724095488.829859&cid=CCK68P2Q2

**Comment by BenTheElder** [comment]
Screenshot 2024-08-19 at 4 18 36 PM
Screenshot 2024-08-19 at 4 18 52 PM

**Comment by BenTheElder** [comment]
discussing mitigations in the above slack thread

**Pull request merged**
