### PR TITLE
k8s infra groups: rotate in bentheelder and upodroid, remove spiffxp

### PR DESCRIPTION
**Pull request by BenTheElder**
xref: https://github.com/kubernetes/community/pull/7584

### CODE REVIEW

**Comment by BenTheElder** [comment]
> --- FAIL: TestHardcodedGroupsForParanoia (0.00s)

haha

**Comment by upodroid** [comment]
do you also want to fix the OWNERS file in this PR?

**Comment by BenTheElder** [comment]
We should update that too, I was focused on making sure you/I have break-glass access to the infrastructure and we don't have dangling account references.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/k8s.io/pull/6045

**Pull request merged**
