### PR TITLE
releng: Image promotion for kubernetes v1.26.0-alpha.3

### PR DESCRIPTION
**Pull request by salaxander**
Image promotion for kubernetes v1.26.0-alpha.3
This is an automated PR generated from `kpromo`
```
kpromo pr --fork salaxander --interactive --tag v1.26.0-alpha.3
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by puerco** [comment]
Thanks @salaxander !
/lgtm
/approve

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by saschagrunert** [comment]
CO is still too slow (1h), but I have another idea for optimizing that. 🤭

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
