### PR TITLE
sig-cluster-lifecycle/cluster-api: add chrischdi to maintainers

### PR DESCRIPTION
**Pull request by chrischdi**
Adding myself to the approvers for cluster-api relevant staging images.

xref:

https://github.com/kubernetes-sigs/cluster-api/pull/9997

/assign sbueringer

### CODE REVIEW

**Comment by ameukam** [comment]
No need to update the `k8s.gcr.io` path. We stopped to do promotions to `k8s.gcr.io`

**Comment by neolit123** [comment]
> [registry.k8s.io/images/k8s-staging-cluster-api/OWNERS](https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-cluster-api/OWNERS)

/approve

**Comment by sbueringer** [comment]
> No need to update the `k8s.gcr.io` path. We stopped to do promotions to `k8s.gcr.io`

Makes sense. But should be fine either way I guess

/lgtm

**Comment by chrischdi** [comment]
Removed from the old registry part (to get rid of `do-not-merge/blocked-path`.

**Comment by sbueringer** [comment]
> Removed from the old registry part (to get rid of `do-not-merge/blocked-path`).

Ah wasn't aware it's blocked on this level :D. Then it makes sense to not add yourself there of course

**Pull request merged**
