### PR TITLE
Add an AR staging repository for ingress-nginx

### PR DESCRIPTION
**Pull request by ameukam**
Related to:
 - https://github.com/kubernetes/ingress-nginx/issues/12400

### CODE REVIEW

**Comment by ameukam** [comment]
cc @upodroid @dims

**Comment by dims** [comment]
Do we need the atlantis stuff to go 🟢 ?

**Comment by ameukam** [comment]
@dims not really. I don't think if it's fully deployed but it's not currently a requirement for this PR.

**Comment by dims** [comment]
/approve
/lgtm
/hold 

(please remove hold when ready)

**Comment by upodroid** [comment]
/override atlantis/plan
/override atlantis/plan: infra/gcp/terraform/k8s-staging-images/default

**Comment by upodroid** [comment]
/override atlantis/plan
/override "atlantis/plan: infra/gcp/terraform/k8s-staging-images/default"

**Pull request merged**
