### PR TITLE
Promoting pause image 3.10

### PR DESCRIPTION
**Pull request by dims**
Changes since 3.9:
https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md#310

```
❯ krane digest gcr.io/k8s-staging-kubernetes/pause:3.10
sha256:ee6521f290b2168b6e0935a181d4cff9be1ac3f505666ef0e3c98fae8199917a
```

Related to: https://github.com/kubernetes/kubernetes/pull/125067

### CODE REVIEW

**Comment by BenTheElder** [comment]
dupe of https://github.com/kubernetes/k8s.io/pull/6839 ? :-)

**Comment by dims** [comment]
Here's where the image was built and pushed:
https://storage.googleapis.com/kubernetes-jenkins/logs/post-kubernetes-push-image-pause/1793743356572995584/build-log.txt

**Review by puerco — APPROVED** [review]

**Comment by BenTheElder** [comment]
> Here's where the image was built and pushed:
> https://storage.googleapis.com/kubernetes-jenkins/logs/post-kubernetes-push-image-pause/1793743356572995584/build-log.txt

We should prefer to get the image digest from the build logs instead of the current staging digest.

**Comment by BenTheElder** [comment]
(as mentioned in https://github.com/kubernetes/k8s.io/pull/6839#issue-2313813747, it's at the end of the build log)

**Pull request closed without merging**
