### PR TITLE
releng: Image promotion for v1.21.0-alpha.1

### PR DESCRIPTION
**Pull request by puerco**
Image promotion for Kubernetes v1.21.0-alpha.1
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
