### PR TITLE
[WIP] Add new conduct committee members

### PR DESCRIPTION
**Pull request by celestehorgan**
Forgot this one! Hopefully this fixes our mailing list woes, too.

cc: @AevaOnline @tashimi @tpepper @karenhchu

### CODE REVIEW

**Comment by celestehorgan** [comment]
😭  I can't get prow to talk to me in this repository, but @spiffxp @thockin please take a look!

**Comment by ameukam** [comment]
@celestehorgan If you need to remove the label `do-not-merge/work-in-progress`, the `[WIP]` need to be removed from the title of the PR.

**Comment by ameukam** [comment]
Duplicate of #1244.

**Comment by spiffxp** [comment]
/close
Closing as duplicate of #1244 (sorry I missed this earlier)

**Pull request closed without merging**
