### PR TITLE
publish scheduler-plugins v0.25.12

### PR DESCRIPTION
**Pull request by Huang-Wei**
cc @zwpaper

### CODE REVIEW

**Comment by zwpaper** [comment]
@denkensk could you please help with this release

**Comment by Huang-Wei** [comment]
@zwpaper you can just approve it by /lgtm if it looks good to you.

**Comment by zwpaper** [comment]
I have checked the PR and build logs, and pull it locally

/lgtm

**Comment by zwpaper** [comment]
I will submit a Member request for Kubernetes org later today, and then I should be able to do /lgtm

**Pull request merged**
