### PR TITLE
Release-1.22: Add 1.22 RT Leads to relevant groups

### PR DESCRIPTION
**Pull request by savitharaghunathan**
Add @annajung @divya-mohan0209 @erismaster  @kikisdeliveryservice @savitharaghunathan to the following:

-   leads@
-   release-managers@
-   release-team@

Offboard 1.21 RT Leads.

/assign
/sig release
/priority critical-urgent
/assign @justaugustus @saschagrunert @jeremyrickard @hasheddan
/cc @annajung @divya-mohan0209 @erismaster @kikisdeliveryservice

### CODE REVIEW

**Comment by savitharaghunathan** [comment]
Ref: https://github.com/kubernetes/sig-release/issues/1522

**Review by justaugustus — CHANGES_REQUESTED** [review]
@savitharaghunathan -- Let's scan the leads@ list for removals as well.

**Pull request merged**
