### PR TITLE
Allow kgolab to write to k8s-staging-autoscaling GCR

### PR DESCRIPTION
**Pull request by kgolab**
Reason: to help with releases, in particular to release new Addon Resizer for https://github.com/kubernetes/autoscaler/pull/5234.

### CODE REVIEW

**Comment by kgolab** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * kgolab
>   
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

Not sure if this helps any but I'm both reviewer & approver under [k/autoscaler/vertical-pod-autoscaler/OWNERS](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/OWNERS).

**Comment by ameukam** [comment]
> k/autoscaler/vertical-pod-autoscaler/OWNERS

Can you open an membership request in https://github.com/kubernetes/org/issues/new/choose ? Since you have a large number of contributions, process should be quick.

**Comment by ameukam** [comment]
/assign @gjtempleton @mwielgus 
For approval

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
