### PR TITLE
Add cluster resources for slack-infra

### PR DESCRIPTION
**Pull request by spiffxp**
Basically a mirror of sigs.k8s.io/slack-infra/cluster/* minus the managed certs and ingress in root

Secrets encrypted with git-crypt

/assign @bartsmykla

### CODE REVIEW

**Comment by spiffxp** [comment]
Copy-pasting resources over here seems like a brute-force approach, prone to drift if that repo sees further development.  As a followup it might be worth investigating an approach that reuses what's there, and patches in what we need.

**Comment by bartsmykla** [comment]
I think we can iterate as I did with perf-dash ([#746](https://github.com/kubernetes/k8s.io/pull/746))

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/k8s.io/issues/751

**Pull request merged**
