### PR TITLE
build-image: Promote kube-cross v1.14.2-1 image

### PR DESCRIPTION
**Pull request by justaugustus**
(Companion PR to https://github.com/kubernetes/release/pull/1246, https://github.com/kubernetes/kubernetes/pull/88638)

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @BenTheElder @cblecker @liggitt @dims @listx
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
@justaugustus for my own edification, the other go work will follow this type of a similar pattern of upgrade

**Comment by justaugustus** [comment]
> @justaugustus for my own edification, the other go work will follow this type of a similar pattern of upgrade

@markyjackson-taulia -- Yep! https://github.com/kubernetes/release/issues/1134 is the umbrella issue for the go1.13.8/go1.13.9 bumps and will give you the best idea of order of operations for all of this (since they're patch releases, not minors).

I'm hoping to have time next week to knock out instructions for the minor bumps and close the first iteration of https://github.com/kubernetes/release/issues/1139.

**Comment by markyjackson-taulia** [comment]
cc @Verolop

**Pull request merged**
