### PR TITLE
Image promotion for metrics-server v0.7.0

### PR DESCRIPTION
**Pull request by dgrisonnet**
Image promotion for metrics-server v0.7.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork dgrisonnet --interactive --project metrics-server --reviewers "CatherineF-dev" --tag v0.7.0 --image metrics-server
```

/hold
cc: CatherineF-dev

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
/assign @serathius 

for approval

**Comment by dgrisonnet** [comment]
I have no clue what `gcr.io/gke-release-staging` is. It sounds like something for downstream GKE?

**Comment by dgrisonnet** [comment]
The upstream staging bucket is here: https://console.cloud.google.com/gcr/images/k8s-staging-metrics-server/GLOBAL?pli=1

**Comment by CatherineF-dev** [comment]
Yes! I can see this image now.

**Pull request merged**
