### PR TITLE
Remove rbac permissions for extensions.io/v1beta1 resources

### PR DESCRIPTION
**Pull request by ameukam**
Ref: https://github.com/kubernetes/k8s.io/issues/1031

/hold

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
`artifactserver/manifest.yaml` still has this but since it's not deployed that's fine; should consider modifying it if you're going to block merges on use of these resources

**Comment by spiffxp** [comment]
Remove /hold when ready to deploy

**Comment by ameukam** [comment]
Change successfully deployed. 

<details>
<summary>Details</summary>
$ ./ensure-namespaces.sh gke_kubernetes-public_us-central1_aaa
Create namespace: gcsweb
namespace/gcsweb unchanged
Apply namespace-user role: gcsweb
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: gcsweb
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: gcsweb is present
Create namespace: kettle
namespace/kettle unchanged
Apply namespace-user role: kettle
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: kettle
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: kettle is present
Create namespace: k8s-io-prod
namespace/k8s-io-prod unchanged
Apply namespace-user role: k8s-io-prod
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: k8s-io-prod
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: k8s-io-prod is present
Create namespace: k8s-io-canary
namespace/k8s-io-canary unchanged
Apply namespace-user role: k8s-io-canary
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: k8s-io-canary
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: k8s-io-canary is present
Create namespace: node-perf-dash
namespace/node-perf-dash unchanged
Apply namespace-user role: node-perf-dash
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: node-perf-dash
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: node-perf-dash is present
Create namespace: perfdash
namespace/perfdash unchanged
Apply namespace-user role: perfdash
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: perfdash
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: perfdash is present
Create namespace: prow
namespace/prow unchanged
Apply namespace-user role: prow
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: prow
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: prow is present
Create namespace: publishing-bot
namespace/publishing-bot unchanged
Apply namespace-user role: publishing-bot
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: publishing-bot
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: publishing-bot is present
Create namespace: sippy
namespace/sippy unchanged
Apply namespace-user role: sippy
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: sippy
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: sippy is present
Create namespace: slack-infra
namespace/slack-infra unchanged
Apply namespace-user role: slack-infra
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: slack-infra
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: slack-infra is present
Create namespace: triageparty-release
namespace/triageparty-release unchanged
Apply namespace-user role: triageparty-release
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: triageparty-release
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: triageparty-release is present
Done
</details>

**Pull request merged**
