### PR TITLE
infra/gcp: Deploy archeio v20220321-19bcd2d

### PR DESCRIPTION
**Pull request by ameukam**
Related:
  - https://github.com/kubernetes/k8s.io/issues/3317
 
Followup of:
  - https://github.com/kubernetes-sigs/oci-proxy/pull/28

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by BenTheElder** [comment]
CLA seems stuck ...

**Comment by mrbobbytables** [comment]
gah
/easycla

**Pull request merged**
