### PR TITLE
add kubetest2 staging project

### PR DESCRIPTION
**Pull request by amwat**
Per https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#creating-staging-repos

fixes: https://github.com/kubernetes/k8s.io/issues/1818

/cc @spiffxp @BenTheElder

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by amwat** [comment]
Is step 4 still manual ?

```
Once the PR merges:

ping @dims or @cblecker to create the necessary google group.
ping @thockin or @justinsb to run ensure-staging-storage.sh to create the staging repo.
```

/cc @dims @cblecker 

/cc @thockin @justinsb

**Comment by spiffxp** [comment]
Uhhhh it is, let me run the script now

**Comment by spiffxp** [comment]
OK, done
```yaml
# $ gcloud projects get-iam-policy k8s-staging-kubetest2
bindings:
- members:
  - serviceAccount:4886069902@cloudbuild.gserviceaccount.com
  - serviceAccount:deployer@k8s-prow.iam.gserviceaccount.com
  - serviceAccount:gcb-builder@k8s-infra-prow-build-trusted.iam.gserviceaccount.com
  role: roles/cloudbuild.builds.builder
- members:
  - group:k8s-infra-staging-kubetest2@kubernetes.io
  role: roles/cloudbuild.builds.editor
- members:
  - serviceAccount:service-4886069902@gcp-sa-cloudbuild.iam.gserviceaccount.com
  role: roles/cloudbuild.serviceAgent
- members:
  - serviceAccount:service-4886069902@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:k8s-infra-gcr-vuln-scanning@k8s-artifacts-prod.iam.gserviceaccount.com
  role: roles/containeranalysis.occurrences.viewer
- members:
  - serviceAccount:service-4886069902@containerregistry.iam.gserviceaccount.com
  role: roles/containerregistry.ServiceAgent
- members:
  - serviceAccount:service-4886069902@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - user:spiffxp@google.com
  role: roles/owner
- members:
  - group:k8s-infra-staging-kubetest2@kubernetes.io
  role: roles/serviceusage.serviceUsageConsumer
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-kubetest2@kubernetes.io
  role: roles/viewer
etag: BwW-TFApFNg=
version: 1
```

**Comment by amwat** [comment]
Thanks Aaron!

**Pull request merged**
