### PR TITLE
releng: Image promotion for v1.21.0-alpha.3

### PR DESCRIPTION
**Pull request by ameukam**
Image promotion for Kubernetes v1.21.0-alpha.3

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

/hold
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by ameukam** [comment]
Release issue with passing mock stage, mock release and stage - kubernetes/sig-release#1457

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
