### PR TITLE
k8s.io/configmap-www-golang.yaml: add code-generator repo

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by thockin** [comment]
I don't even know what this repo is for?

**Comment by thockin** [comment]
@ixdy to merge and push

**Comment by ixdy** [comment]
this seems fine, but maybe we should actually have something in https://github.com/kubernetes/code-generator first?

**Comment by sttts** [comment]
> this seems fine, but maybe we should actually have something in https://github.com/kubernetes/code-generator first?

On its way. Will ping here when the publishing bot is updated.

**Comment by cblecker** [comment]
@ixdy @sttts Would this hurt to merge/deploy before there is actual code there? I'm toying with `dep` again and it's dying because of this :(

**Comment by sttts** [comment]
@cblecker I don't think it hurts. We just have an empty repo behind it.

**Comment by ixdy** [comment]
passes tests on canary. merging.

**Pull request merged**
