### PR TITLE
Manage organization roles

### PR DESCRIPTION
**Pull request by spiffxp**
This addresses most of https://github.com/kubernetes/k8s.io/issues/1659

To do so I added a script to generate roles out of other roles/permissions (https://github.com/kubernetes/k8s.io/issues/1656).

A role spec looks like the following:
```yaml
# role name, e.g.
name: "foo.bar"
# human readable title for the role, e.g.
title: "Foo Barrer"
# human readable description for the role, e.g. 
description: "Allows doing Bar on Foo resources"
# include permissions from the following...
include:
  # a list of permissions, e.g.
  permissions:
  - foo.bar.doSomething
  # a list of roles, e.g.
  roles:
  - roles/foo.bar
  # only include permissions matching any extended regex in this list, e.g.
  permissionRegxes:
  - ^foo.bar.(get|list)
exclude:
  # exclude any permissions matching any extended regex in this list, e.g.
  permissionRegexes:
  - SuperDangerousOperation$
```

Sadly, I did this with bash and yq.  Redoing this with go would be a great help-wanted.

Updates the following managed org roles:
- `prow.viewer` - Auditing `roles/viewer` from `k8s-infra-e2e-prow-viewers@` made me realize they don't have view access to buckets in most e2e projects.  Now they will.

Adds the following previously unmanaged org roles:
- `CustomRole` - not a good name, but held off on migrating to better name until I get some historical context
- `StorageBucketLister` - this can go away once audit.viewer is live

Adds the following new managed org roles:
- `audit.viewer` - replace the sundry bindings used by `k8s-infra-gcp-auditors@`
  - I ran the script this far already to vet the effective permissions before and after look good (https://gist.github.com/spiffxp/7d2bfaa9c510de89a7f2ce1c31ec1a00)
- `organization.admin` - replace the sundry non-`roles/owner` bindings used by `k8s-infra-gcp-org-admins@`
  - not running the script to deploy this until I've gotten review

There is a little more followup I would like to do to close out https://github.com/kubernetes/k8s.io/issues/1659, but not in this PR:
- pull the `ServiceAccountLister` role out of projects and up into the org (but keep the binding(s) project level)
- remove `StorageBucketLister` unless there's a reason to keep it around
- remove the detritus cleanup code marked with TODO's
- setup a periodic job to refresh the custom roles to pick up new permissions that are added over time

### CODE REVIEW

**Comment by dims** [comment]
I like the idea! but don't know enough GCP stuff to review thoroughly. +1 to ship and iterate too!

**Comment by spiffxp** [comment]
Rebased due to https://github.com/kubernetes/k8s.io/pull/1733

**Comment by ameukam** [comment]
/lgtm
(I blindly trust Aaron as a Bash Fighter. 😃)

**Comment by ameukam** [comment]
/hold
Un-hold when you're ready.

**Comment by spiffxp** [comment]
Using the same process as https://gist.github.com/spiffxp/7d2bfaa9c510de89a7f2ce1c31ec1a00, I removed the early exit and ran `./infra/gcp/ensure-organization.sh`

The resulting diff for k8s-infra-gcp-org-admins' permissions looks expected; nothing lost, and resourecemanager.folder permissions gained.
```
$ diff org-admin-permissions-{before,after}.txt
3460a3461,3462
> - resourcemanager.folders.create
> - resourcemanager.folders.delete
3463a3466
> - resourcemanager.folders.move
3464a3468,3469
> - resourcemanager.folders.undelete
> - resourcemanager.folders.update
```

**Comment by spiffxp** [comment]
/kind feature
/kind cleanup
/area infra/auditing
tagging issues/PRs related to audit followup

**Pull request merged**
