### PR TITLE
Promote cluster-proportional-autoscaler 1.8.3 images

### PR DESCRIPTION
**Pull request by MrHohn**
We are cutting a new release for cluster-proportional-autoscaler and need to release these images.

- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler@sha256:67640771ad9fc56f109d5b01e020f0c858e7c890bb0eb15ba0ebd325df3285e7/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-amd64@sha256:dce43068853ad396b0fb5ace9a56cc14114e31979e241342d12d04526be1dfcc/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-arm@sha256:241ee3c88ee69c0362b1e9f20b288345b42f2a59645c1ea8b7d39fdec221af38/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-arm64@sha256:a456b304377b79cba3290e9990003040941c0b3da18621a5ed734265287968c5/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065
- https://pantheon.corp.google.com/gcr/images/k8s-staging-cpa/GLOBAL/cluster-proportional-autoscaler-ppc64le@sha256:ac90f5dc759a917c2c98de81a9b5b77bf426b95e56caebaefcc0f2e01e2b8db9/details?tab=info&project=k8s-staging-cpa&folder&organizationId=758905017065

Ref kubernetes-sigs/cluster-proportional-autoscaler#89.

cc @johngmyers @hakman

### CODE REVIEW

**Comment by MrHohn** [comment]
Hey Linus, mind taking a look again? Thanks!
/assign @listx

**Comment by listx** [comment]
Sorry I didn't get to this in time. Please let me know if there are any issues with the promotion.

**Comment by hakman** [comment]
No issues @listx. Everything worked great. Thanks!

**Pull request merged**
