### PR TITLE
releng: Promote vulndash:v0.4.3-3

### PR DESCRIPTION
**Pull request by cpanato**
The vulndash image is now built with go1.15.7

- `vulndash:v0.4.3-3`: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-release-push-image-vulndash/1357628759401828352

Required for go1.15.8 updates: https://github.com/kubernetes/release/issues/1895

/assign @hasheddan @saschagrunert @xmudrii @puerco 

cc: @kubernetes/release-engineering @ameukam

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
