### PR TITLE
audit: use k8s-infra-ci-robot for audit PRs

### PR DESCRIPTION
**Pull request by spiffxp**
Followup to https://github.com/kubernetes/test-infra/pull/23048

I thought I had this all setup so config changes were only needed in one place (test-infra), but may as well make the defaults match the secret I just set the job to use.

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc @ameukam @dims 
FYI @hh cncf-ci-robot can still be used for stuff but I figured it was time to start using a k8s account for the audit PR job now that we have one setup

**Comment by ameukam** [comment]
/lgtm
/hold
Remove hold when ready to deploy.

**Pull request merged**
