### PR TITLE
Add prometheus-adapter staging repo

### PR DESCRIPTION
**Pull request by dgrisonnet**
Ref: https://github.com/kubernetes-sigs/prometheus-adapter/issues/414

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Running `./infra/gcp/ensure-staging-storage prometheus-adapter`

**Comment by spiffxp** [comment]
Done, should be good to go @dgrisonnet

**Comment by dgrisonnet** [comment]
Awesome, thank you @spiffxp :)

**Pull request merged**
