### PR TITLE
releng: Image promotion for Kubernetes v1.20.beta.0

### PR DESCRIPTION
**Pull request by Verolop**
Logs from the cloud build:

[Mock Stage](https://console.cloud.google.com/cloud-build/builds/fbd13299-28c1-4cd2-b064-5fc23ac52500?authuser=1&project=kubernetes-release-test)
[Mock Release](https://console.cloud.google.com/cloud-build/builds/f13e4558-c21d-44b3-8abe-2d9db2c4a903?project=kubernetes-release-test&authuser=1)
[Stage](https://console.cloud.google.com/cloud-build/builds/fc34df96-d905-4415-bd57-de3771e7833f?project=kubernetes-release-test&authuser=1)

Command to generate the config file used:

`cip-mm --base_dir=$GOPATH/src/github.com/verolop/k8s.io/k8s.gcr.io --staging_repo=gcr.io/k8s-staging-kubernetes --filter_tag=v1.20.0-beta.0`

@kubernetes/release-engineering

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
