### PR TITLE
releng: Image promotion for kubernetes v1.32.0-alpha.2

### PR DESCRIPTION
**Pull request by jimangel**
Image promotion for kubernetes v1.32.0-alpha.2
This is an automated PR generated from `kpromo`
```
kpromo pr --fork jimangel --tag v1.32.0-alpha.2
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/hold cancel

**Pull request merged**
