### PR TITLE
publishing-bot: Add ExternalSecret

### PR DESCRIPTION
**Pull request by ameukam**
Related:
 - Ref: https://github.com/kubernetes/k8s.io/issues/2220
 - Followup of : https://github.com/kubernetes/k8s.io/pull/2825

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/hold
I can't monitor the impact of the change today. I'll will unhold tomorrow morning (CEST)

cc @nikhita @dims

**Comment by spiffxp** [comment]
/assign @nikhita
ref: https://github.com/kubernetes/k8s.io/issues/2430

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
