### PR TITLE
Image promotion for build-image v2.3.1-go1.20.2-bullseye.0 / v2.3.1-go1.19.7-bullseye.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for build-image v2.3.1-go1.20.2-bullseye.0 / v2.3.1-go1.19.7-bullseye.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork cpanato --interactive --project build-image --tag v2.3.1-go1.20.2-bullseye.0 --tag v2.3.1-go1.19.7-bullseye.0
```

related to https://github.com/kubernetes/release/issues/2948

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
