### PR TITLE
Add ii streaming humans to k8s stream-team

### PR DESCRIPTION
**Pull request by hh**
Stephen, Caleb, and myself will be assisting with the Kubernetes Community Celebration Dec 13thish

### CODE REVIEW

**Comment by Riaankl** [comment]
/retitle Add ii streaming humans to k8s stream-team

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
@hh can you remove the `@` symbol from the commit msg? That will fix the invalid commit msg error.

**Pull request closed without merging**
