### PR TITLE
Allow checking pod resource usage

### PR DESCRIPTION
**Pull request by mborsz**
This should allow running kubectl top pods -n namespace

Without that it's hard to validate resource requests and limits.

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
Remove when ready to deploy (I am AFK)

**Comment by spiffxp** [comment]
```
$ gcloud container clusters get-credentials aaa --project=kubernetes-public --region=us-central1
$ cd ./infra/gcp/namespaces
$ ./ensure-namespaces.sh gke_kubernetes-public_us-central1_aaa
Create namespace: gcsweb
namespace/gcsweb unchanged
Apply namespace-user role: gcsweb
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: gcsweb
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: gcsweb is present
Create namespace: k8s-io-prod
namespace/k8s-io-prod unchanged
Apply namespace-user role: k8s-io-prod
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: k8s-io-prod
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: k8s-io-prod is present
Create namespace: k8s-io-canary
namespace/k8s-io-canary unchanged
Apply namespace-user role: k8s-io-canary
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: k8s-io-canary
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: k8s-io-canary is present
Create namespace: node-perf-dash
namespace/node-perf-dash unchanged
Apply namespace-user role: node-perf-dash
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: node-perf-dash
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: node-perf-dash is present
Create namespace: perfdash
namespace/perfdash unchanged
Apply namespace-user role: perfdash
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: perfdash
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: perfdash is present
Create namespace: prow
namespace/prow unchanged
Apply namespace-user role: prow
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: prow
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: prow is present
Create namespace: publishing-bot
namespace/publishing-bot unchanged
Apply namespace-user role: publishing-bot
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: publishing-bot
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: publishing-bot is present
Create namespace: slack-infra
namespace/slack-infra unchanged
Apply namespace-user role: slack-infra
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: slack-infra
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: slack-infra is present
Create namespace: triageparty-release
namespace/triageparty-release unchanged
Apply namespace-user role: triageparty-release
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: triageparty-release
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: triageparty-release is present
Create namespace: wg-reliability-sippy
namespace/wg-reliability-sippy unchanged
Apply namespace-user role: wg-reliability-sippy
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: wg-reliability-sippy
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: wg-reliability-sippy is present
Done
```

**Comment by mm4tt** [comment]
Thanks @spiffxp!

**Pull request merged**
