### PR TITLE
add sig-openstack 1.27.0 images

### PR DESCRIPTION
**Pull request by zetaab**

### CODE REVIEW

**Comment by zetaab** [comment]
@jichenjc can you review and add lgtm if seems legit?

**Comment by jichenjc** [comment]
/lgtm

thanks for the update~

**Comment by mdbooth** [comment]
Pulled all the sha256s from https://storage.googleapis.com/kubernetes-jenkins/logs/cloud-provider-openstack-push-images/1648412422563696640/artifacts/build.log and checked they match this PR

/lgtm

**Comment by mdbooth** [comment]
Incidentally, I also submitted https://github.com/kubernetes/k8s.io/pull/5151 because I think you should have been able to approve this without asking @dims .

**Comment by mdbooth** [comment]
@zetaab You might want to add this to the description?

Fixes: https://github.com/kubernetes/cloud-provider-openstack/issues/2206

**Comment by mdbooth** [comment]
Guessing this will now be auto-approved if @zetaab rebases it.

**Comment by zetaab** [comment]
@mdbooth / @jichenjc need lgtm again because I rebased

**Comment by zetaab** [comment]
@dims can you help lgtm this? :)

**Comment by mdbooth** [comment]
@zetaab Note that the bot auto-approved it when you rebased. This is because you are now in the OWNERS file for that directory. You just need an lgtm next time.

**Pull request merged**
