### PR TITLE
Image promotion for gmsa-webhook v0.4.0

### PR DESCRIPTION
**Pull request by marosset**
Image promotion for gmsa-webhook v0.4.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork marosset --project gmsa-webhook --reviewers "@jayunit100 @jsturtevant @marosset" --tag v0.4.0
```

/hold
cc: @jayunit100 @jsturtevant @marosset

### CODE REVIEW

**Comment by jsturtevant** [comment]
as this is a new process...

Since it is editing the file `k8s.gcr.io/images/k8s-staging-gmsa-webhook/images.yaml` does this mean it will be at the `gcr.io/k8s-staging-gmsa-webhook/k8s-gmsa-webhook:v0.04`  or is it smart enough to put in `gcr.io/k8s-gmsa-webhook/k8s-gmsa-webhook:v0.04`

**Comment by marosset** [comment]
Based on the contents of https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/manifests/k8s-staging-gmsa-webhook/promoter-manifest.yaml I would expect this to show up at `gcr.io/k8s-artifacts-prod/gmsa-webhook` 
I have never done this before though, so I don't know!

**Comment by jsturtevant** [comment]
Thanks! that makes sense to me.
/lgtm

**Pull request merged**
