### PR TITLE
Promote agnhost 2.51

### PR DESCRIPTION
**Pull request by riendeau**
Promote agnhost 2.51 (ref: https://github.com/kubernetes/kubernetes/pull/124382)

```
$ docker pull gcr.io/k8s-staging-e2e-test-images/agnhost:2.51
2.51: Pulling from k8s-staging-e2e-test-images/agnhost
a88dc8b54e91: Already exists 
dbaa86daa50d: Pull complete 
661d3888a6b1: Pull complete 
ac9af3d034fd: Pull complete 
c30a689c8874: Pull complete 
4d1f951b7af5: Pull complete 
8896a382b2a0: Pull complete 
c6d75d169132: Pull complete 
261d0e1e11ea: Pull complete 
78e55f2486b6: Pull complete 
Digest: sha256:488b351e3b19126c378adadd4a2405519dd3ee2533bf172e7c7be0642660ce78
Status: Downloaded newer image for gcr.io/k8s-staging-e2e-test-images/agnhost:2.51
gcr.io/k8s-staging-e2e-test-images/agnhost:2.51
```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test

please check similar prs that shows commands to validate the hash and add them to the description

**Comment by aojea** [comment]
/lgtm
/approve

Thanks

**Comment by riendeau** [comment]
> please check similar prs that shows commands to validate the hash

```
$ docker pull gcr.io/k8s-staging-e2e-test-images/agnhost:2.51
2.51: Pulling from k8s-staging-e2e-test-images/agnhost
a88dc8b54e91: Already exists 
dbaa86daa50d: Pull complete 
661d3888a6b1: Pull complete 
ac9af3d034fd: Pull complete 
c30a689c8874: Pull complete 
4d1f951b7af5: Pull complete 
8896a382b2a0: Pull complete 
c6d75d169132: Pull complete 
261d0e1e11ea: Pull complete 
78e55f2486b6: Pull complete 
Digest: sha256:488b351e3b19126c378adadd4a2405519dd3ee2533bf172e7c7be0642660ce78
Status: Downloaded newer image for gcr.io/k8s-staging-e2e-test-images/agnhost:2.51
gcr.io/k8s-staging-e2e-test-images/agnhost:2.51
```

(Patterned after https://github.com/kubernetes/k8s.io/pull/6765)

> add them to the description

Done!

**Comment by aojea** [comment]
/lgtm
/approve

Thanks

**Pull request merged**
