### PR TITLE
add bentheelder and alphabetize dns/ OWNERS

### PR DESCRIPTION
**Pull request by BenTheElder**
/assign @dims

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @thockin

**Comment by dims** [comment]
/approve

@thockin please lgtm

**Comment by thockin** [comment]
You'll need to be added to the googlegroup, also.

/lgtm
/approve

**Comment by BenTheElder** [comment]
@dims added me to https://groups.google.com/d/forum/k8s-infra-dns-admins 👍

**Comment by thockin** [comment]
With great power...

**Comment by BenTheElder** [comment]
... comes great responsibility.

https://www.youtube.com/watch?v=nhLyPH_KirE :+)

**Pull request merged**
