### PR TITLE
Add infra/aws documentation

### PR DESCRIPTION
**Pull request by BobyMCbobs**
Adds documentation to infra/aws and it's sub-folders.

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
@jaypipes and I shall pair on this tomorrow

**Comment by ameukam** [comment]
/approve 

Leave the `lgtm` to @jaypipes in case they are updates after the pairing session

**Comment by BobyMCbobs** [comment]
Ready for an lgtm and merge!

**Review by jaypipes — APPROVED** [review]
:+1:

**Pull request merged**
