### PR TITLE
Setup image promotion for gateway-api/admission-server

### PR DESCRIPTION
**Pull request by gauravkghildiyal**
Refer https://github.com/kubernetes-sigs/gateway-api/issues/916

(Wait for review from gateway maintainers before removing hold)
/hold

/cc @robscott @shaneutt @youngnick

### CODE REVIEW

**Comment by youngnick** [comment]
LGTM from the Gateway API POV.

Can I do that here? Let's find out.

/lgtm

**Review by shaneutt — APPROVED** [review]

**Comment by robscott** [comment]
Thanks @gauravkghildiyal! 

/lgtm
/assign @thockin

**Pull request merged**
