### PR TITLE
Image promotion for provider-aws v1.32.0

### PR DESCRIPTION
**Pull request by shizuchanw**
Image promotion for provider-aws v1.32.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork shizuchanw --project provider-aws --tag v1.32.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by AndrewSirenko — APPROVED** [review]

**Comment by dims** [comment]
@shizuchanw please remove hold when ready!

**Pull request merged**
