### PR TITLE
Add cri-o staging project

### PR DESCRIPTION
**Pull request by saschagrunert**
Per https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#creating-staging-repos

Fixes https://github.com/kubernetes/k8s.io/issues/1882

cc @mrunalp @haircommander

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
I'll post back here once I've run scripts, I'm trying to land https://github.com/kubernetes/k8s.io/pull/1859 first

**Comment by spiffxp** [comment]
... so actually, cri-o is not actually part of kubernetes anymore (as of https://github.com/kubernetes/community/pull/3668).

It's now a CNCF incubating project: https://cri-o.io/

If it's not part of kubernetes, I don't think k8s-infra is the right place to host its artifacts.

/assign @thockin @dims @ameukam 
for k8s-infra input
/assign @derekwaynecarr @dawnchen
for sig-node input

I think I'd like to revert this.  WDYT new assignees?

**Comment by dims** [comment]
@saschagrunert the best way is to open a servicedesk ticket with CNCF asking for a GCP project for use by CRI-O with a list of names who are owners. then you will have full control over the resources you need for CRI-O

**Comment by thockin** [comment]
A maybe important clarification:  To serve binary artifacts that are not Kubernetes, you need a project (with a name that is acceptable as part of your image pull path) under a different GCP organization with a different billing account.

I don't like being exclusionary, but the funding we have is explicitly for kubernetes, and we have to draw a line somewhere.

**Comment by saschagrunert** [comment]
Sounds good, thank you again for the clarification.

**Pull request merged**
