### PR TITLE
Add k8s.io/kube-openapi to k8s.io golang metadata

### PR DESCRIPTION
**Pull request by mbohlool**
Add entry for godeping k8s.io/kube-openapi.

@thockin @lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by mbohlool** [comment]
@ixdy Is this something you can take care of?

**Comment by ixdy** [comment]
hm, things are in a weird state right now because the changes in #70 have been deployed to prod, but they haven't yet been merged into upstream. @thockin

**Comment by ixdy** [comment]
I deployed this to canary, but the nginx canary pod keeps crashing for unclear reasons.

**Comment by ixdy** [comment]
oh, probably cause I don't have the `/_healthz` from #70.

I've made the canary namespace enough of a mess. I can't deploy this to prod until #70 is merged, I'm afraid.

**Comment by thockin** [comment]
#70 merged - rebase?

**Comment by thockin** [comment]
or rather, this LGTM

**Comment by thockin** [comment]
@ixdy can you push?  I am swamped

**Comment by ixdy** [comment]
canary tests seem happier now. merging.

**Comment by ixdy** [comment]
deployed.

**Pull request merged**
