### PR TITLE
add kubernetes-security@daocloud.io to distributors-announce list

### PR DESCRIPTION
**Pull request by pacoxu**
Fixes https://github.com/kubernetes/committee-security-response/issues/180

I add all information in the issue description.

### CODE REVIEW

**Comment by pacoxu** [comment]
ack

**Comment by ritazh** [comment]
@enj PTAL

**Comment by justaugustus** [comment]
@kubernetes/security-response-committee – Bump for review.

I'm not part of the SRC, so:
/uncc

**Comment by pacoxu** [comment]
> @kubernetes/security-response-committee – Bump for review.

/remove-lifecycle stale

**Comment by pacoxu** [comment]
/assign @enj 
Any action items that I can do for this?

**Comment by pacoxu** [comment]
@enj
any update on this progress? ACK.

**Comment by pacoxu** [comment]
/remove-lifecycle stale 

@enj @kubernetes/security-response-committee
any update on this progress? ACK.

**Comment by enj** [comment]
Sorry, I got stuck trying to get this under the new process which is WIP, but we don't need to block on that for now.

/lgtm
/approve

@pacoxu I will follow-up with you offline in regards to the changes we are making, and how that will impact future membership.

**Comment by pacoxu** [comment]
> Sorry, I got stuck trying to get this under the new process which is WIP, but we don't need to block on that for now.


> @pacoxu I will follow-up with you offline in regards to the changes we are making, and how that will impact future membership.

@enj Understood, and thank you very much for your efforts. 
I truly appreciate it and am looking forward to the new process and the changes ahead. 

At the same time, I am very eager to get involved with the Security Response Committee one day. I'd like to get more involved with any related initiatives, feel free to let me know or help.

**Pull request merged**
