### PR TITLE
Promote NFD-O v0.4.3

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by marquiz — CHANGES_REQUESTED** [review]
The image is built from an incorrect commit, we don't want to promote this one
/hold

**Comment by ArangoGutierrez** [comment]
> The image is built from an incorrect commit, we don't want to promote this one /hold

Fixed
/hold cancel

**Review by marquiz — CHANGES_REQUESTED** [review]
Umm, where did you dig out these hashes? Doesn't look correct to me:
```
$ skopeo inspect docker://gcr.io/k8s-staging-nfd/node-feature-discovery-operator:v0.4.3 | jq .Digest
"sha256:e6ac896f0bf38e362d256f35a8d2ced6086a706321e1e9b7d842e4877c242f67"
```

**Comment by ArangoGutierrez** [comment]
> Umm, where did you dig out these hashes? Doesn't look correct to me:
> 
> ```
> $ skopeo inspect docker://gcr.io/k8s-staging-nfd/node-feature-discovery-operator:v0.4.3 | jq .Digest
> "sha256:e6ac896f0bf38e362d256f35a8d2ced6086a706321e1e9b7d842e4877c242f67"
> ```

I think I didn't waited long enough after fixing the tag

**Review by marquiz — APPROVED** [review]
/lgtm

**Pull request merged**
