### PR TITLE
add readiness probe at /health

### PR DESCRIPTION
**Pull request by jberkus**
Custom readiness probe since / needs to have status 302

Signed-off-by: Josh Berkus <josh@agliodbs.com>

/sig contributor-experience
/committee steering
attn: @ameukam @spiffxp

### CODE REVIEW

**Comment by jberkus** [comment]
@ameukam is this all that's needed, or do we need to add some config under ingress.yaml as well?

**Comment by jberkus** [comment]
addresses comment in #2575

**Comment by ameukam** [comment]
> @ameukam is this all that's needed, or do we need to add some config under ingress.yaml as well?

Nothing to add to the ingress. I suspect you will need to recreate(delete+apply) the ingress object.

**Pull request merged**
