### PR TITLE
releng: Image promotion for v1.17.17 / v1.17.18-rc.0 / v1.18.15 / v1.18.16-rc.0 / v1.19.7 / v1.19.8-rc.0 / v1.20.2 / v1.20.3-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for Kubernetes v1.17.17 / v1.17.18-rc.0 / v1.18.15 / v1.18.16-rc.0 / v1.19.7 / v1.19.8-rc.0 / v1.20.2 / v1.20.3-rc.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Pull request merged**
