### PR TITLE
Image promotion for capi-operator v0.15.1

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Image promotion for capi-operator v0.15.1
This is an automated PR generated from `kpromo`
```
kpromo pr --fork furkatgofurov7 --project capi-operator --reviewers "@Danil-Grigorev @Fedosin @alexander-demicev @damdo @furkatgofurov7" --tag v0.15.1 --image cluster-api-operator
```

/hold
cc: @Danil-Grigorev @Fedosin @alexander-demicev @damdo @furkatgofurov7

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
cc @upodroid is there a way I could do to run the `atlantis/apply` job here?

**Comment by furkatgofurov7** [comment]
atlantis plan

**Comment by furkatgofurov7** [comment]
atlantis unlock

**Comment by upodroid** [comment]
The status check shouldn't block the PR from merging. Apply LGTM and let's see

**Comment by salasberryfin** [comment]
/lgtm

retry

**Pull request merged**
