### PR TITLE
releng: Image promotion for v1.19.14 / v1.19.15-rc.0 / v1.20.10 / v1.20.11-rc.0 / v1.21.4 / v1.21.5-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for Kubernetes v1.19.14 / v1.19.15-rc.0 / v1.20.10 / v1.20.11-rc.0 / v1.21.4 / v1.21.5-rc.0
This is an automated PR generated from `krel The Kubernetes Release Toolbox`

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by puerco** [comment]
/lgtm
Thanks @cpanato

**Comment by cpanato** [comment]
unhold when we got the ack form the google build admins

**Pull request merged**
