### PR TITLE
infra/aws: Tag Policy and Service Control Policy Terraform module

### PR DESCRIPTION
**Pull request by deobieta**
Ref: [#4684](https://github.com/kubernetes/k8s.io/issues/4684)

Enforcing tag policies and utilizing Service Control Policies for tagging at the time of resource creation has the potential to impact our current AWS resource creation practices. It is worth noting that certain AWS services lack the functionality to tag all resources through the AWS console UI during the creation process. For instance, while EC2 allows for the creation of a Security Group during instance creation, the option to tag the group is absent. Consequently, if we decide to enforce Security Groups tags, this may lead to instances failing to launch and an error message indicating insufficient authorization to create the resource. Similarly, ECR repositories do not offer the option to tag repositories during their creation, making ECR console UI ineffective to create repositories. It is essential to exercise caution when enabling tag policy enforcement and service control policies as their efficacy is highly dependent on the agreed upon AWS resource creation methodology.

Tag policy enforcement:  Only has effect on resources that are created with enforced tags. Non-compliant tagging requests on specified resource types are prevented from completing.

Service Control Policy: Enforce tagging at resource creation and deny tag deletion with IAM policies  (with RequestTag conditional).

### Create S3 resources from AWS console

| Resource | Tag policy Enforced | Service Control Policy | Without tags  | With random tag key and value | With tag key and wrong tag value | With correct key and value |
|---|---|---|---|---|---|---|
| bucket   | Yes | No | Succeded | Succeded | ***Succeded with error notice*** | Succeded |

### Delete/Edit Tags S3 resources

| Resource | Tag policy Enforced | Service Control Policy | Add a new random tag key / value  | Remove the random tag key / value | Remove the enforced tag | Edit enforced tag with wrong value
|---|---|---|---|---|---|---|
| bucket   | Yes | No | Succeded | Succeded | ***Succeded*** | Failed |

I couldn't find a way to enforce tags on bucket creation so the SCP is useless in this case.

### Create EC2 resources from AWS console (using "Launch instance" button) 

| Resource | Enforced | Service Control Policy | Without tags  | With random tag key and value | With tag key and wrong tag value | With correct key and value |
|---|---|---|---|---|---|---|
| instance | Yes | Yes | ***Failed*** | Succeded | ***Failed*** | Succeded |
| volume | Yes | Yes | ***Failed*** | Succeded | ***Failed*** | Succeded |

### Create EC2 resources from AWS console (using "Auto Scaling groups")

| Resource | Enforced | Service Control Policy | Without tags  | With random tag key and value | With tag key and wrong tag value | With correct key and value |
|---|---|---|---|---|---|---|
| instance | Yes | Yes | ***Succeded*** | Succeded | ***Failed*** | Succeded |
| volume | Yes | Yes | ***Succeded*** | Succeded | ***Failed*** | Succeded |

### Create EC2 resources from AWS console (using "Spot Requests")

| Resource | Enforced | Service Control Policy | Without tags  | With random tag key and value | With tag key and wrong tag value | With correct key and value |
|---|---|---|---|---|---|---|
| instance | Yes | Yes | ***Failed*** | ***Failed*** | ***Failed*** | ***Failed*** |
| volume | Yes | Yes | ***Failed*** | ***Failed*** | ***Failed*** | ***Failed*** |

### Delete/Edit Tags EC2 resources

| Resource | Enforced | Service Control Policy | Add a new random tag key / value  | Remove the random tag key / value | Remove the enforced tag | Edit enforced tag with wrong value
|---|---|---|---|---|---|---|
| instance | Yes | Yes | Succeded | Succeded | ***Failed*** | ***Failed*** |
| volume | Yes | Yes | Succeded | Succeded | ***Failed*** | ***Failed*** |

### Create VPC resources from AWS console

| Resource | Tag policy Enforced | Service Control Policy | Without tags  | With random tag key and value | With tag key and wrong tag value | With correct key and value |
|---|---|---|---|---|---|---|
| vpc   | Yes | Yes | ***Failed*** | Succeded | ***Failed***  | Succeded |

### Delete/Edit Tags VPC resources

| Resource | Tag policy Enforced | Service Control Policy | Add a new random tag key / value  | Remove the random tag key / value | Remove the enforced tag | Edit enforced tag with wrong value
|---|---|---|---|---|---|---|
| vpc   | Yes | Yes | Succeded | Succeded | ***Failed*** | ***Failed*** |

### Create EKS resources from AWS console

| Resource | Tag policy Enforced | Service Control Policy | Without tags  | With random tag key and value | With tag key and wrong tag value | With correct key and value |
|---|---|---|---|---|---|---|
| cluster   | Yes | Yes | ***Failed*** | Succeded | ***Failed***  | Succeded |

### Delete/Edit Tags EKS resources

| Resource | Tag policy Enforced | Service Control Policy | Add a new random tag key / value  | Remove the random tag key / value | Remove the enforced tag | Edit enforced tag with wrong value
|---|---|---|---|---|---|---|
| vpc   | Yes | Yes | Succeded | Succeded | ***Succeded*** | ***Failed*** |

### CODE REVIEW

**Comment by ameukam** [comment]
/approve
/lgtm

/hold

@deobieta I guess we need to deploy this in order to validate the different policies by creating a few resources on the policy staging account ?

**Comment by deobieta** [comment]
> I guess we need to deploy this in order to validate the different policies by creating a few resources on the policy staging account ?

@ameukam Correct. I have Terraform Code that works for all the enforced resources in this PR. Would you like me to add those examples in this PR or should I create another?

**Comment by ameukam** [comment]
> > I guess we need to deploy this in order to validate the different policies by creating a few resources on the policy staging account ?
> 
> @ameukam Correct. I have Terraform Code that works for all the enforced resources in this PR. Would you like me to add those examples in this PR or should I create another?

Better to do this as a follow-up PR. Will deploy this PR. 

Thank you!!

/hold cancel

**Comment by ameukam** [comment]
@deobieta Deployed.

I guess the policies will be enforced for the new resources created, not the existing one ?

**Comment by deobieta** [comment]
@ameukam  Yes, sorry I should have mentioned that earlier.  Once the policies are attached to the target OU or account, only newly created resources will be affected by the Service Control Policies. However,   if an existing resource uses an enforced tag, the Tag policy will decide if it is compliant or not. We can use AWS Resource Groups console to query those resources.

**Pull request merged**
