### PR TITLE
Image promotion for dns 1.23.1

### PR DESCRIPTION
**Pull request by bzsuni**
Image promotion for dns 1.23.1

cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by aojea** [comment]
dupe of https://github.com/kubernetes/k8s.io/pull/6861 ?

**Comment by bzsuni** [comment]
> dupe of https://github.com/kubernetes/k8s.io/pull/6861 ?

I have made this pr required by the k/k pr
https://github.com/kubernetes/kubernetes/pull/125284

Maybe could you please take a review?

**Comment by bzsuni** [comment]
I noticed that my PR was marked as a duplicate of #6861. However, I submitted my PR 11 hours ago, which was earlier than #6861.

Could we please review my PR as the original submission and consider #6861 as a duplicate?

Thank you for your attention.
@aojea

**Comment by aojea** [comment]
my inbox sorts the in the reverse chronological order 😄 

I don't have objections to which one merges meanwhile are the same

/lgtm

**Comment by bzsuni** [comment]
Thank you very much.

/unhold

**Comment by aojea** [comment]
/assign @bowei 

we need an approval

**Comment by sakshisharma84** [comment]
Guys! thanks a lot for this PR. I was wondering if this can be merged any time sooner. We need the fix for the critical CVE and just waiting for the images to be promoted.

**Comment by bzsuni** [comment]
I apologize and am very grateful for your kindness. Thank you, everyone

**Pull request merged**
