### PR TITLE
Always make GCS buckets alongside GCR repos

### PR DESCRIPTION
**Pull request by thockin**
For consistency and so the various fake-prod test projects can have
buckets.

@dims, this overlaps your #294

@justaugustus this should make your life easier, yes?

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

/hold

(hold for actually running the script)

**Comment by thockin** [comment]
Will run now

**Comment by thockin** [comment]
```
thockin@freakshow2 k8s.io master /infra/gcp$ ./ensure-prod-storage.sh
Ensuring project exists: k8s-artifacts-prod
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-artifacts-prod/billingInfo
projectId: k8s-artifacts-prod
Enabling the container registry API: k8s-artifacts-prod
Enabling the container analysis API: k8s-artifacts-prod
Ensuring the GCR exists and is readable: k8s-artifacts-prod
region us
No changes made to gs://us.artifacts.k8s-artifacts-prod.appspot.com/
Enabling Bucket Policy Only for gs://us.artifacts.k8s-artifacts-prod.appspot.com...
region eu
No changes made to gs://eu.artifacts.k8s-artifacts-prod.appspot.com/
Enabling Bucket Policy Only for gs://eu.artifacts.k8s-artifacts-prod.appspot.com...
region asia
No changes made to gs://asia.artifacts.k8s-artifacts-prod.appspot.com/
Enabling Bucket Policy Only for gs://asia.artifacts.k8s-artifacts-prod.appspot.com...
Empowering GCR admins: k8s-artifacts-prod
region us
Updated IAM policy for project [k8s-artifacts-prod].
bindings:
- members:
  - serviceAccount:service-388270116193@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-388270116193@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-388270116193@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:388270116193-compute@developer.gserviceaccount.com
  - serviceAccount:388270116193@cloudservices.gserviceaccount.com
  - serviceAccount:service-388270116193@containerregistry.iam.gserviceaccount.com
  - user:justinsb@google.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWv6FgbI=
version: 1
No changes made to gs://us.artifacts.k8s-artifacts-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-artifacts-prod.appspot.com/
region eu
Updated IAM policy for project [k8s-artifacts-prod].
bindings:
- members:
  - serviceAccount:service-388270116193@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-388270116193@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-388270116193@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:388270116193-compute@developer.gserviceaccount.com
  - serviceAccount:388270116193@cloudservices.gserviceaccount.com
  - serviceAccount:service-388270116193@containerregistry.iam.gserviceaccount.com
  - user:justinsb@google.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWv6_q6I=
version: 1
No changes made to gs://eu.artifacts.k8s-artifacts-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-artifacts-prod.appspot.com/
region asia
Updated IAM policy for project [k8s-artifacts-prod].
bindings:
- members:
  - serviceAccount:service-388270116193@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-388270116193@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-388270116193@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:388270116193-compute@developer.gserviceaccount.com
  - serviceAccount:388270116193@cloudservices.gserviceaccount.com
  - serviceAccount:service-388270116193@containerregistry.iam.gserviceaccount.com
  - user:justinsb@google.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWv8B1AY=
version: 1
No changes made to gs://asia.artifacts.k8s-artifacts-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-artifacts-prod.appspot.com/
Empowering image promoter: k8s-artifacts-prod
region us
No changes made to gs://us.artifacts.k8s-artifacts-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-artifacts-prod.appspot.com/
region eu
No changes made to gs://eu.artifacts.k8s-artifacts-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-artifacts-prod.appspot.com/
region asia
No changes made to gs://asia.artifacts.k8s-artifacts-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-artifacts-prod.appspot.com/
Enabling the GCS API: k8s-artifacts-prod
Ensuring the GCS bucket exists and is readable: k8s-artifacts-prod
No changes made to gs://k8s-artifacts-prod/
Enabling Bucket Policy Only for gs://k8s-artifacts-prod...
Empowering GCS admins: k8s-artifacts-prod
Updated IAM policy for project [k8s-artifacts-prod].
bindings:
- members:
  - serviceAccount:service-388270116193@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-388270116193@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-388270116193@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:388270116193-compute@developer.gserviceaccount.com
  - serviceAccount:388270116193@cloudservices.gserviceaccount.com
  - serviceAccount:service-388270116193@containerregistry.iam.gserviceaccount.com
  - user:justinsb@google.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWwAji0s=
version: 1
No changes made to gs://k8s-artifacts-prod/
No changes made to gs://k8s-artifacts-prod/
Ensuring project exists: k8s-artifacts-graveyard
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-artifacts-graveyard/billingInfo
projectId: k8s-artifacts-graveyard
Enabling the container registry API: k8s-artifacts-graveyard
Enabling the container analysis API: k8s-artifacts-graveyard
Ensuring the GCR exists and is readable: k8s-artifacts-graveyard
region us
No changes made to gs://us.artifacts.k8s-artifacts-graveyard.appspot.com/
Enabling Bucket Policy Only for gs://us.artifacts.k8s-artifacts-graveyard.appspot.com...
region eu
No changes made to gs://eu.artifacts.k8s-artifacts-graveyard.appspot.com/
Enabling Bucket Policy Only for gs://eu.artifacts.k8s-artifacts-graveyard.appspot.com...
region asia
No changes made to gs://asia.artifacts.k8s-artifacts-graveyard.appspot.com/
Enabling Bucket Policy Only for gs://asia.artifacts.k8s-artifacts-graveyard.appspot.com...
Empowering GCR admins: k8s-artifacts-graveyard
region us
Updated IAM policy for project [k8s-artifacts-graveyard].
bindings:
- members:
  - serviceAccount:service-969606857874@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-969606857874@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-969606857874@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:969606857874-compute@developer.gserviceaccount.com
  - serviceAccount:969606857874@cloudservices.gserviceaccount.com
  - serviceAccount:service-969606857874@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWwFdWmk=
version: 1
No changes made to gs://us.artifacts.k8s-artifacts-graveyard.appspot.com/
No changes made to gs://us.artifacts.k8s-artifacts-graveyard.appspot.com/
region eu
Updated IAM policy for project [k8s-artifacts-graveyard].
bindings:
- members:
  - serviceAccount:service-969606857874@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-969606857874@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-969606857874@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:969606857874-compute@developer.gserviceaccount.com
  - serviceAccount:969606857874@cloudservices.gserviceaccount.com
  - serviceAccount:service-969606857874@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWwGXPk0=
version: 1
No changes made to gs://eu.artifacts.k8s-artifacts-graveyard.appspot.com/
No changes made to gs://eu.artifacts.k8s-artifacts-graveyard.appspot.com/
region asia
Updated IAM policy for project [k8s-artifacts-graveyard].
bindings:
- members:
  - serviceAccount:service-969606857874@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-969606857874@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-969606857874@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:969606857874-compute@developer.gserviceaccount.com
  - serviceAccount:969606857874@cloudservices.gserviceaccount.com
  - serviceAccount:service-969606857874@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWwHZChg=
version: 1
No changes made to gs://asia.artifacts.k8s-artifacts-graveyard.appspot.com/
No changes made to gs://asia.artifacts.k8s-artifacts-graveyard.appspot.com/
Empowering image promoter: k8s-artifacts-graveyard
region us
No changes made to gs://us.artifacts.k8s-artifacts-graveyard.appspot.com/
No changes made to gs://us.artifacts.k8s-artifacts-graveyard.appspot.com/
region eu
No changes made to gs://eu.artifacts.k8s-artifacts-graveyard.appspot.com/
No changes made to gs://eu.artifacts.k8s-artifacts-graveyard.appspot.com/
region asia
No changes made to gs://asia.artifacts.k8s-artifacts-graveyard.appspot.com/
No changes made to gs://asia.artifacts.k8s-artifacts-graveyard.appspot.com/
Enabling the GCS API: k8s-artifacts-graveyard
Ensuring the GCS bucket exists and is readable: k8s-artifacts-graveyard
Creating gs://k8s-artifacts-graveyard/...
Enabling Bucket Policy Only for gs://k8s-artifacts-graveyard...
Empowering GCS admins: k8s-artifacts-graveyard
Updated IAM policy for project [k8s-artifacts-graveyard].
bindings:
- members:
  - serviceAccount:service-969606857874@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-969606857874@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-969606857874@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:969606857874-compute@developer.gserviceaccount.com
  - serviceAccount:969606857874@cloudservices.gserviceaccount.com
  - serviceAccount:service-969606857874@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNWwMg8Os=
version: 1
Ensuring project exists: k8s-cip-test-prod
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-cip-test-prod/billingInfo
projectId: k8s-cip-test-prod
Enabling the container registry API: k8s-cip-test-prod
Enabling the container analysis API: k8s-cip-test-prod
Ensuring the GCR exists and is readable: k8s-cip-test-prod
region us
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
Enabling Bucket Policy Only for gs://us.artifacts.k8s-cip-test-prod.appspot.com...
region eu
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
Enabling Bucket Policy Only for gs://eu.artifacts.k8s-cip-test-prod.appspot.com...
region asia
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
Enabling Bucket Policy Only for gs://asia.artifacts.k8s-cip-test-prod.appspot.com...
Empowering GCR admins: k8s-cip-test-prod
region us
Updated IAM policy for project [k8s-cip-test-prod].
bindings:
- members:
  - serviceAccount:service-693665670941@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-693665670941@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-693665670941@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:693665670941-compute@developer.gserviceaccount.com
  - serviceAccount:693665670941@cloudservices.gserviceaccount.com
  - serviceAccount:service-693665670941@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-cip-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwRvZAs=
version: 1
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
region eu
Updated IAM policy for project [k8s-cip-test-prod].
bindings:
- members:
  - serviceAccount:service-693665670941@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-693665670941@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-693665670941@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:693665670941-compute@developer.gserviceaccount.com
  - serviceAccount:693665670941@cloudservices.gserviceaccount.com
  - serviceAccount:service-693665670941@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-cip-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwSsJRw=
version: 1
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
region asia
Updated IAM policy for project [k8s-cip-test-prod].
bindings:
- members:
  - serviceAccount:service-693665670941@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-693665670941@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-693665670941@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:693665670941-compute@developer.gserviceaccount.com
  - serviceAccount:693665670941@cloudservices.gserviceaccount.com
  - serviceAccount:service-693665670941@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-cip-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwTvVjA=
version: 1
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
Empowering image promoter: k8s-cip-test-prod
region us
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
region eu
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
region asia
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
Enabling the GCS API: k8s-cip-test-prod
Ensuring the GCS bucket exists and is readable: k8s-cip-test-prod
Creating gs://k8s-cip-test-prod/...
Enabling Bucket Policy Only for gs://k8s-cip-test-prod...
Empowering GCS admins: k8s-cip-test-prod
Updated IAM policy for project [k8s-cip-test-prod].
bindings:
- members:
  - serviceAccount:service-693665670941@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-693665670941@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-693665670941@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:693665670941-compute@developer.gserviceaccount.com
  - serviceAccount:693665670941@cloudservices.gserviceaccount.com
  - serviceAccount:service-693665670941@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-cip-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwY93dI=
version: 1
Ensuring project exists: k8s-release-test-prod
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-release-test-prod/billingInfo
projectId: k8s-release-test-prod
Enabling the container registry API: k8s-release-test-prod
Enabling the container analysis API: k8s-release-test-prod
Ensuring the GCR exists and is readable: k8s-release-test-prod
region us
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
Enabling Bucket Policy Only for gs://us.artifacts.k8s-release-test-prod.appspot.com...
region eu
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
Enabling Bucket Policy Only for gs://eu.artifacts.k8s-release-test-prod.appspot.com...
region asia
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
Enabling Bucket Policy Only for gs://asia.artifacts.k8s-release-test-prod.appspot.com...
Empowering GCR admins: k8s-release-test-prod
region us
Updated IAM policy for project [k8s-release-test-prod].
bindings:
- members:
  - serviceAccount:service-925892675446@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-925892675446@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:925892675446-compute@developer.gserviceaccount.com
  - serviceAccount:925892675446@cloudservices.gserviceaccount.com
  - serviceAccount:service-925892675446@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-release-test@kubernetes.io
  role: roles/viewer
etag: BwWNWweLsgw=
version: 1
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
region eu
Updated IAM policy for project [k8s-release-test-prod].
bindings:
- members:
  - serviceAccount:service-925892675446@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-925892675446@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:925892675446-compute@developer.gserviceaccount.com
  - serviceAccount:925892675446@cloudservices.gserviceaccount.com
  - serviceAccount:service-925892675446@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-release-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwfEu2U=
version: 1
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
region asia
Updated IAM policy for project [k8s-release-test-prod].
bindings:
- members:
  - serviceAccount:service-925892675446@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-925892675446@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:925892675446-compute@developer.gserviceaccount.com
  - serviceAccount:925892675446@cloudservices.gserviceaccount.com
  - serviceAccount:service-925892675446@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-release-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwgIrmE=
version: 1
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
Empowering image promoter: k8s-release-test-prod
region us
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
region eu
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
region asia
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
Enabling the GCS API: k8s-release-test-prod
Operation "operations/acf.579b0e57-c88d-4192-8001-d182aaf7fb9c" finished successfully.
Ensuring the GCS bucket exists and is readable: k8s-release-test-prod
Creating gs://k8s-release-test-prod/...
Enabling Bucket Policy Only for gs://k8s-release-test-prod...
Empowering GCS admins: k8s-release-test-prod
Updated IAM policy for project [k8s-release-test-prod].
bindings:
- members:
  - serviceAccount:service-925892675446@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-925892675446@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:925892675446-compute@developer.gserviceaccount.com
  - serviceAccount:925892675446@cloudservices.gserviceaccount.com
  - serviceAccount:service-925892675446@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-release-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwmN4d4=
version: 1
Configuring the web policy on the bucket
Setting website configuration on gs://k8s-artifacts-prod/...
Copying static content into bucket

WARNING: gsutil rsync uses hashes when modification time is not available at
both the source and destination. Your crcmod installation isn't using the
module's C extension, so checksumming will run very slowly. If this is your
first rsync since updating gsutil, this rsync can take significantly longer than
usual. For help installing the extension, please see "gsutil help crcmod".

Building synchronization state...
Starting synchronization...
Empowering k8s-infra-staging-cip-test@kubernetes.io as project viewer in k8s-cip-test-prod
Updated IAM policy for project [k8s-cip-test-prod].
bindings:
- members:
  - serviceAccount:service-693665670941@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-693665670941@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-693665670941@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:693665670941-compute@developer.gserviceaccount.com
  - serviceAccount:693665670941@cloudservices.gserviceaccount.com
  - serviceAccount:service-693665670941@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-cip-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwoB7aA=
version: 1
Empowering k8s-infra-staging-cip-test@kubernetes.io for GCR in k8s-cip-test-prod
region us
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
region eu
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
region asia
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
Empowering k8s-infra-staging-release-test@kubernetes.io as project viewer in k8s-release-test-prod
Updated IAM policy for project [k8s-release-test-prod].
bindings:
- members:
  - serviceAccount:service-925892675446@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-925892675446@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:925892675446-compute@developer.gserviceaccount.com
  - serviceAccount:925892675446@cloudservices.gserviceaccount.com
  - serviceAccount:service-925892675446@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-staging-release-test@kubernetes.io
  role: roles/viewer
etag: BwWNWwqdjQQ=
version: 1
Empowering k8s-infra-staging-release-test@kubernetes.io for GCR in k8s-release-test-prod
region us
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-release-test-prod.appspot.com/
region eu
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-release-test-prod.appspot.com/
region asia
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-release-test-prod.appspot.com/
Done
```

**Comment by justaugustus** [comment]
@thockin -- it does indeed. Thanks again for helping me out! :)

**Pull request merged**
