### PR TITLE
tf/k8s-infra-prow-build: add ExternalSecrets

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/2220
- Followup to: https://github.com/kubernetes/k8s.io/pull/2845

Turns out the k8s secret has two fields: ssh-private and ssh-public, so we'll instead make a GSM secret per field

I populated the GSM secrets, and have added ExternalSecret CRDs to sync the values back to the Kubernetes secrets

### CODE REVIEW

**Comment by spiffxp** [comment]
I have already run `terraform apply`

**Review by chaodaiG — APPROVED** [review]

**Comment by spiffxp** [comment]
This appears to have caused https://github.com/kubernetes/kubernetes/issues/105381

**Comment by spiffxp** [comment]
```
I0930 16:46:54.902] Failure Finished Test Suite on Host 
I0930 16:46:54.903] unable to create gce instance with running docker daemon for image cos-81-12871-1317-1.  instance tmp-node-e2e-abe2f419-cos-81-12871-1317-1 not running docker/containerd/crio daemon - Command failed: load pubkey "/workspace/.ssh/google_compute_engine": invalid format
I0930 16:46:54.903] Load key "/workspace/.ssh/google_compute_engine": invalid format
I0930 16:46:54.903] prow@34.83.126.141: Permission denied (publickey).
I0930 16:46:54.903] 
```

**Comment by spiffxp** [comment]
Found a test pod running a node-e2e job
```
spiffxp@spiffxp-macbookpro:~$ k --context=prow-build -n test-pods exec 436ec7fb-220f-11ec-9d33-e61a535a6f12 -- /bin/bash -c "cat /workspace/.ssh/google_compute_engine" | tail -n1
-----END OPENSSH PRIVATE KEY-----spiffxp@spiffxp-macbookpro:~$
```

I think that should have an extra newline at the end of it

Updated secret value for prow-build-ssh-key-secret-ssh-private

**Comment by spiffxp** [comment]
There's now a newline at the end of the the private key
```
$ k --context=prow-build -n test-pods get secret ssh-key-secret -o=json | jq -r '.data["ssh-private"]' | base64 -d | tail -n1
-----END OPENSSH PRIVATE KEY-----
$
```

**Comment by spiffxp** [comment]
I'll post future updates over in https://github.com/kubernetes/kubernetes/issues/105381

**Pull request merged**
