### PR TITLE
Image promotion for sp-operator v0.8.4

### PR DESCRIPTION
**Pull request by saschagrunert**
Image promotion for sp-operator v0.8.4
This is an automated PR generated from `kpromo`
```
kpromo pr --fork saschagrunert --project sp-operator --tag v0.8.4
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by saschagrunert** [comment]
/unhold

PTAL @ccojocar @pjbgf @JAORMX @jhrozek

**Comment by saschagrunert** [comment]
Part of https://github.com/kubernetes-sigs/security-profiles-operator/issues/2256

**Review by cpanato — COMMENTED** [review]
/lgtm

**Review by JAORMX — APPROVED** [review]

**Pull request merged**
