### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by haripriya9647**
#6242

### CODE REVIEW

**Comment by haripriya9647** [comment]
@MadhavJivrajani Do you want me to add links for all the committees or just for contributor experience

**Review by MadhavJivrajani — CHANGES_REQUESTED** [review]
Thanks for working on this @haripriya9647!

I think there is some confusion as to what needs to be done. Let me try and clarify:
1. We need the redirect to be generic. When I said `sig-contributor-experience`, I only meant it as an example of what the URL that someone would type might look like.
2. You could hard code all groups as redirects, but new groups are added and removed quite frequently in the community, so the redirect list would then be quite stale.
3. You also have not yet added in what needs to be added: the actual redirect in the config file I had linked in the original issue, see the configurations listed here:

https://github.com/kubernetes/k8s.io/blob/5918433899a23de861ef3ff2ce95a5d8d97438d7/apps/k8s-io/configmap-nginx.yaml#L257-L284

4. You will need to add in 2 more entries under the `go.k8s.io` configuration:
```
rewrite ^/contact$          https://github.com/kubernetes/community/tree/master/communication/ redirect;
rewrite ^/contact/([^/]*)/?$ https://github.com/kubernetes/community/tree/master/$1#contact redirect;
```
Note that the above redirects are similar to the redirect configuation for `go.k8s.io/owners`, subsequently, the test cases you write also should be similar to the `/owners` redirect.

5. Update the README accordingly as well.

**Comment by MadhavJivrajani** [comment]
Please also edit the PR description and title to convey what you're working on :)

**Comment by haripriya9647** [comment]
Hello, @MadhavJivrajani. My apologies I had some issues with my laptop so I couldn't add my commits. 
I will finish it by today.

**Comment by MadhavJivrajani** [comment]
Thanks @haripriya9647!

**Comment by MadhavJivrajani** [comment]
/close 
Ref: https://github.com/kubernetes/k8s.io/issues/6242#issuecomment-1943934006

**Pull request closed without merging**
