### PR TITLE
releng: Image promotion for kubernetes v1.26.0-alpha.2

### PR DESCRIPTION
**Pull request by cici37**
Image promotion for kubernetes v1.26.0-alpha.2
This is an automated PR generated from `kpromo`
```
kpromo pr --fork cici37 --interactive --tag v1.26.0-alpha.2
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by puerco — APPROVED** [review]
Thanks Cici!
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

thanks!

**Pull request merged**
