### PR TITLE
Add k8s.io/apiextensions-apiserver to k8s.io golang metadata

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by caesarxuchao** [comment]
lgtm

I don't have merge right. thockin, lavalamp are OOO. @deads2k do you have merge right?

**Comment by sttts** [comment]
This also needs deployment or do we have CI here?

**Comment by deads2k** [comment]
> I don't have merge right. thockin, lavalamp are OOO. @deads2k do you have merge right?

I do not.

**Comment by caesarxuchao** [comment]
I think it needs deployment.

**Comment by deads2k** [comment]
@lavalamp bump

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
We still need a push. Someone besides @thockin knows how to push thees, maybe @apelisse or @foxish?

**Comment by foxish** [comment]
Unfamiliar to me. @kubernetes/test-infra-maintainers might know.
/cc @spxtr

**Comment by dchen1107** [comment]
@ixdy already pushed this last week. Thanks!

**Pull request merged**
