### PR TITLE
Deploy AR mirrors to remaining US AR regions

### PR DESCRIPTION
**Pull request by upodroid**
The image promoter has been optimised and we should be good with adding additional registries.

I'm also going to do the same for the S3 buckets.

/cc @ameukam @BenTheElder

### CODE REVIEW

**Comment by ameukam** [comment]
I don't think we should add more AR/Cloud Run regions. AR costed us more than $10k for Oct and in some regions we barely have 5 RQS.

**Comment by ameukam** [comment]
I think we can convert the entire US multi-region. @upodroid can you only add `us-west3` and `us-west4`?

**Comment by upodroid** [comment]
done

/label tide/merge-method-squash

**Comment by ameukam** [comment]
This is done.

**Pull request merged**
