### PR TITLE
infra/gcp/roles: refresh and add run.viewer to audit.viewer

### PR DESCRIPTION
**Pull request by spiffxp**
There are three commits in here, it'd be less noisy if you reviewed by commit. But basically
- first commit pulls in whatever predefined role changes happened in Google Cloud since these custom roles were last refreshed
- second commit adds `roles/run.viewer` to the custom `audit.viewer` role
- third commit drops embedding the role spec into the generated role (mostly so `yamllint` will stop complaining about trailing spaces)

The second commit is the only intentional role change, the rest is noise.

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
I'd like to confirm whether this gives the desired level of access to cloud run assets

**Comment by spiffxp** [comment]
Agh! Foiled by the yamllint check I just added.  Redoing the script to generate valid yaml...

Deployed via `./infra/gcp/ensure-organization.sh`
```
 @@ -1030,10 +1037,14 @@ includedPermissions:
     - retail.catalogs.list
     - retail.operations.list
     - retail.products.list
  +  - run.configurations.get
     - run.configurations.list
     - run.locations.list
  +  - run.revisions.get
     - run.revisions.list
  +  - run.routes.get
     - run.routes.list
  +  - run.services.get
     - run.services.getIamPolicy
     - run.services.list
     - runtimeconfig.configs.getIamPolicy
```

**Comment by spiffxp** [comment]
/hold cancel
At least spot checking the cip-auditor cloud run deployment, I'm content saying the resources an auditor can see for Cloud Run are reasonable

**Comment by spiffxp** [comment]
/cc @ameukam @dims @listx 
(listx since I did this to hopefully unblock @tylerferrara)

**Comment by rikatz** [comment]
/lgtm
Thanks

**Pull request merged**
