### PR TITLE
ksm: promote v2.2.4 images

### PR DESCRIPTION
**Pull request by dgrisonnet**
Promoting v2.2.4 images of kube-state-metrics based on https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics?project=k8s-staging-kube-state-metrics.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
I also took the opportunity to reorder the image versions since it was a bit messy.

/cc @mrueg @fpetkovski

**Comment by mrueg** [comment]
/lgtm

@dgrisonnet not sure if cip-mm will change the order back again (I believe it's alphabetically by the hash instead of tag)

**Comment by dgrisonnet** [comment]
I don't think so, it doesn't seem to be reordered for other projects:
- https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-prometheus-adapter/images.yaml
- https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-metrics-server/images.yaml

**Pull request merged**
