### PR TITLE
audit: strip etags from json output, fix bq access dump

### PR DESCRIPTION
**Pull request by spiffxp**
Fixes: https://github.com/kubernetes/k8s.io/issues/2029
Fixes: https://github.com/kubernetes/k8s.io/issues/2062

See commits for details

It's tough to test these out locally without hacking the script. I opted not to refactor into functions to allow for faster/easier testing as part of this PR, will save that for followup

### CODE REVIEW

**Comment by ameukam** [comment]
/lgtm
/hold
Remove hold when ready.

**Comment by spiffxp** [comment]
/hold
I'm manually hacking the script a bit and am going to update the audit results in a separate commit

**Comment by spiffxp** [comment]
Waiting for https://github.com/kubernetes/k8s.io/pull/2074 to merge so I can rebase on top of it and maybe update audit results before the next audit PR

**Comment by spiffxp** [comment]
/hold cancel
The last commit contains results from running with the following patch applied, which limits to a hardcoded list of projects
```diff
diff --git a/audit/audit-gcp.sh b/audit/audit-gcp.sh
index 700077cb..d14f94e7 100755
--- a/audit/audit-gcp.sh
+++ b/audit/audit-gcp.sh
@@ -25,6 +25,7 @@ function format_gcloud_json() {
   jq 'delpaths([path(..|.etag?|select(.))])'
 }

+if false; then
 echo "# Removing existing audit files"
 rm -rf org_kubernetes.io
 rm -rf projects
@@ -47,16 +48,20 @@ gcloud \
     --format=json | format_gcloud_json \
     > "org_kubernetes.io/iam.json"

+fi
 echo "## Iterating over Projects"
 gcloud \
     projects list \
     --filter="parent.id=${CNCF_GCP_ORG}" \
     --format="value(name, projectNumber)" \
 | sort \
+| grep -E '^(k8s-artifacts-prod|k8s-cip-test-prod|k8s-conform|k8s-gsuite|k8s-infra-e2e-scale-project|k8s-infra-ii-sandbox|k8s-infra-prow-build|k8s-infra-prow-build-trusted|k8s-infra-public-pii|kubernetes-public)' \
 | while read -r PROJECT NUM; do
     export CLOUDSDK_CORE_PROJECT="${PROJECT}"

     echo "### Auditing Project ${PROJECT}"
+
+    rm -rf "projects/${PROJECT}"
     mkdir -p "projects/${PROJECT}"

     gcloud \
```

The list of projects was everything that had files under `bigquery` or `secrets`
```
find audit | grep -E '/(secrets|bigquery)/' | cut -d/ -f3 | sort | uniq | xargs printf "%s|"; echo
```

**Comment by spiffxp** [comment]
/cc @ameukam @dims 
Would like to land this before next run of the audit job if possible

**Pull request merged**
