### PR TITLE
Add NFD DNS for netlify rendering

### PR DESCRIPTION
**Pull request by iranzo**
Adds entry for netlify project site for NFD

### CODE REVIEW

**Comment by iranzo** [comment]
Seems that other files that I haven't touched had trailing spaces, etc and made the checks to fail on something that was not touched

**Comment by iranzo** [comment]
Thanks @dims for the review!

**Comment by iranzo** [comment]
@dims is it fine now that the CI reports as passing? 

Thanks!

**Comment by dims** [comment]
/approve
/lgtm

thanks!

**Pull request merged**
