### PR TITLE
releng: Image promotion for v1.19.1 and v1.19.2-rc.0

### PR DESCRIPTION
**Pull request by cpanato**
Logs from the cloudbuild:
- [Stage](https://console.cloud.google.com/cloud-build/builds/6fe9905e-e9ab-4a8e-9b79-fd1aa713eca5?project=kubernetes-release-test)

Command to generate the config file used:
 ```shell
cip-mm --base_dir=$GOPATH/src/github.com/kubernetes/k8s.io/k8s.gcr.io --staging_repo=gcr.io/k8s-staging-kubernetes --filter_tag=v1.19.1

cip-mm --base_dir=$GOPATH/src/github.com/kubernetes/k8s.io/k8s.gcr.io --staging_repo=gcr.io/k8s-staging-kubernetes --filter_tag=v1.19.2-rc.0
```

removed the part of the mock images.

@kubernetes/release-engineering
/assign @justaugustus @saschagrunert @hasheddan

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/approve
/hold

**Comment by saschagrunert** [comment]
@puerco with respect to https://github.com/kubernetes/release/issues/1384, we could also use this yaml for providing the link to the target images in the changelog. Should be easier than parsing the staged image tarballs. :shrug:

**Comment by cpanato** [comment]
/hold cancel

Google build Engineer is available to cut the packages.

**Pull request merged**
