### PR TITLE
add docs.prow.k8s.io

### PR DESCRIPTION
**Pull request by listx**

### CODE REVIEW

**Comment by listx** [comment]
I followed https://github.com/kubernetes/k8s.io/pull/185/files as a template.

Additional context: https://github.com/kubernetes/k8s.io/issues/3315#issuecomment-1023889417

**Comment by listx** [comment]
More context: https://github.com/kubernetes/test-infra/issues/24821

**Comment by ameukam** [comment]
/lgtm
cc @dims @cblecker

**Pull request merged**
