### PR TITLE
Formatting Terraform code. No code changes.(Minor)

### PR DESCRIPTION
**Pull request by vishnuswmech**

### CODE REVIEW

**Comment by vishnuswmech** [comment]
If possible, we can have a Terraform Format checks on PR stage itself. It is a standard practice.

**Comment by vishnuswmech** [comment]
@BenTheElder Thanks for pointing out.

While we haven't faced issues before, consistent formatting enhances better readability, which makes the code easier to review and understand.

And it will be more helpful for the new contributors to understand the code quickly.

Kindly share your thoughts on this.

**Comment by ameukam** [comment]
better readability is the benefit of this PR and it doesn't affect the state of the resources. IMHO, we should start with some non-blocking HCL checks.

/lgtm
/approve

**Pull request merged**
