### PR TITLE
Image promotion for cluster-api v1.2.11

### PR DESCRIPTION
**Pull request by ykakarap**
Image promotion for cluster-api v1.2.11
This is an automated PR generated from `kpromo`
```
kpromo pr --fork ykakarap --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri" --tag v1.2.11 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
approve

**Pull request merged**
