### PR TITLE
infra: Enable Google Artifact Registry for RelEng staging projects

### PR DESCRIPTION
**Pull request by justaugustus**
Part of https://github.com/kubernetes/k8s.io/issues/1343.
Slack convo: https://kubernetes.slack.com/archives/CCK68P2Q2/p1639432351160600

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @ameukam @dims @thockin 
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by ameukam** [comment]
/approve
/hold

For others to comment.

**Comment by puerco** [comment]
image

**Comment by justaugustus** [comment]
Continued in https://github.com/kubernetes/k8s.io/pull/3191.

**Pull request merged**
