### PR TITLE
Promote VPA 0.12.0 images

### PR DESCRIPTION
**Pull request by jbartosik**
E2e tests with those images passed

I generated entries with a script (had to copy&paste output because
script messess up formatting):

```python
import yaml
import subprocess

original = yaml.safe_load(open("images/k8s-staging-autoscaling/images.yaml"))

def get_image_sha(image):
  return subprocess.run(['gcloud', 'container', 'images', 'describe', image, '-q', '--format=value(image_summary.digest)', '--verbosity=none'], capture_output=True).stdout[:-1].decode("utf-8")

tag = '0.12.0'
repo = 'gcr.io/k8s-staging-autoscaling'
images = [x['name'] for x in original if x['name'].startswith('vpa')]

for image in images:
  image_path = '{}/{}:{}'.format(repo, image, tag)
  sha = get_image_sha(image_path)
  print(image)
  print('"{}": ["{}"]'.format(sha, tag))
  for image_entry in original:
    if image_entry['name'] != image:
      continue
    image_entry['dmap'][sha] = [tag]
print(original)
```

### CODE REVIEW

**Comment by jbartosik** [comment]
Also CI tests are passing: https://k8s-testgrid.appspot.com/sig-autoscaling-vpa#Summary  (summary still shows some flaky/ failing test suites but when you click to individual tabs you you'll see that all tests are passing now)

**Comment by jbartosik** [comment]
@mwielgus @krzysied please take a look

**Comment by jbartosik** [comment]
/hold cancel

I built new images from current branch (after merging https://github.com/kubernetes/autoscaler/pull/5168).

I tested new images, full-vpa test suite passed in 1.25 cluster (images and tests from https://github.com/kubernetes/autoscaler/tree/vpa-release-0.12 ([commit 612005f796ac8e810d6cb41e5302cb6055af06d5](https://github.com/kubernetes/autoscaler/commit/612005f796ac8e810d6cb41e5302cb6055af06d5)))

**Comment by jbartosik** [comment]
@mwielgus please take a look

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
