### PR TITLE
Empty out the registry.k8s.io folder and update the README.md

### PR DESCRIPTION
**Pull request by upodroid**

### CODE REVIEW

**Comment by upodroid** [comment]
/cc @ameukam @BenTheElder 

My plan is to move the k8s.gcr.io contents directly in to this folder in March and retain the modified README.md that I proposed in this PR.

We need to merge https://github.com/kubernetes/test-infra/pull/28668 this first and verify that it works.
/hold

**Comment by ameukam** [comment]
Please open a PR with all this content to `github.com/kubernetes/registry.k8s.io/tree/main/experiment` before we close this.

**Comment by sftim** [comment]
This PR addss a good README - you might like to change the PR title to reflect that @upodroid

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by upodroid** [comment]
Cancelling the hold as the script is no longer being called.

Context https://github.com/kubernetes/test-infra/pull/28932

/hold cancel

**Pull request merged**
