### PR TITLE
remove stale k8s.gcr.io docs and clarify directory state

### PR DESCRIPTION
**Pull request by BenTheElder**
These are misleading, let's be clearer that this directory is inactive.

Also, drop all the OWNERS files for images in this directory, because they're a recurring source of PRs being blocked / confusion during attempts to update project owners, and there's no need for these anymore with the directory frozen.

### CODE REVIEW

**Comment by ameukam** [comment]
The time has come.
/lgtm

**Comment by ameukam** [comment]
cc @kubernetes/release-engineering

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
