### PR TITLE
Promote EBS CSI Driver v1.13.0

### PR DESCRIPTION
**Pull request by torredil**
```
$ crane manifest gcr.io/k8s-staging-provider-aws/aws-ebs-csi-driver:v20221104-v1.13.0         
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1162,
         "digest": "sha256:8e9ff73ef6f365efa689f6c089a3c8cb21c91489f44eabbe3d4a64c98d998ee2",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1162,
         "digest": "sha256:1bdcc9e9118c42a83b2358b2b03541720151b3354ea46d4fd754c7a34d11f5fc",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 956,
         "digest": "sha256:5fdd4963c13834527518b1500f25002a494a7f896c809767ec6762f36a9bfc77",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.3532"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 957,
         "digest": "sha256:a3bfbf107546e7d676d551eeec01a4be5fb532636e401288f404c0bc82372d3b",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.1889"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 956,
         "digest": "sha256:68b23da43beadd4fb9aac1ddca573dd6bd9421fb8a100a530a78453a300ab40e",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.3532"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 956,
         "digest": "sha256:7efc130db71a56582916f4bcd036b658d68aa2a0b2456aa5f04f4fa6320b260a",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.20348.1129"
         }
      }
   ]
}%
```

Signed-off-by: torredil <torredil@amazon.com>

### CODE REVIEW

**Comment by ConnorJC3** [comment]
@torredil wrong version on image
```
{
  "driverVersion": "v20221104-v1.13.0",
  "gitCommit": "",
  "buildDate": "2022-11-04T13:53:18+00:00",
  "goVersion": "go1.19.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by torredil** [comment]
Confirmed latest image has the correct version, thx 👍 

```
$ docker run --rm gcr.io/k8s-staging-provider-aws/aws-ebs-csi-driver:v20221104-v1.13.0 --version    
{
  "driverVersion": "v1.13.0",
  "gitCommit": "",
  "buildDate": "2022-11-04T20:24:28+00:00",
  "goVersion": "go1.19.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Pull request merged**
