### PR TITLE
audit: fix create-or-update-audit-pr.sh

### PR DESCRIPTION
**Pull request by spiffxp**
A fix and some changes to support k8s-infra image:

- fix typo in 'fork' remote uri
- create or update 'fork' remote
- don't rebuild pr-creator if it's already in PATH

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
wrong author/committer

**Comment by spiffxp** [comment]
/hold cancel
now authored/committed by me instead of @cncf-ci

**Comment by ameukam** [comment]
Fixed with https://github.com/kubernetes/k8s.io/pull/2206.

**Pull request merged**
