### PR TITLE
Promoted pause image version tag: 3.7"

### PR DESCRIPTION
**Pull request by dims**
This PR promotes the pause image to version 3.7.

Staging image details: https://console.cloud.google.com/gcr/images/k8s-staging-kubernetes/global/pause@sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c/details

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

### CODE REVIEW

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/109123

**Comment by Verolop** [comment]
lgtm

**Comment by ameukam** [comment]
```shell
crane digest gcr.io/k8s-staging-kubernetes/pause:3.7
sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c
```

/lgtm

**Comment by dims** [comment]
So say we all! https://prow.k8s.io/log?container=test&id=1508915438342377472&job=post-k8sio-image-promo

```
level=info msg="Request {0 gcr.io/k8s-staging-kubernetes us.gcr.io/k8s-artifacts-prod k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com pause pause sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c  3.7}: OK\n"
level=info msg="Request {0 gcr.io/k8s-staging-kubernetes us.gcr.io/k8s-artifacts-prod/kubernetes k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com pause pause sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c  3.7}: OK\n"
level=info msg="Request {0 gcr.io/k8s-staging-kubernetes eu.gcr.io/k8s-artifacts-prod k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com pause pause sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c  3.7}: OK\n"
level=info msg="Request {0 gcr.io/k8s-staging-kubernetes eu.gcr.io/k8s-artifacts-prod/kubernetes k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com pause pause sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c  3.7}: OK\n"
level=info msg="Request {0 gcr.io/k8s-staging-kubernetes asia.gcr.io/k8s-artifacts-prod/kubernetes k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com pause pause sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c  3.7}: OK\n"
level=info msg="Request {0 gcr.io/k8s-staging-kubernetes asia.gcr.io/k8s-artifacts-prod k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com pause pause sha256:bb6ed397957e9ca7c65ada0db5c5d1c707c9c8afc80a94acbe69f3ae76988f0c  3.7}: OK\n"
level=info msg="********** FINISHED **********"
```

**Pull request merged**
