### PR TITLE
Add controller-tools staging bucket & group

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold 
for mails

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
/assign @dims

**Review by alvaroaleman — APPROVED** [review]

**Comment by sbueringer** [comment]
/assign @dims 

Not sure who should be assigned here

**Comment by vincepri** [comment]
xref https://github.com/kubernetes/k8s.io/issues/2647

**Comment by vincepri** [comment]
/assign @BenTheElder
as well

**Comment by ameukam** [comment]
Note that the bucket created in a staging project has 90 days retention policy. Not sure if that meets your needs (I still unclearly on what we need to do this)

**Comment by sbueringer** [comment]
/hold

To clarify what our options are (discussion ongoing in https://kubernetes.slack.com/archives/CCK68P2Q2/p1713279196825609?thread_ts=1713174342.482079&cid=CCK68P2Q2)

**Comment by sbueringer** [comment]
Closing for now. We'll try GitHub release attachments

**Pull request closed without merging**
