### PR TITLE
Revert "k8s-staging-csi-secrets-store: retag v0.0.22 to include #545"

### PR DESCRIPTION
**Pull request by listx**
This reverts commit ebd4d3a8c0061c313a711ca33b2c84d9740d1cb9.

Commit ebd4d3a8c0061c313a711ca33b2c84d9740d1cb9 attempted to retag a
production image, which is not allowed.

### CODE REVIEW

**Comment by tam7t** [comment]
This change in tags was done before we published the release and was necessary to fix an issue in the release, https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.22

TBH i think reverting would cause more harm than good as it would introduce a bug to clusters that are currently using v0.0.22 images

**Comment by aramase** [comment]
I agree with @tam7t

@listx Did the retag not work when the PR for retag was merged?

**Comment by listx** [comment]
> I agree with @tam7t
> 
> @listx Did the retag not work when the PR for retag was merged?

Correct, the retag did not work because retagging is not supposed to work. So if you pull `us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver:v0.0.22` right now it will pull `us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver@sha256:1db2d1879a4ef656e3037a1d32be6bdb08cb10ea5800b6cca393361d6ac0330c` (the old digest).

In other words, merging this PR will have no effect on production. Instead it is merely cleanup of unrealized config changes.

**Comment by spiffxp** [comment]
This is not the first time we've merged something that broke things. Should have been caught by presubmits. I'll find the open issue...

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by listx** [comment]
> This is not the first time we've merged something that broke things. Should have been caught by presubmits. I'll find the open issue...

I created https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/375

**Comment by spiffxp** [comment]
Found it: https://github.com/kubernetes/k8s.io/issues/1520

Assigned to you and linked to the CIP issue

**Comment by aramase** [comment]
> In other words, merging this PR will have no effect on production. Instead it is merely cleanup of unrealized config changes.

Thanks for confirming!

**Pull request merged**
