### PR TITLE
Adding BlueSky TXT Records

### LINKED ISSUE #7445: kubernetes.dev DNS TXT record for BlueSky account
### Type of DNS update:

Create

### Domain being modified:

kubernetes.dev

### New DNS Record:

```yaml
_atproto.kubernetes.dev:
- type: TXT
  value: did=did:plc:kyg4uikmq7lzpb76ugvxa6ul
```

### Reason for update:

SIG ContribEx Contributor Comms is setting up accounts on BlueSky now that social network momentum is swinging that way. This request is for the K8sContributors equivalent handle on other networks.

### PR DESCRIPTION
**Pull request by chris-short**
These records verify BlueSky accounts Contributor Comms is spinning up

Resolves #7445 and #7444

### CODE REVIEW

**Comment by chris-short** [comment]
cc @kaslin

**Comment by ameukam** [comment]
According to https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial, this looks ok.

/approve
/hold

cc @cblecker @BenTheElder

**Pull request merged**
