### PR TITLE
Increase AUTO_DELETION_DAYS to 60 for staging repos

### PR DESCRIPTION
**Pull request by nikhita**
At least until the image promoter is ready.

/assign @dims

### CODE REVIEW

**Comment by dims** [comment]
/approve
/hold

/assign @thockin @spiffxp 

( hold for review by @thockin and @spiffxp )

**Comment by thockin** [comment]
Running reconcile now

**Comment by thockin** [comment]
hmm, something not right - first time changing lifecycle, so maybe need to be more explicit.  Will investigate

**Comment by thockin** [comment]
I am dumb - I forgot to rebase to upstream :)

```
thockin@freakshow2 k8s.io master /infra/gcp$ ./ensure-staging-storage.sh 
build-image
Ensuring project exists: k8s-staging-build-image
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-build-image/billingInfo
projectId: k8s-staging-build-image
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-build-image.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-build-image].
bindings:
- members:
  - serviceAccount:service-960211007710@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVk1ym3E=
version: 1
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
Empowering k8s-infra-staging-build-image@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
No changes made to gs://artifacts.k8s-staging-build-image.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-build-image/
Enabling Bucket Policy Only for gs://k8s-staging-build-image...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-build-image/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-build-image/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-build-image].
bindings:
- members:
  - serviceAccount:service-960211007710@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVk49Ais=
version: 1
No changes made to gs://k8s-staging-build-image/
No changes made to gs://k8s-staging-build-image/
Empowering k8s-infra-staging-build-image@kubernetes.io to GCS
No changes made to gs://k8s-staging-build-image/
No changes made to gs://k8s-staging-build-image/
Done
cip-test
Ensuring project exists: k8s-staging-cip-test
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-cip-test/billingInfo
projectId: k8s-staging-cip-test
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-cip-test.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-cip-test.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-cip-test].
bindings:
- members:
  - serviceAccount:service-324460563566@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:324460563566-compute@developer.gserviceaccount.com
  - serviceAccount:324460563566@cloudservices.gserviceaccount.com
  - serviceAccount:service-324460563566@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVk8Gf20=
version: 1
No changes made to gs://artifacts.k8s-staging-cip-test.appspot.com/
No changes made to gs://artifacts.k8s-staging-cip-test.appspot.com/
Empowering k8s-infra-staging-cip-test@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-cip-test.appspot.com/
No changes made to gs://artifacts.k8s-staging-cip-test.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-cip-test/
Enabling Bucket Policy Only for gs://k8s-staging-cip-test...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-cip-test/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-cip-test/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-cip-test].
bindings:
- members:
  - serviceAccount:service-324460563566@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:324460563566-compute@developer.gserviceaccount.com
  - serviceAccount:324460563566@cloudservices.gserviceaccount.com
  - serviceAccount:service-324460563566@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVk_OZzM=
version: 1
No changes made to gs://k8s-staging-cip-test/
No changes made to gs://k8s-staging-cip-test/
Empowering k8s-infra-staging-cip-test@kubernetes.io to GCS
No changes made to gs://k8s-staging-cip-test/
No changes made to gs://k8s-staging-cip-test/
Done
cluster-api
Ensuring project exists: k8s-staging-cluster-api
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-cluster-api/billingInfo
projectId: k8s-staging-cluster-api
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-cluster-api.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-cluster-api.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-cluster-api].
bindings:
- members:
  - serviceAccount:service-190130481896@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:190130481896-compute@developer.gserviceaccount.com
  - serviceAccount:190130481896@cloudservices.gserviceaccount.com
  - serviceAccount:service-190130481896@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlCWZIY=
version: 1
No changes made to gs://artifacts.k8s-staging-cluster-api.appspot.com/
No changes made to gs://artifacts.k8s-staging-cluster-api.appspot.com/
Empowering k8s-infra-staging-cluster-api@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-cluster-api.appspot.com/
No changes made to gs://artifacts.k8s-staging-cluster-api.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-cluster-api/
Enabling Bucket Policy Only for gs://k8s-staging-cluster-api...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-cluster-api/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-cluster-api/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-cluster-api].
bindings:
- members:
  - serviceAccount:service-190130481896@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:190130481896-compute@developer.gserviceaccount.com
  - serviceAccount:190130481896@cloudservices.gserviceaccount.com
  - serviceAccount:service-190130481896@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlFZxzY=
version: 1
No changes made to gs://k8s-staging-cluster-api/
No changes made to gs://k8s-staging-cluster-api/
Empowering k8s-infra-staging-cluster-api@kubernetes.io to GCS
No changes made to gs://k8s-staging-cluster-api/
No changes made to gs://k8s-staging-cluster-api/
Done
cluster-api-aws
Ensuring project exists: k8s-staging-cluster-api-aws
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-cluster-api-aws/billingInfo
projectId: k8s-staging-cluster-api-aws
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-cluster-api-aws.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-cluster-api-aws.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-cluster-api-aws].
bindings:
- members:
  - serviceAccount:service-433651898792@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlIhdRk=
version: 1
No changes made to gs://artifacts.k8s-staging-cluster-api-aws.appspot.com/
No changes made to gs://artifacts.k8s-staging-cluster-api-aws.appspot.com/
Empowering k8s-infra-staging-cluster-api-aws@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-cluster-api-aws.appspot.com/
No changes made to gs://artifacts.k8s-staging-cluster-api-aws.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-cluster-api-aws/
Enabling Bucket Policy Only for gs://k8s-staging-cluster-api-aws...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-cluster-api-aws/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-cluster-api-aws/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-cluster-api-aws].
bindings:
- members:
  - serviceAccount:service-433651898792@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlLn3o0=
version: 1
No changes made to gs://k8s-staging-cluster-api-aws/
No changes made to gs://k8s-staging-cluster-api-aws/
Empowering k8s-infra-staging-cluster-api-aws@kubernetes.io to GCS
No changes made to gs://k8s-staging-cluster-api-aws/
No changes made to gs://k8s-staging-cluster-api-aws/
Done
coredns
Ensuring project exists: k8s-staging-coredns
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-coredns/billingInfo
projectId: k8s-staging-coredns
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-coredns.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-coredns.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-coredns].
bindings:
- members:
  - serviceAccount:service-848617618266@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-848617618266@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-848617618266@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:848617618266-compute@developer.gserviceaccount.com
  - serviceAccount:848617618266@cloudservices.gserviceaccount.com
  - serviceAccount:service-848617618266@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlOyuf0=
version: 1
No changes made to gs://artifacts.k8s-staging-coredns.appspot.com/
No changes made to gs://artifacts.k8s-staging-coredns.appspot.com/
Empowering k8s-infra-staging-coredns@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-coredns.appspot.com/
No changes made to gs://artifacts.k8s-staging-coredns.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-coredns/
Enabling Bucket Policy Only for gs://k8s-staging-coredns...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-coredns/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-coredns/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-coredns].
bindings:
- members:
  - serviceAccount:service-848617618266@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:service-848617618266@container-analysis.iam.gserviceaccount.com
  role: roles/containeranalysis.ServiceAgent
- members:
  - serviceAccount:service-848617618266@gcp-sa-containerscanning.iam.gserviceaccount.com
  role: roles/containerscanning.ServiceAgent
- members:
  - serviceAccount:848617618266-compute@developer.gserviceaccount.com
  - serviceAccount:848617618266@cloudservices.gserviceaccount.com
  - serviceAccount:service-848617618266@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlR0lzY=
version: 1
No changes made to gs://k8s-staging-coredns/
No changes made to gs://k8s-staging-coredns/
Empowering k8s-infra-staging-coredns@kubernetes.io to GCS
No changes made to gs://k8s-staging-coredns/
No changes made to gs://k8s-staging-coredns/
Done
csi
Ensuring project exists: k8s-staging-csi
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-csi/billingInfo
projectId: k8s-staging-csi
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-csi.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-csi.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-csi].
bindings:
- members:
  - serviceAccount:service-874328413592@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:874328413592-compute@developer.gserviceaccount.com
  - serviceAccount:874328413592@cloudservices.gserviceaccount.com
  - serviceAccount:service-874328413592@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlU05Tg=
version: 1
No changes made to gs://artifacts.k8s-staging-csi.appspot.com/
No changes made to gs://artifacts.k8s-staging-csi.appspot.com/
Empowering k8s-infra-staging-csi@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-csi.appspot.com/
No changes made to gs://artifacts.k8s-staging-csi.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-csi/
Enabling Bucket Policy Only for gs://k8s-staging-csi...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-csi/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-csi/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-csi].
bindings:
- members:
  - serviceAccount:service-874328413592@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:874328413592-compute@developer.gserviceaccount.com
  - serviceAccount:874328413592@cloudservices.gserviceaccount.com
  - serviceAccount:service-874328413592@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlX7SlU=
version: 1
No changes made to gs://k8s-staging-csi/
No changes made to gs://k8s-staging-csi/
Empowering k8s-infra-staging-csi@kubernetes.io to GCS
No changes made to gs://k8s-staging-csi/
No changes made to gs://k8s-staging-csi/
Done
kops
Ensuring project exists: k8s-staging-kops
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-kops/billingInfo
projectId: k8s-staging-kops
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-kops.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-kops.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-kops].
bindings:
- members:
  - serviceAccount:service-889470918518@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVla-mFQ=
version: 1
No changes made to gs://artifacts.k8s-staging-kops.appspot.com/
No changes made to gs://artifacts.k8s-staging-kops.appspot.com/
Empowering k8s-infra-staging-kops@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-kops.appspot.com/
No changes made to gs://artifacts.k8s-staging-kops.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-kops/
Enabling Bucket Policy Only for gs://k8s-staging-kops...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-kops/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-kops/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-kops].
bindings:
- members:
  - serviceAccount:service-889470918518@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVleGkgU=
version: 1
No changes made to gs://k8s-staging-kops/
No changes made to gs://k8s-staging-kops/
Empowering k8s-infra-staging-kops@kubernetes.io to GCS
No changes made to gs://k8s-staging-kops/
No changes made to gs://k8s-staging-kops/
Done
publishing-bot
Ensuring project exists: k8s-staging-publishing-bot
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-publishing-bot/billingInfo
projectId: k8s-staging-publishing-bot
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-publishing-bot.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-publishing-bot.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-publishing-bot].
bindings:
- members:
  - serviceAccount:service-438481731081@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlhGvxM=
version: 1
No changes made to gs://artifacts.k8s-staging-publishing-bot.appspot.com/
No changes made to gs://artifacts.k8s-staging-publishing-bot.appspot.com/
Empowering k8s-infra-staging-publishing-bot@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-publishing-bot.appspot.com/
No changes made to gs://artifacts.k8s-staging-publishing-bot.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-publishing-bot/
Enabling Bucket Policy Only for gs://k8s-staging-publishing-bot...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-publishing-bot/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-publishing-bot/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-publishing-bot].
bindings:
- members:
  - serviceAccount:service-438481731081@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:thockin@google.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlkQGFo=
version: 1
No changes made to gs://k8s-staging-publishing-bot/
No changes made to gs://k8s-staging-publishing-bot/
Empowering k8s-infra-staging-publishing-bot@kubernetes.io to GCS
No changes made to gs://k8s-staging-publishing-bot/
No changes made to gs://k8s-staging-publishing-bot/
Done
release-test
Ensuring project exists: k8s-staging-release-test
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-release-test/billingInfo
projectId: k8s-staging-release-test
Enabling the container registry API
Ensuring the registry exists and is readable
No changes made to gs://artifacts.k8s-staging-release-test.appspot.com/
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-release-test.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-release-test].
bindings:
- members:
  - serviceAccount:service-634027639865@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlnZZqw=
version: 1
No changes made to gs://artifacts.k8s-staging-release-test.appspot.com/
No changes made to gs://artifacts.k8s-staging-release-test.appspot.com/
Empowering k8s-infra-staging-release-test@kubernetes.io to GCR
No changes made to gs://artifacts.k8s-staging-release-test.appspot.com/
No changes made to gs://artifacts.k8s-staging-release-test.appspot.com/
Enabling the GCS API
Ensuring the bucket exists and is world readable
No changes made to gs://k8s-staging-release-test/
Enabling Bucket Policy Only for gs://k8s-staging-release-test...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-release-test/...
Ensuring the bucket has auto-deletion of 60 days
Setting lifecycle configuration on gs://k8s-staging-release-test/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-release-test].
bindings:
- members:
  - serviceAccount:service-634027639865@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNVlqeM2s=
version: 1
No changes made to gs://k8s-staging-release-test/
No changes made to gs://k8s-staging-release-test/
Empowering k8s-infra-staging-release-test@kubernetes.io to GCS
No changes made to gs://k8s-staging-release-test/
No changes made to gs://k8s-staging-release-test/
Done
```

**Pull request merged**
