### PR TITLE
promoting newly built opentelemetry image

### PR DESCRIPTION
**Pull request by longwuyuan**
- After multiple PRs, we have a new build of the opentelemetry image
- Thanks to the wonderful help & support from @esigo , we fixed the compile and other problems
- Now need to promote the image, change the values file of the chart to include the image and test

/assign @rikatz @strongjz

### CODE REVIEW

**Comment by longwuyuan** [comment]
Odd, James I see your lgtm mail but the PR does not show that. Or is it my browser cache.

Thanks,
---
; Long Wu Yuan

**Comment by longwuyuan** [comment]
@strongjz @rikatz when you get a chance, please review this. Need it to test opentelemetry by others

**Comment by rikatz** [comment]
/approve
Thanks

**Pull request merged**
