### PR TITLE
Remove NS records from all canary zones

### PR DESCRIPTION
**Pull request by thockin**
Currently we (again) have dangling NS delegations.

### CODE REVIEW

**Comment by thockin** [comment]
Hold for manual tests

**Comment by thockin** [comment]
/remove hold

Seems to work in dry-run

**Review by stp-ip — APPROVED** [review]
/approve

**Comment by thockin** [comment]
@stp-ip did you mean to LGTM too or are you looking for another reviewer?   This PR is not assigned to anyone - who wants it?

**Comment by stp-ip** [comment]
Thought I give some time for anyone to jump in, but happy to get it merged.

/lgtm

**Comment by thockin** [comment]
Is Prow running these updates now, or should I push manually?

**Comment by thockin** [comment]
Looks like prow did it!

**Pull request merged**
