### PR TITLE
Promote aws-ebs-csi-driver v1.5.0

### PR DESCRIPTION
**Pull request by gtxu**

### CODE REVIEW

**Comment by vdhanan** [comment]
the hash should be ddd1b2e650ce5a10b3f5e9ae706cc384fc7e1a15940e07bba75f27369bc6a1ac

**Comment by vdhanan** [comment]
➜  aws-ebs-csi-driver git:(release-1.5) gcloud container images list-tags gcr.io/k8s-staging-provider-aws/aws-ebs-csi-driver --format='get(tags, digest)' --filter='tags:v1.5.0 AND tags!~rc'
v20211117-v1.5.0-windows-amd64-20H2	sha256:54c8f91e68896ecd359a91c0908a3af07ad0a125d5f6764838e6d823303877f1
v20211117-v1.5.0-windows-amd64-2004	sha256:69dabb7ae21c32c6a02152e39518272d8bb2b22585d08056b046669fcceae1cf
v20211117-v1.5.0-windows-amd64-1809	sha256:e415ace09a13dfbcb9760f3b98488e87c4d22025466f6caaec06f922c28a5864
v20211117-v1.5.0-linux-arm64-amazon	sha256:40a55d5486e060a8ce78f1c7b59958ae8b735827b80d42a69c33ef519d5dc8d9
v20211117-v1.5.0-linux-amd64-amazon	sha256:0b0d587f060d7c34b721510c19408c385639b70f97b7c18a8a4528ea131be81d
v20211117-v1.5.0	sha256:ddd1b2e650ce5a10b3f5e9ae706cc384fc7e1a15940e07bba75f27369bc6a1ac

**Comment by hakman** [comment]
SHA256 corresponds to that from [staging registry](https://console.cloud.google.com/gcr/images/k8s-staging-provider-aws/global/aws-ebs-csi-driver@sha256:ddd1b2e650ce5a10b3f5e9ae706cc384fc7e1a15940e07bba75f27369bc6a1ac/details).
/lgtm

**Pull request merged**
