### PR TITLE
Promote 1.25-rc.0 images to experimental for testing Artifact Registry

### PR DESCRIPTION
**Pull request by upodroid**
Part of #3976 

Promoting the images from #4063 to the experimental subproject. The idea is to test promoting images to AR. 

This PR will promote 28 images to 26 registries.

Before we do this:
- #3956 needs to be merged
- Infra from #3968 needs to be deployed.
```
 REDACTED  MCW0CDP3YY  ~  ERROR  $  gcrane ls europe-west2-docker.pkg.dev/k8s-artifacts-prod/images/
2022/08/10 16:39:35 No matching credentials were found for "europe-west2-docker.pkg.dev"
Error: GET https://europe-west2-docker.pkg.dev/v2/token?scope=repository%3Ak8s-artifacts-prod%2Fimages%2F%3Apull&service=: DENIED: Artifact Registry API has not been used in project 388270116193 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=388270116193 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
- Merging #3956 should give me permissions to push images to the `gcr.io/k8s-staging/experimental`, i'll cp the images with gcrane from `gcr.io/k8s-staging-kubernetes` to experimental
- @puerco said something about bugs in the image-promoter that need to be fixed. https://kubernetes.slack.com/archives/CJH2GBF7Y/p1660077867016269?thread_ts=1660057694.134999&cid=CJH2GBF7Y

/cc @kubernetes/release-engineering @dims

### CODE REVIEW

**Comment by upodroid** [comment]
I synced the images:

```python
import yaml
import os
from yaml.loader import SafeLoader

with open('images.yaml') as f:
    data = yaml.load(f, Loader=SafeLoader)
    for images in data:
        for image in images['dmap']:
            os.system(f"gcrane cp gcr.io/k8s-staging-kubernetes/{images['name']}@{image} gcr.io/k8s-staging-experimental/{images['name']}@{image}")
```

/test pull-k8sio-cip


The infra is up.

**Comment by ameukam** [comment]
/assign @puerco 
cc @kubernetes/release-engineering

**Review by cpanato — APPROVED** [review]
/approve
/lgtm

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
