### PR TITLE
Replace master branch references with main

### PR DESCRIPTION
**Pull request by nikhita**
Ref: https://github.com/kubernetes/k8s.io/issues/1597#issuecomment-790810435

/assign @spiffxp 

/hold
hold should be removed by someone who can deploy the k8s.io changes

### CODE REVIEW

**Comment by nikhita** [comment]
>  hold should be removed by someone who can deploy the k8s.io changes

It looks like @thockin has been deploying recently

/assign @thockin

**Comment by dims** [comment]
i can do this

/approve
/lgtm
/hold cancel

**Comment by thockin** [comment]
@dims - when you push these nginx changes to prod you also need to bounce
the nginx instances - they don't self-restart.

**Comment by dims** [comment]
@thockin aha! could we add any extra step to the README please? usually i just read that and execute step by step :)

**Comment by thockin** [comment]
Which README?  The one that says to `make deploy` (which doesn't exist, LOL).

**Comment by dims** [comment]
LOL

**Pull request merged**
