### PR TITLE
Add coredns v1.11.3

### PR DESCRIPTION
**Pull request by dims**
coredns [v1.11.3](https://github.com/coredns/coredns/releases/tag/v1.11.3) shipped an hour ago!

I can see it here:
https://explore.ggcr.dev/?image=docker.io%2Fcoredns%2Fcoredns:1.11.3

Here's the manifest/layers:
```
root@ip-172-31-47-86:/home/davanum# nerdctl pull coredns/coredns:1.11.3
docker.io/coredns/coredns:1.11.3:                                                 resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:9caabbf6238b189a65d0d6e6ac138de60d6a1c419e5a341fbbb7c78382559c6e:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:f0b8c589314ed010a0c326e987a52b50801f0145ac9b75423af1b5c66dbd6d50: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:c69fa2e9cbf5f42dc48af631e956d3f95724c13f91596bc567591790e5e36db6:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:2ae710cd8bfef4545fa3a6dc274d6b7a991ca379cdaa3cdf460d5cb5840a3c88:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:804c8aba2cc61168600515a6831474978d0ea8faddd8a66f99cc9f2bbd576105:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:d095569ed07d46f67b8d67f2fd1456c4ab693f33c70d3d31e8ad0148cd1052ee:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:d858cbc252ade14879807ff8dbc3043a26bbdb92087da98cda831ee040b172b3:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:0f8b424aa0b96c1c388a5fd4d90735604459256336853082afb61733438872b5:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:307c1adadb60e6e9b8aca553ec620d77fedc112737cc54e9ee73ac165e7f3cbc:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:5318d93a3a6582d0351c833fa3cf04ab41352b2e6c77c9ec3d330581eb267683:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:f9d565286af529b228717cf8bb117abb80fe7f5433c2d1087c70759fd97ad98e:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:d557676654e572af3e3173c90e7874644207fda32cd87e9d3d66b5d7b98a7b21:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:1069fc2daed1aceff7232f4b8ab21200dd3d8b04f61be9da86977a34a105dfdc:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:c8022d07192eddbb2a548ba83be5e412f7ba863bbba158d133c9653bb8a47768:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:b40161cd83fc5d470d6abe50e87aa288481b6b89137012881d74187cfbf9f502:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:d462aa3453675bb1f9a271a72cc72a53e628521a7d0e94b720bd07f9ca4962dc:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.7 s                                                                    total:  17.7 M (10.4 MiB/s)
```

cross checked with `crane` as well:
```
❯ crane digest docker.io/coredns/coredns:1.11.3
sha256:9caabbf6238b189a65d0d6e6ac138de60d6a1c419e5a341fbbb7c78382559c6e
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
🎉 

Thanks dims!

Can we document this process somewhere? (can wait for later)

**Comment by dims** [comment]
Cheat sheet for populating the staging repo from the docker registry

ensure you have nerdctl and are logged into gcloud
```
gcloud components install docker-credential-gcr
gcloud auth login
```

Then pull the layers/images for all platforms, tag them with the new staging repo info and push it.
```
nerdctl pull coredns/coredns:1.11.3 --all-platforms
nerdctl tag coredns/coredns:1.11.3 gcr.io/k8s-staging-coredns/coredns:1.11.3
nerdctl push gcr.io/k8s-staging-coredns/coredns:1.11.3 --all-platforms
```

**Pull request merged**
