### PR TITLE
add generator script for image promotion

### PR DESCRIPTION
**Pull request by aramase**
Can be used to generate the promoter manifests for release

```yaml
- name: driver
  dmap:
    "sha256:384a5e90b409c16186a26152728ec265ed4dd15eae9d7e518962226aa2886b2b": [ "v0.0.12" ]
```

### CODE REVIEW

**Comment by justaugustus** [comment]
I'd suggest using `cip-mm` (the manifest merger) instead: https://github.com/kubernetes-sigs/k8s-container-image-promoter/tree/master/cmd/cip-mm

**Comment by ritazh** [comment]
Thanks @justaugustus! We will look into it!

**Pull request merged**
