### PR TITLE
Bootstrap GCP sandbox infrastructure for archeio

### PR DESCRIPTION
**Pull request by ameukam**
Related:
  - https://github.com/kubernetes/k8s.io/issues/3317

### CODE REVIEW

**Comment by ameukam** [comment]
cc @BenTheElder @dims 

The Terraform part is already deployed.

**Comment by dims** [comment]
@ameukam looks like we need to fix the verify?

```
[0;31mFAILED[0m   verify-boilerplate.sh	0s
```

**Comment by ameukam** [comment]
@dims Fixed.

**Pull request merged**
