### PR TITLE
aaa: Update rbac permissions

### PR DESCRIPTION
**Pull request by ameukam**
Allow workloads operators to :
 - list and watch the `ExternalSecrets`
 - create/update/delete the `ManagedCertificates`.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims @spiffxp

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
Remove when ready to deploy

**Comment by spiffxp** [comment]
_actually_ deploying this now, sorry for the delay

**Comment by spiffxp** [comment]
```$ ./ensure-namespaces.sh gke_kubernetes-public_us-central1_aaa
Create namespace: elekto
namespace/elekto unchanged
Apply namespace-user role: elekto
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: elekto
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: elekto is present
Create namespace: gcsweb
namespace/gcsweb unchanged
Apply namespace-user role: gcsweb
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: gcsweb
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: gcsweb is present
Create namespace: kettle
namespace/kettle unchanged
Apply namespace-user role: kettle
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: kettle
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: kettle is present
Create namespace: k8s-io-prod
namespace/k8s-io-prod unchanged
Apply namespace-user role: k8s-io-prod
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: k8s-io-prod
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: k8s-io-prod is present
Create namespace: k8s-io-canary
namespace/k8s-io-canary unchanged
Apply namespace-user role: k8s-io-canary
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: k8s-io-canary
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: k8s-io-canary is present
Create namespace: kubernetes-external-secrets
namespace/kubernetes-external-secrets unchanged
Apply namespace-user role: kubernetes-external-secrets
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: kubernetes-external-secrets
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: kubernetes-external-secrets is present
Create namespace: perfdash
namespace/perfdash unchanged
Apply namespace-user role: perfdash
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: perfdash
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: perfdash is present
Create namespace: prow
namespace/prow unchanged
Apply namespace-user role: prow
role.rbac.authorization.k8s.io/namespace-user configured
Apply namespace-user role binding: prow
rolebinding.rbac.authorization.k8s.io/namespace-user configured
Ensure only one role binding in namespace: prow is present
Only one role binding per namespace is allowed (current: 9)```

**Pull request merged**
