### PR TITLE
Prep to flip k8s.io to "aaa" cluster

### LINKED ISSUE #504: Move k8s.io from old Google-only cluster to aaa
Other than the existing TLS secrets which will need to be manually copied, the YAML exists.

1) PR to make a group and namespace

2) Load YAML in aaa cluster, get new IP

3) figure out what tests we want to do to convince ourselves it is sane

4) Monitoring (at least up-checks)

5) Flip DNS to new IP

6) Turn down old

### PR DESCRIPTION
**Pull request by thockin**
I am running it in there now.  Tests pass at both the canary IP and the real IP.

I have manually uploaded the original SSL cert so when DNS flips it should "just work".  @munnerz to triple check.

Fixes #504 

TODO:
- [x] Verify TLS is settled
- [x] Set DNS TTL back to  normal
- [x] Actuate groups config
- [x] Scale old deployment to 0 and verify everything is still good
- [ ] move alerting config to kubernetes-public project

### CODE REVIEW

**Comment by thockin** [comment]
DNS is active, with a low TTL in case we need to flip it back.

Certs are provisioning, but because of combined oddities of GCLB and cert-manager, we hit quota limits.  Bumped those up, now watching.

**Comment by thockin** [comment]
Certs seem stable now, thanks @munnerz

**Comment by munnerz** [comment]
/lgtm
/hold

(holding in case this shouldn't merge yet/others have opinions on other parts) - but the contents of this PR look good to me 😄

**Comment by thockin** [comment]
Google groups activation is all that is left.  k8s.io has left the building!

**Comment by BenTheElder** [comment]
thank you both!

**Comment by thockin** [comment]
Approve the PR! :)

**Comment by BenTheElder** [comment]
it is approved? :P
Screen Shot 2020-02-19 at 9 29 31 PM

/approve

**Comment by thockin** [comment]
Actuating groups config now

**Pull request merged**
