### PR TITLE
cluster-api-provider-openstack delete conformance bucket

### PR DESCRIPTION
**Pull request by sbueringer**
We don't need this bucket anymore as we migrated from OpenLab to Prow.

I'm not sure how I'm actually deleting this bucket in if this PR is correct. 
I assume just because I delete the config the resources are not automatically deleted.

I'm also not sure what the policy is. We won't use this bucket from now on, but it contains old
conformance test results. I assume nobody needs them anymore.

xrefs: 
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/785
* https://github.com/kubernetes/test-infra/pull/21445

### CODE REVIEW

**Review by spiffxp — CHANGES_REQUESTED** [review]
You are correct that deletion is at present manual.  Myself, @ameukam or @dims can do this.

Before we do, can you update your PR to remove this line from this file? https://github.com/kubernetes/k8s.io/blob/679793367ace456d678779c8908df83e5f6b9c4b/infra/gcp/ensure-conformance-storage.sh#L48

**Comment by sbueringer** [comment]
> You are correct that deletion is at present manual. Myself, @ameukam or @dims can do this.
> 
> Before we do, can you update your PR to remove this line from this file?
> 
> https://github.com/kubernetes/k8s.io/blob/679793367ace456d678779c8908df83e5f6b9c4b/infra/gcp/ensure-conformance-storage.sh#L48

Ah missed that one. Fixed & push force'd (I assume squash before merge is required anyway)

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Ah the joys of permissions...
```
$ gsutil rb gs://k8s-conform-capi-openstack/
Removing gs://k8s-conform-capi-openstack/...
NotEmptyException: 409 BucketNotEmpty (k8s-conform-capi-openstack)
$ gsutil rm -r gs://k8s-conform-capi-openstack/
Removing gs://k8s-conform-capi-openstack/README.md#1582738137715833...
AccessDeniedException: 403 Object 'k8s-conform-capi-openstack/README.md' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2030-02-25T21:28:57.715612877-08:00
$ gsutil rm -rf gs://k8s-conform-capi-openstack/*
CommandException: 849 files/objects could not be removed.
```

I'll keep poking

**Comment by sbueringer** [comment]
> Ah the joys of permissions...
> 
> ```
> $ gsutil rb gs://k8s-conform-capi-openstack/
> Removing gs://k8s-conform-capi-openstack/...
> NotEmptyException: 409 BucketNotEmpty (k8s-conform-capi-openstack)
> $ gsutil rm -r gs://k8s-conform-capi-openstack/
> Removing gs://k8s-conform-capi-openstack/README.md#1582738137715833...
> AccessDeniedException: 403 Object 'k8s-conform-capi-openstack/README.md' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2030-02-25T21:28:57.715612877-08:00
> $ gsutil rm -rf gs://k8s-conform-capi-openstack/*
> CommandException: 849 files/objects could not be removed.
> ```
> 
> I'll keep poking

Oh sorry :). Could also schedule a task for 2030 :)

**Comment by spiffxp** [comment]
```
$ gsutil lifecycle get gs://k8s-conform-capi-openstack
gs://k8s-conform-capi-openstack/ has no lifecycle configuration.
$ gsutil retention get gs://k8s-conform-capi-openstack
  Retention Policy (UNLOCKED):
    Duration: 10 Year(s)
    Effective Time: Wed, 05 Feb 2020 00:02:48 GMT
```

```yaml
# $ gsutil iam get gs://k8s-conform-capi-openstack | json2yaml
bindings:
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - projectEditor:k8s-conform
  - projectOwner:k8s-conform
  role: roles/storage.legacyBucketOwner
- members:
  - projectViewer:k8s-conform
  role: roles/storage.legacyBucketReader
- members:
  - group:k8s-infra-conform-capi-openstack@kubernetes.io
  role: roles/storage.legacyBucketWriter
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  - group:k8s-infra-conform-capi-openstack@kubernetes.io
  role: roles/storage.objectAdmin
- members:
  - serviceAccount:service-capi-openstack@k8s-conform.iam.gserviceaccount.com
  role: roles/storage.objectCreator
- members:
  - allUsers
  role: roles/storage.objectViewer
```

```
$ gsutil retention clear gs://k8s-conform-capi-openstack
Clearing Retention Policy on gs://k8s-conform-capi-openstack/...
$ gsutil retention get gs://k8s-conform-capi-openstack
gs://k8s-conform-capi-openstack/ has no Retention Policy.
$ gsutil -m rm -r gs://k8s-conform-capi-openstack
# ...
Operation completed over 838 objects.
Removing gs://k8s-conform-capi-openstack/...
$ gsutil rb -f gs://k8s-conform-capi-openstack
Removing gs://k8s-conform-capi-openstack/...
```

OK that should do it

**Pull request merged**
