### PR TITLE
Image promotion for cluster-api v1.5.3

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Image promotion for cluster-api v1.5.3
This is an automated PR generated from `kpromo`
```
kpromo pr --fork furkatgofurov7 --project cluster-api --reviewers "@CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri" --tag v1.5.3 --image cluster-api-controller --image kubeadm-control-plane-controller --image kubeadm-bootstrap-controller --image clusterctl
```

/hold
cc: @CecileRobertMichon @enxebre @fabriziopandini @killianmuldoon @sbueringer @vincepri

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

Feel free to unhold!

**Comment by furkatgofurov7** [comment]
Double checked image shas' and they do match with gcr registry

**Pull request merged**
