### PR TITLE
Push ibm-powervs-block-csi-driver v0.6.0

### PR DESCRIPTION
**Pull request by yussufsh**
https://console.cloud.google.com/gcr/images/k8s-staging-cloud-provider-ibm/global/ibm-powervs-block-csi-driver@sha256:a7fd78e2034ca834d39a9ff4e26d255d027dd9ee349e4525215ecbd50e1e6737/details

### CODE REVIEW

**Comment by yussufsh** [comment]
Waiting on response from https://github.com/kubernetes/k8s.io/pull/6328#issuecomment-1910313845

**Comment by ameukam** [comment]
> Waiting on response from [#6328 (comment)](https://github.com/kubernetes/k8s.io/pull/6328#issuecomment-1910313845)

@yussufsh All PRs making the test failing have been merged. Please rebase from the main branch.

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
