### PR TITLE
add go.k8s.io/bot-commands

### PR DESCRIPTION
**Pull request by spiffxp**
I bikeshedded in my head over bot-commands vs commands and can be swayed.  I opted for commands since it's shorter

### CODE REVIEW

**Comment by spiffxp** [comment]
FYI @kubernetes/sig-testing-pr-reviews @kubernetes/sig-contributor-experience-pr-reviews

**Comment by thockin** [comment]
I think I prefer `bot-commands` or `github-bots` or something - I expected
`commands` to be about kubectl.

**Comment by spiffxp** [comment]
bot-commands it is

**Comment by spiffxp** [comment]
ping @ixdy

**Pull request merged**
