### PR TITLE
Add staging for git-sync

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by stp-ip** [comment]
+1 from me, but as I am one of the reviewers listed not doing to lgtm etc.

**Review by justaugustus — CHANGES_REQUESTED** [review]
Hey @thockin -- I think you'll need to actuate the project in https://github.com/kubernetes/k8s.io/blob/af78aa95a4705166a4b9a920160125fd89c3cf48/infra/gcp/ensure-staging-storage.sh#L43, right?

**Comment by thockin** [comment]
fixed!

**Comment by justaugustus** [comment]
Thanks Tim!
/lgtm

**Comment by stp-ip** [comment]
> /hold what's this for again?

git-sync is a project done at k/git-sync and is therefore in the vicinity of Kubernetes. It's main use is as a git pulling sidecar.
Container builds and publishing is currently done manually by Tim and with this PR would be moved to be governed by 2 people instead of one and also open to non googlers. Also open to be automated as well later etc. pp.

**Comment by dims** [comment]
Ack @stp-ip we can remove hold when someone runs the script for creating the staging repo.

**Comment by thockin** [comment]
Group added.

**Comment by thockin** [comment]
Staging created

**Pull request merged**
