### PR TITLE
test images: Promote newly built E2E test images

### PR DESCRIPTION
**Pull request by claudiubelu**
These images have been built, as it can be seen here: https://testgrid.k8s.io/sig-testing-images

A few images are not included here yet:

- echoserver
- metadata-concealment
- pets/peer-finder
- redis

### CODE REVIEW

**Comment by claudiubelu** [comment]
Presubmit jobs with these images: https://github.com/kubernetes/kubernetes/pull/87607

**Comment by spiffxp** [comment]
/hold
Not all of these images have been built AFAICT

e.g. recent failures for:
- https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-echoserver-test-images
- https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-metadata-concealment-test-images

**Review by spiffxp — APPROVED** [review]
/hold cancel
/approve
/lgtm

**Comment by spiffxp** [comment]
Part of https://github.com/kubernetes/k8s.io/issues/1522, https://github.com/kubernetes/kubernetes/issues/96770

**Pull request merged**
