### PR TITLE
Image promotion for publishing-bot v0.1.0-1

### PR DESCRIPTION
**Pull request by justaugustus**
Image promotion for publishing-bot v0.1.0-1
This is an automated PR generated from `kpromo`
```
kpromo pr --fork justaugustus --interactive --project publishing-bot --tag v0.1.0-1
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by justaugustus** [comment]
Given:

- k/publishing-bot can now automatically build images
- images were previously tagged as `latest`

I _believe_ the last manually built image is based on https://github.com/kubernetes/publishing-bot/tree/673e96332a3e605613363d59c462f7913d4a7f42.

I then tagged that image as gcr.io/k8s-staging-publishing-bot/k8s-publishing-bot:v0.1.0-1 and ran `kpromo pr`.

/assign @cpanato @saschagrunert 
cc: @kubernetes/publishing-bot-maintainers

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
