### PR TITLE
Add mailing list for CEL related discussions

### PR DESCRIPTION
**Pull request by jpbetz**
We already have a mailing list (https://groups.google.com/a/google.com/g/wg-sig-api-machinery-cel-dev-external) but it is not external or community managed, so we'd like to move to this list.

cc @kubernetes/sig-api-machinery-leads

### CODE REVIEW

**Comment by ameukam** [comment]
@jpbetz please ensure this group is listed in https://github.com/kubernetes/k8s.io/blob/main/groups/restrictions.yaml#L21-L23

**Comment by jpbetz** [comment]
> Joe Betz please ensure this group is listed in https://github.com/kubernetes/k8s.io/blob/main/groups/restrictions.yaml#L21-L23

Added. Thanks!

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
