### PR TITLE
releng: Image promotion for kubernetes v1.25.0 / v1.25.1-rc.0

### PR DESCRIPTION
**Pull request by jeremyrickard**
Image promotion for kubernetes v1.25.0 / v1.25.1-rc.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork jeremyrickard --interactive --tag v1.25.0 --tag v1.25.1-rc.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by jeremyrickard** [comment]
cc: @puerco @Verolop

**Comment by puerco** [comment]
Lets'g goooooo :rocket: 
/lgtm

**Comment by katcosgrove** [comment]
IT'S HAPPENING

/pony

**Pull request merged**
