### PR TITLE
Add release-test infra

### LINKED ISSUE #292: [sig-release] GCS + GCR repos for mocking release workflow
In support of this [Releng brainstorm](https://docs.google.com/document/d/1Js_36K51Q6AjEsVUjRBMISTA4D7cnjZmoSkn43_Jmxo/edit), which will soon become KEPs or updates to existing KEPs, I'd like to request a playground so Release Engineering can start to mock the release process end-to-end.

We know we produce:
- binaries
- tarballs
- container images
- rpms
- debs

so it sounds like at the very least, we'd need a GCS bucket and GCR repo.

- SIG Release Chairs would have ownership (hopefully) via IAM
- [Release Engineering personnel](https://github.com/kubernetes/release/blob/master/OWNERS_ALIASES#L8-L24) would have write access (this can happen as a follow-up)
- Service account with write access that we can wire into test-infra for jobs

Naming: `k8s-staging-release`?

I think that covers first steps, but I'm new to GCP, so please steer me in the right direction :)

/cc @kubernetes/sig-release-admins @kubernetes/release-managers @dims @thockin 
/sig release
/area release-eng
/milestone v1.16
/priority important-soon

### PR DESCRIPTION
**Pull request by thockin**
This lets sig-release test their release tooling.  It follows the cip-test pattern.

Fixes #292

### CODE REVIEW

**Comment by dims** [comment]
/hold

for creation of the resources

**Comment by dims** [comment]
So ... this PR will end up creating `k8s-staging-release-test` and `k8s-release-test-prod` GCP projects

per @thockin `"Eventually we won't need the -prod, since the One True Promoter should handle it.  Eventually"`

**Comment by justaugustus** [comment]
Thanks @thockin + @dims!

/lgtm
/approve
/cc @kubernetes/sig-release-admins

**Comment by dims** [comment]
google groups creation - DONE
```
2019/07/09 17:58:30 Trying to create group: k8s-infra-staging-release-test@kubernetes.io
2019/07/09 17:58:30 > Successfully created group k8s-infra-staging-release-test@kubernetes.io
2019/07/09 17:58:31 > Successfully updated group settings for k8s-infra-staging-release-test@kubernetes.io to allow external members and other security settings
2019/07/09 17:58:33 Added davanum@gmail.com to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:33 Added ihor@cncf.io to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:34 Added spiffxp@google.com to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:35 Added thockin@google.com to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:36 Added stephen@agst.us to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:37 Added caselim@gmail.com to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:38 Added tpepper@gmail.com to k8s-infra-staging-release-test@kubernetes.io as a MEMBER
2019/07/09 17:58:39 Removing Stephen@agst.us from k8s-infra-staging-release-test@kubernetes.io as a MEMBER
```

**Comment by dims** [comment]
staging storage resources - DONE

```
[dims@dims-a01 18:03] ~/go/src/k8s.io/k8s.io ⟩ ./infra/gcp/ensure-staging-storage.sh release-test
release-test
Ensuring project exists: k8s-staging-release-test
Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-staging-release-test].
Waiting for [operations/cp.7416472484910200740] to finish...done.
billingAccountName: billingAccounts/018801-93540E-22A20E
billingEnabled: true
name: projects/k8s-staging-release-test/billingInfo
projectId: k8s-staging-release-test
Enabling the container registry API
Operation "operations/acf.05ed1eb2-cf9d-423b-b7f2-f1657bea9ad5" finished successfully.
Ensuring the registry exists and is readable
Using default tag: latest
latest: Pulling from pause
Digest: sha256:a78c2d6208eff9b672de43f880093100050983047b7b0afe0217d3656e1b0d5f
Status: Image is up to date for k8s.gcr.io/pause:latest
The push refers to repository [gcr.io/k8s-staging-release-test/ceci-nest-pas-une-image]
5f70bf18a086: Layer already exists
e16a89738269: Pushed
latest: digest: sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74 size: 938
Digests:
- gcr.io/k8s-staging-release-test/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- gcr.io/k8s-staging-release-test/ceci-nest-pas-une-image:latest
Deleted [gcr.io/k8s-staging-release-test/ceci-nest-pas-une-image:latest].
Deleted [gcr.io/k8s-staging-release-test/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Enabling Bucket Policy Only for gs://artifacts.k8s-staging-release-test.appspot.com...
Empowering GCR admins
Updated IAM policy for project [k8s-staging-release-test].
bindings:
- members:
  - serviceAccount:service-634027639865@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNRr5SpDs=
version: 1
Empowering k8s-infra-staging-release-test@kubernetes.io to GCR
Enabling the GCS API
Operation "operations/acf.a2b2fd52-53a9-417c-b27c-95f37919463a" finished successfully.
Ensuring the bucket exists and is world readable
Creating gs://k8s-staging-release-test/...
Enabling Bucket Policy Only for gs://k8s-staging-release-test...
Ensuring the bucket has retention of 30d
Setting Retention Policy on gs://k8s-staging-release-test/...
Ensuring the bucket has auto-deletion of 30 days
Setting lifecycle configuration on gs://k8s-staging-release-test/...
Empowering GCS admins
Updated IAM policy for project [k8s-staging-release-test].
bindings:
- members:
  - serviceAccount:service-634027639865@containerregistry.iam.gserviceaccount.com
  role: roles/editor
- members:
  - user:davanum@gmail.com
  role: roles/owner
- members:
  - group:k8s-infra-artifact-admins@kubernetes.io
  role: roles/viewer
etag: BwWNRr_QZTc=
version: 1
Empowering k8s-infra-staging-release-test@kubernetes.io to GCS
Done
```

**Comment by dims** [comment]
prod storage resources - DONE

```
Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/k8s-release-test-prod].
Waiting for [operations/cp.6232341688357062983] to finish...done.
Operation "operations/acf.3d992aa0-6e0c-45ba-8692-5ebc53b367f4" finished successfully.
Operation "operations/acf.6910cf7d-474a-4f9e-81e5-65f5dcdcef81" finished successfully.
Digests:
- us.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- us.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image:latest
Deleted [us.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image:latest].
Deleted [us.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Digests:
- eu.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- eu.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image:latest
Deleted [eu.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image:latest].
Deleted [eu.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Digests:
- asia.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74
  Associated tags:
 - latest
Tags:
- asia.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image:latest
Deleted [asia.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image:latest].
Deleted [asia.gcr.io/k8s-release-test-prod/ceci-nest-pas-une-image@sha256:ec3ca3ee90e4dafde96c83232b30f17b5e8992ff35479d0661b8f4ff2f21bf74].
Updated IAM policy for project [k8s-release-test-prod].
Updated IAM policy for project [k8s-release-test-prod].
Updated IAM policy for project [k8s-release-test-prod].
Created service account [k8s-infra-gcr-promoter].
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://us.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://eu.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://asia.artifacts.k8s-cip-test-prod.appspot.com/
No changes made to gs://k8s-artifacts-prod/
Updated IAM policy for project [k8s-artifacts-prod].
No changes made to gs://k8s-artifacts-prod/
No changes made to gs://k8s-artifacts-prod/
Setting website configuration on gs://k8s-artifacts-prod/...
Building synchronization state...
Starting synchronization...
Copying file://infra/gcp/static/prod-storage/index.html [Content-Type=text/html]...
- [1 files][   55.0 B/   55.0 B]
Operation completed over 1 objects/55.0 B.
```

**Pull request merged**
