### PR TITLE
Add staging for kubernetes/website docker container images

### PR DESCRIPTION
**Pull request by ameukam**
Closes https://github.com/kubernetes/k8s.io/issues/1033.

Ref: https://github.com/kubernetes/website/issues/22515

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
/assign @spiffxp @listx 
cc @kubernetes/sig-docs-leads

**Comment by jimangel** [comment]
/lgtm

Thanks @ameukam !

**Review by spiffxp — APPROVED** [review]
/aprove
/lgtm

**Comment by spiffxp** [comment]
Ran `./infra/gcp/ensure-staging-storage.sh sig-docs`

**Pull request merged**
