### PR TITLE
AWS: update the timeout EKS update for the kOps build cluster.

### PR DESCRIPTION
**Pull request by ameukam**

### CODE REVIEW

**Comment by ameukam** [comment]
@bryantbiggs There is no change in the `terraform plan`.  I wonder if the module ignore this change. 🤔

**Comment by bryantbiggs** [comment]
no - we don't have any ignore on the timeouts, those should always be respected

**Comment by ameukam** [comment]
I can't see why this is ignored. I can see in the debug logs the ref of the variables:

```
1009   2024-08-21T19:55:43.871+0200 [DEBUG] ReferenceTransformer: "module.eks.var.cluster_name (expand)" references: [local.cluster_name (expand)]
1010   2024-08-21T19:55:43.871+0200 [DEBUG] ReferenceTransformer: "module.eks.var.cluster_timeouts (expand)" references: []
```

but no changes:
```bash
module.eks.aws_security_group_rule.node["ingress_cluster_8443_webhook"]: Refreshing state... [id=sgrule-2721142640]
module.eks.aws_security_group_rule.cluster["ingress_nodes_443"]: Refreshing state... [id=sgrule-4148544704]
module.eks.aws_eks_cluster.this[0]: Refreshing state... [id=k8s-infra-kops-prow-build]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

Not sure how to debug this.

**Pull request closed without merging**
