### PR TITLE
rename service-apis to gateway-api

### PR DESCRIPTION
**Pull request by hbagdi**

### CODE REVIEW

**Comment by robscott** [comment]
Thanks!

/lgtm
/assign @spiffxp

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

The groups job seems to be failing for other reasons right now, so I may not be able to deploy this until that's resolved.  I'll report back on this PR once done

**Comment by spiffxp** [comment]
Ran 
- `infra/gcp/ensure-staging-storage.sh gateway-api` to setup the new project
- `gcloud projects delete k8s-staging-service-apis` to delete the old project (after confirming no container images hosted inside)

**Comment by hbagdi** [comment]
Thanks, @spiffxp!
Now, onto the last piece of this puzzle: https://github.com/kubernetes/test-infra/pull/21881 : )

**Pull request merged**
