### PR TITLE
Allow akhilerm to access publishing-bot instance

### PR DESCRIPTION
**Pull request by nikhita**
Akhil is a publishing-bot reviewer and has created multiple non-trivial and complicated PRs to the bot. His PRs demonstrate that he understands how the bot works and I'm confident that he can help with fixing any bot failures.

Ref: https://github.com/kubernetes/publishing-bot/pulls?q=+is%3Apr+involves%3Aakhilerm+

/assign @dims 
cc @akhilerm

### CODE REVIEW

**Comment by nikhita** [comment]
/hold

for lgtm from dims

**Comment by nikhita** [comment]
cc @kubernetes/release-engineering

**Review by saschagrunert — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

thanks!!

**Review by xmudrii — APPROVED** [review]
Thanks, @akhilerm!
/lgtm

**Review by palnabarun — APPROVED** [review]
Thank you @akhilerm for all your effort towards the publishing bot and for volunteering to maintain the publishing bot! ❤️ 

/lgtm
/approve

**Pull request merged**
