### PR TITLE
Promoted pause image version 'tag: 3.6'

### PR DESCRIPTION
**Pull request by nick5616**
### This PR promotes the pause image to version 3.6.

**Staging image details:** https://console.cloud.google.com/gcr/images/k8s-staging-kubernetes/GLOBAL/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db/details?tag=3.6

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
