### PR TITLE
Add BigDarkClown@ to k8s-staging-autoscaling owners, remove inactive members

### PR DESCRIPTION
**Pull request by BigDarkClown**

### CODE REVIEW

**Comment by gjtempleton** [comment]
Same recommendation as on [the other PR ](https://github.com/kubernetes/k8s.io/pull/5604#issuecomment-1647888130) around moving some of the no longer active members of the SIG to emeritus approver status.

**Comment by BigDarkClown** [comment]
SGTM, done.

**Comment by gjtempleton** [comment]
Thanks.
/lgtm
/approve

**Comment by BigDarkClown** [comment]
This is a frozen registry, opened new PR with correct file changed.

**Pull request closed without merging**
