### PR TITLE
Image promotion for etcd 3.5.13-0

### PR DESCRIPTION
**Pull request by liangyuanpeng**
continue https://github.com/kubernetes/kubernetes/pull/124026

```shell
k8s.io$ docker inspect gcr.io/k8s-staging-etcd/etcd:3.5.13-0
[
    {
        "Id": "sha256:1b2ba9f3d2043b4c8010fdb3dbc98b9ccc684fdf28f589985d35db06e8252fad",
        "RepoTags": [
            "gcr.io/k8s-staging-etcd/etcd:3.5.13-0"
        ],
        "RepoDigests": [
            "gcr.io/k8s-staging-etcd/etcd@sha256:f8b7ad2d8552d815ad85b3df088ca1a2cbc079ad216630ded0057cc79c2d257f"
        ],
```

/assign @dims @saschagrunert

### CODE REVIEW

**Comment by serathius** [comment]
cc @kubernetes/release-engineering

**Review by saschagrunert — APPROVED** [review]
Thanks!

**Pull request merged**
