### PR TITLE
Promote descheduler to 1.20 (with multi-arch images)

### PR DESCRIPTION
**Pull request by damemi**
Previous 1.19 image: https://github.com/kubernetes/k8s.io/pull/1201

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @seanmalloy @ingvagabund

**Review by soltysh — APPROVED** [review]
/lgtm
/hold
for final look from @seanmalloy

**Review by seanmalloy — APPROVED** [review]
LGTM

**Pull request merged**
