### PR TITLE
Add known issues section to eks-prow-build cluster readme

### PR DESCRIPTION
**Pull request by koksay**
Adding a "Known issues" section to AWS eks-prow-build cluster after this incident: https://kubernetes.slack.com/archives/CCK68P2Q2/p1720637247581549

### CODE REVIEW

**Comment by koksay** [comment]
CC: @xmudrii

**Comment by ameukam** [comment]
Thank you!

/lgtm
/approve
/hold

if folx want to add more.
cc @dims @BenTheElder

**Comment by BenTheElder** [comment]
/lgtm
/approve
/hold cancel
thank you!!

**Pull request merged**
