### PR TITLE
Fix sha256 cut and paste mistake.

### PR DESCRIPTION
**Pull request by jkh52**
v0.1.1 had agent and server swapped.
v0.0.36 had server value twice.

Test:

```
docker pull gcr.io/k8s-staging-kas-network-proxy/proxy-agent@sha256:939c42e815e6b6af3181f074652c0d18fe429fcee9b49c1392aee7e92887cfef
docker pull gcr.io/k8s-staging-kas-network-proxy/proxy-agent@sha256:1e69b140a018d33e7568ff1e2ac66eec13b2d698893aff560f4732c7084adabe
docker pull gcr.io/k8s-staging-kas-network-proxy/proxy-server@sha256:28dd2aeadb4d96cf54f4b3461925e1e1ea2e69e77ff841f68d43bbebff6f8d15
docker pull gcr.io/k8s-staging-kas-network-proxy/proxy-server@sha256:b1389e7014425a1752aac55f5043ef4c52edaef0e223bf4d48ed1324e298087c
```

### CODE REVIEW

**Comment by dims** [comment]
Hmm, if the original sha's were present, the tag would have already been created. which means the new intended updates won't work

**Comment by ameukam** [comment]
/hold

Tag mutation is not supported for images already promoted.

**Comment by jkh52** [comment]
> Tag mutation is not supported for images already promoted.

To be clear only 1 of 4 seems successfully promoted. This fixes the other 3.

**Comment by jkh52** [comment]
> if the original sha's were present, the tag would have already been created. which means the new intended updates won't work

I think the explanation is that the sha256 were for mismatched image names, so not present.

**Comment by dims** [comment]
> Not published:
> registry.k8s.io/kas-network-proxy/proxy-agent:v0.0.36
> registry.k8s.io/kas-network-proxy/proxy-server:v0.1.1
> registry.k8s.io/kas-network-proxy/proxy-agent:v0.1.1

As long as we are going to publish new tags and not try to rewrite we are good.

/hold cancel

**Comment by jkh52** [comment]
> As long as we are going to publish new tags and not try to rewrite we are good.

Yes. for posterity, the prior state:

```
$ docker pull registry.k8s.io/kas-network-proxy/proxy-server:v0.0.36
v0.0.36: Pulling from kas-network-proxy/proxy-server
Digest: sha256:28dd2aeadb4d96cf54f4b3461925e1e1ea2e69e77ff841f68d43bbebff6f8d15
Status: Image is up to date for registry.k8s.io/kas-network-proxy/proxy-server:v0.0.36
registry.k8s.io/kas-network-proxy/proxy-server:v0.0.36

$ docker pull registry.k8s.io/kas-network-proxy/proxy-agent:v0.0.36
Error response from daemon: manifest for registry.k8s.io/kas-network-proxy/proxy-agent:v0.0.36 not found: manifest unknown: Failed to fetch "v0.0.36"

$ docker pull registry.k8s.io/kas-network-proxy/proxy-server:v0.1.1
Error response from daemon: manifest for registry.k8s.io/kas-network-proxy/proxy-server:v0.1.1 not found: manifest unknown: Failed to fetch "v0.1.1"

$ docker pull registry.k8s.io/kas-network-proxy/proxy-agent:v0.1.1
Error response from daemon: manifest for registry.k8s.io/kas-network-proxy/proxy-agent:v0.1.1 not found: manifest unknown: Failed to fetch "v0.1.1"

```

**Pull request merged**
