### PR TITLE
Image promotion for dns 1.23.0

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Image promotion for dns 1.23.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork liangyuanpeng --interactive --project dns --tag 1.23.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
PR https://github.com/kubernetes/k8s.io/pull/6500 was created manually by me after referring to https://github.com/kubernetes/k8s.io/pull/6088. It only contains 24 necessary images, and there is no new and complete platform architecture image.

This PR is create from tools of `kpromo`, It generates a more complete mirror list, more   new architectural platform, like ` k8s-dns-dnsmasq-amd64` , `k8s-dns-dnsmasq-arm` , `k8s-dns-dnsmasq-arm64`, etc...

/assign @aojea @kl52752

**Comment by aojea** [comment]
why so much changes and the new architectures?

can we add only just the new images version to the existing ones?

**Comment by liangyuanpeng** [comment]
> why so much changes and the new architectures?

Most are changes caused by sort, like:

```diff
"sha256:d662183a2351b8f63a5e8090896361377f20e5e45c25172936929eb12b87002b": ["1.22.1"]
-"sha256:3deb59400efae07f276589031746b195ce2574f2d3b1597ab7311b8b4d1eb8a0": ["1.22.2"]
"sha256:8f4b801fcd7a21aecea42e0880109ebb292be3df3ef11d433b82c1470f88df25": ["1.22.19"]
+"sha256:3deb59400efae07f276589031746b195ce2574f2d3b1597ab7311b8b4d1eb8a0": ["1.22.2"]
```

For the change of new architectures, i'm not sure, I have check the k8s-dns-dnsmasq-arm64 and it's exist in `k8s.io` and not exist in `registry.k8s.io`, I think it is intentional.

> can we add only just the new images version to the existing ones?

please free feel to close this and jump to https://github.com/kubernetes/k8s.io/pull/6500  :)

**Comment by liangyuanpeng** [comment]
> can we add only just the new images version to the existing ones?

Closing... and continue with https://github.com/kubernetes/k8s.io/pull/6500

**Pull request closed without merging**
