### PR TITLE
Promote NFD-Operator v0.4.1

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
```bash
[eduardo@fedora k8s.io]$ skopeo inspect docker://gcr.io/k8s-staging-nfd/node-feature-discovery-operator:v0.4.1-minimal |grep Digest
    "Digest": "sha256:5ee0f6028de8fcc5ba6f131fc848c992e57e871a785471682217e297a3cdbbb3",
[eduardo@fedora k8s.io]$ skopeo inspect docker://gcr.io/k8s-staging-nfd/node-feature-discovery-operator:v0.4.1 |grep Digest
    "Digest": "sha256:2f23452ae8bb59b3fedca1b5298cb0bd3445dec589f466b599552a35ac4779fd",
```
/unhold

**Review by marquiz — APPROVED** [review]
/lgtm

**Pull request merged**
