### PR TITLE
releng: Image promotion for kubernetes v1.27.0-alpha.3

### PR DESCRIPTION
**Pull request by gracenng**
Image promotion for kubernetes v1.27.0-alpha.3
This is an automated PR generated from `kpromo`
```
kpromo pr --fork gracenng --interactive --tag v1.27.0-alpha.3
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by cici37** [comment]
@kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
Thanks
/approve

**Pull request merged**
