### PR TITLE
Add rbac and namespace for triageparty cli

### PR DESCRIPTION
**Pull request by eddiezane**
This PR adds rbac and namespace configs for sig-cli triage party.

ref: #2460 

/cc @soltysh @KnVerey 
/assign @ameukam

### CODE REVIEW

**Comment by eddiezane** [comment]
/assign @spiffxp

For groups approval.

**Comment by ameukam** [comment]
@eddiezane Also need to add the group to https://github.com/kubernetes/k8s.io/blob/main/groups/restrictions.yaml#L11. 
(The documentation need to be updated about this)

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
I'm away from keyboard so someone else remove /hold when ready to deploy

**Comment by eddiezane** [comment]
> @eddiezane Also need to add the group to https://github.com/kubernetes/k8s.io/blob/main/groups/restrictions.yaml#L11.
> (The documentation need to be updated about this)

Opened https://github.com/kubernetes/k8s.io/pull/2468

**Comment by ameukam** [comment]
Namespace created: 

```
Create namespace: triageparty-cli 
namespace/triageparty-cli created
Apply namespace-user role: triageparty-cli 
role.rbac.authorization.k8s.io/namespace-user created
Apply namespace-user role binding: triageparty-cli 
rolebinding.rbac.authorization.k8s.io/namespace-user created
Ensure only one role binding in namespace: triageparty-cli is present 
```

```
kubectl get serviceaccount -n triageparty-cli 
NAME      SECRETS   AGE
default   1         3m50s
```

**Comment by eddiezane** [comment]
I don't think the groups were created yet?

```
$ gcloud container clusters get-credentials aaa --project kubernetes-public --region=us-central1
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission(s) for "projects/kubernetes-public/locations/us-central1/clusters/aaa".
```

**Comment by spiffxp** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-k8sio-groups/1423056456134955008 - the postsubmit for this PR failed

But I suspect the most recent periodic reconciled you in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-k8sio-groups/1423611869041528832

**Comment by eddiezane** [comment]
Ah yes looks all good now ty!

**Pull request merged**
