### PR TITLE
AWS: Fix name for the prod account of artifacts.k8s.io

### PR DESCRIPTION
**Pull request by ameukam**
- Fix account name
- set provider for the CUR buckets.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
cc @dims @justinsb

**Comment by justinsb** [comment]
Thanks for cleaning this up!

/lgtm

**Comment by justinsb** [comment]
/hold

In case you want to hold it

**Pull request merged**
