### PR TITLE
Promote v0.1.10 image

### PR DESCRIPTION
**Pull request by SanikaGawhane**
/cc @codenrhoden

### CODE REVIEW

**Comment by spiffxp** [comment]
... why _did_ k8s-infra-ci-robot merge this? @ameukam I didn't think we had tide setup on k8s-infra-prow in a configuration that would allow it to merge anything?

**Comment by ameukam** [comment]
> ... why _did_ k8s-infra-ci-robot merge this? @ameukam I didn't think we had tide setup on k8s-infra-prow in a configuration that would allow it to merge anything?

I think it's : https://github.com/kubernetes/k8s.io/pull/2789/files I'll revert it.

**Comment by codenrhoden** [comment]
@spiffxp Does this have to do with the `label-that-does-not-exist` thing I saw from tide before I approved? I was wondering what that was...

Hopefully everything is okay here -- the request it's self was routing and we really did want the image promoted. I wasn't aware of any blocked-out periods or anything. Did I miss something important?

**Pull request merged**
