### PR TITLE
ExternalDNS: promote v0.7.0

### PR DESCRIPTION
**Pull request by linki**
Promotes a new image to the production registry.

### CODE REVIEW

**Comment by bartsmykla** [comment]
Hi @linki 
Are you sure the checksum is correct? https://console.cloud.google.com/gcr/images/k8s-staging-external-dns/GLOBAL/external-dns?gcrImageListsize=30 Shows different sha for version 0.7

**Comment by linki** [comment]
@bartsmykla @njuettner Absolutely, thanks for double-checking!

**Pull request merged**
