### PR TITLE
add in eu-west-1 AWS region

### PR DESCRIPTION
**Pull request by jaypipes**
Signed-off-by: Jay Pipes <jaypipes@gmail.com>

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
@jaypipes, thank you for the PR!

Just missing one thing, will need to add to the main.tf like this
https://github.com/kubernetes/k8s.io/blob/892884dc6205118740f156bd4c4a815f5bf9c5b8/infra/aws/terraform/registry.k8s.io/main.tf#L76-L85

**Comment by jaypipes** [comment]
> @jaypipes, thank you for the PR!
> 
> Just missing one thing, will need to add to the main.tf like this
> 
> https://github.com/kubernetes/k8s.io/blob/892884dc6205118740f156bd4c4a815f5bf9c5b8/infra/aws/terraform/registry.k8s.io/main.tf#L76-L85

@BobyMCbobs done!

**Comment by ameukam** [comment]
> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> 
> **The list of commits with invalid commit messages**:
> 
>     * [dde7705](https://github.com/kubernetes/k8s.io/commits/dde77050f40b27beffa6296239d61a50ff73b49b) add in eu-west-1 AWS region

@jaypipes You can't have `#` in your commit message. You can drop the link of the comment.

**Comment by jaypipes** [comment]
> > [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> > **The list of commits with invalid commit messages**:
> > ```
> > * [dde7705](https://github.com/kubernetes/k8s.io/commits/dde77050f40b27beffa6296239d61a50ff73b49b) add in eu-west-1 AWS region
> > ```
> 
> @jaypipes You can't have `#` in your commit message. You can drop the link of the comment.

@ameukam OK, done... not sure why we can't link to issues ot GH users in commit messages, but OK :)

**Pull request merged**
