### PR TITLE
k8s.gcr.io/images/k8s-staging-kube-state-metrics/images.yaml: promote 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by mrueg**
Promote https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/GLOBAL/kube-state-metrics@sha256:95e06a9e1eb075873adefcf1b3646997e4800fee2653a1514fa35531245a5aeb/details?tab=info

/assign @lilic 
/assign @tariq1890 
/assign @brancz

### CODE REVIEW

**Comment by tariq1890** [comment]
Should we not add the docker shas for the other CPU architectures? Otherwise, this will not be stored as a multi-arch image in GCR, yes?

**Comment by lilic** [comment]
As Tariq said, you should bump all the things. I use a binary for this that I found in k8s org called `cip-mm` and run it by doing
```
cip-mm --base_dir=/Users/lili/go/src//k8s.io/k8s.io/k8s.gcr.io --staging_repo=gcr.io/k8s-staging-kube-state-metrics --filter_tag='v2.0.0-rc.1'
```

Which gives me this diff:
```
--- a/k8s.gcr.io/images/k8s-staging-kube-state-metrics/images.yaml
+++ b/k8s.gcr.io/images/k8s-staging-kube-state-metrics/images.yaml
@@ -4,6 +4,7 @@
     "sha256:45cc40cf7eacd83418fbf55df8c4c107b70c226ed6e5438008606654d8fa8252": ["v2.0.0-alpha.3"]
     "sha256:47d3a12d9da6699a9d95df8aaff235305229ef08203fae3fc1f1d47b2a409f89": ["v1.9.8"]
     "sha256:73867f9c84ef0ffb061b1bcb950b1947b1d60cb842ede63c0321a94b8cc6b6c8": ["2.0.0-alpha"]
+    "sha256:95e06a9e1eb075873adefcf1b3646997e4800fee2653a1514fa35531245a5aeb": ["v2.0.0-rc.1"]
     "sha256:aa84c31d4ab935acbd7debdc23a18e87dc344727290d8313f0d7d14b96293482": ["v2.0.0-alpha.2"]
     "sha256:e3b9095a56b7d75b868c134089326566c545aa086360713647b1675c1a1738f3": ["2.0.0-alpha.1"]
     "sha256:ed886c793c35596c64e45d0bf34dd345bf42caaf246a7e55e160be36bf70c085": ["v2.0.0-rc.0"]
@@ -14,12 +15,14 @@
     "sha256:66625016a7bf75933a3c678cfbb85eb15ab60b78c85e61b9e82b8f5d70d46a56": ["v2.0.0-rc.0"]
     "sha256:73867f9c84ef0ffb061b1bcb950b1947b1d60cb842ede63c0321a94b8cc6b6c8": ["2.0.0-alpha"]
     "sha256:9f19f21c36c8febc07081ffb4d35681337d820093fbcd17dfd441c5c6bbde2dd": ["v2.0.0-beta"]
+    "sha256:a13d8bb0013420d1dab20bddf8d64979702f010976958519449ee312218b3e68": ["v2.0.0-rc.1"]
     "sha256:d739b81fa5285895093a86596ac5dfadced4a92114483c0c140673746c1ed0ff": ["v1.9.8"]
     "sha256:e3b9095a56b7d75b868c134089326566c545aa086360713647b1675c1a1738f3": ["2.0.0-alpha.1"]
 - name: kube-state-metrics-arm
   dmap:
     "sha256:04a9984452422c2ef594135a0f7ff7060049deab41069e483c753267cf0ec99d": ["v2.0.0-beta"]
     "sha256:255894e01b3042564d8b5968abbc027dc7be816ba14c7d7426bd3ce54131219c": ["2.0.0-alpha"]
+    "sha256:26f2907773ba9ba270539a27da7973b6e08d4f84008076543e30feefab8a14fe": ["v2.0.0-rc.1"]
     "sha256:49fc73f35d02706f62161062f0905130bccec1c5188f34f70d3bcb068d93a1d5": ["v2.0.0-alpha.3"]
     "sha256:6f8a6c406ae8bab657f87338527afca0a35dcf43d6336e929c1d5c18a35dc7dc": ["2.0.0-alpha.1"]
     "sha256:8a461442e11fe633ede5886d7cbac9a0de78a79edc8c626dfb4e8dad4b7f754b": ["v2.0.0-rc.0"]
@@ -30,12 +33,14 @@
     "sha256:354b91c8a6c49d5ef265f0feed4d94da69a4e177789c92a667929bcc3489aef6": ["v2.0.0-beta"]
     "sha256:501bde1baf4931c46a401ac52d4baa00b35ecfbba5ba52b50b5591f9bc003158": ["v2.0.0-alpha.3"]
     "sha256:5dcbaec3e9fa314f34eb61083e293b0d12a8ca44181eb177280187b838d29460": ["2.0.0-alpha.1"]
+    "sha256:7b14be924dcdb14bf2a55674b7f9c42fdf3fea507e2608017df91020d4954312": ["v2.0.0-rc.1"]
     "sha256:82eaf406027e70b80af977c0128539f00845e6c54996a50d422041f3d5a12fc2": ["v1.9.8"]
     "sha256:8366f2b04f28621fea9c072004a669dfc7b97c14bd91934b341a8f014d1acf0f": ["v2.0.0-rc.0"]
     "sha256:b53b10d9415a0b8ff2ad960707a1268b4d0917f704b65e4275d5832792a34b12": ["v2.0.0-alpha.2"]
     "sha256:f18e7fff7b327511ca6ccd85b11b5cc14df9d99307baaab85ec7b4d18ca13a61": ["2.0.0-alpha"]
 - name: kube-state-metrics-ppc64le
   dmap:
+    "sha256:03effc1512436ac598c8eb2e168e996103d6d083e0656023b72a35aec89ed7f9": ["v2.0.0-rc.1"]
     "sha256:2f3c1173a7a9924ec1d358d5a5ca2715b4616cdfdb9d08afc4e6f6ef1faf2670": ["v2.0.0-rc.0"]
     "sha256:53a9f175e565896f17033fceddf3895fe3958469de4e5865f950685ad59baca7": ["v2.0.0-alpha.2"]
     "sha256:66509fb7483152884aef09d1f717580bc399f09c92b005b734dcd95aabcbe980": ["v1.9.8"]
@@ -47,4 +52,5 @@
     "sha256:ae6e276f7094c0f1b66d941ac0f1dcf7fd48e7301c291425e2f99fe88e2148f0": ["v2.0.0-beta"]
     "sha256:b1199f0ad44b72b6bf9a77726eba0e808268fec73a68c9462c7f8ef53f00d6c9": ["v1.9.8"]
     "sha256:cb720387f8ef254612552d0f8c7113a066ced4ef3a1ebc945746e8a2f15fca31": ["v2.0.0-alpha.3"]
+    "sha256:f4c63300bb699754d1209aab54c510d8054ae0e2c25d60b23db0e3af266cd334": ["v2.0.0-rc.1"]
     "sha256:f8c09f6cfbcdcac693811a04b4aa3e61987fa08a1c69083da9fbf3fbe442f4cb": ["v2.0.0-rc.0"]
```

**Comment by lilic** [comment]
/lgtm

Thanks, will follow up with the rest in a separate PR so we don't block our users from being able to use the latest release. Thank you! 🎉

**Pull request merged**
