### PR TITLE
Add area/ labels to OWNERS files

### PR DESCRIPTION
**Pull request by spiffxp**
I'd like to see more of our PRs get auto-labeled based on what they're touching

### CODE REVIEW

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/pull/17149 to ensure we're not using any manually managed labels. If we want to rename down the road we can

**Comment by justaugustus** [comment]
@spiffxp -- Can you add `area/release-eng` in too while you're here?
I keep trying to label with that and the bots yell at me.

**Comment by bartsmykla** [comment]
It looks good to me. I'm holding because I'm not sure if @justaugustus wants to have changes in this PR or is the question related more to https://github.com/kubernetes/test-infra/pull/17149
@justaugustus is there any OWNER file in this repository you would like to add the label or the question was more to the other PR?
@justaugustus I leave unholding to you
/lgtm
/hold

**Comment by justaugustus** [comment]
@bartsmykla -- hehe, thanks for checking. I did mean to comment on the test-infra PR instead. :)
/lgtm
/hold cancel

**Pull request merged**
