### PR TITLE
Azure: Setup Prow build cluster

### PR DESCRIPTION
**Pull request by ameukam**
Setup an AKS cluster where we can run ProwJobs similarly to the GKE
cluster `k8s-infra-prow-build`.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

### CODE REVIEW

**Comment by ameukam** [comment]
We currently can't use the official AKS module due to the provider incompatibility:

https://github.com/Azure/terraform-azurerm-aks/blob/ddb919ad53703c3ba24d5a4c652fe55dbe422eeb/versions.tf#L9-L12

**Comment by ameukam** [comment]
@upodroid I did an attempt with https://github.com/Azure/terraform-azurerm-aks/:

```bash
terraform init
Initializing the backend...
Initializing modules...
Downloading registry.terraform.io/Azure/aks/azurerm 9.1.0 for aks...
- aks in .terraform/modules/aks
Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Finding azure/azapi versions matching ">= 1.4.0, < 2.0.0"...
- Reusing previous version of hashicorp/random from the dependency lock file
- Finding hashicorp/null versions matching ">= 3.0.0"...
- Finding hashicorp/tls versions matching ">= 3.1.0"...
- Installing azure/azapi v1.15.0...
- Installed azure/azapi v1.15.0 (signed by a HashiCorp partner, key ID 6F0B91BDE98478CF)
- Using previously-installed hashicorp/random v3.6.3
- Installing hashicorp/null v3.2.3...
- Installed hashicorp/null v3.2.3 (signed by HashiCorp)
- Installing hashicorp/tls v4.0.6...
- Installed hashicorp/tls v4.0.6 (signed by HashiCorp)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azurerm: locked provider registry.terraform.io/hashicorp/azurerm 4.7.0 does not match configured version constraint >= 3.106.1, ~> 4.0, < 4.0.0; must use terraform init -upgrade to allow selection of new versions
```

**Comment by upodroid** [comment]
The plugin supports less than v4 because v4 is like 2 months old.

https://github.com/Azure/terraform-azurerm-aks/?tab=readme-ov-file#requirements

Using the latest version of v3.x should solve it

**Comment by ameukam** [comment]
@upodroid switched to terraform modules. PTAL.

**Review by upodroid — APPROVED** [review]
LGTM

/hold cancel after apply

**Comment by ameukam** [comment]
I have a weird bug while running `terraform plan`:

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+/- create replacement and then destroy

Terraform will perform the following actions:

  # module.prow_build.azurerm_kubernetes_cluster_node_pool.node_pool_create_before_destroy["pool1"] must be replaced
+/- resource "azurerm_kubernetes_cluster_node_pool" "node_pool_create_before_destroy" {
      - custom_ca_trust_enabled       = false -> null
      - enable_host_encryption        = false -> null
      - enable_node_public_ip         = false -> null
      - fips_enabled                  = false -> null
      ~ id                            = "/subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/rg-k8s-infra-prow-build/providers/Microsoft.ContainerService/managedClusters/k8s-infra-aks/agentPools/pool11ca3" -> (known after apply)
      ~ max_pods                      = 250 -> (known after apply)
      ~ name                          = "pool11ca3" -> (known after apply)
      ~ node_count                    = 50 -> (known after apply)
      ~ node_labels                   = {} -> (known after apply)
      - node_taints                   = [] -> null
      ~ orchestrator_version          = "1.30" -> (known after apply)
      - tags                          = {} -> null
      - vnet_subnet_id                = "/subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/rg-k8s-infra-prow-build/providers/Microsoft.Network/virtualNetworks/vnet-rg-k8s-infra-prow-build/subnets/snet-rg-k8s-infra-prow-build" -> null # forces replacement
      - zones                         = [] -> null
        # (22 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Pull request merged**
