### PR TITLE
Add mailing list for WG k8s Batch

### PR DESCRIPTION
**Pull request by alculquicondor**
Based on https://github.com/kubernetes/community/tree/master/wg-batch

Ref kubernetes/community#6263

### CODE REVIEW

**Comment by alculquicondor** [comment]
@ahg-g @endocrimes @soltysh @Huang-Wei @swatisehgal can you please confirm your emails?

**Comment by alculquicondor** [comment]
/hold
for organizers to confirm their email

**Comment by swatisehgal** [comment]
> @ahg-g @endocrimes @soltysh @Huang-Wei @swatisehgal can you please confirm your emails?

Thanks @alculquicondor for creating this PR. Please use `swati.tcd@gmail.com` as my email address.

**Comment by endocrimes** [comment]
Thanks! - `lancashiredanielle@gmail.com` is best for anything tied to google IAM

**Review by soltysh — APPROVED** [review]
> @ahg-g @endocrimes @soltysh @Huang-Wei @swatisehgal can you please confirm your emails?

looks good, thx!

**Pull request merged**
