### PR TITLE
Promote CoreDNS v1.7.0

### PR DESCRIPTION
**Pull request by rajansandeep**

### CODE REVIEW

**Comment by stp-ip** [comment]
Note: Vanity Domain Flip hasn't happened yet (tracked in https://github.com/kubernetes/release/issues/270) and therefore without the legacy way this won't show up on k8s.gcr.io for a few more weeks most likely. The staging image should work so.

**Comment by rajansandeep** [comment]
@stp-ip @johnbelamaric In that case, can CoreDNS 1.7.0 be promoted to k8s.gcr.io manually?
We plan to include it for k8s 1.19

**Comment by stp-ip** [comment]
@thockin can you push v1.7.0 the legacy way. Already in the staging repo.
Reference to the last "manual" push: https://github.com/kubernetes/kubernetes/issues/88343

**Comment by thockin** [comment]
I don't see this tag in the new repo either - does it actually exist?

**Comment by thockin** [comment]
e.g. `gcr.io/k8s-staging-coredns/coredns:v1.7.0` and `us.gcr.io/k8s-artifacts-prod/coredns/coredns:v1.7.0` should exist.

@listx

**Comment by listx** [comment]
I see in the logs for the promoter that the image (exact sha 73ca82b4ce829766d4f1f10947c3a338888f876fbed0540dc849c89ff256e90c asked-for in the manifest) was not found in the staging repo:

```
E0629 15:33:03.177923      12 inventory.go:482] edge {{gcr.io/k8s-staging-coredns   true} {coredns v1.7.0} sha256:73ca82b4ce829766d4f1f10947c3a338888f876fbed0540dc849c89ff256e90c {asia.gcr.io/k8s-artifacts-prod/coredns k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com  false} {coredns v1.7.0}}: skipping gcr.io/k8s-staging-coredns/  coredns@sha256:73ca82b4ce829766d4f1f10947c3a338888f876fbed0540dc849c89ff256e90c because it is _LOST_ (can't find it in src registry!)
```

**Comment by thockin** [comment]
Sandeep, can you please push this to the staging repo, so promoter can
handle it?

**Comment by rajansandeep** [comment]
The image is now available, http://gcr.io/k8s-staging-coredns/coredns:1.7.0
thank you @stp-ip for pushing it.

**Comment by stp-ip** [comment]
sidenote: on the tag
"1.7.0" is used in staging and the legacy process
"v1.7.0" is used with the promoted images to make them more consistent with the other promoted images.

**Pull request merged**
