### PR TITLE
Added go.k8s.io/redirects redirection

### PR DESCRIPTION
**Pull request by bartsmykla**
Closes https://github.com/kubernetes/k8s.io/issues/340

go.k8s.io/redirects will point to the list of recirections inside README

Signed-off-by: Bart Smykla <bsmykla@vmware.com>

### CODE REVIEW

**Comment by stp-ip** [comment]
Looks like a good first iteration for #340.

We can wait for the full generate list from redirect entries once we have the redirector in place.

One note. I think /help might be too broad. How about /redirects?

**Comment by nikhita** [comment]
> I think /help might be too broad. 

I agree, might end up being confusing since we have `/help-wanted` too. :thinking:

**Comment by bartsmykla** [comment]
@nikhita what do you think of @stp-ip suggestion about `/redirects`?

**Comment by nikhita** [comment]
`/redirects` sounds good to me :)

**Comment by bartsmykla** [comment]
@stp-ip @nikhita I updated the PR. Can you look now? :-)

**Pull request merged**
