### PR TITLE
groups: update steering-committee groups

### PR DESCRIPTION
**Pull request by spiffxp**
ref: https://github.com/kubernetes/steering/pull/157
/committee steering

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
until https://github.com/kubernetes/steering/pull/157 is merged

**Comment by nikhita** [comment]
Ah, good catch! Thanks, @spiffxp!

**Comment by nikhita** [comment]
/lgtm

https://github.com/kubernetes/steering/pull/157 has merged.

Will let someone who can run the script cancel the hold.

**Pull request merged**
