### PR TITLE
added email to k8s-infra-prow-viewers mailing list

### PR DESCRIPTION
**Pull request by snowmanstark**

### CODE REVIEW

**Comment by dims** [comment]
@snowmanstark can you please share what you are trying to do here?

**Comment by snowmanstark** [comment]
Hi @dims I was starting on contributing to in k8s in kubernetes/test-infra and currently working on issue #18852

**Comment by dims** [comment]
/approve
/lgtm
/ok-to-test

thanks for the detail @snowmanstark welcome!

**Pull request merged**
