### PR TITLE
Update KSM 2.4.0 image refs

### PR DESCRIPTION
**Pull request by fpetkovski**
Adds references to the ksm 2.4.1 docker images

### CODE REVIEW

**Comment by mrueg** [comment]
Can you re-run the job? It looks like `- name: kube-state-metrics` didn't get one

**Comment by fpetkovski** [comment]
Pushed another commit to trigger prow jobs. This is what I see for the repository: https://prow.k8s.io/?repo=kubernetes%2Fk8s.io

**Comment by mrueg** [comment]
something is off, it looks like the image did not get built for all kube-state-metrics? 
https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/global/kube-state-metrics

**Comment by mrueg** [comment]
It looks like there was an issue during push: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kube-state-metrics-push-images/1493489893693722624

**Pull request merged**
