### PR TITLE
Add 1.20 Bug Triage Shadows

### PR DESCRIPTION
**Pull request by bai**
This PR adds 1.20 RT Bug Triage Shadows to release mailing lists.

/assign @jeremyrickard @lachie83
/cc @kubernetes/release-team-leads

### CODE REVIEW

**Comment by dims** [comment]
/approve

please ask one of the leads for `/lgtm`

**Review by savitharaghunathan — CHANGES_REQUESTED** [review]
@bai 👋 Can you sort the GitHub id's alphabetically?

**Comment by bai** [comment]
@savitharaghunathan done 🙏

**Review by savitharaghunathan — COMMENTED** [review]
Thank you, @bai. 

/lgtm

**Comment by palnabarun** [comment]
/lgtm

Thank you @bai :slightly_smiling_face:

**Pull request merged**
