### PR TITLE
Promote dns 1.23.1 images to registry.k8s.io

### PR DESCRIPTION
**Pull request by DamianSawicki**
This is to promote the images from the kubernetes/dns release [1.23.1](https://github.com/kubernetes/dns/releases/tag/1.23.1). This was requested [multiple](https://github.com/kubernetes/dns/issues/620#issuecomment-2144465907) [times](https://docs.google.com/document/d/1_w77-zG_Xj0zYvEMfQZTQ-wPP4kXkpGD8smVtW_qqWM/edit).

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve

@DamianSawicki for subsequent PRs is useful to add to the description a log of a command validating the hash, I have checked the gcr.io/k8s-staging-dns/k8s-dns-kube-dns:1.23.1 and others

**Comment by DamianSawicki** [comment]
> /lgtm /approve
> 
> @DamianSawicki for subsequent PRs is useful to add to the description a log of a command validating the hash, I have checked the gcr.io/k8s-staging-dns/k8s-dns-kube-dns:1.23.1 and others

Thanks for checking and approving @aojea! _"a log of a command validating the hash"_ – do you have a specific command in mind? I've prepared this manually by running `docker pull` and copy-pasting.

**Comment by bzsuni** [comment]
I’m sorry, but based on this update, I have already submitted a PR #6859

**Comment by DamianSawicki** [comment]
> I’m sorry, but based on this update, I have already submitted a PR #6859

Oh, I didn't know you're also working on that, @bzsuni. I was following up on an even earlier discussion https://github.com/kubernetes/dns/issues/620#issuecomment-2143417250 😅

**Comment by DamianSawicki** [comment]
@kl52752 Could you please approve https://github.com/kubernetes/k8s.io/pull/6859/? It's identical as the present PR, but it was submitted a few hours before, so let's choose the earlier one.

**Comment by kl52752** [comment]
done, please close this PR

**Comment by DamianSawicki** [comment]
(Closed as duplicate of https://github.com/kubernetes/k8s.io/pull/6859.)

**Pull request closed without merging**
