### PR TITLE
reorg promoter manifests to use thin manifests

### PR DESCRIPTION
**Pull request by listx**
This is blocked on https://github.com/kubernetes/test-infra/pull/14897

/hold

/assign @thockin @cblecker

### CODE REVIEW

**Comment by listx** [comment]
README updated

**Comment by listx** [comment]
OK so the pull-k8sio-cip test was legit failing; https://github.com/kubernetes/test-infra/pull/14919 should fix it.

**Comment by listx** [comment]
@nikhita can you lgtm?

**Comment by listx** [comment]
I will update this PR to also take into account the newly-added kube-state-metrics subproject (#384) to use thin manifests.

**Comment by listx** [comment]
Updated. PTAL

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
