### PR TITLE
promote csi-secrets-store driver:v1.3.2

### PR DESCRIPTION
**Pull request by nilekhc**
Test run with the staging image: https://github.com/kubernetes-sigs/secrets-store-csi-driver/actions/runs/4473116867

/assign @tam7t @aramase

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
Confirmed the test run with staging image `v1.3.2` (xref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/actions/runs/4473116867)

/lgtm
/approve

**Review by aramase — CHANGES_REQUESTED** [review]
[k8s.gcr.io Image registry is frozen from April 2023. Please update the manifests in registry.k8s.io folder instead]

@nilekhc can you make the change in https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-csi-secrets-store/images.yaml instead of this file?

**Comment by nilekhc** [comment]
> [k8s.gcr.io Image registry is frozen from April 2023. Please update the manifests in registry.k8s.io folder instead]
> 
> @nilekhc can you make the change in https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-csi-secrets-store/images.yaml instead of this file?

Done!

**Review by aramase — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
