### PR TITLE
feat: add shortlink pointing to k8s logo page

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>

Fixes kubernetes/community#5360

### CODE REVIEW

**Comment by nikhita** [comment]
lgtm

/hold
should be approved by someone who can deploy this. with that,

/assign @thockin 
for approving + deploying this

**Review by thockin — COMMENTED** [review]
Can you please add this to test.py, too.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
/hold

I won't be able to apply this until later.  @dims or @spiffxp - if you have time, go nuts.  If not, I can get this later.

**Comment by thockin** [comment]
deployed

**Pull request merged**
