### PR TITLE
www-golang: add ingress

### PR DESCRIPTION
**Pull request by euank**
Someone ran into this not working https://github.com/kubernetes/ingress/issues/147

### CODE REVIEW

**Comment by thockin** [comment]
I wish I could make it work generically...

**Comment by euank** [comment]
Using `github.com/kubernetes/...` for the import path works generically and is easier for a beginner to go from import path -> source code.

No clue why the vanity urls are being used in the first place.

**Comment by thockin** [comment]
There was some thought that we might move off of github, and a shorter URL
was attractive.

**Comment by vharsh** [comment]
> There was some thought that we might move off of github, and a shorter URL was attractive.
Looks like this was possible just because `go get` is not just `git clone` outright as most beginners begin to think.
view-source:https://k8s.io/kubectl?go-get=1

**Pull request merged**
