### PR TITLE
Image promotion for provider-aws v1.23.18

### PR DESCRIPTION
**Pull request by cartermckinnon**
Image promotion for provider-aws v1.23.18
This is an automated PR generated from `kpromo`
```
kpromo pr --fork cartermckinnon --project provider-aws --tag v1.23.18
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Review by xmudrii — APPROVED** [review]

**Pull request closed without merging**
