### PR TITLE
Add cluster-api-ibmcloud staging repo

### PR DESCRIPTION
**Pull request by mkumatag**
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/332

### CODE REVIEW

**Comment by mkumatag** [comment]
I don't see any error in the PR jobs, neither an error why `do-not-merge/invalid-owners-file` tagged, @nikhita any idea what is going wrong here?

**Comment by mkumatag** [comment]
> /verify-owners

oops,! thanks for that @nikhita

**Comment by dims** [comment]
/approve
/lgtm

@spiffxp @ameukam do we already have automation for the gcb buckets? or should one of us run it by hand?

/hold

**Comment by ameukam** [comment]
> /approve
> /lgtm
> 
> @spiffxp @ameukam do we already have automation for the gcb buckets? or should one of us run it by hand?
> 
> /hold

@dims we still need to run the scripts for those by hand.

**Comment by mkumatag** [comment]
I just resolved the merge conflicts and pushed the PR, I don't want to bother @dims as he is on vacation, wondering someone can help me merge this PR and get the resource creates @ameukam @cblecker @spiffxp

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by mkumatag** [comment]
Thanks, @spiffxp I can see the google group and a GCS buckets as well :)

**Comment by spiffxp** [comment]
Ran ` ./infra/gcp/bash/ensure-staging-storage.sh cluster-api-ibmcloud`

**Pull request merged**
