### PR TITLE
Release metrics-server v0.3.7

### PR DESCRIPTION
**Pull request by serathius**
/cc @loburm @s-urbaniak

### CODE REVIEW

**Comment by bartsmykla** [comment]
@serathius @s-urbaniak as platform specific hashes are present in image [manifest](https://console.cloud.google.com/gcr/images/k8s-staging-metrics-server/GLOBAL/metrics-server@sha256:eec279de92328954ec69e9c2ef920861de28d31bb14b5290b53b5ef3dfa96502/details?tab=info&project=k8s-staging-metrics-server&organizationId=758905017065)
placing them explicitly in promotion manifest file is incorrect (and unnecessary). Please could you followup with the fix? :-)

**Comment by bartsmykla** [comment]
Actually, I created a PR with the fix already: https://github.com/kubernetes/k8s.io/pull/769

**Comment by serathius** [comment]
Hey @bartsmykla,
Vanity domain flip gonna be done soon (I hope), so I wanted to check if Metrics Server are correctly promoted. From docs and promoter logs I would expect that image should be available under `us.gcr.io/k8s-artifacts-prod/metrics-server`, but it doesn't work for me.

```console
$ docker pull us.gcr.io/k8s-artifacts-prod/metrics-server:v0.3.7
Error response from daemon: manifest for us.gcr.io/k8s-artifacts-prod/metrics-server:v0.3.7 not found: manifest unknown: Failed to fetch "v0.3.7" from request "/v2/k8s-artifacts-prod/metrics-server/manifests/v0.3.7".
``` 
Do you know what could be the reason for this? Thanks

**Pull request merged**
