### PR TITLE
Image promotion for build-image v0.4.1 / v0.4.0

### PR DESCRIPTION
**Pull request by cpanato**
Image promotion for build-image v0.4.1 / v0.4.0
This is an automated PR generated from `kpromo`
```
kpromo pr --fork cpanato --interactive --project build-image --tag v0.4.1 --tag v0.4.0
```

/hold
cc: @kubernetes/release-engineering

### CODE REVIEW

**Comment by cpanato** [comment]
cc @rikatz

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
