### PR TITLE
fix: updated aws canary cluster information

### PR DESCRIPTION
**Pull request by rjsadow**
/kind support

This CR updates the EKS canary cluster from v1.25 to use v1.26 with cluster autoscaler v1.26.2 and the latest 1.26 ubuntu EKS node AMI. 

AMI ref: https://cloud-images.ubuntu.com/aws-eks/
image
Autoscaler ref: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.26.2
ref: https://github.com/kubernetes/k8s.io/issues/5166

### CODE REVIEW

**Comment by rjsadow** [comment]
@xmudrii, it looks like EKS support for 1.27 dropped today. Would you want to bump this to 1.27 already, or should yherebe some bake time on eks first?

**Comment by xmudrii** [comment]
@rjsadow Let me think about it and discuss with folks and I'll get back to you as soon as possible.

**Comment by rjsadow** [comment]
It looks like we're still waiting on a ubuntu 1.27 AMI. Does anyone know the process for how Chronicle creates or manages these AMIs? Is there a ticket that can be created asking if its generation is in the works?

**Comment by xmudrii** [comment]
@rjsadow I don't think that we have any contacts at Canonical so I don't think there's anything else that we can do besides waiting.

**Comment by rjsadow** [comment]
@xmudrii the 1.27 AMI is finally out!! https://cloud-images.ubuntu.com/aws-eks/

With that I think all the necessary components to upgrade to 1.27 are avail, should I update this PR to

1. AMI: ami-03e44b22a81b26f27
2. Autoscaler: 1.27.2 https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.27.2
3. k8s: 1.27

**Comment by xmudrii** [comment]
Putting this on hold until:
- we don't figure out why we have stability issues (https://github.com/kubernetes/k8s.io/issues/5473)
- we don't figure out how to properly handle upgrades (last time we rotated AMI it took a lot of time and effort)
/hold

**Pull request closed without merging**
